### DISCUSSION TITLE
Add two services

### DISCUSSION THREAD

**Discussion by onetwo81** [mampfes/hacs_waste_collection_schedule#1067] [Q&A] [answered]
Hi all,

is it possble to add two services?
I live in Berlin and have two collectors. I add two services, one after one but in the calendar I got only one service

**Comment by 5ila5** [comment, marked as answer]
you can add multiple sources like this:

```yaml
waste_collection_schedule:
  sources:
    - name: bsr_de
      args:
        abf_strasse: "Bahnhofstr., 12159 Berlin (Tempelhof-Schöneberg)"
        abf_hausnr: 1
    - name: bsr_de
      args:
        abf_strasse: "Bahnhofstr., 12159 Berlin (Tempelhof-Schöneberg)"
        abf_hausnr: 2
    - name: abfall_io
      args:
        key: "8215c62763967916979e0e8566b6172e"
        f_id_kommune: 2999
        f_id_strasse: 1087
```

This will add 3 different calendars. 

If you want to change the names of the calendars you can do this by adding the `calendar_title` attribute:

```yaml
waste_collection_schedule:
  sources:
    - name: bsr_de
      args:
        abf_strasse: "Bahnhofstr., 12159 Berlin (Tempelhof-Schöneberg)"
        abf_hausnr: 1
      calendar_title: Haus 1
    - name: bsr_de
      args:
        abf_strasse: "Bahnhofstr., 12159 Berlin (Tempelhof-Schöneberg)"
        abf_hausnr: 2
      calendar_title: Haus 2
    - name: abfall_io
      args:
        key: "8215c62763967916979e0e8566b6172e"
        f_id_kommune: 2999
        f_id_strasse: 1087
      calendar_title: Haus 1 ALBA
```
