### DISCUSSION TITLE
Cant get the sensor to show up (possibly basic newby error)

### DISCUSSION THREAD

**Discussion by linuxstony** [mampfes/hacs_waste_collection_schedule#1384] [Q&A]
Hi,

I apologize when this is tiresome, but I am not able to setup the schedule correctly. 

I added : 

```yaml
waste_collection_schedule:
  sources:
  - name: app_abfallplus_de
    args:
      app_id: de.k4systems.awrplus
      city: Rotenburg
      strasse: "Streetname with "ä" in it"
      hnr: Alle Hausnummern
```
in the configuration.yaml

I include Sensors with 
sensor: !include sensor.yaml

And the sensor is 

```yaml
- platform: waste_collection_schedule
  name: muell
```

just to get started.

Sadly the sensor.muell doesnt show up.

No errors are shown in the log.
I see the Dates in the added "Apps by Abfall+" Calender entry though.

And now I am at a loss what the frick I am missing here... 

Thanks for your help 

Stefan

**Comment by 5ila5** [comment]
Your configuration looks fine.
This works for me:
```yaml
waste_collection_schedule:
    sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.awrplus
        city: Rotenburg
        strasse: Altmärker Weg
        hnr: Alle Hausnummern
        
sensor:
  - platform: waste_collection_schedule
    name: muell
```

have you properly restarted homeassistant after changing your config file? Quick-reload does not work propperly with this integration.
Is your calendar populated? http://{URL}:8123/calendar ?
