### DISCUSSION TITLE
Is there a card?

### DISCUSSION THREAD

**Discussion by dopeytree** [mampfes/hacs_waste_collection_schedule#1439] [General]
Have got it configured very basically and it's created a recycling calendar and shows which days is recycling or black bin bag days.
So far it is showing this in the calendar feed cards.

How do I get to see the raw data of whats available so I customise it?

Or in other words how do I get it to look like the installation guide?

Thanks

<img width="1050" alt="Screenshot 2023-11-22 at 07 37 59" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/103341262/10352335-e4b3-42d2-acb1-2523fedbe58e">

This is my code:

```
# Waste collection integration code
waste_collection_schedule:
  sources:
    - name: iweb_itouchvision_com
      args:
        postcode: "BA16 0JN"
        uprn: "250004708"
        council: "somerset"
      calendar_title: "recycling"
          
sensor:
  - platform: waste_collection_schedule
    name: next_collection
    details_format: generic
    #count: COUNT
    #leadtime: LEADTIME
    #value_template: VALUE_TEMPLATE
    #date_template: DATE_TEMPLATE
    #add_days_to: ADD_DAYS_TO
    #event_index: EVENT_INDEX
    types:
      - Waste Type 1
      - Waste Type 2
```

and this is the current output

<img width="364" alt="Screenshot 2023-11-22 at 07 39 14" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/103341262/6dadb566-9f9c-404e-ba89-746da5aaf91c">

<img width="337" alt="Screenshot 2023-11-22 at 07 39 08" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/103341262/ffe06727-8110-4aff-8d87-ba4ab1532930">
ut:
