### DISCUSSION TITLE
After Upgrade to1.44.0 Sensors not available

### DISCUSSION THREAD

**Discussion by PuschRo** [mampfes/hacs_waste_collection_schedule#1473] [General]
Hi, i updated my waste scheduler Version to Version 1.44.0 this morning.
After this there were no Sensors and no more Data available. 
Message: Enitity is no longer available by the Integraton waste_collection_schedule  

What happens?

My Sensors:

  ```
- platform: waste_collection_schedule
    value_template: '{{value.types|join(", ")}}|{{value.daysTo}}|{{value.date.strftime("%d.%m.%Y")}}|{{value.date.strftime("%a")}}'
    name: next_yard_collection
    types:
      - Bio

  - platform: waste_collection_schedule
    value_template: '{{value.types|join(", ")}}|{{value.daysTo}}|{{value.date.strftime("%d.%m.%Y")}}|{{value.date.strftime("%a")}}'
    name: next_garbage_collection
    types:
      - Restmüll

  - platform: waste_collection_schedule
    value_template: '{{value.types|join(", ")}}|{{value.daysTo}}|{{value.date.strftime("%d.%m.%Y")}}|{{value.date.strftime("%a")}}'
    name: next_paper_collection
    types:
      - Papier
  
  - platform: waste_collection_schedule
    value_template: '{{value.types|join(", ")}}|{{value.daysTo}}|{{value.date.strftime("%d.%m.%Y")}}|{{value.date.strftime("%a")}}'
    name: next_recycle_collection
    types:
      - Gelber Sack     
```

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
         file: "/config/files/2023.ics"
      customize:
      - type: Biotonne in Nördlingen
        alias: Bio
      - type: Papiertonne in Nördlingen
        alias: Papier
      - type: Restmüll in Nördlingen
        alias: Restmüll  
      - type: Gelber Sack in Nördlingen
        alias: Gelber Sack   
  fetch_time: "01:00"
  day_switch_time: "23:00"
```
