### DISCUSSION TITLE
Help with WCS getting to run - Austria

### DISCUSSION THREAD

**Discussion by stefa75** [mampfes/hacs_waste_collection_schedule#1547] [Q&A] [answered]
Hi there,
im relative new to HA and automated my Energy and EVs in the future.
Now i want to build a Dashboard for our house and integrate the Waste Schedule.

My Config is like this:
```yaml
waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "krems"
        municipal: "Gobelsburg, Mittelberg, Reith, Schiltern, Zöbing"
      
sensor:
  - platform: waste_collection_schedule
    name: Müllabholung
```

But i get no entries in the calendar and the Sensor "Müllabholung" says "unknown".

Someone here who uses the "Umweltverbände" Source?

Thanks,
Stefan

**Comment by 5ila5** [comment]
This source seems to be not perfectly made for multiple scedules within one municipality. In the current implementation you need to use
```yaml
waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "krems"
        municipal: "Langenlois"
```
and then remove the wrong one using customize.

I did some improvements in #1553 to solve this problem then you can use

```yaml
waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "krems"
        municipal: "Langenlois"
        calendar: "Gobelsburg, Mittelberg, Reith, Schiltern, Zöbing"
```
to only get your relevant entries.

This improvement will be part of release 1.45.0 or is available now as master (git) version (HACS: 3-dot menu -> redownload -> change version to master. This will increase updates by a lot)

**Reply by stefa75** [reply]
Thank you for this fast answer and solution. Will try the master version ;-)

**Reply by stefa75** [reply]
Have installed the 1.45.0 and now only the related Collection seems to be fetched from the website.

For example: Today is shown "Restmüll". But this is only for the "2-weekly-interval". The normal Interval is 4 weeks and shouldnt be shown in my case.
Also no Schedules for 2024 are in the calendar. Are they first fetched after 31.12. ?

In the PDF Calendar there ist shown "Restmüll" and "Restmüll 2".  In their "text" calendar there ist "Restmüll monatlich" and "Restmüll 14-tägig". 
Were do you get the data from?

**Reply by 5ila5** [reply, marked as answer]
we do not parse the pdf but take the information from the table below Kalenderansicht on their page. If I have to guess they probably name the collections Restmüll and "Restmüll 2" like in the pdf. You could change this behaviour by providing customization:

```yaml
waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "krems"
        municipal: "Langenlois"
        calendar: "Gobelsburg, Mittelberg, Reith, Schiltern, Zöbing"
      customize:
        - type: Restmüll
          show: false
        - type: Restmüll 2
          alias: Restmüll
```

As for dates in 2024 they are not yet listed in Kalenderansicht. If they do not publish them there you need to switch to the [ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) and get the ICS file as we will not parse PDFs and I do not see any other location where collection dates are listed
