### DISCUSSION TITLE
Brisbane City Council source with unknown sensors

### DISCUSSION THREAD

**Discussion by CodeFatherG** [mampfes/hacs_waste_collection_schedule#1582] [Q&A]
Hi!

I have followed the installation and configuration instructions, and also used #1258 as a guide. All of my sensors show as unknown

```
waste_collection_schedule:
  sources:
    - name: brisbane_qld_gov_au
      args:
        suburb: SUBURB
        street_name: STREET
        street_number: NUMBER
      customize:
        - type: rubbish
          alias: Rubbish
          icon: mdi:trash-can
        - type: recycle
          alias: Recycle
          icon: mdi:recycle

sensor:
  - platform: waste_collection_schedule
    name: Next Rubbish Collection Date
    types:
      - rubbish
    value_template: '{{value.date.strftime("%d %b")}}'

  - platform: waste_collection_schedule
    name: Next Recycling Collection Date
    types:
      - recycle
    value_template: '{{value.date.strftime("%d %b")}}'

  - platform: waste_collection_schedule
    name: Next Rubbish Collection Days
    types:
      - rubbish
    value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'

  - platform: waste_collection_schedule
    name: Next Recycling Collection Days
    types:
      - recycle
    value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'

  - platform: waste_collection_schedule
    name: Next Rubbish Collection This Week
    types:
      - rubbish
    value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% elif value.daysTo <= 6 %}This {{value.date.strftime("%A")}}{% else %}in {{value.daysTo}} days{% endif %}'

  - platform: waste_collection_schedule
    name: Next Recycling Collection This Week
    types:
      - recycle
    value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% elif value.daysTo <= 6 %}This {{value.date.strftime("%A")}}{% elif value.daysTo < 13 %}Next {{value.date.strftime("%A")}}{% else %}in {{value.daysTo}} days{% endif %}'
```

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/38738958/ca537d8b-0a38-46dc-bcff-939824b892d6)
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/38738958/66c0fcdd-653c-4028-bc99-45bb880b4fd1)
