### DISCUSSION TITLE
Please help me solve my scraping problem.

### DISCUSSION THREAD

**Discussion by Knowix** [mampfes/hacs_waste_collection_schedule#1583] [Q&A]
Hey guys,

First of all, thank you for creating this integration!

I run into a small problem where the scraping runs into an error. From the log I see that the problem is that the Nyitra utca is not found. However, it's in the log as an available street. I also checked the fkf_bp_hu site and it also recognise the street.

SO what am I doing wrong?

File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/fkf_bp_hu.py", line 87, in fetch
    raise Exception("Street not found, available streets: " + available_streets)
Exception: Street not found, available streets: Ábrahám Géza utca, Ady Endre utca ..... Nyitra utca and the rest.

In my configuration.yaml file I have the following:

```yaml
# Waste Collection Schedule Configuration
waste_collection_schedule:
  sources:
    - name: fkf_bp_hu
      args:
        district: 1204
        street: "Nyitra utca"
        house_number: 10
      customize:
        - type: "Kommunális"
          alias: "Kuka"
    - name: fkf_bp_hu
      args:
        district: 1204
        street: "Nyitra Utca"
        house_number: 10
      customize:
        - type: "Szelektív"
          alias: "Szelektív"
          
sensor:
  - platform: waste_collection_schedule
    name: Kommunális
    value_template: '{{value.date.strftime("%m/%d/%Y")}}'
    types:
      - Kommunális
  - platform: waste_collection_schedule
    name: Szelektív
    value_template: '{{value.date.strftime("%m/%d/%Y")}}'
    types:
      - Szelektív
```

> edit by @5ila5: formatted yaml

**Comment by 5ila5** [comment]
your first street needs to be all capitalized (like your second one)

But I do not get why you're using twice the same source you can use multiple customize statements in one source. If you want a dedicated calendar you can do this as well:

```yaml
waste_collection_schedule:
  sources:
    - name: fkf_bp_hu
      args:
        district: 1204
        street: "Nyitra utca"
        house_number: 10
      customize:
        - type: "Kommunális"
          alias: "Kuka"
        - type: "Szelektív"
          alias: "Szelektív"
          use_dedicated_calendar: true
```

**Reply by Knowix** [reply]
I'm not too familiar with coding so that's why I did that. I just copy-pasted your answer and did a manual fetch but it's getting the same error.

2023-12-28 15:26:54.342 ERROR (SyncWorker_6) [waste_collection_schedule.source_shell] fetch failed for source FKF Budapest:
Traceback (most recent call last):
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch
    entries = self._source.fetch()
              ^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/fkf_bp_hu.py", line 87, in fetch
    raise Exception("Street not found, available streets: " + available_streets)
Exception: Street not found, available streets:

**Reply by 5ila5** [reply]
sorry I copied your typo Fixed it (Nyitra utca -> Nyitra Utca)

**Reply by Knowix** [reply]
tried with capital and lowercase but still the same problem :/

**Reply by 5ila5** [reply]
Sorry was not paying attention enough the first example should have worked (`Nyitra utca`) the aliases need to be different (but this does not explain the error) fully restart homeassistant completely after changing your configuration.

Tested to work:

```yaml
waste_collection_schedule:
    sources:
    - name: fkf_bp_hu
      args:
        district: 1204
        street: Nyitra utca
        house_number: 10
      customize:
        - type: "Communal"
          alias: "Kuka"
        - type: "Selective"
          alias: "Szelektív"
          use_dedicated_calendar: true
```

**Reply by Knowix** [reply]
Thanks a lot! 

I managed to get the Selective type running and got the right date. However, the Communal type remained unknown. Also, I tried to restart Home Assistant and now everything is gone again..

**Reply by Knowix** [reply]
I'm trying to bring it to life but for some reason, the date is not shown properly. I created an Identity card into my dashboard and added sensor.selective & sensor.communal but these are only showing unknown value.

Sorry for bothering you but I'd appreciate the help! @5ila5 

```yaml
# Waste Collection Schedule Configuration
waste_collection_schedule:
    sources:
    - name: fkf_bp_hu
      args:
        district: 1204
        street: Nyitra utca
        house_number: 10
      customize:
        - type: "Communal"
          alias: "Kommunális"
        - type: "Selective"
          alias: "Szelektív"
          use_dedicated_calendar: true
          
sensor:
  - platform: waste_collection_schedule
    name: Kommunális
    value_template: '{{value.date.strftime("%m/%d/%Y")}}'
    types:
      - Communal
  - platform: waste_collection_schedule
    name: Szelektív
    value_template: '{{value.date.strftime("%m/%d/%Y")}}'
    types:
      - Selective
```
      
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/84448145/e56a24aa-cc64-481f-8ef4-9b94416ffbf5)

**Reply by 5ila5** [reply]
providing an alias renames the type. You then need to use the new name in the sensor config:

```yaml
# Waste Collection Schedule Configuration
waste_collection_schedule:
    sources:
    - name: fkf_bp_hu
      args:
        district: 1204
        street: Nyitra utca
        house_number: 10
      customize:
        - type: "Communal"
          alias: "Kommunális"
        - type: "Selective"
          alias: "Szelektív"
          use_dedicated_calendar: true
          
sensor:
  - platform: waste_collection_schedule
    name: Kommunális
    value_template: '{{value.date.strftime("%m/%d/%Y")}}'
    types:
      - Kommunális
  - platform: waste_collection_schedule
    name: Szelektív
    value_template: '{{value.date.strftime("%m/%d/%Y")}}'
    types:
      - Szelektív
```
