### DISCUSSION TITLE
Problem with strange type name in ICS file

### DISCUSSION THREAD

**Discussion by rs3hc** [mampfes/hacs_waste_collection_schedule#1618] [General]
Hi guys.

I got my trash calendar working, but just one type is "unknown" in the entities.

Everything except "Gelber Sack" is displayed correctly

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/69956680/169026aa-9f3c-482b-8fb9-e4ffc4040864)

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/69956680/361dad65-0cca-4433-bc93-4f107faf3d4c)

Can anybody help?

Here is the part of the ICS file:

```

SUMMARY;LANGUAGE=de:Schadstoff 
SUMMARY;LANGUAGE=de:Restmuelltonne 02-woechentl.
SUMMARY;LANGUAGE=de:Papiertonne 04-woechentl.
SUMMARY;LANGUAGE=de:Gelber Sack\, Gelbe Tonne 
SUMMARY;LANGUAGE=de:Weihnachtsbaum
```

Here is the part of the configuration.yaml
```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/Leerungstermine102993.ics"
      customize:
        - type: Gelber Sack\, Gelbe Tonne
          alias: GelberSack
          icon: mdi:recycle
        - type: Restmuelltonne 02-woechentl.
          alias: Restmuell
          icon: mdi:trash-can
        - type: Papiertonne 04-woechentl.
          alias: PapierTonne
          icon: mdi:trash-can-outline
        - type: Schadstoff
          show: false
        - type: Weihnachtsbaum
          show: false

```

My sensors.yaml :

```

# Müll Termine
    
  - platform: waste_collection_schedule
    name: AbfallRestmuell
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - 'Restmuell'

  - platform: waste_collection_schedule
    name: AbfallPapierTonne
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - 'PapierTonne'

  - platform: waste_collection_schedule
    name: AbfallGelberSack
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - 'GelberSack'


  - platform: waste_collection_schedule
    name: AbfallRestmuellnext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - 'Restmuell'

  - platform: waste_collection_schedule
    name: AbfallPapierTonnenext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - 'PapierTonne'

  - platform: waste_collection_schedule
    name: AbfallGelberSacknext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - 'GelberSack'

      
  - platform: waste_collection_schedule
    name: AbfallNaechster
    details_format: "upcoming"
    value_template: ' {{ value.daysTo }} '
    
```

**Comment by 5ila5** [comment]
you might need to use "Gelber Sack\\, Gelbe Tonne" as you now try to escape the , char. To use the actual \ char you need to escape it using an other \ before it.

If this does happen for multiple values you could use this should generally delete everything that comes after an \ cahr (4 \ chars for escaping 2 that will be intepreted by the regex library as one escaping the other)

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/Leerungstermine102993.ics"
        regex: "(.*?)\\\\"
      customize:
        - type: Restmuelltonne 02-woechentl.
          alias: Restmuell
          icon: mdi:trash-can
        - type: Papiertonne 04-woechentl.
          alias: PapierTonne
          icon: mdi:trash-can-outline
        - type: Schadstoff
          show: false
        - type: Weihnachtsbaum
          show: false
```
