### DISCUSSION TITLE
Additional info how to setup "Static Source"

### DISCUSSION THREAD

**Discussion by tonyv78** [mampfes/hacs_waste_collection_schedule#1621] [Q&A]
Hi to everybody, is the first time that i write in Github, i would like to ask if is possible to set a range of dates on the variable
"excludes" from the documentation there are example only with single date not with ranges of dates.

```
waste_collection_schedule:
  sources:
    - name: static
      args:
        type: Altpapier
        frequency: WEEKLY
        interval: 4
        start: '2022-01-14'
        until: '2022-12-31'
        excludes: # Add exception for the recurrence
          - '2022-07-29'
          - '2022-09-23'
        dates: # Manually add dates that are not part of the recurrence
          - '2022-07-28'
          - '2022-09-22'
```

I need to exclude a period of 4 month so if a need to insert day by day it will be time consuming it will be better to have the 
possibility to insert a range of dates.

Thanks in advance to anyone that can help me.
