### DISCUSSION TITLE
abfallnavi aachen - Searching the right args

### DISCUSSION THREAD

**Discussion by GregGraetssche** [mampfes/hacs_waste_collection_schedule#1627] [Q&A]
Sorry, I am not able to find the right args for abfallnavi for the german city of Aachen. I tried it with https://abfallnavi.api.bund.dev/ and got some id, but they do not work.

waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: aachen
        ort: Aachen
        strasse: Erckensstrasse
        
Only an empty calendar appears. I installed Python, but were not able to run the script.

Who can send me the right args?

Thank you in advance

**Comment by 5ila5** [comment]
you config should look like this:
```yaml
# waste_collection_schedule source configuration
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: aachen
        ort: Aachen
        strasse: Erckensstraße
        hausnummer: 36
```
