### DISCUSSION TITLE
Automation and Dont Show

### DISCUSSION THREAD

**Discussion by Sheepish2** [mampfes/hacs_waste_collection_schedule#1650] [Q&A]
Hi all,

I'm trying to create an automation that will show me every other bin over the General Waste (Blue Bin). I have put into my configurations.yaml the below code but no give.. Any ideas? 

```yaml
waste_collection_schedule:
  sources:
    - name: 
      args:
        post_code: 
        suburb: 
        street_name: 
        street_number: 
    - name: General Waste (Blue Bin)
      customize:
        - type: Unwanted Waste Type
          show: false
```
> edited by @5ila5 (add code block formatting)
