### DISCUSSION TITLE
New Sources for Austria

### DISCUSSION THREAD

**Discussion by M4d4lyNN** [mampfes/hacs_waste_collection_schedule#1689] [Q&A]
Can we have 2 additional cities in Austria: Maria Enzersdorf (postal code 2344) and Brunn am Gebirge (postal code 2340)

**Comment by 5ila5** [comment]
both are supported by the [umweltverbaende_at source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/umweltverbaende_at.md) Also listed in the README.md as GVA Mödling.

```yaml
waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "moedling" 
        municipal: "Maria Enzersdorf, Marktgemeinde" 
```

```yaml
waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "moedling" 
        municipal: "Brunn am Gebirge, Marktgemeinde" 
```

You might need to play around with the calendar attribute to limit the events listed (not quite shure whats the best apporach but something like would work (not shure if all/the right collections are shown):

```yaml
waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "moedling" 
        municipal: "Maria Enzersdorf, Marktgemeinde"
        calendar: "Tour 1"
```
