### DISCUSSION TITLE
Integrate with ERZ (Zürich waste collection)

### DISCUSSION THREAD

**Discussion by harrolf** [mampfes/hacs_waste_collection_schedule#1724] [Ideas]
Zurich waste collection has its own API and is already integrated in HA, however it would be great to have it through this custom component with all its benefits.

Related documents:

- https://www.stadt-zuerich.ch/portal/de/index/ogd/anwendungen/2019/open_erz_api.html
- http://openerz.metaodi.ch/documentation
- https://github.com/metaodi/openerz

**Comment by 5ila5** [comment]
The API looks pretty good, but do you know if there is an easy way for users to get their area (which seems to be required by the API)?


We don't even need to implement a dedicated source, as we can just use the ICS source like this:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        params:
          area: 8048
          region: zurich
          zip: 8048
        regex: (.*), .*
        url: https://openerz.metaodi.ch/api/calendar.ics?types=bulky_goods&types=cardboard&types=cargotram&types=chipping_service&types=etram&types=incombustibles&types=metal&types=oekibus&types=organic&types=paper&types=special&types=textile&types=waste&sort=date&offset=0&limit=500
```

I want to add documentation for this and added a PR here:  #1726 
Could you have a look if you want to change something
