### DISCUSSION TITLE
Die NÖ Umweltverbände - tulln - Tulbing

### DISCUSSION THREAD

**Discussion by taifuuun** [mampfes/hacs_waste_collection_schedule#1741] [Q&A] [answered]
Hi,
i am trying to get all waste collection reminders configured,
```
waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "tulln"
        municipal: "Tulbing"
        calendar: "Haushalte 2"
```
is quite good, but does not show appointments for Biotonne. Now i tried to add this by 
`calendar: "Haushalte 2, Biotonne"`

or 

```
waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "tulln"
        municipal: "Tulbing"
        calendar: "Haushalte 2"
    - name: umweltverbaende_at
          args:
            district: "tulln"
            municipal: "Tulbing"
            calendar: "Biotonne"
```
'Biotonne' alone works as good as 'Haushalte 2' alone, but i do not get to combine them. I thought it would be an easy task, because of the example

```
waaste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "krems" # Krems
        municipal: "Langenlois" # Municipal
        calendar: "Gobelsburg, Mittelberg, Reith, Schiltern, Zöbing" # Rayon
```
which combines calendars as well. Any ideas/suggestions?
thank you and br

**Comment by 5ila5** [comment, marked as answer]
I don't think this possible currently. The calendar argument just checks weather `calendar` is a substring of the event listed on the website, e.g _Haushalte 2: Altpapier_ .

I added the ability to supply multiple calendar arguments as list in #1742.

You should then be able to use:

```yaml
waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "tulln" # Tulln
        municipal: "Tulbing" # Municipal
        calendar: 
          - "Haushalte 2"
          - "Biotonne"
```

or (equivalent)

```yaml
waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "tulln" # Tulln
        municipal: "Tulbing" # Municipal
        calendar: ["Haushalte 2", "Biotonne"]
```

This feature will be part of release 1.46.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
