### DISCUSSION TITLE
Problem with creating sensor for Glass og metallemballasje - remidt - norway

### DISCUSSION THREAD

**Discussion by acidkill** [mampfes/hacs_waste_collection_schedule#1780] [Q&A] [answered]
Hi there. I based my configuration on:
doc/source/remidt_no.md

and everything works - except sensor for "Glass og metallemballasje"

this is example output from their api:
[Link to example response from remidt api](https://kalender.renovasjonsportal.no/api/address/d87b0a15-b991-46a1-bffd-37bc8082d218/details
))
`{"disposals":[{"date":"2024-02-13T00:00:00","description":null,"type":null,"fraction":"Papir","symbolId":0},{"date":"2024-02-13T00:00:00","description":null,"type":null,"fraction":"Matavfall","symbolId":0},{"date":"2024-02-27T00:00:00","description":null,"type":null,"fraction":"Restavfall","symbolId":15},{"date":"2024-02-27T00:00:00","description":null,"type":null,"fraction":"Matavfall","symbolId":0},{"date":"2024-02-28T00:00:00","description":null,"type":null,"fraction":"Glass og metallemballasje","symbolId":0},{"date":"2024-02-28T00:00:00","description":null,"type":null,"fraction":"Plastemballasje","symbolId":2},{"date":"2024-03-12T00:00:00","description":null,"type":null,"fraction":"Papir","symbolId":0},{"date":"2024-03-12T00:00:00","description":null,"type":null,"fraction":"Matavfall","symbolId":0},{"date":"2024-03-26T00:00:00","description":null,"type":null,"fraction":"Restavfall","symbolId":15},{"date":"2024-03-26T00:00:00","description":null,"type":null,"fraction":"Matavfall","symbolId":0},{"date":"2024-04-09T00:00:00","description":null,"type":null,"fraction":"Papir","symbolId":0},{"date":"2024-04-09T00:00:00","description":null,"type":null,"fraction":"Matavfall","symbolId":0},{"date":"2024-04-10T00:00:00","description":null,"type":null,"fraction":"Glass og metallemballasje","symbolId":0},{"date":"2024-04-10T00:00:00","description":null,"type":null,"fraction":"Plastemballasje","symbolId":2}]}`

my sensor configuration below:
```
sensor:
  # next collection
  - platform: waste_collection_schedule
    name: next_collection
    
  # next Papir waste collection
  - platform: waste_collection_schedule
    name: next_papir_collection
    types:
      - Papir

  # next Matavfall waste collection
  - platform: waste_collection_schedule
    name: next_matavfall_collection
    types:
      - Matavfall

  # next Plastemballasje waste collection
  - platform: waste_collection_schedule
    name: next_plast_collection
    types:
      - Plastemballasje

  # next Glass og metallemballasje waste collection
  - platform: waste_collection_schedule
    name: next_glass_og_metallemballasje_collection
    types:
      - Glass og metallemballasje
```
