### DISCUSSION TITLE
Recycling-company uses / as delimiter in .ics (Newbie Question)

### DISCUSSION THREAD

**Discussion by colin1256** [mampfes/hacs_waste_collection_schedule#1785] [Q&A]
Hi,

I'm trying to make WCS work with the AWG in Wuppertal, Germany.

I have imported their ics file into WCS in configuration.yaml as follows

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/2024-AWG.ics"
```

Unfortunately, they are not using ', ' as delimiter between individual collections taking place the same day.

Their Data is structured like this:

```
SUMMARY:Restmüll/Restmüll-50%/Gelb/ !!! Terminverschiebung !!!
DESCRIPTION:Müllabfuhr:Restmüll/Restmüll-50%/Gelb/ !!! 
```

In order to handle this, I'm trying to change the delimiter in the join instruction from ', ' to '/'. I've already tried with the / escaped and non-escaped, but it's not working:

```
platform: waste_collection_schedule
name:  "Nächste Abholung"
value_template: '{{value.types|join("//")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
```

If I take the "Restmüll"-Sensor for instance, it will always only report "unknown":
```
platform: waste_collection_schedule
name: "Restmüll"
details_format: "upcoming"
value_template: '{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
types:
  - Restmüll
```

What am I doing wrong? Should I try to regex-replace the '/' with ', ' in order to make this work or is there a better way to do this?

Thanks a lot in advance!

Colin

**Comment by 5ila5** [comment]
The ICS source does not split entries if they are in one ICS event by default. You can pass the split_at argument to split entries at a specific delimiter into multiple entries:

To remove Terminverschiebung you can pass a regex as well.


```yaml 
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/2024-AWG.ics"
        split_at: "/"
        regex: (.*)/ !!! Terminverschiebung !!!
```

**Comment by HeizOel** [comment]
Ich habe einfach mehrere Sensoren angelegt, vorher die .ICs Datei natürlich angepasst 😅 in dem Fall manuell im Editor mit "suchen und Ersetzen" (Proof of concept) sollte aber Recht einfach sein ein script dafür zu schreiben.

```
#Müllsensor

- platform: waste_collection_schedule
  name: Schwarze Tonne
  details_format: upcoming
  count: 4
  value_template: 'Schwarzetonne in {{value.daysTo}} Tag(en)'
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
  - 'Restmuell-50-Gelb'
  - 'Gelb'
  - 'Restmuell-50-Gelb'

- platform: waste_collection_schedule
  name: Gelbe Tonne
  details_format: upcoming
  count: 4
  value_template: 'Gelbetonne in {{value.daysTo}} Tag(en)'
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
  - 'Gelb'
  - 'Restmuell-50'
  - 'Restmuell-50-Gelb'

- platform: waste_collection_schedule
  name: Braune Tonne
  details_format: upcoming
  count: 4
  value_template: 'Biotonne in {{value.daysTo}} Tag(en)'
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
  - 'Bio'
  - 'Bio/Papier'

- platform: waste_collection_schedule
  name: Blaue Tonne
  details_format: upcoming
  count: 4
  value_template: 'Papiertonne in {{value.daysTo}} Tag(en)'
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
  - 'Papier'
  - 'Bio/Papier'

- platform: waste_collection_schedule
  name: Sperrmuell
  details_format: upcoming
  count: 4
  value_template: 'Sperrmuell in {{value.daysTo}} Tag(en)'
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
  - 'Sperrmuell'

```
