### DISCUSSION TITLE
Reminder - best practice

### DISCUSSION THREAD

**Discussion by riesi77** [mampfes/hacs_waste_collection_schedule#1787] [Q&A] [answered]
Hi everyone,
it's great to see to have such a powerful integration for waste schedule management. However, what I did not find so far is a best practice for a reminder.
Let's say the following: Every day at 7:00 in the morning, I'd like to get a Notification if at the current day a waste collection is scheduled. Of course it can also be 2 at the same day, then it should combine them.
How would you configure the sensors? How set up the automation?

**Comment by 5ila5** [comment]
My automation which notifies me at 16:00 the day before the collection is due. (You can just change the time to `07:00:00` and the `below` value to 1 to archive what you're searching for. (you can import this in the GUI editor if you prefer.) and change your sensors to the ones you set up.
 
```yaml
alias: Müll notification
description: ""
trigger:
  - platform: time
    at: "16:00:00"
condition: []
action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: sensor.biomuell_days
            below: 2
        sequence:
          - service: notify.mobile_app_iphone
            data:
              title: Biomülltonne
              message: Biomüll raus stellen
      - conditions:
          - condition: numeric_state
            entity_id: sensor.restmuell_days
            below: 2
        sequence:
          - service: notify.mobile_app_iphone
            data:
              title: Restmülltonne
              message: Restmüll raus stellen
      - conditions:
          - condition: numeric_state
            entity_id: sensor.papier_days
            below: 2
        sequence:
          - service: notify.mobile_app_iphone
            data:
              title: Papier Tonne
              message: Papiermüll raus stellen
      - conditions:
          - condition: numeric_state
            entity_id: sensor.gelbersack_days
            below: 2
        sequence:
          - service: notify.mobile_app_iphone
            data:
              title: Gelber Sack
              message: Gelber Sack raus stellen
mode: single
```

my sensor config (you probably want to adjust `name` and `types`:

```yaml
sensor:
  - platform: waste_collection_schedule
    name: restmuell_days
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    add_days_to: true
    types:
      - Restmüll Container wöchentlich

  - platform: waste_collection_schedule
    name: gelbersack_days
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    add_days_to: true
    types:
      - Gelber Sack

  - platform: waste_collection_schedule
    name: biomuell_days
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    add_days_to: true
    types:
      - Biomüll

  - platform: waste_collection_schedule
    name: papier_days
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    add_days_to: true
    types:
      - Papier Tonnen und Container
```

**Comment by 5ila5** [comment, marked as answer]
A easier way which will include all collection types would be something like this:

```yaml
alias: müll 2
description: ""
trigger:
  - platform: time
    at: "16:00:00"
condition:
  - condition: numeric_state
    entity_id: sensor.next_collection_days
    below: 2
action:
  - service: notify.mobile_app_iphone
    metadata: {}
    data:
      message: put out {{ states('sensor.next_collection_types') }}
mode: single
```


with sensors:

```yaml
  - platform: waste_collection_schedule
    name: next_collection_days
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    add_days_to: true
  - platform: waste_collection_schedule
    name: next_collection_types
    details_format: appointment_types
    value_template: "{{ value.types|join(' and ') }}"
    add_days_to: true
```
