### DISCUSSION TITLE
"Unknown" on all 3 sensors

### DISCUSSION THREAD

**Discussion by tonyrsutton** [mampfes/hacs_waste_collection_schedule#1836] [General]
Hi all,

Maybe it's because it's very late in evening and I'm still half asleep, but what am I missing with this config? All three are coming up as "Unknown". I am in the UK and am using breckland_gov_uk as the name and using uprn as the args.

```
sensor:
  - platform: waste_collection_schedule
    name: next_collection
    details_format: upcoming
    value_template: '{{value.date.strftime("%m/%d/%Y")}}'
    types:
      - Garbage
      - Recycle
      - Garden
      
sensor:
  - platform: waste_collection_schedule
    name: next_garbage_collection
    details_format: upcoming
    value_template: 'on {{value.date.strftime("%a")}}, {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - Garbage

  - platform: waste_collection_schedule
    name: next_recycle_collection
    details_format: upcoming
    value_template: 'on {{value.date.strftime("%a")}}, {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - Recycle
      
  - platform: waste_collection_schedule
    name: next_garaden_collection
    details_format: upcoming
    value_template: 'on {{value.date.strftime("%a")}}, {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - Garden
```

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/18743629/11052717-48e1-4e12-944a-2d59a99e766c)

What am I missing?

Thanks all.
