### DISCUSSION TITLE
Republic Services: Bulk Waste Not Visible - Bulk Days are blank

### DISCUSSION THREAD

**Discussion by Landsailor** [mampfes/hacs_waste_collection_schedule#1881] [Q&A]
Hopefully this is a configuration issue and not a bug, but in Southern Nevada, Republic Services provides a "Bulk Waste" pickup with a regular trash truck every other week in addition to the Solid Waste and Recycling container pickups.

The Bulk Service days are completely blank.
<img width="272" alt="Screenshot 2024-03-08 at 2 39 43 PM" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/1393119/5077946f-d193-4d62-b2d9-ec73978c7a2d">

The schedule URL is here:
https://www.republicservices.com/schedule
![Screenshot 2024-03-08 at 3 08 24 PM](https://github.com/mampfes/hacs_waste_collection_schedule/assets/1393119/8efa9501-0eb9-4e26-aaa1-2d11e2c697a9)

There might be issues with my config, so please let me know. I've tried both Bulk Service and Bulk Waste with no difference. Where can I look to see what data is returned from the GET?

Here's my config with a random address that would be on the same schedule entered.

```yaml
waste_collection_schedule:
  sources:
    - name: republicservices_com
      args:
        street_address: "4420 Oasis Hill Ave, North Las Vegas, NV 89085"
        method: 1
      customize:
        - type: "Bulk Waste"
          alias: None
          show: True
          picture: ""
          use_dedicated_calendar: True
          dedicated_calendar_title: "Trash Service"
      calendar_title: ""
  fetch_time: "03:00"
  random_fetch_time_offset: 10
  day_switch_time: "23:00"
  separator: ","

sensor:
  - platform: waste_collection_schedule
    source_index:
    name: "Trash Sensor"
    details_format: "upcoming"
    count: 4
    leadtime: 14
    value_template: "value.date"
    date_template: "value.date"
    add_days_to: True
    event_index: 0
    types: -"Solid Waste"
      -"Recycle"
      -"Bulk Waste"
```

Thanks!
