### DISCUSSION TITLE
Is it possible to use is_state() for value templates?

### DISCUSSION THREAD

**Discussion by Socio241** [mampfes/hacs_waste_collection_schedule#1889] [Q&A]
Hi,

I created an input_boolean that indicates if the bins that are to be emptied were already brought out to the street.
This input_boolean is used to send an actionable notification to my phone every hour until I confirm that the bins are out.
Now I also want to use this input_boolean to modify the sensor state from "Today" to "Ready for emptying" so my wife can easily check the wallpanel to see if the bins are out without having to ask me or take a look outside herself.

So I tried to modify the value template like this:
![ha_value_template](https://github.com/mampfes/hacs_waste_collection_schedule/assets/154612657/f5c2590c-2bef-4cd3-b071-5e44fd27b3dc)

But the variable **rausgestellt** will always evaluate to **False**. 
So for **value.daysTo == 0** the sensor state is always **Heute** even though the input_boolean is set to **on**.
If I change the condition of the if statement to **(...) and rausgestellt == False %}** the sensor state changes to **Rausgestellt**.

I tested this code in the template tool of the dev section and there everything works fine:
![ha_template](https://github.com/mampfes/hacs_waste_collection_schedule/assets/154612657/fd03e276-c528-4fd7-898e-a4ab2081424c)

So is it maybe just possible to use limited templates here (therefore no is_state()) or am I overlooking something?

Thanks
Ben

**Comment by 5ila5** [comment]
The sensor is only updated when collections change, so your is_state function is only rendered once per day or at reboot.
You need to use something like this:

```yaml
sensor:
  - platform: waste_collection_schedule
    name: collection
    value_template: "{{ value.daysTo }}"
  - platform: template
    sensors:
      collection2:
        value_template: "{{ is_state('input_boolean.rausgestellt', 'on') }}, {{ states('sensor.collection') }}"
```
