### DISCUSSION TITLE
Source arguments for EBE Essen

### DISCUSSION THREAD

**Discussion by slartibartfass** [mampfes/hacs_waste_collection_schedule#1902] [Q&A]
Entsorgungsbetriebe Essen
https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfall_io.md

Doe anyone get EBE Essen to work with hacs_waste Collection.

The URL EBE delivers kind of..
_https://api.abfall.io/?key=51be67f3758f1fb57b420efe065c0663&mode=export&idhousenumber=9806&wastetypes=1146,66,42&timeperiod=20240101-20241231&showinactive=false&type=pdf_
or
_https://api.abfall.io/?key=51be67f3758f1fb57b420efe065c0663&mode=export&idhousenumber=12260&wastetypes=51,1146,66,177,42&timeperiod=20240101-20241231&showinactive=false&type=pdf_

So i got a **key** (51be67f3758f1fb57b420efe065c0663) parameters for **f_abfallarten** (51,66,117,42)
But where is
**f_id_kommune
f_id_bezirk
f_id_strasse
f_id_strasse_hnr**

**Comment by 5ila5** [comment]
The website uses the new API there is PR (#1802) open fixing this, but we could just support this by using the ICS source and add dedicated documentation for them (there is allready mechanism for that) needs to be done in the near future. You can just copy the ICS button URL and put it in the ICS source (then change the year with `{%Y}`) like 

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://api.abfall.io/?key=51be67f3758f1fb57b420efe065c0663&mode=export&idhousenumber=32918&wastetypes=51,1146,66,177,42,1826&timeperiod={%Y}0101-{%Y}1231&showinactive=false&type=ics
```

Alternativly they seem to still support the old API with an old key.
Huptstr. 15:

```
waste_collection_schedule:
  sources:
    - name: abfall_io
      args:
        key: 9b5390f095c779b9128a51db35092c9c
        f_id_kommune: 5844
        f_id_strasse: 1187
        f_id_strasse_hnr: 36146
```

You can generate this by cloning the repository and running the wizzard:

```bash
git clone https://github.com/mampfes/hacs_waste_collection_schedule
cd hacs_waste_collection_schedule

pip install inquirer 
# or
pip3 install inquirer

python custom_components/waste_collection_schedule/waste_collection_schedule/wizard/abfall_io.py
```
