### DISCUSSION TITLE
Sensor config: Should type be alias?

### DISCUSSION THREAD

**Discussion by pmharris77** [mampfes/hacs_waste_collection_schedule#1905] [Q&A]
I set up some customized aliases for my sources in my configuration.yaml like so:

``` yaml
waste_collection_schedule:
  sources:
  - name: welhat_gov_uk
    args:
      uprn: "*"
      postcode: "*"
     customize:
       - type: garden # source name
         alias: Garden Waste # my friendly name for  sensor state display
```

However, when I come to create sensors, it seems to be expecting the type field to be the source type **alias**, rather than the original source type  (e.g. it expects "Garden Waste" instead of "garden") - if I just use the source type, the sensors have an "Unknown" state.

``` yaml
- platform: waste_collection_schedule
  name: next_garden_bin_collection
  types:
    - Garden Waste  # garden (original source type name) does not work
  add_days_to: true
```

Is this expected behaviour, or a bug?  It doesn't seem to be documented anywhere that alias overrides the original source type name
