### DISCUSSION TITLE
Argument for Rhythm

### DISCUSSION THREAD

**Discussion by JohnnyVi** [mampfes/hacs_waste_collection_schedule#1909] [Q&A]
Hi,

I managed to make this integration work for Schwarzwald Baar Kreis (the street argument was a Teilort). 
Now I encountered a new problem: I have the "Restmüll" rhythm / intervals for 14 days set in my smartphone app. 
This integration seems to be showing the rhythm/interval for 4-week collection. 
Is there a way to make the integration choose the other interval/ pickup rhythm?
Any help would be greatly appreciated

**Comment by 5ila5** [comment]
This was a bug. The PR #1910 fixes this, you will see all collections with its rhythms appended (if relevant) you can then disable the ones you do not want using the customize: type:Type show:False 
```yaml
waste_collection_schedule:
    sources:
    - name: app_abfallplus_de
      args:
        app_id: APP ID
        city: STADT/KOMMUNE
        # ....
      customize:
        - type: TYPE
          show: False

        
```
syntax.

This will be part of release 1.47.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
