### DISCUSSION TITLE
All the "meetings" appears two times

### DISCUSSION THREAD

**Discussion by SavanFlou** [mampfes/hacs_waste_collection_schedule#1945] [Q&A]
Hello everybody,
so I am living in a smal town called Klein-Engersdorf in Austria, I used this fantastic tool to retrieve information but I noticed 2 things,
Here is my code.
In configuration.yaml

```yaml
#Waste Collection Schedule
waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "korneuburg"
        municipal: "Bisamberg"
        calendar: "Zone B"

```
in sensors.yaml
```yaml
#Schedule Waste Collection
- platform: waste_collection_schedule
  name: "poubelles"
  details_format: upcoming
  value_template: "in {{value.daysTo}} days"
```

I did not try for now to rename it, but will do in future. This works, I just have my zone reported in my calendar but

- first, I do not understand why but I always see 2 meetings even if, when I look in the state in the development tools, there should be only one.
 Attribute in the development tool.

```yaml
message: Biotonne
all_day: true
start_time: "2024-04-05 00:00:00"
end_time: "2024-04-06 00:00:00"
location: ""
description: ""
friendly_name: Die NÖ Umweltverbände
```
Do you have an idea about what I did wrong?
- We have a specific garbage pickup, the "restmüll 14 tage" which I did not buy let's say, but it appears just as a regular "restmüll" schedule, so I do not know how to exclude it. Do you have any idea?

> edit by @5ila5: fixed code blocks

**Comment by 5ila5** [comment]
The `calendar` has quite a hacky implementation, if you remove this argument you get the collections like shown on the webpage like `Bisamberg Zone B, Restmüll 14-tägig: Restmüll` the current implementation of calendar just looks if this string is part of the event text, splits this string by `:` and takes just the last element. This worked for all the regions I checked, but Bisamberg uses `,` as separator and lists multiple collections as one entry (first one I saw doing it this way).

So I added support for two additional arguments in #1947: `calendar_title_separator` and `calendar_splitter` which allow setting these kinds of separators manually without the need to rely on the hard-coded version.

So you will be able to use it like this:

```yaml
waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "korneuburg" # Korneuburg
        municipal: "Bisamberg" # Municipal
        calendar: "Zone B" # Rayon
        calendar_title_separator: ","
        calendar_splitter: ":"
```


This will be part of release 1.47.0 or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
