### DISCUSSION TITLE
Problems with exclude calendar events

### DISCUSSION THREAD

**Discussion by clipse2004** [mampfes/hacs_waste_collection_schedule#1951] [Q&A]
Hello everyone, 
I have a problem with hiding a calendar entry. It concerns the following events:

Gartenabfall , 16.00 - 18.00, Spielplatz, Igelsdorf
Gartenabfall  , 08.00 - 11.00, Galgenbrücke, Wellerstadt
etc.

Everything that comes after garden waste changes with each entry. How do I specify this in the config so that it ignores it? 
My config currently looks like this:

```yaml
waste_collection_schedule:
  sources:
    - name: erlangen_hoechstadt_de
      calendar_title: Müllabfuhr
      args:
        city: Baiersdorf
        street: Baiersdorf, Ort
      customize:
        - type: Restmülltonne
          show: true
          icon: mdi:trash-can
          alias: Restmüll & Biotonne
        - type: Papiertonne
          show: true
          icon: mdi:recycle
          alias: Papiertonne & Gelber Sack
        - type: Biotonne
          show: false
          icon: mdi:leaf
        - type: Gelber Sack
          show: false
          icon: mdi:recycle
        - type: Restmüllcontainer
          show: False
        - type: Gartenabfall
          show: False
        - type: Problemabfall
          show: False
        - type: Wertstoffcontainer
          show: False
```

So he successfully blinds me to the recycling container and problem waste
But how do I get it to ignore all events with "Gartenabfall" and not display them?

thanks guys

> edit by @5ila5: fixed code block
