### DISCUSSION TITLE
Suddenly stoped working - where can i get the logs to dig deeper into this?

### DISCUSSION THREAD

**Discussion by promufa** [mampfes/hacs_waste_collection_schedule#1991] [Q&A]
Similar issue to #1990 here. It was working fine for months and yesterday (17-Apr) around 18:00 everything turned to "unknown".
No updates to HA Core / Supervisor around that time that could have caused issues with the sensors.

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/57601488/a3f7cee2-e228-4dc3-a608-9eeb651b3673)

My config is below (lives inside the configuration.yaml):

```
waste_collection_schedule:
  sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.abfallappbh
        city: Schallstadt
        strasse: Alle Straßen

sensor:
  - platform: waste_collection_schedule
    #   source_index: SOURCE_INDEX
    name: Paper
    #    details_format: DETAILS_FORMAT
    #   count: COUNT
    leadtime: 7
    value_template: "{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}"
    #    date_template: DATE_TEMPLATE
    #    add_days_to: ADD_DAYS_TO
    #    event_index: EVENT_INDEX
    types:
      - Papier
      - Papier (verlegt)

  - platform: waste_collection_schedule
    #   source_index: SOURCE_INDEX
    name: Bio
    #    details_format: DETAILS_FORMAT
    #   count: COUNT
    leadtime: 7
    value_template: "{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}"
    #    date_template: DATE_TEMPLATE
    #    add_days_to: ADD_DAYS_TO
    #    event_index: EVENT_INDEX
    types:
      - Bio
      - Bio (verlegt)

  - platform: waste_collection_schedule
    #   source_index: SOURCE_INDEX
    name: Waste
    #   details_format: DETAILS_FORMAT
    #   count: COUNT
    leadtime: 7
    value_template: "{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}"
    #    date_template: DATE_TEMPLATE
    #    add_days_to: ADD_DAYS_TO
    #    event_index: EVENT_INDEX
    types:
      - Hausmüll
      - Hausmüll (verlegt)

  - platform: waste_collection_schedule
    #   source_index: SOURCE_INDEX
    name: Recycling
    #    details_format: DETAILS_FORMAT
    #   count: COUNT
    leadtime: 7
    value_template: "{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}"
    #    date_template: DATE_TEMPLATE
    #    add_days_to: ADD_DAYS_TO
    #    event_index: EVENT_INDEX
    types:
      - gelbe Tonne
      - gelbe Tonne (verlegt)
```

I am not sure if the source has changed but the android app did not have any updates recently and works fine.
Any help is appreciated as I am unable to even find the logs for the custom component.
