### DISCUSSION TITLE
ESG Soest source not found

### DISCUSSION THREAD

**Discussion by KazemaRyukuro** [mampfes/hacs_waste_collection_schedule#1996] [Q&A] [answered]
I currently have the problem that the HomeAssistant logs show that the source is not available. I don't know what to do. All in all, I would like to have a sensor for each type of waste to be able to display the different mushroom chips.

configuation.yaml:
```
waste_collection_schedule:
  sources:
    - name: esg-soest.de
      args:
        url: https://www.esg-soest.de/abfallkalender/moehnesee/anton-brune-weg/herunterladen
      customize:
        - type: Altpapier
          alias: Altpapier
          show: True
          icon: mdi:newspaper-variant-multiple
        - type: Biomüll
          alias: Biomüll
          show: True
          icon: mdi:leaf
        - type: Restmüll 14-täglich
          alias: Restmüll (14-täglich)
          show: True
          icon: mdi:trash-can
        - type: Restmüll 4-wöchentl.
          alias: Restmüll (monatlich)
          show: True
          icon: mdi:delete-circle
        - type: Gelber Sack
          alias: Gelber Sack
          show: True
          icon: mdi:recycle
      calendar_title: Abfallkalender Möhnesee
```

#sensors
```
- platform: waste_collection_schedule
    name: Altpapier
    count: "3"
    types:
      - Altpapier
  - platform: waste_collection_schedule
    name: Biomüll
    count: "3"
    types:
      - Biomüll
  - platform: waste_collection_schedule
    name: Restmüll 14-täglich
    count: "3"
    types:
      - Restmüll 14-täglich
  - platform: waste_collection_schedule
    name: Restmüll 4-wöchentl.
    count: "3"
    types:
      - Restmüll 4-wöchentl.
  - platform: waste_collection_schedule
    name: Gelber Sack
    count: "3"
    types:
      - Gelber Sack
```

Logs

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:192
Integration: waste_collection_schedule (Dokumentation)
Erstmals aufgetreten: 19. April 2024 um 23:46:39 (1 Vorkommnisse)
Zuletzt protokolliert: 19. April 2024 um 23:46:39

source not found: esg-soest.de
```

**Comment by 5ila5** [comment]
The name argument is the name of the source (script) used to get the data. It needs to be `ics` in your case. You can set a custom name with the `calendar_title` argument.

**Reply by KazemaRyukuro** [reply]
That's what I did. But he has a problem with the source and I don't know why.

**Reply by 5ila5** [reply, marked as answer]
you need to use 
```yaml
waste_collection_schedule:
  sources:
    - name: ics # NOT esg-soest.de
      args:
        url: https://www.esg-soest.de/abfallkalender/moehnesee/anton-brune-weg/herunterladen
# .....
```

If you already did this and still encounter problems, please post your new configuration and new logs
