### DISCUSSION TITLE
HA newbie struggling to get this working at all

### DISCUSSION THREAD

**Discussion by Sodgester** [mampfes/hacs_waste_collection_schedule#2079] [Q&A]
Hi, I've added the sources and sensors to configuration. I'm not getting any errors when rebooting, but also not getting any data either. I've tested the providers website and that seems ok. I can add to dash board but is just shows "up-to-date", no details of any services.

My configuration is below. I've tried to keep it as simple as possible to test basic connection first. Also tried to run the test_sources.py file from the terminal and got a bad command error.

```yaml
waste_collection_schedule:
 sources:
    - name: maldon_gov_uk
      args:
        uprn: "100090562169"
      customize:
        - type: Recycling
        - type: Refuse Collection
        - type: Green
        - type: Food
sensor:
    - platform: waste_collection_schedule
      name: Recycling
      details_format: upcoming
      value_template: 'in {{value.daysTo}} days'
```

Any help gratefully received, thanks!
