### DISCUSSION TITLE
Entity date switches to next date too early?

### DISCUSSION THREAD

**Discussion by dergreg** [mampfes/hacs_waste_collection_schedule#2093] [Q&A]
Hi, so I have this entity here which used to have a next collection date of 17.05.2024. The value however switched to the next one, 31.05.2024 already on the 16.05.2024 at around 19:51.

Why is this? Additionally, the `days_to `went up from 1 to 15 at this time.

<img width="576" alt="Bildschirmfoto 2024-05-16 um 22 08 26" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/39279568/b9cf9fe5-a2ad-4956-8a1e-1240eff3b1ca">

The calendar this perfectly shows tommorrow's date:

<img width="277" alt="Bildschirmfoto 2024-05-16 um 22 21 00" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/39279568/cbaa4353-999a-44b2-8794-e0349b8a672b">

The sensor has no special configuration, pretty standard:

```
  - platform: waste_collection_schedule
    name: BEST_Abfuhr_Biotonne
    event_index: 2
    add_days_to: True
    value_template: '{{value.types|join(", ")}}|{{value.daysTo}}|{{value.date.strftime("%d.%m.%Y")}}|{{value.date.strftime("%a")}}'
    types:
      - Biotonne
```

**Comment by 5ila5** [comment]
That's odd, did you set the `day_switch_time` of the source? (this should not happen no matter what the day_switch_time is set) I will try to reproduce this later

**Comment by dergreg** [comment]
I did set the `day_switch_time` on the evening when the schedule switched, I'm not sure if it was one 19:51, though. That's how the sensor is currently configured:

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://xxx"
      customize:
        - type: Graue Tonne
        - type: Gelbe Tonne
        - type: Biotonne
        - type: Papiertonne
  day_switch_time: "06:00"
```
