### DISCUSSION TITLE
How to get a list of the upcoming dates?

### DISCUSSION THREAD

**Discussion by superpower10** [mampfes/hacs_waste_collection_schedule#2109] [Q&A]
I want to to tap/click on the entity and get a formatted list of dates of the upcoming dates of the that garbage type. Something like this:

```
Restmüll:
Donnerstag, 13. Juni 2024
Donnerstag, 27. Juni 2024
Donnerstag, 11. Juli 2024
```
Can anybody know how to do this?

**Comment by 5ila5** [comment]
You can just create a sensro like this:

```yaml
sensor:
  - platform: waste_collection_schedule
    name: NAME
    details_format: upcoming #optional (alternatives: 'appointment_types', 'generic', 'hidden')
    #types: # optional
    #  - Waste Type 1
    #  - Waste Type 2
    # .....
```

[detailed documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#configuring-sensors)

You should then see the list in the attributes section of the sensor like shown in the images in the [`Options for details_format parameter` table](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#options-for-details_format-parameter):

![image](https://github.com/mampfes/hacs_waste_collection_schedule/raw/master/images/more-info-upcoming.png)

![image](https://github.com/mampfes/hacs_waste_collection_schedule/raw/master/images/more-info-appointment-types.png)
