### DISCUSSION TITLE
Show collection is today (Not unknown)

### DISCUSSION THREAD

**Discussion by Spookster** [mampfes/hacs_waste_collection_schedule#2131] [General]
With the standard code, if **today** is the collection day, the output is 'unknown'
Im no expert in code, so how do we make it show 'Today' instead of unknown?

```
- platform: waste_collection_schedule
  name: waste_recycle
  value_template: '{{value.date.strftime("%a")}}, {{value.date.strftime("%d/%m/%Y")}}'
  types:
    - recycle
```

**Comment by 5ila5** [comment]
Generally if you would want to show Today instead of the date you could use a value_template like `{% if now().date() == value.date %}Today{% else %}{{value.date.strftime("%a")}}, {{value.date.strftime("%d/%m/%Y")}}{% endif %}`

But if the sensor gets Unknown, this probably means that there is no collection in the calendar (probably because the source does not get dates for the current date for some reason). If you could say which source you're using, I could take a look at the code.

**Comment by Spookster** [comment]
The source is:

```
waste_collection_schedule:
  sources:
    - name: aucklandcouncil_govt_nz
      args:
        area_number: 12343515470
```

It did seem odd that the dates prior to and after the collection day were normal.

**Reply by 5ila5** [reply]
Seems to look fine for me still showing the dates as expected. Do you see events of Today in your calendar?

I think it's something different the integration only shows the next collection and the default behavior is to not show collections on the current day after `day_switch_time` ([configuration details](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#configuring-sources)), which defaults to 10:00 AM. So your sensor probably switches to UNKNOWN at 10:00 AM and refetches the new collection dates in the night at the next day. If you just set the `day_switch_time` to 23:59 the sensor should not go to UNKNONW on the collection date

**Comment by silkit** [comment]
Adding to this post as i have exactly the same issue and was looking for an answer. I have tried to incroporate the day switch trigger, but it has not made any difference

My calendar is showing a collection today:
![Screenshot 2024-08-13 124545](https://github.com/user-attachments/assets/8a707fe9-4b35-4a06-9150-dd8e91bed076)

But the output is "unknown"
![Screenshot 2024-08-13 124611](https://github.com/user-attachments/assets/9e3990f2-5f3e-4926-8e13-22f5d6254906)

It is this "unknown" i would like to change so it reads "Today". so i think @Spookster  was onto something with the value template.
Would @5ila5 suggestion work to resolve this please?
Thanks

```yaml
waste_collection_schedule:
    sources:
    - name: wealden_gov_uk
      args:
        uprn: "10033417169"
      customize:
        - type: Rubbish
        - type: Recycling
day_switch_time: 23:59

sensor:        
  - platform: waste_collection_schedule
    name: Rubbish
    details_format: upcoming
    value_template: 'Due in {{value.daysTo}} days'
    types:
      - Rubbish
  - platform: waste_collection_schedule
    name: Recycling
    details_format: upcoming
    value_template: 'Due in {{value.daysTo}} days'
    types:
      - Recycling
```
