### DISCUSSION TITLE
show Tomorrow & Today instead of 1 days & 0 days to collection

### DISCUSSION THREAD

**Discussion by woody166** [mampfes/hacs_waste_collection_schedule#2154] [Q&A]
How do I display the words Tomorrow or Today for a collection instead of 1 days or 0 days?

**Comment by 5ila5** [comment]
[FAQ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/faq.md) 3rd question

**Reply by woody166** [reply]
thank you, greatly appreciate you pointing me at the solution and my bad for not looking there first.

**Reply by tarek-moustafa** [reply]
Guys, I'm new here. where do i do such changes? @5ila5 @woody166

**Reply by 5ila5** [reply]
If you configured the source through the GUI you can find the Sensor configuration by clicking configure next to your configured source. You can then select an existing sensor or to create a new one and click next. There you can make these changes.

For YAML configuration, you can find all information here: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#configuring-sensors

The GUI configuration has basically the same options as the YAML configuration, so you can use the docs as a reference for GUI configuration too.

**Comment by woody166** [comment]
ok so now I've lost the the value.type when changing the value_template to 
value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'
<img width="446" alt="Screenshot 2024-06-20 at 00 21 06" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/58831155/ab7680ea-097a-43b4-bb15-51ad451221b0">

How do I show which bin(s) is/are due to be collected.  

If I remove the above live then it reverts back to normal showing "(bin type) in X days"
<img width="446" alt="Screenshot 2024-06-20 at 00 23 37" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/58831155/f532f328-6e11-46ff-b9a5-b985a49fb078">


if I add {{value.types}} and enclose the whole line in "" then I get ['(Bin type)'] Tomorrow  but I just want (bin type) Tomorrow
value_template: "{{value.types}} {% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}"

<img width="446" alt="Screenshot 2024-06-20 at 00 18 22" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/58831155/aa55dbd1-aa40-4b60-89fa-9c7d52508cdb">

**Reply by 5ila5** [reply]
value.types is a list (of all collections due at this date), so you get this python notation of a list (in your case, with only one item). You can use {{value.types|join(", ")}} to join the list with `, ` (converts the list to a string and puts `, ` between elements)

**Reply by woody166** [reply]
Hey there,

I already have a sensor that shows the value types and whether it's 1 or 2 bin collections (see attachment), so I don't think I need the join command.

![Screenshot 2024-06-20 at 20 41 33](https://github.com/mampfes/hacs_waste_collection_schedule/assets/58831155/60ebd1ba-10bd-4f86-80d1-b02edc6e9951)

So just want it to show "Gary bin Tomorrow/Today" or "Blue bin, Green bin Tomorrow/Today" this is where I'm struggling as I don't know python (maybe it's time I learnt it, lol)

Appreciate you help on this so far :-)

This is the code in my sensors.yaml file:

```yaml
- platform: waste_collection_schedule
  source_index: 0
  name: Next bin
  details_format: upcoming
  # returns "Today" if value.daysTo == 0
  # returns "Tomorrow" if value.daysTo == 1
  # returns "in X days" if value.daysTo > 1
  #value_template: "{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}"
  add_days_to: true
  types:
    - Grey bin
    - Blue bin
    - Brown bin
    - Green bin
  #
- platform: waste_collection_schedule
  source_index: 0
  name: Grey Bin
  details_format: upcoming
  add_days_to: true
  types:
    - Grey bin
    #
- platform: waste_collection_schedule
  source_index: 0
  name: Green Bin
  details_format: upcoming
  add_days_to: true
  types:
    - Green bin
  #
- platform: waste_collection_schedule
  source_index: 0
  name: Brown Bin
  details_format: upcoming
  add_days_to: true
  types:
    - Brown bin
  #
- platform: waste_collection_schedule
  source_index: 0
  name: Blue bin
  details_format: upcoming
  add_days_to: true
  types:
    - Blue bin
```

**Reply by 5ila5** [reply]
I don't quite understand your problem you know how to write which bins are next (using join to convert this list to a string) and you know how to show Today/Tomorrow/in .. days. So you can just combine them:

```yaml
  # shows 'Grey bin Today' if only Grey is due Today or 'Grey bin, Green bin Tomorrow' or 'Grey bin, Green bin in 8 days' if Grey and Green are due at the same day
  value_template: "{{value.types|join(", ")}} {% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}"

  #  shows 'Grey bin Today' .... or 'Grey bin Tomorrow' even though Grey and Green are due at the same day (only takes first element just throws away everything else)
   value_template: "{{value.types[0]}} {% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}"
```
