### DISCUSSION TITLE
please add city kummerfeld

### DISCUSSION THREAD

**Discussion by marv4u** [mampfes/hacs_waste_collection_schedule#2172] [Ideas]
Hey @all
first of all thanks for all the work going into this!

can u please add the city "kummerfeld", its just not working for my place :/

its part of the bigger city pinneberg 25421 but has its own name kummerfeld 25495.

i cant get working result for my street "ophof" in "kummerfeld 25495"

thanks!

**Comment by 5ila5** [comment]
For the abfallnavi_de you need to specify a street but kummerfeld seems to only report the street `alle Straßen` so you need this as street parameter. I just made `strasse` an optional parameter for those cases, but it will only be part of the next release. (#2178)

You currently can use this:

```yaml
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: pi
        ort: Kummerfeld
        strasse: alle Straßen
```

Alternatively, you can use the ICS source (copy the link of the ICAL-Export button) and use this configuration:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://abfallkalender.regioit.de/kalender-pi/downloadfile.jsp?format=ics&jahr=2024&ort=Kummerfeld&strasse=14838433&fraktion=0&fraktion=1&fraktion=2&fraktion=4&fraktion=5&fraktion=7&fraktion=9"
```
