### DISCUSSION TITLE
After HA update - from 2024.6.x to 2024.7.x - waste collection schedule doesnt work anymore

### DISCUSSION THREAD

**Discussion by Expello** [mampfes/hacs_waste_collection_schedule#2364] [Q&A]
Hi,

this is the error:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 31. Juli 2024 um 01:46:44 (2 Vorkommnisse)
Zuletzt protokolliert: 01:26:21

fetch failed for source Zweckverband Abfallwirtschaft Region Hannover: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/aha_region_de.py", line 103, in fetch raise Exception( Exception: Invalid response from server, check you configuration if it is correct.
```

Config is:

```yaml
waste_collection_schedule:
  sources:
    - name: aha_region_de
      args:
        gemeinde: Neustadt a. Rbge.
        strasse: Kornstr. / Neustadt
        hnr: "26"
        zusatz: ""
```

   
Anyone have an idea to solve the problem?

Thanks a lot!
        

![image](https://github.com/user-attachments/assets/451c71b3-954d-4dde-b49d-88b302e5a6cd)
