### DISCUSSION TITLE
Next Collection Date in the past - How to handle in code?

### DISCUSSION THREAD

**Discussion by DavidSpackman** [mampfes/hacs_waste_collection_schedule#2516] [Q&A]
Hi, 

I created the source for knox_vic_gov_au
I have realised that the source website does not update the next collection date immediately and still shows the "previous" collection date for an unknown amount of time.

i.e. It is the 21 August now, and the website is still reporting "Next collection is 20 August 2024"
This breaks HA sensors like below

```
  - platform: waste_collection_schedule
    name: Rubbish knox_vic_gov_au
    details_format: appointment_types
    add_days_to: true
    types:
      - Rubbish
```
      
Usually they would have the value "[wastetype] in [x] days", instead their state becomes "unknown"

Is this something that I should look at addressing in the hacs_waste_collection_schedule source for knox_vic_gov_au, or is how I have configured my HA sensors?
