### DISCUSSION TITLE
Die NÖ Umweltverbände (Schwechat) no calendar entry possible

### DISCUSSION THREAD

**Discussion by mparal** [mampfes/hacs_waste_collection_schedule#2599] [Q&A]
Hello,
I kindly ask you to review this page: https://schwechat.umweltverbaende.at/?gem_nr=32419&jahr=2024&kat=32
There is no appropriate calendar entry possible.  In the 3th colume (seperator ",")  there are only 2 characters in order to point out  the waste-variety. 
For example I will need  R2 B3 A5 and GS1 to cover all waste schedules.
I ask you kindly for a hint how I can cover this.
Thks in advance !

**Comment by 5ila5** [comment]
There is something more wrong than just the calendar selector, The table is formatted diffent than every other table from umwetlverbaende.at I've seen so far and it's even different from the other schwechat tables, which seem to be formatted correctly.
I Fixed this in #2600


## If the table would be formatted correctly (or after WCS update):

### YAML

In the YAML config, you can just configure multiple calendar entities

```yaml
waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "schwechat"
        municipal: "Schwechat"
        calendar:
          - R 2
          - B 3
          - A 5
          - S 1
          - G 1
```

### GUI/config_flow

The source did not communicate the type of the variable so the GUI defaultet to a text input filed. I changed thins in #2600 and you will be able to select multiple calendar entires after the WCS update.


## WCS Update:

This will be part of the next release or is available now as master (git) version 

install master/git: Developer tools -> actions -> select `update: Install update` -> click `Coose entity` and select WCS -> select `version` and type `master` in the input field -> run the action -> restart HA

install master with HACS version < 2.0: (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)
