### DISCUSSION TITLE
Bug? Calendar does not show up anymore

### DISCUSSION THREAD

**Discussion by tobiasmuecksch** [mampfes/hacs_waste_collection_schedule#2627] [Q&A] [answered]
Hey there,

after working perfectly fine for a while, the waste calendar doesn't show up anymore. The sensors still work as expected, the Calendar menu item (on the left) is still there, but the calendar is empty:

<img width="1667" alt="image" src="https://github.com/user-attachments/assets/977c209f-ac22-4773-8009-7cb9fea958ff">

This is my configuration:

```yaml

### Abfallkalender
waste_collection_schedule:
  sources:
    - name: ics
      calendar_title: "Abfallkalender"
      args:
        url: webcal://neu-isenburg.mein-abfallkalender.online/ical.ics?***PRUNED FOR SECURITY REASONS***
      customize:
        - type: Hausmüll 7 tägig
          show: false
        - type: Hausmüll 14 tägig
          alias: Hausmüll

sensor:
# Nächste Abholung Gelber Sack
  - platform: waste_collection_schedule
    name: "Gelber Sack"
    value_template: '{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    types:
      - Gelber Sack
  # Nächste Abholung Biomüll
  - platform: waste_collection_schedule
    name: "Biomüll"
    value_template: '{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    types:
      - Biomüll
  # Nächste Abholung Altpapier
  - platform: waste_collection_schedule
    name: "Altpapier"
    value_template: '{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    types:
      - Altpapier
  # Nächste Abholung Hausmüll
  - platform: waste_collection_schedule
    name: "Hausmüll"
    value_template: '{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    types:
      - Hausmüll

```

Is my configuration wrong? Or is it a bug? How can I debug this further?
