### DISCUSSION TITLE
XMLURL config > unavailable?

### DISCUSSION THREAD

**Discussion by nuki47** [mampfes/hacs_waste_collection_schedule#2967] [Q&A]
What's wrong with my configuration?

```
waste_collection_schedule:
  sources:
    - name: data_umweltprofis_at
      args:
        xmlurl: https://data.umweltprofis.at/opendata/AppointmentService/AppointmentService.asmx/GetTermineForLocationSecured?Key=TEMPKeyabvvMKVCic0cMcmsTEMPKey&StreetNr=96127&HouseNr=Alle&intervall=2-wöchentlich
      customize:
        - type: Hausabfall
          alias: restabfall 
          icon: midi:trash-can
        - type: Biotonne
          alias: bioabfall
          icon: midi:trash-can
        - type: Gelber Sack
          alias: gelbersack
          icon: midi:recycle
        - type: Papiertonne
          alias: Papiertonne
          icon: midi:recycle
      calendar_title: Abfallkalender    
  fetch_time: "04:00"
  day_switch_time: "11:00"

```
