### DISCUSSION TITLE
How do I use the attribute customize with the multiple source wrapper?

### DISCUSSION THREAD

**Discussion by s-b-n** [mampfes/hacs_waste_collection_schedule#3109] [Q&A] [answered]
Hello,

I'm trying to setup two "normal" sources with the multiple source wrapper and can't figure out, how to add customize to the sources to rename the events and choose desired icons.

Working code with the multiple wrapper:
```
waste_collection_schedule:
  sources:
    - name: multiple
      args:
        bsr_de:
          abf_strasse: !secret bsr_street
          abf_hausnr: !secret bsr_house_number
        berlin_recycling_de:
          username: !secret berlin_recycling_user
          password: !secret berlin_recycling_password
      calendar_title: "waste_collection"
  fetch_time: "03:30"
  random_fetch_time_offset: 60
  day_switch_time: "10:30"
``` 

Working yaml with customize but without the multiple wrapper (so seperate calendars):
```
waste_collection_schedule:
  sources:
    - name: bsr_de
      args:
        abf_strasse: !secret bsr_street
        abf_hausnr: !secret bsr_house_number
      customize:
        - type: "Abholung Hausmüll"
          alias: "Restmüll"
          icon: mdi:trash-can
          use_dedicated_calendar: true
          dedicated_calendar_title: "waste_general"
        - type: "Abholung Biogut"
          alias: "Biomüll"
          icon: mdi:leaf-circle
          use_dedicated_calendar: true
          dedicated_calendar_title: "waste_bio"
        - type: "Abholung Wertstoffe (Abholung durch ALBA)"
          alias: "Gelber Sack"
          icon: mdi:recycle
          use_dedicated_calendar: true
          dedicated_calendar_title: "waste_recycling"
    - name: berlin_recycling_de
      args:
        username: !secret berlin_recycling_user
        password: !secret berlin_recycling_password
      customize:
        - type: "5.01 Altpapier, gemischt"
          alias: "Papiermüll"
          icon: mdi:newspaper-variant
          use_dedicated_calendar: true
          dedicated_calendar_title: "waste_paper"
  fetch_time: "03:30"
  random_fetch_time_offset: 60
  day_switch_time: "10:30"
``` 

Can anybody help me integrate the customize attribute into the multiple wrapper config to get the renamed events into one calendar?

Thanks! :)

**Comment by 5ila5** [comment, marked as answer]
It should work exactly like with the normal sources but you need to put all customize entries in a single customize block with the same indent as args:


```yaml
waste_collection_schedule:
  sources:
    - name: multiple
      args:
        bsr_de:
          abf_strasse: !secret bsr_street
          abf_hausnr: !secret bsr_house_number
        berlin_recycling_de:
          username: !secret berlin_recycling_user
          password: !secret berlin_recycling_password
      customize:
        - type: "5.01 Altpapier, gemischt"
          alias: "Papiermüll"
          icon: mdi:newspaper-variant
          use_dedicated_calendar: true
          dedicated_calendar_title: "waste_paper"
        - type: "Abholung Hausmüll"
          alias: "Restmüll"
          icon: mdi:trash-can
          use_dedicated_calendar: true
          dedicated_calendar_title: "waste_general"
        - type: "Abholung Biogut"
          alias: "Biomüll"
          icon: mdi:leaf-circle
          use_dedicated_calendar: true
          dedicated_calendar_title: "waste_bio"
        - type: "Abholung Wertstoffe (Abholung durch ALBA)"
          alias: "Gelber Sack"
          icon: mdi:recycle
          use_dedicated_calendar: true
          dedicated_calendar_title: "waste_recycling"
```

**Reply by s-b-n** [reply]
Thank you so much for the quick reply and the solution! It works perfectly now! I always tried to include one customize block for each source. Maybe the example in the documentation could be improved to include the customize option?

Your code example includes the "use_dedicated_calendar" option, I removed that and got a working config now. Thanks again!

For reference if anybody is searching for the same, here is my working config:
```
waste_collection_schedule:
  sources:
    - name: multiple
      args:
        bsr_de:
          abf_strasse: !secret bsr_street
          abf_hausnr: !secret bsr_house_number
        berlin_recycling_de:
          username: !secret berlin_recycling_user
          password: !secret berlin_recycling_password
      customize:
        - type: "5.01 Altpapier, gemischt"
          alias: "Papiermüll"
          icon: mdi:newspaper-variant
        - type: "Abholung Hausmüll"
          alias: "Restmüll"
          icon: mdi:trash-can
        - type: "Abholung Biogut"
          alias: "Biomüll"
          icon: mdi:leaf-circle
        - type: "Abholung Wertstoffe (Abholung durch ALBA)"
          alias: "Gelber Sack"
          icon: mdi:recycle
      calendar_title: "waste_collection"
  fetch_time: "03:30"
  random_fetch_time_offset: 60
  day_switch_time: "10:30"
```
