### DISCUSSION TITLE
Sensor values unavailable

### DISCUSSION THREAD

**Discussion by nuki47** [mampfes/hacs_waste_collection_schedule#3222] [Q&A] [answered]
Core: 2024.12.3
Supervisor: 2024.11.4
OS Version: HA 14.0

I use an ics file with the data:
```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/abfallkalender.ics"
 customize:
        - type: Restabfall (2-wöchentlich)
          alias: restabfall 
          icon: midi:trash-can
```

Sensor:
```
- platform: waste_collection_schedule
    name: Restabfall
    details_format: "upcoming"
    value_template: '{{ value.daysTo }}'
    add_days_to: True
    types:
      - restabfall
```

but the sensor state is unavailable

abfallkalender.ics

```
BEGIN:VCALENDAR
METHOD:PUBLISH
PRODID:-//GEM2GO//iCalendar MIMEDIR//EN
VERSION:2.0
BEGIN:VEVENT
DTEND;VALUE=DATE:20241228
DTSTAMP:20241216T054020Z
DTSTART;VALUE=DATE:20241227
GEO:48.231611;13.939501
SEQUENCE:0
SUMMARY:Restabfall (2-wöchentlich)
TRANSP:TRANSPARENT
UID:8e943d72-5aa6-4d4d-8423-f1afed5b7d9b
END:VEVENT

```

**Comment by 5ila5** [comment]
Is the customize indentation an copy paste error?
indentation needs to be as foolows:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/abfallkalender.ics"
       customize:
        - type: Restabfall (2-wöchentlich)
          alias: restabfall 
          icon: midi:trash-can
```

The type in the senosr needs to be written exaclty like shown in your calendar. Whats the name of the event in your Calendar?
