### DISCUSSION TITLE
incomplete import of ICS File

### DISCUSSION THREAD

**Discussion by NongJoWo** [mampfes/hacs_waste_collection_schedule#3258] [Q&A] [answered]
Hi all,

I am currently updating the waste calendar for 2025. However, I have the problem that the dates are only included up to December 11th, 2025. The last dates for December 24th and 30th are missing. Unfortunately, I cannot add a date manually. But the ICS file contains all data up to end of 2025.

I integrated it via the configuration.yaml

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: `"www/abfallkalender_2025.ics"
```

It would be great if someone has an idea.

Many thanks!
Joerg
