### DISCUSSION TITLE
Heinz Entsorgung Freising with Linked ICS Source

### DISCUSSION THREAD

**Discussion by nobbilie** [mampfes/hacs_waste_collection_schedule#3380] [Q&A]
Hallo zusammen,

ich habe mein wcs eingerichtet wie es in der Beschreibung steht. Ich habe auch den korrekten Kalender auf der Providerseite bekommen und dieser würde theoratisch auch in Home Assistant funktionieren (getestet über ICS Upload). Leider zeigt es mir nichts an in Home Assistant wenn ich die Daten eintrage in der config yaml (Neustarts sind immer erfolgt).

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://www.heinz-entsorgung.de/wp-includes/heinz_forms/Abfuhrkalender/php/query.php?ICAL=1&ORT=GShFyZhBiLkBiLBBXblBgc==&STRASSE=2VsFHZldwZ==&ERINNERUNG=-6&ISERINNERUNG=true&Jahr=2025&FRAKTIONEN=W3siZnJha3Rpb24iOiJSZXN0YWJmYWxsIn0seyJmcmFrdGlvbiI6IkdlbGJlciBTYWNrIn0seyJmcmFrdGlvbiI6IlBhcGllciJ9XQ==

sensor:
  # ------- Garbage Collection -------
  # next collection
  - platform: waste_collection_schedule
    name: "Nächste Abholung"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
  # Nächste Restmüll-Abholung
  - platform: waste_collection_schedule
    name: "Restmüll"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Restmüll
    # Nächste gelber-Sack Abholung
  - platform: waste_collection_schedule
    name: "Gelber Sack"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Gelber Sack
  # Nächste Papiermüll Abholung
  - platform: waste_collection_schedule
    name: "Papier"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Papiertonne
```

How do I get this to work?

I have also tried the example configuration - this is also not displayed.

https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/heinz_entsorgung_de.md

And here is the error log:

Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:366
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 15:54:27 (4 Vorkommnisse)
Zuletzt protokolliert: 15:54:27

Error while setting up waste_collection_schedule platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/waste_collection_schedule/sensor.py", line 147, in async_setup_platform
    raise ValueError(
        f"source_index {i} out of range (0-{len(api.shells) - 1}) please check your sensor configuration"
    )
ValueError: source_index 0 out of range (0--1) please check your sensor configuration

Second error log:

Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:226
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 16:09:45 (1 Vorkommnisse)
Zuletzt protokolliert: 16:09:45

error loading source ics: No module named 'icalendar.windows_to_olson' Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 217, in create source_module: SourceModule = importlib.import_module( ~~~~~~~~~~~~~~~~~~~~~~~^ f"waste_collection_schedule.source.{source_name}" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func return func(*args, **kwargs) File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module return _bootstrap._gcd_import(name[level:], package, level) ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap>", line 1387, in _gcd_import File "<frozen importlib._bootstrap>", line 1360, in _find_and_load File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 935, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 1026, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 15, in <module> from waste_collection_schedule.service.ICS import ICS File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 7, in <module> from icalevents import icalevents File "/usr/local/lib/python3.13/site-packages/icalevents/icalevents.py", line 3, in <module> from .icalparser import parse_events, Event File "/usr/local/lib/python3.13/site-packages/icalevents/icalparser.py", line 18, in <module> from icalendar.windows_to_olson import WINDOWS_TO_OLSON ModuleNotFoundError: No module named 'icalendar.windows_to_olson'
