### DISCUSSION TITLE
how to use both: gui and yaml for configuration ?

### DISCUSSION THREAD

**Discussion by perlchamp** [mampfes/hacs_waste_collection_schedule#3595] [General]
Hello out there,
Is it possible to configure waste collection schedule using both GUI and yaml?
What I did:
I installed waste Collection schedule via HA -> Settings -> Devices & Services -> +Add Integration -> waste Collection schedule, and during installation I specified the service operator, the country, the URL to the .ics file and the name of the calendar . I also specified that a simple calendar should be created (Show garbage type customization menu and Show sensor configuration NOT selected). Then HA restarted.

After the restart everything was fine, the calendar was displayed and was also filled with the relevant data.

Then I did the complete configuration in Studio Code Server via yaml and also created the sensors and templates. However, I now see two calendars with the same name, only the entity ID is different (calendar.ebs and calendar.ebs_2).

This really annoys me. I had previously integrated waste collection schedule into HA without GUI installation (via yaml) and everything went well. The only downside was that waste collection schedule was not listed among the integrations in HA (in HACS it was). I wanted to change this. Now I have two identical calendars.

QUESTION:
Is there a way to install/configure waste collection schedule via GUI and yaml without duplicated calendars?
Is there a way to show waste collection schedule in HA under Devices & Services as an integration if it has only been installed/configured via yaml?

Who can help me?

**Comment by 5ila5** [comment]
You can use both, but only if you create a separate source for GUI and YAML configuration. You cannot add sensors in YAML for sources configured in the GUI. But you can do everything you did in the YAML configuration in the GUI configuration (except multiple source wrapper and sensors taking data from multiple sources). 

You should either configure your source (with customizes) + sensors in YAML or configure your source (with customizes) + sensors in the GUI. You can add/modify sensors and customizes in the GUI by clicking the `Customize` button next to your configured source. Or select `Show garbage type customization menu`/`Show sensor configuration menu` on initial setup

**Reply by perlchamp** [reply]
hm...
i'm still testing, but seams to work (without customized sensor or any sensor at all). The calendar seams to work. Next step is to customize one sensor and seeing what will happen.
What i did:
gui-integration of wcs with only given country and url(ics) -> Restart HA -> rename via GUI from 'Gipsprojekt' to 'EBS Speyer' and deaktivate (via Gui). Then in the configuration.yaml:
`waste_collection_schedule: !include waste-collection-schedule.yaml `
and in waste-collection-schedule.yaml:
```
sources: 
  - name: EBS Speyer
    args:
      url: https://www.stadtwerke-speyer.de/speyerGips/Gips?SessionMandant=Speyer&Anwendung=Abfuhrkalender&Methode=TermineAnzeigenICS&Mandant=Speyer&Abfuhrkalender=Speyer{%Y}&Bezirk_ID=17&Jahr={%Y}
    calendar_title: "EBS Speyer"
    day_offset: 0
fetch_time: "01:16"
random_fetch_time_offset: 15
day_switch_time: "15:00" 
separator: "," 
```
Then i activatet via GUI -> one calendar ! 
Let's see what will happen after customizing the first sensor via yaml. All will configurated via yaml...

So long
Pc
