### DISCUSSION TITLE
Ich bekomme absolut keine Sensorwerte

### DISCUSSION THREAD

**Discussion by moonsorrox** [mampfes/hacs_waste_collection_schedule#3606] [General]
Guten Tag,
ich habe in den letzten beiden Wochen so meine ich 2 Update von waste collection gehabt.
Mit der neuen Homeassistent Version 2025.1.2 habe ich jetz absolute Probleme, habe es schon 2x deinstalliert und wieder installiert, aber keine Sensor Werte.

Auf einem Testsystem habe ich es installiert und sofort funktioniert es und ich bekomme Abfal Sensorwerte.

Auf meinem Produktiv System keine Chance.
Gleich anfang Januar gab es dazu ja etwas das man Zeilen löschen mußte dann hat es wieder funktioniert.
Mittlerweilelhabe ich die Waste Collection Version 2.6.0 drauf und ich habe keine Sensore Werte mehr.

Wo muss ich jetzt eingreifen das ich wieder Sensoren bekomme, denn ein deinstallieren hat nicht geholfen.
Hier mal der Code:

configuration.yaml

```yaml
#-----------------------------------------------------------
#   .. Müllabfuhr - AKTUELL
#-----------------------------------------------------------
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/muell/Abfallkalender.ics"

```
sensor.yaml

```yaml
- platform: waste_collection_schedule
  name: "Nächste Abholung"
  value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
  details_format: "upcoming"
#  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
#  value_template: >-
#    {% set wochentag = ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"] %}
#    {% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} In {{value.daysTo}} Tagen ( {{ wochentag[1] }}, den {{value.date.strftime("%d.%m.%Y")}} ){% endif %}


#--------------------------------------------------------------------
# --- Sensor für das Template "sensor.abfall_termine_template"
#--------------------------------------------------------------------
- platform: waste_collection_schedule
  name: Naechster
  details_format: "upcoming"
  value_template: '{{ value.daysTo }}'
#  value_template: '{% if value.daysTo == 0 %} Heute {% elif value.daysTo == 1 %} Morgen {% else %} in {{value.daysTo}} Tagen am {{value.date.strftime("%d.%m.%Y")}} {% endif %}'
#  value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
  add_days_to: True


#-----------------------------------------------------------
# --- Sensor Restabfall ---
#-----------------------------------------------------------
- platform: waste_collection_schedule
  name: Restabfall # SensorName
  details_format: "upcoming"
  value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
    - Restabfall # so steht es im Abfallkalender


#-----------------------------------------------------------
# --- Sensor Papier ---
#-----------------------------------------------------------
- platform: waste_collection_schedule
  name: Papier # SensorName
  details_format: "upcoming"
  value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
    - Papier # so steht es im Abfallkalender

#-----------------------------------------------------------
# --- Sensor Gelbe Tonne ---
#-----------------------------------------------------------
- platform: waste_collection_schedule
  name: Gelbe Tonne # SensorName
  details_format: "upcoming"
  value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
    - Leichtverpackungen # so steht es im Abfallkalender
```

> edit by @5ila5 fixed yaml code blocks
