### DISCUSSION TITLE
Restmüll 2-wöchentlich doesnt shown as an additional entity

### DISCUSSION THREAD

**Discussion by Timsche2210** [mampfes/hacs_waste_collection_schedule#3999] [Q&A] [answered]
Hi,

after the problems with [awb_es_de](https://github.com/mampfes/hacs_waste_collection_schedule/issues/3989) I have the issue that I can add the Restmüll 2-wöchentlich in the configuration but it doesnt shown than as an enity.
<img width="226" alt="Bildschirmfoto 2025-04-05 um 22 42 55" src="https://github.com/user-attachments/assets/0055d322-a3bb-4696-aede-edcaf584887c" />
<img width="303" alt="Bildschirmfoto 2025-04-05 um 22 43 21" src="https://github.com/user-attachments/assets/85263492-3985-496a-bd3c-c3e2d57582e0" />

Do you have any idea how I can add the Restmüll 2-wöchentlich to my sensors?

if I let show all my sensors the entity is also missing:
<img width="474" alt="Bildschirmfoto 2025-04-05 um 22 44 25" src="https://github.com/user-attachments/assets/2fa4cbe0-722d-487e-a38e-073de51c08bd" />

**Comment by Maarc** [comment]
Hey there!

Here is the configuration I am using. The "Restmüll 2-wöchentlich" is showing up for me.


configuration.yaml
```
  # ------- Garbage Collection -------
  # next collection
  - platform: waste_collection_schedule
    name: "Nächste Abholung"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
  # Nächste Restmüll-Abholung (4-wöchentlich)
  - platform: waste_collection_schedule
    name: "Restmüll 4-wöchentlich"
    #value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    value_template: "{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}"
    types:
      - Restmüll 4-wöchentlich
  # Nächste Restmüll-Abholung
  - platform: waste_collection_schedule
    name: "Restmüll 2-wöchentlich"
    value_template: "{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}"
    types:
      - Restmüll 2-wöchentlich
  # Nächste Biomüll Abholung
  - platform: waste_collection_schedule
    name: "Biotonne"
    #value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    value_template: "{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}"
    types:
      - Biotonne
  # Nächste gelber-Sack Abholung
  - platform: waste_collection_schedule
    name: "Gelber Sack"
    value_template: "{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}"
    types:
      - Gelbe/r Sack/Tonne
  # Nächste Papiermüll Abholung
  - platform: waste_collection_schedule
    name: "Papier"
    value_template: "{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}"
    types:
      - Papiertonne
```

Hope this helps!

**Reply by Timsche2210** [reply]
thanks for your yaml input.

Where do you see than the Restmüll 2-wöchentlich?
I use the same kind of yaml but the restmüll entity in the integration -> waste collection schedule only shows "in 22 days" (total 6 entities shown...)
![image](https://github.com/user-attachments/assets/e9f834d1-8a6d-463a-a541-507433e36524)


my yaml:
`# ------- Garbage Collection -------
  # Nächste Abholung Gelber Sack
  - platform: waste_collection_schedule
    name: "Gelber Sack"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - "Gelber Sack"
  # Nächste Abholung Biomüll
  - platform: waste_collection_schedule
    name: "Biotonne"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Biotonne
  # Nächste Abholung Restmüll
  - platform: waste_collection_schedule
    name: "Restmüll"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - "Restmüll (4)"
  # Nächste Abholung Papier
  - platform: waste_collection_schedule
    name: "Papiertonne"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Papiertonne
  # Nächste Abholung Sensor
  - platform: waste_collection_schedule
    name: "Nächste Abholung"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
`

**Comment by Maarc** [comment, marked as answer]
It looks like you have configured the `hacs_waste_collection_schedule` integration by adding the corresponding integration using the "+ Add Integration" button on the `Settings -> Devices & services -> Integrations` page. It might somehow work, but it is not what I have done.

I just added the snippet above directly into the `configuration.yaml` file and this snippet (sorry for missing it yesterday) to point to the right AWB calendar (city & street) to be used:

```
# waste_collection_schedule source configuration
waste_collection_schedule:
  sources:
    - name: awb_es_de
      args:
        city: YOUR_CITY
        street: "YOUR_STREET_NAME"
```

Then I properly see the "Restmüll 2-wöchentlich" entity listed under `Settings -> Devices & services -> Entities`.

I would recommend you to delete the waste management configuration that you added over the UI in `Settings -> Devices & services -> Integrations` ... and add the two snippets above to configure your waste entities and the source you use, replacing YOUR_CITY / YOUR_STREET_NAME by your relevant values. 

HTH!
