### DISCUSSION TITLE
401 Client Error: Unauthorized for url: https://app.abfallplus.de/assistent/bundesland/

### DISCUSSION THREAD

**Discussion by treffNIX9815** [mampfes/hacs_waste_collection_schedule#4250] [Q&A]
Hello,

i tried to install waste collection but i get an error 

401 Client Error: Unauthorized for url: https://app.abfallplus.de/assistent/bundesland/

`Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
Integration: Waste Collection Schedule ([Dokumentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
Erstmals aufgetreten: 18:35:51 (1 Vorkommnis)
Zuletzt protokolliert: 18:35:51

fetch failed for source Apps by Abfall+: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py", line 183, in fetch for d in self._app.generate_calendar(): ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 988, in generate_calendar self.select_bundesland() ~~~~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 579, in select_bundesland for bundesland in self.get_bundeslaender(): ~~~~~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 565, in get_bundeslaender r.raise_for_status() ~~~~~~~~~~~~~~~~~~^^ File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://app.abfallplus.de/assistent/bundesland/`

configuration.yaml

```
#WasteCalendar/Müllkalender
waste_collection_schedule:
  sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.abfallzak
        city: Rangendingen
        strasse: Donaustraße
        hnr: 23
        bundesland: Baden-Württemberg
        landkreis: Zollernalbkreis
```

pls. help

Txh
