### DISCUSSION TITLE
Wyre Forest integration

### DISCUSSION THREAD

**Discussion by johntheth1rd** [mampfes/hacs_waste_collection_schedule#660] [General]
![image](https://user-images.githubusercontent.com/108230216/216692712-f4eee20c-8125-4d50-89bc-6221f9018dd6.png)
I've added this integration yesterday, and it was showing recycling (green bin) over and over in the card. However today, its showing "Unknown" 
![image](https://user-images.githubusercontent.com/108230216/216693672-268b5bf9-f5e8-40ce-8832-0e4d9978911d.png)
this is my config entry
```
waste_collection_schedule:
  sources:
    - name: wyreforestdc_gov_uk
      args:
        uprn: 10012xxxxxx
      customize:
        - type: recycling (green bin)
          alias: Green Bin
        - type: rubbish (black bin)
          alias: Black Bin
sensor:
  # next collection
  - platform: waste_collection_schedule
    name: next_collection
```
