### DISCUSSION TITLE
New Integration

### DISCUSSION THREAD

**Discussion by Svenson3501** [mampfes/hacs_waste_collection_schedule#675] [Ideas]
Hello,
Can you please add an integration for the Gütersloh waste calendar in Germany? That would help me a lot.
https://buergerportal.guetersloh.de/waste-calendar
Thanks very much

**Comment by 5ila5** [comment]
Gütersloh is already supported by the [abfallnavi_de](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfallnavi_de.md) source.
config:
```yaml
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: gt2
        ort: Gütersloh
        strasse: ADLERWEG #add your street here
```

**Comment by GregGraetssche** [comment]
Can anybody please help me. I am not able to get the args for abfallnavi in german city of Aachen.

I tried it with https://abfallnavi.api.bund.dev/ and got some ids. But do not know, how to proceed.

**Reply by 5ila5** [reply]
Something like this should work

```yaml
# waste_collection_schedule source configuration
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: aachen
        ort: Aachen
        strasse: Achterstraße
        hausnummer: 6
```
