### DISCUSSION TITLE
Add additional source for AWIDO: AWV Isar-Inn

### DISCUSSION THREAD

**Discussion by m4c3** [mampfes/hacs_waste_collection_schedule#687] [General]
Hi,
the awido integration also works great with the data for [Abfallwirtschaftsverband Isar-Inn](https://www.awv-isar-inn.de/) 

```
waste_collection_schedule:
  sources:
    - name: awido_de
      args:
        customer: awv-isar-inn
        city: Simbach a. Inn
        street: Bayernwerkstr.
```
can somebody add this? Thanks!
