### DISCUSSION TITLE
Problem with ics-file

### DISCUSSION THREAD

**Discussion by HolliDolli** [mampfes/hacs_waste_collection_schedule#702] [General]
Hello everybody,

I'm trying to get WCS running with ical-file for Schwalm-Eder-Kreis.
The download can be done here:
https://www.zva-sek.de/online-dienste/abfallkalender-2023/abfallkalender-2023.html
Felsberg/Felsberg was used by me.
But the file seems to include information WCS can process. 
All i get staring the service fetch_data is a "failed to start, unknown error".
I check with another file from gemos-management.de, everthing works fine.
I already tried to remove the ";LANGUAGE=de", but problem still exist.
Also the removal of the VALARM Sections did not solve the problem.
Can someone tell me why this ical-files are not accepted?

Thanks in advance,

Holger

Config:
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/felsberg-2023.ics"

sensor:
  - platform: waste_collection_schedule
    name: Abfall
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'

[felsberg-2023.zip](https://github.com/mampfes/hacs_waste_collection_schedule/files/10814562/felsberg-2023.zip)

**Comment by dt215git** [comment]
Saved the Felsberg/Felsberg ics from the zva-sek website to my HA instance as _testcal.ics_ and the file seems to work okay for me.
You probably need to include the `add_days_to: true` arg, otherwse the `value_template` won't find a `value.daysTo` entry. 

```yaml
sources:
  - name: ics
    calendar_title: Test_Waste
    args:
      file: "www/testcal.ics"
      version: 1

sensor:
  - platform: waste_collection_schedule
    name: Test_Waste
    details_format: appointment_types
    add_days_to: true
```
![image](https://user-images.githubusercontent.com/86194065/222258484-73974f45-0eea-41b5-8fa0-2bcdd51252f9.png)
