### DISCUSSION TITLE
Abfallkalender für Havelland implementieren, hier: Dallgow-Döberitz

### DISCUSSION THREAD

**Discussion by thebigmutz** [mampfes/hacs_waste_collection_schedule#835] [Q&A]
Hallo, kannst du den Abfallkalender für das Havelland implementieren (Ort Dallgow-Döberitz)?
Der Link findet sich hier:
https://www.abfall-havelland.de/index.php?page_id=543

Vielen Dank!

**Comment by 5ila5** [comment]
abfall-havelland.de scheint eine ICAL Datei anzubieten deren URL sich nicht ändert. Wenn du `Export der Kalenderdaten` drückst, kannst du eine `.ics` Datei herunter laden. Wenn du dann den Downloadlink kopierst kannst du den in die [ICAL/ICS](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) source als `url` Parameter einfügen.

bsp:
```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://www.abfall-havelland.de/UserFiles/Files/Abfuhrtermine%20Ahornstr%20Dallgow-D%C3%B6beritz.ics"
```
