### DISCUSSION TITLE
Notification on Sonoff NSPanel

### DISCUSSION THREAD

**Discussion by Roxxor91** [mampfes/hacs_waste_collection_schedule#889] [Q&A] [answered]
Hi!
I am running a Sonoff NSPanel with Lovelace UI and can send notifications to it with this script snippet:

```yaml
nspanel_screensaver_notification:
  alias: Screensaver Notification
  sequence:
  - service: mqtt.publish
    data:
      topic: cmnd/tasmota_NsPanelTerrasse/Backlog
      payload: CustomSend notify~{{ heading }}~{{ message }}; Buzzer 2,2,2
  mode: single
  icon: mdi:message-badge
```

Source: https://docs.nspanel.pky.eu/notifications/#notification-on-screensaver

Now I want to be informed 1 day before the trash is emptied. Somebody knows how to write a script how to do this?
So eg. 1 day before emtpying recycling trash at 17:00 o'clock I want to send a notification about it via this mqtt service.

Would be great if you could help me. I tried via Homeassitant GUI but couldnt find a trigger or condition which applies to 1 day before emptying.

Thanks!

**Comment by dt215git** [comment, marked as answer]
No experience of using NSPanel, but you could probably do what you're trying to using an automatrion that checks against the two criteria you mention.

You can trigger an automation each day at at 17:00.

If you've implemented the [add_days_to](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#configuring-sensors) argument in your waste sensor then you can evaluate the `days_To` attribute.

If all the conditions are met, call the service that sends your notification to NSPanel.

![image](https://user-images.githubusercontent.com/86194065/234375799-71dd721b-f463-45ef-8493-037b5f5ce648.png)

Maybe that'll work, maybe not, and there's probably several other ways to doing what you want. Think of this a starting point rather than the final answer...

**Reply by Roxxor91** [reply]
What you are writing makes sense and should enable my trigger. But how do I configure "add_days_to"? I dont understand it from the documentation, and dont know enough of HomeAssistant to figure this out. I just wrote strings as I thought that it would be the name of the attribute? But no, this error:
`The system cannot restart because the configuration is not valid: Invalid config for [sensor.waste_collection_schedule]: invalid boolean value tage for dictionary value @ data['add_days_to']. Got 'Tage'. (See ?, line ?). `

**Reply by dt215git** [reply]
Can you post the yaml for your waste sensor?

**Reply by Roxxor91** [reply]
```
sensor:
  - platform: waste_collection_schedule
    name: Restmülltonne
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    add_days_to: ADD_DAYS_TO
    types:
      - Restmülltonne
  - platform: waste_collection_schedule
    name: Biotonne
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
#    add_days_to: ADD_DAYS_TO
    types:
      - Biotonne
  - platform: waste_collection_schedule
    name: Gelber Sack
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    add_days_to: Tage
    types:
      - Gelber Sack
  - platform: waste_collection_schedule
    name: Papiertonne
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
#    add_days_to: ADD_DAYS_TO
    types:
      - Papiertonne

waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://www.abfalltermine-bamberg.de/Bamberg/Landkreis/Stegaurach/ics
      customize:
        - type: Biotonne
          alias: Biotonne
        - type: Restmülltonne
          alias: Restmülltonne
        - type: Gelber Sack
          alias: Gelber Sack
        - type: Papiertonne
          alias: Papiertonne
```
