### DISCUSSION TITLE
Local time format

### DISCUSSION THREAD

**Discussion by kwithus** [mampfes/hacs_waste_collection_schedule#925] [Q&A] [answered]
I use
value_template: '{{value.date.strftime("%A")}}|{{value.daysTo}}|{{value.types|join(", ")}}'
to show the weekday of next collection by name of the day, which does generally work.
However, it shows the English name, not the German name as I would like to have it.
Is there a way to have the name shown confirming to the local setting in HA?

**Comment by dt215git** [comment]
Something similar was discussed on the [HA Community forum](https://community.home-assistant.io/t/template-time-format-still-english-instead-german/200940/5)

**Reply by kwithus** [reply]
Thanks, that was generally helpful. However, I don’t succeed to format it correctly.
I tried as follows:
value_template: '{% set weekdays = ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"] %} {{value.date.strftime("%A")}}|{{value.daysTo}}|{{value.types|join(", ")}}|{{weekdays[value.date.strftime("%w")]}}'
  
  But the part {{weekdays[value.date.strftime("%w")]}} doesn’t return anything.
When I replace value.date.strftime("%w") with a number (e.g. 3) it works.
%w should give the weekday as number, shouldn’t it?

**Reply by dt215git** [reply, marked as answer]
I think you need to convert `value.date.strftime("%w")` to an integer in order to access the list. Perhaps something like this

```yaml
- platform: waste_collection_schedule
  name: TempName  # change this to something else
  details_format: appointment_types
  value_template: >
    {% set weekdays = ["Sonntag", "Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag"] %}
    {% set day = value.date.strftime("%w") | int %}
    {% set binday = weekdays[day] %}
    {{value.date.strftime("%A")}} | {{value.daysTo}} | {{value.types|join(", ")}} | {{day}} | {{binday}}
  add_days_to: true
```
