### ISSUE TITLE
Integration with republic apepars not to work

### ISSUE THREAD

**Issue by robertmain** [mampfes/hacs_waste_collection_schedule#1012]
Trying to get this working with Republic, but thus far failing. I have the following in `configration.yaml`:

```yaml
waste_collection_schedule:
  sources:
    - name: republicservices_com
      args:
        street_address: <My street address>
```

Which produces the following logs:
```
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 10:42:57 PM (1 occurrences)
Last logged: 10:42:57 PM
fetch failed for source Republic Services: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/republicservices_com.py", line 35, in fetch r_json = json.loads(response2.text)["data"] KeyError: 'data'
```
