### ISSUE TITLE
add Hochtaunuskreis - Kronberg

### ISSUE THREAD

**Issue by NOYB4Europe** [mampfes/hacs_waste_collection_schedule#1023]
Could you please add Kronberg im Taunus :

https://abfallkalender.regioit.de/kalender-kronberg/downloadfile.jsp?format=ics&jahr=2023&ort=Kronberg&strasse=92752&fraktion=0&fraktion=4&fraktion=5&fraktion=6&fraktion=9&fraktion=10&fraktion=11

https://abfallnavi.de/kronberg/

not working was : 
_waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: kronberg
        ort: Kronberg
        strasse: Niederhöchstädter Straße_

Thank you in advance for the great work

**Comment by 5ila5** [comment]
tested this and it works as well.
```yaml
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: kronberg
        ort: Kronberg
        strasse: Niederhöchstädter Straße
```
Did you restart Homeassistant after changing your Config (Hot reload does not work properly)
