### ISSUE TITLE
Even / Odd weeks

### ISSUE THREAD

**Issue by Gilles-Clemenceau** [mampfes/hacs_waste_collection_schedule#1032]
Hello,
Is there a way in a custom collection to have every Monday only in even weeks  as date ?
I don't find anything in the documentation : https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md
Thanks

**Comment by 5ila5** [comment]
There is no support for week numbers but you can use this:

**Monday odd Weeks:**
```yaml
waste_collection_schedule:
  sources:
    - name: static
      args:
        type": "WasteType"
        frequency: "WEEKLY"
        weekdays: "MO"
        interval: 2
        start: "2023-01-02"
        until: "2026-12-31"
```
**Tuesday even Weeks:**
```yaml
waste_collection_schedule:
  sources:
    - name: static
      args:
        type: "WasteType"
        frequency: "WEEKLY"
        weekdays: "TU"
        interval: 2
        start: "2023-01-09"
        until: "2026-12-31"
```

This should work till 2026 (next time a year has 53 weeks instead of 52, at least (german week numbers))
