### ISSUE TITLE
Request for Trondheim, Norway

### ISSUE THREAD

**Issue by Atriusftw** [mampfes/hacs_waste_collection_schedule#1048]
TRV (Trondheim Renholdsverk) provides the waste collection schedules as iCal through webcal links.
I'm not sure how to extract the needed information to set it up manually using the integration, so today i'm using a dirty hack where i import the webcal URL to Google Calendar, then import that to HA through an iCal integration.

Example URL for a schedule from TRV: webcal://trv.no/calendar/91dc135b-fc26-4219-b636-b706a2584b7f

**Comment by 5ila5** [comment]
just use the [ICAL source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) 

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: webcal://trv.no/calendar/91dc135b-fc26-4219-b636-b706a2584b7f
```

Does this url expire? if so we should add a dedicated source. if the url does not expire we should just add a [ICAL source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/contributing_ics.md) (official documentation for trv.no on how to use the ical source)
