### ISSUE TITLE
City of Bocholt, Germany

### ISSUE THREAD

**Issue by justusk18s** [mampfes/hacs_waste_collection_schedule#1053]
I've been trying to get the integration to work with home assistant for the last three hours and i'm going mad. The city of Bocholt, where I live, publishes its waste collection schedule with the local it service of RegioIT which is supported by the integration however my city isn't in the wizards list. Can someone please help me get out of this mess? The ical/ics integration doesnt work either because of som weird formatting quirk with RegioIT.

**Comment by 5ila5** [comment]
Bochahlt is part of the EGW Westmünsterland in the wizzard (request data with service id `wml2`)

```yaml
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: wml2
        ort: Bocholt
        strasse: Auf dem Geuting
```

the ICS integration works for me as well (just copy the link ical-Export replace 2023 with {%y} (to work after 2023) ):
```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://abfallkalender.regioit.de/kalender-wml/downloadfile.jsp?format=ics&jahr={%y}&ort=Bocholt&strasse=3523289&fraktion=1&fraktion=2&fraktion=4&fraktion=5&fraktion=10"

```
