### ISSUE TITLE
AWM München integration

### ISSUE THREAD

**Issue by ThomDietrich** [mampfes/hacs_waste_collection_schedule#106]
The AWM service offers a ICS and can be found for your location, as documented here: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md

I found the setup a but more cumbersome so decided to post my polished config for others to copy and paste:

1. Find your ICS export link via the AWM web page
2. Insert and adapt the configuration below (almost all fields must be changed using the URL from 1, beware of the year field)
3. Enjoy!

@mampfes if there is a better place to document this, please let me know or copy over ;) I would suggest to add a section to the ics.md file.

I started to work on a `source.py`, however I am not certain about half of the fields and fear we would run into more issues than doing good...

Feel free to close.

Config:
```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://www.awm-muenchen.de/entsorgen/abfuhrkalender\
          ?tx_awmabfuhrkalender_abfuhrkalender[section]=ics\
          &tx_awmabfuhrkalender_abfuhrkalender[strasse]=Bahnstr.\
          &tx_awmabfuhrkalender_abfuhrkalender[hausnummer]=11\
          &tx_awmabfuhrkalender_abfuhrkalender[stellplatz][bio]=70024507\
          &tx_awmabfuhrkalender_abfuhrkalender[stellplatz][papier]=70024507\
          &tx_awmabfuhrkalender_abfuhrkalender[stellplatz][restmuell]=70024507\
          &tx_awmabfuhrkalender_abfuhrkalender[leerungszyklus][B]=1/2;U\
          &tx_awmabfuhrkalender_abfuhrkalender[leerungszyklus][P]=001;U\
          &tx_awmabfuhrkalender_abfuhrkalender[leerungszyklus][R]=001;U\
          &tx_awmabfuhrkalender_abfuhrkalender[singlestandplatz]=false\
          &tx_awmabfuhrkalender_abfuhrkalender[standplatzwahl]=true\
          &tx_awmabfuhrkalender_abfuhrkalender[year]={%Y}"
      calendar_title: AWM München, Bahnstr. 11
      customize:
        - type: "Achtung: Biotonne, Bahnstr. 11"
          alias: "Biotonne"
        - type: "Achtung: Papiertonne, Bahnstr. 11"
          alias: "Papiertonne"
        - type: "Achtung: Restmülltonne, Bahnstr. 11"
          alias: "Restmülltonne"
        - type: "Biotonne, Bahnstr. 11"
          alias: "Biotonne"
        - type: "Papiertonne, Bahnstr. 11"
          alias: "Papiertonne"
        - type: "Restmülltonne, Bahnstr. 11"
          alias: "Restmülltonne"
  fetch_time: "03:00"
  random_fetch_time_offset: 120
  day_switch_time: "11:00"

sensor:
  - platform: waste_collection_schedule
    name: "Nächste Müll-Entsorgung"
    details_format: appointment_types
    value_template: >-
      {% if value.daysTo == 0 %}
        {{ value.types|join(", ") }} Heute
      {% elif value.daysTo == 1 %}
        {{ value.types|join(", ") }} Morgen
      {% else %}
        {{ value.types|join(", ") }} in {{ value.daysTo }} Tagen
      {% endif %}
```
