### ISSUE TITLE
Request for Winchester City Council, UK

### ISSUE THREAD

**Issue by Millsmad** [mampfes/hacs_waste_collection_schedule#1071]
Hi has anyone done an integration for Winchester City Council.

Regards

Paul

**Comment by dt215git** [comment]
Do that actually publish collection dates on the website, or just a link to the pdf?
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/86194065/e86340ab-bfba-4f32-969d-2bd6465832e9)

If it's the latter, then you'll probably have to use the [static source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md) to replicate the information contained in the pdf collection schedule.

**Comment by markvp** [comment]
Winchester City Council is now supported via the [`iapp_itouchvision_com`](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/iapp_itouchvision_com.md) source (added in November 2024).

Configure it like this:

```yaml
waste_collection_schedule:
  sources:
    - name: iapp_itouchvision_com
      args:
        uprn: "YOUR_UPRN"
        municipality: "WINCHESTER"
```

You can look up your UPRN at https://www.findmyaddress.co.uk/.

Closing this as the request is now fulfilled.
