### ISSUE TITLE
Problem with AWIDO based service

### ISSUE THREAD

**Issue by arifroni** [mampfes/hacs_waste_collection_schedule#109]
Hello

I set up an AWIDO based service. but one of the attributes doesn't grab time. you can see this in the screenshot.
![image](https://user-images.githubusercontent.com/59896374/142468680-f6041bdb-e3ab-4c25-b09f-3ad458909f29.png)

My config is:
```
waste_collection_schedule:
  sources:
    - name: awido_de
      args:
        customer: zv-muc-so
        city: Neubiberg
```

**Comment by mampfes** [comment]
I assume that there is no further collection for "Spermüll- und Wertstoffsammlung" in this year. That's why the field is empty.
If you need further help, please provide your street name and sensor configuration.

**Comment by arifroni** [comment]
it's true there isn't any date this year. the day I added these sensors, that was the last day for this waste sensor. i was expecting today or that day's timestamp. but it was also empty that day. is this normal?

configuration.yaml
```
waste_collection_schedule:
  sources:
    - name: awido_de
      args:
        customer: zv-muc-so
        city: Neubiberg
        street: Lilienthalstraße
```

sensor.yaml
```
- platform: waste_collection_schedule
  name: garbage_collection
  details_format: appointment_types
```
