### ISSUE TITLE
Calendar Entries Incorrect for City of Port Adelaide Enfield, South Australia

### ISSUE THREAD

**Issue by bbayu123** [mampfes/hacs_waste_collection_schedule#1110]
**Version: 1.41.0**
**HA Version: core-2023.7.2**

The Calendar entries do not match the data on https://www.cityofpae.sa.gov.au/live/waste/bin-collection.

There are 4 dates shown on the City of PAE site. When compared with the HA calendar entries:
- 2 dates are correct
- 1 date is listed for the wrong month
- 1 date is completely missing

Address is redacted in screenshots, but this was tested using an address in the Tuesday Area 1 collection zone.
Update: Also tested with the address listed [in the source code under `TEST_CASES`](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/portenf_sa_gov_au.py#L21), which is Tuesday Area 2 - it has the same problem.

---

Collection schedule for Tuesday Area 1 taken from City of PAE website
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/26726381/08261654-8757-4f9e-ba4f-2610aa7fd6ca)

---

Calendar entries populated in HA for July and August
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/26726381/c0045416-828f-4460-a4b9-8e46562af623)
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/26726381/249a7075-24f2-45fb-b79f-c545685a3948)

---

Config.yml entry
```yaml
waste_collection_schedule:
  sources:
    - name: portenf_sa_gov_au
      args:
        suburb: !secret local_address_suburb
        street: !secret local_address_street
        house_number: !secret local_address_house_num
```
