### ISSUE TITLE
Config creates duplicate entities when configuring multiple sources

### ISSUE THREAD

**Issue by mattclair** [mampfes/hacs_waste_collection_schedule#1140]
I receive the following error in the logs when I configure multiple sources for the waste collection sensor.

Logger: homeassistant.components.calendar
Source: helpers/entity_platform.py:613
Integration: Calendar (documentation, issues)
First occurred: 9:33:08 AM (1 occurrences)
Last logged: 9:33:08 AM

Platform waste_collection_schedule does not generate unique IDs. ID republicservices_com[('street_address', '111 My Street, City, State zipcode')]_calendar already exists - ignoring calendar.republic_services

Configuration.yaml

```yaml
waste_collection_schedule:
  fetch_time: '00:00'
  day_switch_time: '00:00'
  sources:
    - name: republicservices_com
      args:
        street_address: !secret street_address
      customize:
        - type: Recycle
          alias: Recycling
          icon: mdi:recycle
          use_dedicated_calendar: true
          dedicated_calendar_title: Republic Services Recycling
    - name: republicservices_com
      args:
        street_address: !secret street_address
      customize:
        - type: Solid Waste
          alias: Trash
          icon: mdi:delete
          use_dedicated_calendar: true
          dedicated_calendar_title: Republic Services Trash
```

**Comment by 5ila5** [comment]
You can not create two identical sources like this but I don't get the use-case of this anyway maybe you want this:

This generates 3 dedicated calendars: Republic Services Recycling, Republic Services Trash and Republic Services (for any entries which are neither Trash nor recycling)

```yaml
waste_collection_schedule:
  fetch_time: '00:00'
  day_switch_time: '00:00'
  sources:
    - name: republicservices_com
      args:
        street_address: !secret street_address
      customize:
        - type: Recycle
          alias: Recycling
          icon: mdi:recycle
          use_dedicated_calendar: true
          dedicated_calendar_title: Republic Services Recycling
        - type: Solid Waste
          alias: Trash
          icon: mdi:delete
          use_dedicated_calendar: true
          dedicated_calendar_title: Republic Services Trash
```
