### ISSUE TITLE
No data loading for awido_de zv-muc-so

### ISSUE THREAD

**Issue by thorok73** [mampfes/hacs_waste_collection_schedule#1146]
Config appears to be valid, but no data loading into the calendar despite several restarts (formatting lost on copy/paste)

```yaml
sources:
  - name: awido_de
    args:
      customer: zv-muc-so
      city: Höhenkirchen-Siegertsbrunn
      street: valid street
      housenumber: valid number
```

Also tried an address in Ottobrunn which did not work

Thank you for your support

**Comment by 5ila5** [comment]
zv-muc-so/Höhenkirchen-Siegertsbrunn

seem to not request a house number. could you try to remove the housenumber argument. In my test providing an housenumber for your customer+city combination lead to an error

**Comment by markvp** [comment]
Thanks for the report! This issue has since been resolved by subsequent improvements to the `awido_de` source.

The bug at the time was that providing a `housenumber` for a customer+city combination that does not support house-level data caused an error. This has been fixed — the source now gracefully falls back to street-level data when the API indicates no housenumber breakdown exists, and city/street lookups are now case-insensitive.

Your config should now work correctly either with or without the `housenumber` argument:

```yaml
sources:
  - name: awido_de
    args:
      customer: zv-muc-so
      city: Höhenkirchen-Siegertsbrunn
      street: <your street name>
```

Closing as resolved. Please re-open if you continue to experience issues.
