### ISSUE TITLE
Please add support for Landkreis Nürnberger Land

### ISSUE THREAD

**Issue by r100gs** [mampfes/hacs_waste_collection_schedule#1149]
Hello,

can you please have a look at Landkreis Nürnberger Land.
They provide us with a search under https://abfuhrkalender.nuernberger-land.de/waste_calendar/ical?id=16699001&filter=rm:bio:p:dsd:poison&reminder=null for ICS-Downloads or schedule printing.

I tried it with this config:

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://abfuhrkalender.nuernberger-land.de/waste_calendar/ical?id=16699001&filter=rm:bio:p:dsd:poison&reminder=null
      customize:
        - type: Restmüll/Bioabfall
          alias: Restmüll
          icon: mdi:trash-can
        - type: Bioabfall 1-wöchentlich
          alias: Bioabfall
          icon: mdi:flower-outline
        - type: Papier
          alias: Papierabfall
          icon: mdi:trash-can-outline
        - type: Gelber Sack
          icon: mdi:recycle
```

This is my error:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 07:44:56 (1 occurrences)
Last logged: 07:44:56

fetch failed for source ICS: Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/icalendar/prop.py", line 486, in from_ical minutes=int(minutes or 0), ^^^^ AttributeError: 'NoneType' object has no attribute 'groups' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 168, in fetch return self.fetch_url(self._url, self._params) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 193, in fetch_url return self._convert(r.text) ^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 204, in _convert dates = self._ics.convert(data) ^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 38, in convert events: List[Any] = icalevents.events( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalevents/icalparser.py", line 288, in parse_events calendar = Calendar.from_ical(content) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalendar/cal.py", line 383, in from_ical raise File "/usr/local/lib/python3.11/site-packages/icalendar/prop.py", line 337, in from_ical return vPeriod.from_ical(ical) ^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalendar/prop.py", line 498, in from_ical ValueError: Invalid iCalendar duration: -PTnull
```

THX,
Stefan

**Comment by bbr111** [comment]
Can verify the problem. testesd with just the ICS part without customize.
Same problem.
Looks like some errors in the ics interpreter or the ics file is in an invalid format.

**Comment by dt215git** [comment]
Trimming the url seems to make it work, and the number of events remains at 32.
```yaml
sources:
  - name: ics
    args:
      url: "https://abfuhrkalender.nuernberger-land.de/waste_calendar/ical?id=16699001&filter=rm:bio:p:dsd:poison"
      version: 1
```
Trimming it further reduces the number of events to 18.
```yaml
sources:
  - name: ics
    args:
      url: "https://abfuhrkalender.nuernberger-land.de/waste_calendar/ical?id=16699001"
      version: 1
```

Both 32-event ics files seem valid ([link](https://icalendar.org/validator.html?url=https://abfuhrkalender.nuernberger-land.de/waste_calendar/ical?id=16699001&filter=rm:bio:p:dsd:poison&reminder=null) and [link](https://icalendar.org/validator.html?url=https://abfuhrkalender.nuernberger-land.de/waste_calendar/ical?id=16699001&filter=rm:bio:p:dsd:poison)). The the main difference seems to be duplicate lines like this:

```
UID:2023-07-19-Papier-gelber_Sack@abfallwirtschaft.nuernberger-land.de
UID:2023-07-19-Papier-gelber_Sack@abfallwirtschaft.nuernberger-land.de
```
and sections like this:
```
BEGIN:VALARM
X-WR-ALARMUID:alarm-2023-07-19-Papier-gelber_Sack@abfallwirtschaft.nuernber
 ger-land.de
TRIGGER;RELATED=START:-PTnull
REPEAT:1
DURATION:PT15M
ACTION:DISPLAY
```
The error suggests the `TRIGGER;RELATED=START:-PTnull` line is what's causing issues.
