### ISSUE TITLE
Stockton-on-Tees, UK - Calendar Blank

### ISSUE THREAD

**Issue by geecy84** [mampfes/hacs_waste_collection_schedule#1171]
UK, Stockton-on-Tees Borough Council
Calendar does not pull any data, calendar appears blank.

```
waste_collection_schedule:
  sources:
    - name: stockton_gov_uk
      args:
        uprn: uprninteger
```
