### ISSUE TITLE
Sensors not being updated on the next day

### ISSUE THREAD

**Issue by guardiande** [mampfes/hacs_waste_collection_schedule#1188]
I've just started using WCS and I'm afraid I'm doing some sort of a noob mistake as the dependent sensors don't update when it's the next day.

Firstly, I need to restart Home Assistant to accept changes to the WCS configuration, but I think this is expected.

I've created sensors to tell me when a specific garbage type is collected, e.g "tomorrow", "today", "in 3 days". This works after I've restarted HA (sensor shows "tomorrow") but on the next it is not updated to "today"). Restarting makes it work.

Any idea? Below is my configuration.

Excerpt from **configuration.yaml**:

```
waste_collection_schedule: !include waste.yaml
```

**waste.yaml**

```
sources:
  - name: static
    args:
      type: Papier
      frequency: WEEKLY
      interval: 4
      start: '2023-08-02'
      until: '2025-12-31'
  - name: static
    args:
      type: Bio
      frequency: WEEKLY
      interval: 2
      start: '2023-08-01'
      until: '2025-12-31'
  - name: static
    args:
      type: Restmüll
      frequency: WEEKLY
      interval: 2
      start: '2023-08-01'
      until: '2025-12-31'
  - name: static
    args:
      type: "Gelber Sack"
      frequency: WEEKLY
      interval: 2
      start: '2023-08-07'
      until: '2025-12-31'
```

**sensors.yaml**

```

- platform: waste_collection_schedule
  source_index: 0
  name: waste_paper
  value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
  types:
    - Papier
- platform: waste_collection_schedule
  source_index: 1
  name: waste_bio
  value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
  types:
    - Bio
- platform: waste_collection_schedule
  source_index: 2
  name: waste_rest
  value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
  types:
    - Restmüll
- platform: waste_collection_schedule
  source_index: 3
  name: waste_plastic
  value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
  types:
    - "Gelber Sack"
- platform: waste_collection_schedule
  source_index: 0
  name: waste_paper_in_days
  value_template: '{{ value.daysTo }}'
  types:
    - Papier
- platform: waste_collection_schedule
  source_index: 1
  name: waste_bio_in_days
  value_template: '{{ value.daysTo }}'
  types:
    - Bio
- platform: waste_collection_schedule
  source_index: 2
  name: waste_rest_in_days
  value_template: '{{ value.daysTo }}'
  types:
    - Restmüll
- platform: waste_collection_schedule
  source_index: 3
  name: waste_plastic_in_days
  value_template: '{{ value.daysTo }}'
  types:
    - "Gelber Sack"
```
