### ISSUE TITLE
Errors in the logs

### ISSUE THREAD

**Issue by tomik671108** [mampfes/hacs_waste_collection_schedule#1207]
Hi.
I have a problem, WSC seems to work, it displays the dates of the next collection of waste, but in the logs I have these entries:

Logger: homeassistant.components.sensor
Source: custom_components/waste_collection_schedule/waste_collection_schedule/collection_aggregator.py:22
Integration: Sensor (documentation, issues)
First occurred: 00:13:17 (2 occurrences)
Last logged: 00:13:17

Error adding entities for domain sensor with platform waste_collection_schedule
Error while setting up waste_collection_schedule platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 750, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/waste_collection_schedule/sensor.py", line 146, in async_added_to_hass
    self._update_sensor()
  File "/config/custom_components/waste_collection_schedule/sensor.py", line 267, in _update_sensor
    self._add_refreshtime()
  File "/config/custom_components/waste_collection_schedule/sensor.py", line 161, in _add_refreshtime
    if self._aggregator.refreshtime is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/collection_aggregator.py", line 22, in refreshtime
    return self._shells[0].refreshtime
           ~~~~~~~~~~~~^^^
IndexError: list index out of range


Logger: homeassistant.util.logging
Source: util/logging.py:168
First occurred: 00:13:21 (1 occurrences)
Last logged: 00:13:21

Exception in _update_sensor when dispatching 'wcs_update_sensors_signal': () Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/sensor.py", line 267, in _update_sensor self._add_refreshtime() File "/config/custom_components/waste_collection_schedule/sensor.py", line 161, in _add_refreshtime if self._aggregator.refreshtime is not None: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/collection_aggregator.py", line 22, in refreshtime return self._shells[0].refreshtime ~~~~~~~~~~~~^^^ IndexError: list index out of range

My setup.:

'waste_collection_schedule:
  sources:
    - name: real_luzern_ch
      args:
        municipality_id: 22
      customize:
        - type: Kehricht
          alias: Śmieci
          show: True
          icon: mdi:trash-can
          picture: None
          use_dedicated_calendar: False
          dedicated_calendar_title: None
        - type: Grüngut
          alias: Odpady zielone
          show: True
          icon: mdi:leaf
          picture: None
          use_dedicated_calendar: False
          dedicated_calendar_title: None
        - type: Papier
          alias: Papier
          show: True
          icon: mdi:newspaper-variant-multiple
          picture: None
          use_dedicated_calendar: False
          dedicated_calendar_title: None
        - type: Karton
          alias: Karton
          show: True
          icon: mdi:package-variant
          picture: None
          use_dedicated_calendar: False
          dedicated_calendar_title: None
  fetch_time: "03:00"
  random_fetch_time_offset: "60"
  day_switch_time: "13:30"
  separator: ","

`- platform: waste_collection_schedule
    source_index:
    name: real_luzern_ch
    details_format: appointment_types
    count: "4"
    types:
      - Kehricht
      - Grüngut
      - Papier
      - Karton`
      
I assume I'm doing a configuration error, but where?.

**Comment by dt215git** [comment]
I don't get any errors when using the config you provided - although it's difficult to work out the indentations you have. Do you get the same error messages appear if you restart Home Assistant as it re-queries the source?

For simplicity, I removed most of the config that was just replicating default behaviours - makes it easier to work out if the config is the issue, or something else is going wrong. These also generate no errors for me:

```yaml
waste_collection_schedule:
  sources:
    - name: real_luzern_ch
      args:
        municipality_id: 22
      customize:
        - type: Kehricht
          alias: Śmieci
          icon: mdi:trash-can
        - type: Grüngut
          alias: Odpady zielone
          icon: mdi:leaf
        - type: Papier
          alias: Papier
          icon: mdi:newspaper-variant-multiple
        - type: Karton
          alias: Karton
          icon: mdi:package-variant
  fetch_time: "03:00"
  random_fetch_time_offset: 60
  day_switch_time: "13:30"
  separator: ","
```
```yaml
- platform: waste_collection_schedule
  name: Luzern_Test
  details_format: appointment_types
  count: 4
  types:
    - Kehricht
    - Grüngut
    - Papier
    - Karton
```

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/86194065/73eb0c68-aef6-4b60-99ca-94299a364caf)
