### ISSUE TITLE
How to announce both calendar entities scheduled on same date ?

### ISSUE THREAD

**Issue by atv2016** [mampfes/hacs_waste_collection_schedule#1220]
Could i just check for if the council calendar entity is 'on' and then announce the message content in HA ? 
Currently i check for 2 conditions, if the calendar entity is on and if the message is equal to say, 'Food waste' it announces that it's 'Food waste'.

I'd rather just automatically announce the content of whatever calendar subject there is, rather then me hardcoding it. I'm sure i can do this but the problem is from currently looking at the council calendar entity, it only shows 'Food waste' and not the other one scheduled for that same date.

So i'm thinking it will never announce both if i did it dynamically ?

**Comment by dt215git** [comment]
Still not sure what you mean by "announce the message..." etc.
Using one of the test cases and this sensor set up
```yaml
waste_collection_schedule:
  sources:
    - name: croydon_gov_uk
      args:
        postcode: "CR0 6LN"
        houseID: "64 Coniston Road"
      calendar_title: Croydon_Test
```

```yaml
- platform: waste_collection_schedule
  name: Croydon_Test
  details_format: appointment_types
  add_days_to: true
```
I get this:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/86194065/f7a31712-b10e-4954-bcf1-34dcad885f21)

Isn't the sensor `state` text , what you're wanting?
