### ISSUE TITLE
Recycle Coach - Correct on Website, Off a Day in HA

### ISSUE THREAD

**Issue by Snuffy2** [mampfes/hacs_waste_collection_schedule#1227]
With Labor Day in the USA being Sept 4, many towns have delayed trash pickup from Mon to Tue. My town has done this. I only set this up a little over a month ago, but the dates have been accurate.

On the Recycle Coach website, this shows correctly with Garbage pickup now being Sept 5.
<img width="945" alt="2023-09-03_22-16-24 copy 033" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/6526076/efe689f4-a56c-4441-9ff5-d2f10fe3a96b">

In HA though, the Garbage pickup is still showing as Sept 4.
<img width="592" alt="2023-09-03_22-17-15 774 copy" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/6526076/03d8be16-ed58-4904-a52c-926ce2c72904">

```yaml
waste_collection_schedule:
  sources:
    - name: recyclecoach_com
      calendar_title: <Town> Trash
      args:
        street: <my address>
        city: <town>
        state: nj
        district_id: <town>
        project_id: NJ_BER
        zone_id: zone-z13155
      customize:
          - type: Recycling Containers 1 & 2
            alias: Recycling
            icon: mdi:recycle
          - type: Metal
            icon: mdi:robot-dead
          - type: Bulk
            icon: mdi:sofa
          - type: Garbage
            icon: mdi:trash-can
          - type: Holiday
            show: False
          - type: HHW - Mahwah
            show: False
          - type: HHW - Paramus
            show: False
          - type: HHW - Moonachie
            show: False
```
```yaml
sensor:
- platform: waste_collection_schedule
  source_index: 0
  name: Allendale Trash - Garbage
  details_format: upcoming
  count: 1
  add_days_to: True
  types:
    - Garbage
```
