### ISSUE TITLE
Please check my config, I only get Unknown in my sensors.

### ISSUE THREAD

**Issue by hvddrift** [mampfes/hacs_waste_collection_schedule#1258]
I am sure I am missing something simple, I have tried a service call, but all my sensors are “UNKNOWN”

<img width="1190" alt="image" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/972926/9738e8a7-ce59-486f-8439-541bd407f484">

```
########### Waste
waste_collection_schedule:
  sources:
    - name: brisbane_qld_gov_au
      args:
        suburb: Hawthorne
        street_name: Dutton
        street_number: 57
      customize:
        - type: rubbish
          alias: Rubbish
          icon: mdi:trash-can
        - type: recycle
          alias: Recycle
          icon: mdi:recycle
```

And my sensors
```
- platform: waste_collection_schedule
  name: Next Rubbish Collection Date
  types:
    - rubbish
  value_template: '{{value.date.strftime("%d %b")}}'

- platform: waste_collection_schedule
  name: Next Recycling Collection Date
  types:
    - recycle
  value_template: '{{value.date.strftime("%d %b")}}'

- platform: waste_collection_schedule
  name: Next Rubbish Collection Days
  types:
    - rubbish
  value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'

- platform: waste_collection_schedule
  name: Next Recycling Collection Days
  types:
    - recycle
  value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'

- platform: waste_collection_schedule
  name: Next Rubbish Collection This Week
  types:
    - rubbish
  value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% elif value.daysTo <= 6 %}This {{value.date.strftime("%A")}}{% else %}in {{value.daysTo}} days{% endif %}'

- platform: waste_collection_schedule
  name: Next Recycling Collection This Week
  types:
    - recycle
  value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% elif value.daysTo <= 6 %}This {{value.date.strftime("%A")}}{% elif value.daysTo < 13 %}Next {{value.date.strftime("%A")}}{% else %}in {{value.daysTo}} days{% endif %}'
```
