### ISSUE TITLE
Only getting "Unknown" state and no data

### ISSUE THREAD

**Issue by kevinholtkamp** [mampfes/hacs_waste_collection_schedule#1268]
I installed the integration through HACS, and added the following to my configuration.yaml:
```yaml
sensor:
  - platform: waste_collection_schedule
    name: "Awigo"

waste_collection_schedule:
    sources:
    - name: awigo_de
      args:
        ort: "***"
        strasse: "***"
        hnr: "***"
```

The sources are all matching up with the documentation, but all i get is a sensor with "Unknown" state, and no entries in my calendar:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/32170328/a984d7b2-ee69-45f5-a460-1acad7408fc6)

What am I missing/doing wrong?

**Comment by 5ila5** [comment]
# awigo_de not yet part of current release

awigo_de is a new source and not yet part of the current release 1.42.0 it will be part of release 1.43.0 or you can get it by changing the version to master (When using HACS at redownload -> change version) or copy the [source file](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/awigo_de.py) to the right location.

# If you have the source but this still shows unknown

Are there any log entries for this integration?
Are There any events displayed in the calendar?
have you tried the test configuration (something wrong with this specific address):
```yaml
waste_collection_schedule:
    sources:
    - name: awigo_de
      args:
        ort: Bippen
        strasse: Am Bad
        hnr: 4
```
