### ISSUE TITLE
Requirements icalevents not found

### ISSUE THREAD

**Issue by dcbo** [mampfes/hacs_waste_collection_schedule#1271]
Hi, 
I am running Home Assistant in a Docker container.
I always get an error, when checking the "configuration.yaml" in HA.

What I did:
- Installed hacs_waste_collection_schedule
  - manual 
  - via HACS
- **Restarted Home Assistant**
- Inserted my waste_collection_schedule in the "configuration.yaml"
  - my personal configuration loading my local ICS-File 
  - as well as a provided demo Configuration
- Went to Hass and pressed the Button in the Developer Tools to check the "configuration.yaml"
- After a long time I get this Error Message:

`Integration error: waste_collection_schedule - Requirements for waste_collection_schedule not found: ['icalevents'].`

I tried any Combination of installation method and many other demo Configuration i found in the internet, all with the same result.

**What am i doing wrong?**

Here my Configuration
```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/Abfallkalender.ics"
        version: 1
      customize:
        - type: USB Abfuhr Grau - Restmüll
          alias: usb_rest
          icon: mdi:trash-can
        - type: USB Abfuhr Gelb - kombinierte Wertstofftonne
          alias: usb_gelbersack
          icon: mdi:recycle
        - type: USB Abfuhr Blau - Altpapier
          alias: usb_papier
          icon: mdi:trash-can-outline    
  fetch_time: "04:00"
  day_switch_time: "10:00"
 ```
