### ISSUE TITLE
awigo_de wrong calendar data

### ISSUE THREAD

**Issue by kevinholtkamp** [mampfes/hacs_waste_collection_schedule#1278]
Configuration:
```
sensor:
  - platform: waste_collection_schedule
    name: "Awigo"
    types:
      - Restmülltonne
      - Papiermülltonne
      - Gelbe Tonne/Gelben Sack
waste_collection_schedule:
    sources:
    - name: awigo_de
      args:
        ort: "Berge"
        strasse: "Poststraße"
        hnr: 3
```

Awigo Website:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/32170328/c2118a5d-a62d-4661-8173-87c2c4f75a41)

Home Assistant Calendar:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/32170328/17817792-ff5c-4c6b-b973-5ee448d89432)

The street name has to be different, using the same as on the website gives an error saying the street does not exist
