### ISSUE TITLE
Add support for Knittel Entsorgung that collects waste in a few cities/towns close to Neu-Ulm (Germany)

### ISSUE THREAD

**Issue by fetzerch** [mampfes/hacs_waste_collection_schedule#1281]
Unfortunately as far as I can see they don't offer an API or calendar files, but only PDFs:
https://www.knittel-entsorgung.com/abfuhrkalender-2023/

**Comment by 5ila5** [comment]
we generally avoided parsing pdfs as it is not easy to extract the correct information. 
Your best way is probably to use the [static source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md) and define your collections manually (looks like they follow a pretty straight forward pattern):

example (not tested):
holzheim ([pdf](https://www.knittel-entsorgung.com/wp-content/uploads/2022/12/2023_HOLZHEIM.pdf)):

```yaml
waste_collection_schedule:
  sources:
    - name: static
      args:
        type: Gelber Sack
        frequency: WEEKLY
        interval: 2
        start: '2023-01-03'
        until: '2023-12-31'
        excludes: # Add exception for the recurrence
          - '2023-04-11'
          - '2023-10-15'
        dates: # Manually add dates that are not part of the recurrence
          - '2023-04-12'
          - '2023-10-16'
    - name: static
      args:
        type: Papiertonne
        frequency: WEEKLY
        interval: 4
        start: '2023-01-18'
        until: '2023-12-31'
        excludes: # Add exception for the recurrence
          - '2023-10-16'
        dates: # Manually add dates that are not part of the recurrence
          - '2023-10-17'
    - name: static
      args:
        type: Restmüll
        frequency: WEEKLY
        interval: 2
        start: '2023-01-05'
        until: '2023-12-31'
        excludes: # Add exception for the recurrence
          - '2023-04-13'
          - '2023-06-08' 
          - '2023-10-17'
        dates: # Manually add dates that are not part of the recurrence
          - '2023-04-14'
          - '2023-06-09' 
          - '2023-10-18'
```

**Comment by fetzerch** [comment]
Starting 2025, Knittel now does also provide ICS files: https://www.knittel-entsorgung.com/abfuhrkalender-2025/

**Comment by markvp** [comment]
Thanks for the follow-up! Good news — Knittel Entsorgung is already supported via the generic ICS source. You can find the setup instructions in the docs:

https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/knittel_entsorgung_com.md

The short version:
1. Go to https://www.knittel-entsorgung.com and navigate to the waste collection calendar for your area.
2. Right-click the **Kalender** download link for your municipality and copy the URL.
3. Use that URL as the `url` parameter with the `ics` source:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://www.knittel-entsorgung.com/wp-content/uploads/...YOUR_MUNICIPALITY....ics
```

Note that the ICS files are year-specific — when a new year's file is published, you'll need to update the URL. Closing this as resolved.
