### ISSUE TITLE
Cities Apps

### ISSUE THREAD

**Issue by DerTurl** [mampfes/hacs_waste_collection_schedule#1312]
Cites Apps doesn´t work !

**_custom_components/waste_collection_schedule/waste_collection_schedule/wizard/citiesapps_com.py", line 1, in <module>
    from waste_collection_schedule.service.CitiesAppsCom import CitiesApps
ModuleNotFoundError: No module named 'waste_collection_schedule'_**

**Comment by 5ila5** [comment]
Its only the wizzard that is broken I fixed it in #1313 together with some minor reformatting.
Update this script from this reposetroy or move the first import line below site.addsitedir(str(package_dir)) and the wizzard should work again. configuring the.

**Comment by DerTurl** [comment]
Sorry i need Austria

**Comment by DerTurl** [comment]
I updated the repo and managed to use the wizard @linuxmint so i get the corect code for my village. 
import in configuration.yaml =>  restart => States / calendar.app_cities => unavailable !

Maybe there is no connection as a guest to "https://api.citiesapps.com/" ?

**Comment by 5ila5** [comment]
The source works on my side without any problem. If you can use the wizzard your requests are not blocked by the Server so you have connections as guest.

1. Please take a look at your logs weather there are any errors.
2. Try one example configuration that should work:

```yaml
waste_collection_schedule:
    sources:
    - name: citiesapps_com
      args:
        city: Fürstenfeld
        calendar: Haushalt Altenmarkt
```
