### ISSUE TITLE
missing file or path in source: aha_region_de.py

### ISSUE THREAD

**Issue by droelf123** [mampfes/hacs_waste_collection_schedule#1317]
Hi,
I recently installed Version 1.42.0 using HACS and cant get it to run.
Changed the adress to one of the test-adresses, but same issue.

That home directory '/home/silas/tmp/test.html' seems like debug file for some server-responds. But thats not going to work :)

Any ideas?

Thanks for your help!

configuration.yaml
```
waste_collection_schedule:
  sources:
    - name: aha_region_de
      args:
        gemeinde: "Hannover"
        strasse: "Voltastr. / Vahrenwald"
        hnr: "25"
        zusatz: ""
```

```
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 20:08:22 (2 occurrences)
Last logged: 20:09:05

fetch failed for source Zweckverband Abfallwirtschaft Region Hannover: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/aha_region_de.py", line 85, in fetch with open("/home/silas/tmp/test.html", "w") as f: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory: '/home/silas/tmp/test.html'`
```
