### ISSUE TITLE
Can't create the sensor part of the integration, for the love of God

### ISSUE THREAD

**Issue by ionuttimofte53** [mampfes/hacs_waste_collection_schedule#132]
this is the message from HA, when i try to save and restart: 

Invalid config for [sensor.waste_collection_schedule]: [sensors] is an invalid option for [sensor.waste_collection_schedule]. Check: sensor.waste_collection_schedule->sensors. (See ?, line ?).
This is how the sensor input looks in sensors.yaml : https://pastebin.com/VpCPsQ22

**Comment by mampfes** [comment]
Please check the documentation. Your sensor configuration should look like this:

```
sensor:
  - platform: waste_collection_schedule
    name: NAME
```

**Comment by Northcountry** [comment]
@mampfes the name has to match what is in the calendar.   - platform: waste_collection_schedule
  ```
name: next_garbage_all_collection
  types:
    - Garbage
    - Leaf & Yard Trimmings
    - Blue Box
    - Green Cart
```
In my calendar on collection day it has Garbage, Leaf & Yard Trimmings, Blue Box, Green Cart, all as separate entries.

**Comment by mampfes** [comment]
Did you manage to solve the issue?

**Comment by ionuttimofte53** [comment]
Hi, 
I went a different route, and i still arrived at the desired solution in my case. I chased GA to notify me one day before garbage collection. And i used the calendar input already created, to just announce me the type of garbage coming the next day, using a template. ( In my case, pickup is the same day of the week, just with different types of garbage).
I'm on my phone. I will try to fiddle with them, to get those sensors working, at a later time, even if i don't really need them.  Once i find the time, i will confirm if it works. But i don't understand why the sensors have to follow the naming from an external source. If the external source changes naming, sensors won't work, leading to broken automations. Not sure if you can change anything, if it's time consuming and so on. It's a suggestion from my part, for future versions.

**Comment by mampfes** [comment]
The sensor name is defined by you. The waste type is defined by your service provider. If you don't like it, you can give it an alias.

Regarding automation: Not sure what you actually want to achieve. Therefore this is just a hint: Add one sensor per waste type (by adding `types` and then specify only one waste type).
```yaml
sensor:
 - platform: waste_collection_schedule 
   name: next_garbage_collection
   types:
     - Garbage

 - platform: waste_collection_schedule 
   name: next_blue_box_collection
   types:
     - Blue Box
```
Use these sensors for automations.

**Comment by mampfes** [comment]
Any updates?

**Comment by Hohenloherin** [comment]
Sorry, but I can't get it to run, please help. 
I added the following into my configuration.yaml under sensor
```
-platform: waste_collection_schedule 
    sources:
        - name: abfallnavi_de
          args:
            service: n
            ort: Nuernberg
            strasse: xyzstrasse
 ```

After saving it, I get an error message from the server performing the configuration test:

`Platform error sensor.waste_collection_schedule - Integration 'waste_collection_schedule' not found.` 

Can someone give me a hint where to look and fix this? Thanks in advance.

**Comment by Northcountry** [comment]
@Hohenloherin I believe you don't have to put it in the sensors section for the service you're trying to get working and you also have to pay attention to the number of spaces in your yaml code, it's very specific. Try this below in your configuration.yml
```
waste_collection_schedule: 
 sources:
   - name: abfallnavi_de
     args:
       service: n
       ort: Nuernberg
       strasse: xyzstrasse
```
