### ISSUE TITLE
Multiple sources doesn't work (ICS and abfall_io)

### ISSUE THREAD

**Issue by og9gjz567** [mampfes/hacs_waste_collection_schedule#136]
Hi,
the last year your integration works very well and I like your work very much. In 2022 our waste will be collected from two different companies. The first one is available like the year before with abfall_io. The collection dates from the second company I put in an next-cloud calendar.
In the calendar-tab from ha I see both types of collections. The sensors show only the collection dates from abfall_io. If I comment out the abfall_io-part I get the collections from the ical.

Here's my config:
```
waste_collection_schedule:
  sources:
    
    - name: abfall_io
      calendar_title: Schönmackers
      args:
        key: <stripped>
        f_id_kommune: <stripped>
        f_id_strasse: <stripped>
        f_id_strasse_hnr: <stripped>
      customize:
        - type: Leichtverpackungen
          alias: gelbe Tonne
        - type: Papier
          alias: blaue Tonne
        - type: Schadstoffe
          show: false
        - type: Grünbündel
          show: false

    
    - name: ics
      calendar_title: RMG Rohstoffmanagement
      args:
        url: !secret ical_trash
      customize:
        - type: Restabfall
          alias: graue Tonne
        - type: Bioabfall
          alias: braune Tonne
```

My sensors:
```
- platform: waste_collection_schedule
  name: muell_kalender_test
  details_format: upcoming
```

![grafik](https://user-images.githubusercontent.com/58255842/148365360-af543e2c-0b7f-4a4a-9009-84a86e7c6db7.png)

How can I debug what's wrong. Is it stil possible to use 2 sources?

Thank you very much!
