### ISSUE TITLE
N Somerset - only getting one bin type returned and seems like fetch service isn't working?

### ISSUE THREAD

**Issue by BobC76** [mampfes/hacs_waste_collection_schedule#1376]
Hi
Struggling to work out how to get multiple bin schedules from my provider, North Somerset, UK.

From https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/nsomerset_gov_uk.md :

> "If collection data is available for the address provided, it will return food, rubbish and recycling waste collection dates."

Example postcode/URN that on the council site has two entries for Rubbish and Recycling:
```
waste_collection_schedule:
    sources:
    - name: nsomerset_gov_uk
      args:
        postcode: BS481RT
        uprn: 24128581
```

returns 
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/32709143/e00308d4-cebe-45ac-bdb5-a3ddca149b7f)

But the council web page gives:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/32709143/bb83fd07-e072-41a7-a7c8-6d2c023a2b69)

Am I doing something wrong in the configuration?

Further question: calling service "waste_collection_schedule: Fetch data from all sources." doesn't seem to update the last updated date/time for the calendar entity...

I tried to enable debug logging for the integration but seem to have nothing further in the logs.

Thanks very much
