### ISSUE TITLE
Problem with Abfall.IO / AbfallPlus.de value

### ISSUE THREAD

**Issue by florianibach** [mampfes/hacs_waste_collection_schedule#1377]
Hi, since a couple of days I am having trouble with my Value Sensor. I am using the Abfall.IO / AbfallPlus calendar: [Abfall.IO / AbfallPlus.de](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfall_io.md#abfallio--abfallplusde)

The configuration of the waste_collection_schedule is: 
```
sources:
    - name: abfall_io
      args:
        key: bb296b78763112266a391990f803f032
        f_id_kommune: 5745
        f_id_bezirk: 20
        f_id_strasse: 1522
        f_abfallarten:
          - 66
          - 177
          - 951
          - 190
          - 33
          - 347
```

and the configuration of the sensors is: 
```
- platform: waste_collection_schedule
  name: AbfallNotify
  details_format: 'upcoming'
  value_template: '{{value.daysTo}}'

- platform: waste_collection_schedule
  name: AbfallNotifyTyp
  details_format: "upcoming"
  source_index: 1
  value_template: '{{value.types|join(", ")}}'
```
for the first sensor (AnfallNotify) I am receiving the correct amount of days till the next schedule. 
But for the AbfallNotify the value is unavailable: 

It looks like the Dates and Types are returned correctly
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/60299630/6426800e-e1a6-4774-b136-7f16b0f4ab11)

It worked already in the past. 

System Info: 
Home Assistant Docker: 2023.6.3
Waste Collection Schedule: v1.43.0 (installed via HACS)
