### ISSUE TITLE
[Source Request]: Bergischer Abfallwirtschaftsverband

### ISSUE THREAD

**Issue by Patrickoli** [mampfes/hacs_waste_collection_schedule#1381]
### Municipality / Region

Burscheid / Bergischer Abfallwirtschaftsverband

### Collection Calendar Webpage

https://www.bavweb.de/Bergischer-Abfallwirtschaftsverband/Sammlung-und-Transport/

### Example Address

 Hauptstraße 36, 51399 Burscheid, Deutschland 

### Collection Data Format

As ICS/ICAL file

### Additional Information

There are 8 regions for which there are different waste calendars sorted by street.

**Comment by 5ila5** [comment]
Bergischer Abfallwirtschaftsverband is allready supported by the abfallnavi_de source like documented in the README.md 

[Bergischer Abfallwirtschaftverbund](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfallnavi_de.md) / bavweb.de

A valid configuration would be:
```yaml
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: bav
        ort: Burscheid
        strasse: Hauptstraße
        hausnummer: 36
```
 

Or did I miss something?
