### ISSUE TITLE
'day_switch_time' not working in HASS 0.118.0

### ISSUE THREAD

**Issue by derwolff** [mampfes/hacs_waste_collection_schedule#14]
Hi, 
I noticed that 'day_switch_time'  parameter is not working after HASS update to version 0.118.0.
The waste information disappears after midnight and not at the adjusted time.

**Comment by mampfes** [comment]
Hi, I just upgraded to 0.118. Need some more time to reconstruct the issue.

**Comment by derwolff** [comment]
Hi, I have deleted the 'day_switch_time' parameter in my config as a workaround. In this this case the default switch time of 10:00 is working.

**Comment by mampfes** [comment]
Interesting! Which value did you use for day_switch_time?

**Comment by derwolff** [comment]
This is my current configuration:

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "/config/custom_components/cal.ics"
#  day_switch_time: "09:00"
```
