### ISSUE TITLE
[Bug]: ZVA no longer working, bezirk not found

### ISSUE THREAD

**Issue by HolliDolli** [mampfes/hacs_waste_collection_schedule#1401]
### I Have A Problem With:

A specific source

### What's Your Problem

Hello everybody, 

there is an error in the log, telling the bezirk could not be found.
Error comes up with no change in configuration, but I can't find out when it happens first.
I tested with multiple bezirks, using the fetch data service. Error stays the same.
Error exist also in a second installation at another location, so hardware, software, internet-connection can be sorted out.

I already checked the website of ZVA, but can't see any changes. 

Any help is appreciated.

Holger

### Source (if relevant)

Zweckverband Abfallwirtschaft Schwalm Eder ZVA

### Logs

```Shell
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: November 6, 2023 at 1:14:09 AM (12 occurrences)
Last logged: 10:44:05 AM

fetch failed for source Zweckverband Abfallwirtschaft Schwalm-Eder-Kreis: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/zva_sek_de.py", line 68, in fetch raise Exception(f"bezirk not found") Exception: bezirk not found
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  fetch_time: "09:00"
#  day_switch_time: "12:00"
#  separator: ";"
  sources:
    - name: zva_sek_de
      calendar_title: "ZVA"
      args:
        bezirk: "Felsberg"
        ortsteil: "Felsberg"

Happens also for 

        bezirk: "Guxhagen"
        ortsteil: "Guxhagen"

And for the example:
        bezirk: "Fritzlar"
        ortsteil: "Fritzlar-kernstadt"
        strasse: "Ahornweg"
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
