### ISSUE TITLE
Unable to create custom garbage collection from ICS

### ISSUE THREAD

**Issue by rubenkr** [mampfes/hacs_waste_collection_schedule#141]
Hi there,

this addon is awesome! That said it lives and dies with the compatibility to use for my local garbage collection.

Home-Assistant is running on the maintained docker container from here: [dockerhub](https://hub.docker.com/r/homeassistant/home-assistant)

I read through the wiki and found that eventually the best route for me is via ICS GET Method.

**URL**: `https://service-dillingen-saar.fbo.de/date/Lilienthalstra%C3%9Fe/2022-01-01/+1%20year/?format=ics&type=rm,gs,bio,pa`

So I installed waste_collection_schedule via HACS and added the following to the Home-Assistant configuration.yaml:

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://service-dillingen-saar.fbo.de/date/Lilienthalstra%C3%9Fe/2022-01-01/+1%20year/?format=ics&type=rm,gs,bio,pa"

sensor:
  # next collection
  - platform: waste_collection_schedule
    name: next_waste_collection
```
Trying to check the configuration.yaml Home-Assistant does not finish its job. Forcing to restart does not show the desired sensor.next_collection.

Any help is much appreciated. Which route should I go? Import the calendar into Google Calendar and export it? Try to download the ICAL file?

Your help is much appreciated I would be happy to support this addition.

Kind regards!
