### ISSUE TITLE
[Bug]: Stadt Karlsruhe: Some addresses need a "ladeort" parameter

### ISSUE THREAD

**Issue by acn128** [mampfes/hacs_waste_collection_schedule#1412]
### I Have A Problem With:

A specific source

### What's Your Problem

Hi,

I've noticed that for some addresses in the City of Karlsruhe, when entering them on the web page (https://web6.karlsruhe.de/service/abfall/akal/akal.php), a new field "Abholplatz" is displayed.
For example, for the address "Bernsteinstraße 10" (example address), two "Abholplätze" are displayed (Bernsteinstraße 10 and Mauzenbergstraße 4).
Depending on the selected Abholplatz, different types of waste are displayed, eg. the paper waste is only displayed for Mauzenbergstraße 4.

The variable for "Abholplatz" is called "ladeort".
I tried adding it 'quick and dirty' like this to karlsruhe_de.py:
```
class Source:
    def __init__(self, street: str, hnr: str | int, ladeort: str | int):
        self._street: str = street
        self._hnr: str | int = hnr
        self._ladeort: str | int = ladeort

    def fetch(self):
        args = {
            "strasse_n": self._street,
            "hausnr": self._hnr,
            "ladeort": self._ladeort,
            "anzeigen": "anzeigen",
        }
```

and like this to configuration.yaml:

```
waste_collection_schedule:
    sources:
    - name: karlsruhe_de
      args:
        street: Bernsteinstraße
        hnr: 10
        ladeort: 2
      calendar_title: Müllabfuhr
```   

But I guess this does not work correctly for all other addresses :)

It would be great if this could be added in the correct way :)

Thank you very much!
acn128

### Source (if relevant)

karlsruhe_de

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: karlsruhe_de
      args:
        street: Bernsteinstraße
        hnr: 10
        ladeort: 2
      calendar_title: Müllabfuhr
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
