### ISSUE TITLE
[Bug]: waverley_gov_uk has corrected buggy POST data field name, meaning address name is no longer passed

### ISSUE THREAD

**Issue by gavink2** [mampfes/hacs_waste_collection_schedule#1422]
### I Have A Problem With:

A specific source

### What's Your Problem

waverley_gov_uk passes four POST fields - `address_name_numer`, `address_street`, `street_town` and `address_postcode`. Note the deliberate typo in the first one, which matches a typo in the server implementation. However, a couple of weeks ago the server implementation was updated and now expects `address_name_number` instead of `address_name_numer`.  This means that currently `address_name_numer` is being ignored and the incorrect schedule being returned as a result. This may affect other providers with a similar implementation, e.g. northherts_gov_uk, too.

### Source (if relevant)

waverley_gov_uk

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: waverley_gov_uk
      args:
        address_postcode: "GU27 XXX"
        address_name_numer: "XX"
        address_street: "XXXX"
        street_town: "XXXX"
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
