### ISSUE TITLE
[Bug]: Entries for all the Collection are existing twice in the calendar

### ISSUE THREAD

**Issue by reentier** [mampfes/hacs_waste_collection_schedule#1467]
### I Have A Problem With:

The integration in general

### What's Your Problem

Since a few days all the entries generated by the integration are shown twice in the calendar.

<img width="1067" alt="image" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/77726631/8da8de35-1fe9-4f92-8814-f32cd04bcf25">

### Source (if relevant)

sbazv_de

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: sbazv_de
      args:
        city: "My"
        district: "Address"
        street: "here"
sensor:
  # next collection
  - platform: waste_collection_schedule
    name: next_collection
    add_days_to: true # this line is important
    value_template: >-
      {% if value.daysTo == 0 %}
      HEUTE
      {% elif value.daysTo == 1 %}
      MORGEN
      {% else %}
      in {{value.daysTo}} Tagen
      {% endif %}
    
  # next yard waste collection
  - platform: waste_collection_schedule
    name: next_restmuell_collection
    add_days_to: true # this line is important
    value_template: >-
      {% if value.daysTo == 0 %}
      HEUTE
      {% elif value.daysTo == 1 %}
      MORGEN
      {% else %}
      in {{value.daysTo}} Tagen
      {% endif %}
    types:
      - Restmülltonnen
    
  # next garbage collection
  - platform: waste_collection_schedule
    name: next_papier_collection
    add_days_to: true # this line is important
    value_template: >-
      {% if value.daysTo == 0 %}
      HEUTE
      {% elif value.daysTo == 1 %}
      MORGEN
      {% else %}
      in {{value.daysTo}} Tagen
      {% endif %}
    types:
      - Papiertonnen

  # next garbage collection
  - platform: waste_collection_schedule
    name: next_gelbe_saecke_collection
    add_days_to: true # this line is important
    value_template: >-
      {% if value.daysTo == 0 %}
      HEUTE
      {% elif value.daysTo == 1 %}
      MORGEN
      {% else %}
      in {{value.daysTo}} Tagen
      {% endif %}
    types:
      - Gelbe Säcke
      
  # next garbage collection
  - platform: waste_collection_schedule
    name: next_laubsaecke_collection
    add_days_to: true # this line is important
    value_template: >-
      {% if value.daysTo == 0 %}
      HEUTE
      {% elif value.daysTo == 1 %}
      MORGEN
      {% else %}
      in {{value.daysTo}} Tagen
      {% endif %}
    types:
      - Laubsäcke
      
  # next garbage collection
  - platform: waste_collection_schedule
    name: next_weihnachtsbaeume_collection
    add_days_to: true # this line is important
    value_template: >-
      {% if value.daysTo == 0 %}
      HEUTE
      {% elif value.daysTo == 1 %}
      MORGEN
      {% else %}
      in {{value.daysTo}} Tagen
      {% endif %}
    types:
      - Weihnachtsbäume

  - platform: waste_collection_schedule
    name: MyButtonCardSensor
    value_template: '{{value.types|join(", ")}}|{{value.daysTo}}|{{value.date.strftime("%d.%m.%Y")}}|{{value.date.strftime("%a")}}'
      
# configuration.yaml
  - platform: waste_collection_schedule
    name: garbage_days
    details_format: appointment_types
    add_days_to: true # this line is important
    value_template: >-
      {% if value.daysTo == 0 %}
      HEUTE
      {% elif value.daysTo == 1 %}
      MORGEN
      {% else %}
      in {{value.daysTo}} Tagen
      {% endif %}
    types:
      - Restmülltonnen
      - Gelbe Säcke
      - Papiertonnen
      - Laubsäcke

  - platform: template
    sensors:
      garbage:
        value_template: >
          {% if state_attr('sensor.garbage_days', 'daysTo')|int > 2 %}
            2
          {% else %}
            {{ state_attr('sensor.garbage_days', 'daysTo')|int }}
          {% endif %}
        attribute_templates:
          next_date: "{{ state_attr('sensor.garbage_days', 'Garbage') }}"
          days: "{{ state_attr('sensor.garbage_days', 'daysTo')|int }}"
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
