### ISSUE TITLE
[Bug]: collect error after update to OS 11.2

### ISSUE THREAD

**Issue by cooki537** [mampfes/hacs_waste_collection_schedule#1483]
### I Have A Problem With:

The integration in general

### What's Your Problem

after updating to os 11.2, ther integration cannot collect the waste schedules.
i have not changed the configuration. with the previous OS 11.1 (i think) it was working without problems.

### Logs

```Shell
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 15:22:40 (1 occurrences)
Last logged: 15:22:40

fetch failed for source Abfallwirtschaft Nürnberger Land: Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 339, in parts validate_token(name) File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 128, in validate_token raise ValueError(name) ValueError: BEGIN During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/nuernberger_land_de.py", line 45, in fetch dates = self._ics.convert(ics) ^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert events: List[Any] = icalevents.events( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalevents/icalparser.py", line 288, in parse_events calendar = Calendar.from_ical(content) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalendar/cal.py", line 328, in from_ical name, params, vals = line.parts() ^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/icalendar/parser.py", line 353, in parts raise ValueError( ValueError: Content line could not be parsed into parts: ' BEGIN:VCALENDAR': BEGIN
```

### Relevant Configuration

```YAML
configuration.yaml
sensor: !include_dir_merge_list sensor/
waste_collection_schedule:
  sources:
    - name: nuernberger_land_de
      args:
        id: 14631001
  day_switch_time: "10:00"
sensor/sensor.yaml
- platform: waste_collection_schedule
  name: abfall_all
  types:
    - "Papier"
    - "Gelber Sack"
    - "Biotonne"
    - "Restmüll"
  add_days_to: 1
- platform: waste_collection_schedule
  name: abfall_papier
  details_format: "upcoming"
  value_template: '{{value.date.strftime("%d.%m.%Y")}}'
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  add_days_to: 1
  types:
    - "Papier"
- platform: waste_collection_schedule
  name: abfall_rest
  details_format: "upcoming"
  value_template: '{{value.date.strftime("%d.%m.%Y")}}'
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  add_days_to: 1
  types:
    - "Restmüll"
- platform: waste_collection_schedule
  name: abfall_bio
  details_format: "upcoming"
  value_template: '{{value.date.strftime("%d.%m.%Y")}}'
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  add_days_to: 1
  types:
    - "Biotonne"
- platform: waste_collection_schedule
  name: abfall_gelb
  details_format: "upcoming"
  value_template: '{{value.date.strftime("%d.%m.%Y")}}'
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  add_days_to: 1
  types:
    - "Gelber Sack"
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
