### ISSUE TITLE
[Bug]: 1.44.0 worked for a few days but now showing a completely new city/data

### ISSUE THREAD

**Issue by FS1961** [mampfes/hacs_waste_collection_schedule#1486]
### I Have A Problem With:

A specific source

### What's Your Problem

Not sure what happened. Previously identified an issue at 1.42.0 and the suggested fix was use master or wait for 1.44.0.  I used master for a while and then loaded 1.44.0 which worked for a couple of days.  You can see it was correct, but now I have the following.

Rebooted, reloaded, etc. no change.

<img width="584" alt="Screenshot 2023-12-06 at 9 08 13 AM" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/98458806/1297d833-e823-4de8-8bce-c04471b85f91">

### Source (if relevant)

landkreis_kusel_de

### Relevant Configuration

```YAML
- platform: waste_collection_schedule
    name: Trash
    details_format: upcoming
    count: 1
    leadtime: 2
    value_template: '{{value.types|join(", ")}} {% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} Days{% endif %}'

waste_collection_schedule:
  sources:
    - name: landkreis_kusel_de
      args:
        ortsgemeinde: Erdesbach
      calendar_title: "Trash Pickup"
      customize:
        - type: "Glasabfuhr"
          alias: "Glass"
          icon: mdi:sack-outline
        - type: "Bioabfall"
          alias: "Bio"
        - type: "Restmüll"
          alias: "Trash"
        - type: "Wertstoffsäcke"
          alias: "Recycling"
          icon: mdi:recycle
        - type: "Umweltmobil"
          alias: "Recycling van"
          icon: mdi:truck
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
