### ISSUE TITLE
[Bug]: Sheffield city council

### ISSUE THREAD

**Issue by barrel24** [mampfes/hacs_waste_collection_schedule#1493]
### I Have A Problem With:

A specific source

### What's Your Problem

This entity is no longer being provided by the waste_collection_schedule integration. If the entity is no longer in use, delete it in settings. error

SHOWS FINE IN CALENDER BUT UNAVAILIBLE ON SENSOR

### Source (if relevant)

sheffield_gov_uk

### Relevant Configuration

```YAML
waste_collection_schedule:
 sources:
 - name: sheffield_gov_uk
   args:
     uprn: *REDACTED*
   customize:
     - type: brown bin
       alias: Glass bin
     - type: blue bin
       alias: Paper bin
     - type: black bin
       alias: General bin
sensor:
   # next collection
 - platform: waste_collection_schedule
   name: next_collection
    
  # next yard waste collection
 - platform: waste_collection_schedule
   name: Blue Bin
   types:
   - Blue bin
    
  # next garbage collection
 - platform: waste_collection_schedule
   name: Black Bin
   types:
    - Black bin
 - platform: waste_collection_schedule
   name: Brown Bin
   types:
    - Brown Bin
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
