### ISSUE TITLE
[Source Request]: Zweckverband Ostholstein / MyMüll.de

### ISSUE THREAD

**Issue by Heilitown** [mampfes/hacs_waste_collection_schedule#1499]
### Municipality / Region

heiligenhafen / Ostholstein / Germany

### Collection Calendar Webpage

https://www.zvo.com/abfuhrkalender2024

### Example Address

23774 Heiligenhafen No Street is needed here (small town)

### Collection Data Format

As ICS/ICAL file, As html on a webpage, Dedicated IOS/Android APP

### Additional Information

Is listed at mymuell.de/app as MyMüll de Luxe "AbfallApp für Ostholstein" for ZVO - Zweckverband Ostholstein

**Comment by 5ila5** [comment]
ZVO is supported by the [jumomind_de source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/jumomind_de.md) I added offical Documentation in #1501 you can use the following:

```yaml
waste_collection_schedule:
  sources:
    - name: jumomind_de
      args:
        service_id: zvo
        city: Heiligenhafen
```
