### ISSUE TITLE
[Bug]: Mannheim / Germany - name: app_abfallplus_de - app_id: abfallMA.ucom.de

### ISSUE THREAD

**Issue by drueppela** [mampfes/hacs_waste_collection_schedule#1518]
### I Have A Problem With:

A specific source

### [Bug]: Mannheim / Germany - name: app_abfallplus_de - app_id: abfallMA.ucom.de

None of the configured args in Mannheim / Germany deliver a calendar (Excerp)

https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/app_abfallplus_de.md

```
waste_collection_schedule:
    sources:
    - name: app_abfallplus_de
      args:
        app_id: abfallMA.ucom.de
        city: Mannheim
        strasse: Am Hain
        hnr: 1
        city: Mannheim
        strasse: Alle Straßen
```

```
waste_collection_schedule:
    sources:
    - name: app_abfallplus_de
      args:
        app_id: abfallMA.ucom.de
        city: Mannheim
        strasse: Alle Straßen
```

### Street Directory of Mannheim / Germany:
https://mannheim.opendatasoft.com/explore/dataset/strassennamen-in-mannheim/table/?flg=de-de&disjunctive.beschlussdatum_bis

### [Working]: Braunschweig / Germany - name: app_abfallplus_de - app_id: de.albagroup.app

```
waste_collection_schedule:
    sources:
    - name: app_abfallplus_de
      args:
        app_id: de.albagroup.app
        city: Braunschweig
        strasse: Hauptstraße
        hnr: 7A
```

### Source (if relevant)

https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/app_abfallplus_de.md

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
