### ISSUE TITLE
[Bug]: Doku of landkreis_kusel_de is wrong

### ISSUE THREAD

**Issue by totow93** [mampfes/hacs_waste_collection_schedule#1520]
### I Have A Problem With:

A specific source

### What's Your Problem

The YAML Code is not correct.
The Exemple is:
```
waste_collection_schedule:
    sources:
    - name: landkreis_kusel_de
      args:
        ortsgemeinde: Adenbach
```
but this is right:
```
waste_collection_schedule:
  sources:
    - name: landkreis_kusel_de
      args:
        ortsgemeinde: Adenbach
```
https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/landkreis_kusel_de.md

### Source (if relevant)

landkreis_kusel_de

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
