### ISSUE TITLE
[Bug]: Exception: Region ... not found (Landkreis Waldshut, AbfallPlus)

### ISSUE THREAD

**Issue by halli77** [mampfes/hacs_waste_collection_schedule#1537]
### I Have A Problem With:

A specific source

### What's Your Problem

I use this integration for the first time and can't get it working. To create the config i used the wizard. Calendar is created, but empty. Logs shows some exceptions. I also tested with other communities or other streets in my district "Waldshut", with same effect. And I tried de.k4systems.unterallgaeu instead de.abfallwecker as app_id, because "Waldshut" is listet there as well. Same result.
Since I'm running out of ideas how to get it running, it might be a bug?
On my service providers site https://www.abfall-landkreis-waldshut.de/ there is an info, that a new city/street directory is implemented, maybe that could have an impact here?
<img width="1239" alt="Bildschirmfoto 2023-12-19 um 10 51 15" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/12441798/926848f0-e5d3-4ee6-8b51-bedd1d5015bc">

### Source (if relevant)

app_abfallplus_de

### Logs

```Shell
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 10:20:24 (2 occurrences)
Last logged: 10:20:48
fetch failed for source Apps by Abfall+: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py", line 124, in fetch for d in self._app.generate_calendar(): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 750, in generate_calendar self.select_kommune() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 490, in select_kommune raise Exception(f"Region {self._region_search} not found.") Exception: Region Lauchringen not found.
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: app_abfallplus_de
      args:
        app_id: de.abfallwecker
        city: Lauchringen
        strasse: [...]
        hnr: [...]
        bundesland: Baden-Württemberg
        landkreis: Waldshut
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
It's Kreis Waldshut not Waldshut the app seems to not show the internal name but the shortened one (first time I encountered this and I made this source)

this works for me:

```yaml
waste_collection_schedule:
    sources:
      - name: app_abfallplus_de
        args:
          app_id: de.abfallwecker
          city: Lauchringen
          strasse: Dr.-Urnau-Str.
          hnr: 5
          bundesland: Baden-Württemberg
          landkreis: Kreis Waldshut
```
