### ISSUE TITLE
[Feature]:  Add support for 2 or moore different locations with their own calendar

### ISSUE THREAD

**Issue by Masonmann1** [mampfes/hacs_waste_collection_schedule#1566]
### I propose a feature for:

The integration in general

### Describe your wanted feature

I would like to have the possibility to add 2 different locations/adresses and then to have seperate calendars for it in HA.

**Comment by 5ila5** [comment]
not sure what you mean excactly as you can do (Example for awb_emsland_de works with every source and different ones as well)
```yaml
waste_collection_schedule:
  sources:
    - name: awb_emsland_de
      args:
        city: Neubörger
        street: Aschendorfer Straße
        house_number: 1
        address_suffix: A
    - name: awb_emsland_de
      args:
        city: "Andervenne"
        street: "Am Gallenberg"
        house_number: 1
```

if you want to give different names use the calendar_title arguemtn:
```yaml
waste_collection_schedule:
  sources:
    - name: awb_emsland_de
      args:
        city: Neubörger
        street: Aschendorfer Straße
        house_number: 1
        address_suffix: A
      calendar_title: My first collection calendar 
    - name: awb_emsland_de
      args:
        city: "Andervenne"
        street: "Am Gallenberg"
        house_number: 1
      calendar_title: My second collection calendar 
```
