### ISSUE TITLE
[Bug]: Source buergerportal_de.py, operator alb_donau not working

### ISSUE THREAD

**Issue by carslen** [mampfes/hacs_waste_collection_schedule#1572]
### I Have A Problem With:

A specific source

### What's Your Problem

When adding source with operator `alb_donau` provided by `buergerportal.py`, no source at all is available in Calendar. 

As a work around I've configured ICS instead, also the exapmle config for operator `cochem_zell` works, but when adding a 3rd source with operator `alb_donau` the previously available calendars disapper and nothing is displayed.

Calendar with 2 sources:
<img width="1095" alt="grafik" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/28647218/d8cefe9f-4ca7-4e1d-957b-1ba2529a1089">

Empty calendar when all 3 sources configured as shown in `configuration.yaml` below:
<img width="1101" alt="grafik" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/28647218/7d7455ce-41f7-4898-b8f1-f215ef68dad3">

Tested with 1.44.0 and master.

@Chris909090 is your setup still working?

### Source (if relevant)

buergerportal_de

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
# waste_collection_schedule source configuration 
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: calendars/Abfallkalender2024.ics
        regex: "Abfuhr: (.*)"
    - name: buergerportal_de
      args:
        operator: cochem_zell
        district: Bullay
        subdistrict: Bullay
        street: Layenweg
        number: 3
    - name: blaubeuren
      args:
        operator: alb_donau
        district: Blaubeuren
        street: Alberstraße
        number: 3
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Alb-Donau works just fine on my end. Your config is wrong. You're trying to add a source called blaubeuren which does not exists you need to use the `name` buergerportal_de if you want to rename the calendar use the `calendar_title` argument. When adding the third wrong source there will be an error setting up the source (you should see a log entriy telling you so) and therefore the whole setup process fails.

the correct configuration would be:
```YAML
# waste_collection_schedule source configuration 
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: calendars/Abfallkalender2024.ics
        regex: "Abfuhr: (.*)"
    - name: buergerportal_de
      args:
        operator: cochem_zell
        district: Bullay
        subdistrict: Bullay
        street: Layenweg
        number: 3
    - name: buergerportal_de
      args:
        operator: alb_donau
        district: Blaubeuren
        street: Alberstraße
        number: 3
```
