### ISSUE TITLE
Shows wrong year (2023)

### ISSUE THREAD

**Issue by daloki83** [mampfes/hacs_waste_collection_schedule#1575]
### I Have A Problem With:

The integration in general

### What's Your Problem

I just added the new calendar for 2024 and placed it localy like in the past. For some reason is shows the upcoming events for 2023 not for 2024
ics File:
[abfallkalender.ics.zip](https://github.com/mampfes/hacs_waste_collection_schedule/files/13777016/abfallkalender.ics.zip)

![Bildschirmfoto vom 2023-12-27 09-42-36](https://github.com/mampfes/hacs_waste_collection_schedule/assets/29686097/74cb6744-53cf-46b6-88ae-fa2205fe520b)

I already redownloaded WCS and switched to Master branch but no changes :-( 

Maybe its because the entities does not contain a year?
![Bildschirmfoto vom 2023-12-27 09-44-17](https://github.com/mampfes/hacs_waste_collection_schedule/assets/29686097/10922dc2-a890-418d-a37d-d15566269a29)

Home Assistant Calendar tab - is fine. Everything in 2024

### Source (if relevant)

local .ics file

### Logs

```Shell
n/a
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/abfallkalender.ics"
      customize:
        - type: "Papier - Hauptstraße (Altenmittlau) - Freigericht"
          alias: Papiertonne
          picture: http://192.168.178.72:8123/local/Blauetonne.png
        - type: "Gelbe Tonne - Hauptstraße (Altenmittlau) - Freigericht"
          alias: GelberSack
          picture: http://192.168.178.72:8123/local/Gelbetonne.png
        - type: "Restmüll - Hauptstraße (Altenmittlau) - Freigericht"
          alias: Restmuell
          picture: http://192.168.178.72:8123/local/Schwarzetonne.png
  fetch_time: "04:00"
  day_switch_time: "12:00"
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
I will have a look later but:

you should be able to use this btw. So you do not need to update your local ics file.

```yaml
waste_collection_schedule:
  sources:
    - name: jumomind_de
      args:
        service_id: mkk
        city: Freigericht
        street: Hauptstraße (Altenmittlau)
```
