### ISSUE TITLE
[Bug]: Error when configuring Recycle Coach

### ISSUE THREAD

**Issue by cdn4lf** [mampfes/hacs_waste_collection_schedule#1596]
### I Have A Problem With:

A specific source

### What's Your Problem

Receiving error when configuring recycle coach for Vaughan Ontarion (unlisted city, but supported by recycle coach)

### Source (if relevant)

recycle coach

### Logs

```Shell
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 3:10:21 PM (1 occurrences)
Last logged: 3:10:21 PM

fetch failed for source Recycle Coach: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/recyclecoach_com.py", line 159, in fetch self._lookup_zones() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/recyclecoach_com.py", line 135, in _lookup_zones for zone_res in zone_data["results"]: ~~~~~~~~~^^^^^^^^^^^ KeyError: 'results'
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
  - name: recyclecoach_com 
    calendar_title: Waste Collection Schedule
    args:
      street: <<street address in lowercase>>
      city: <<city in lowercase>>
      state: <<province in lowercase>>
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
