### ISSUE TITLE
[Bug]: Waste type not showing for City of Doncaster  (Green Bin Collection)

### ISSUE THREAD

**Issue by skylineboy200000** [mampfes/hacs_waste_collection_schedule#1602]
### I Have A Problem With:

A specific source, The integration in general

### What's Your Problem

For Doncaster Council the Green bin collection only runs 9months out of 12. Next collection is in early March which can be viewed via the Council bin look-up calendar, but the waste type is not returned on the integration, it only seems to scrape 3 weeks in advance, can this be changed? 

### Source (if relevant)

doncaster_gov_uk

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: doncaster_gov_uk
      args:
        uprn: "xxxxxxx"

  - platform: waste_collection_schedule
    name: Bins
    details_format: appointment_types
    leadtime: 90
#    value_template: VALUE_TEMPLATE
#    date_template: DATE_TEMPLATE
    add_days_to: true
#    event_index: EVENT_INDEX
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
