### ISSUE TITLE
[Bug]: No Data for Nürnberger Land

### ISSUE THREAD

**Issue by GunterAv** [mampfes/hacs_waste_collection_schedule#1631]
### I Have A Problem With:

The integration in general

### What's Your Problem

Hello,

I no longer receive data for residual waste, Giftmobil and organic waste.
The error is since today. (HA Core 2024.1.0)

I reinstall with Version: "Master".
Downloaded Version : e1ea6a9

Best reagrds 
Gunter

### Source (if relevant)

nuernberger_land_de

### Relevant Configuration

```YAML
configuration.yaml:
waste_collection_schedule:
sources:
- name: nuernberger_land_de
args:
id: 16432001

sensors.yaml:

    platform: waste_collection_schedule
    name: muell
    types:
        "Biotonne"
        "Restmüll"
        "Papier"
        "Gelber Sack"
        "Giftmobil Röthenbach"
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
