### ISSUE TITLE
Static Source allow to exclude date range

### ISSUE THREAD

**Issue by 5ila5** [mampfes/hacs_waste_collection_schedule#1634]
### Discussed in https://github.com/mampfes/hacs_waste_collection_schedule/discussions/1621

<div type='discussions-op-text'>

<sup>Originally posted by **tonyv78** January  2, 2024</sup>
Hi to everybody, is the first time that i write in Github, i would like to ask if is possible to set a range of dates on the variable
"excludes" from the documentation there are example only with single date not with ranges of dates.

```
waste_collection_schedule:
  sources:
    - name: static
      args:
        type: Altpapier
        frequency: WEEKLY
        interval: 4
        start: '2022-01-14'
        until: '2022-12-31'
        excludes: # Add exception for the recurrence
          - '2022-07-29'
          - '2022-09-23'
        dates: # Manually add dates that are not part of the recurrence
          - '2022-07-28'
          - '2022-09-22'
```

I need to exclude a period of 4 month so if a need to insert day by day it will be time consuming it will be better to have the 
possibility to insert a range of dates.

Thanks in advance to anyone that can help me.
</div>

**Comment by markvp** [comment]
Thanks for the request! This has been implemented — the `excludes` parameter now accepts both individual date strings and range dicts, so you can write something like:

```yaml
excludes:
  - start: '2022-07-01'
    end: '2022-10-31'
```

A PR is open for review.
