### ISSUE TITLE
cannot import name 'SensorEntity'

### ISSUE THREAD

**Issue by KonstBr** [mampfes/hacs_waste_collection_schedule#165]
Hello,

i get the following error when checking the configuration:

Platform error sensor.waste_collection_schedule - cannot import name 'SensorEntity' from 'homeassistant.components.sensor' (/usr/src/homeassistant/homeassistant/components/sensor/__init__.py)

I use Home Assistant Core. I therefore installed the component manually.

I use the following configuration and it works. I see the calendar in HA

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/awb-abfuhrtermine.ics"
      customize:
        - type: Wertstoff (gelb) AWB Köln
          alias: gelb
          icon: mdi:recycle
        - type: Restmüll (grau) AWB Köln
          alias: rest
          icon: mdi:trash-can
        - type: Papier (blau) AWB Köln
          alias: papier
          icon: mdi:trash-can
  fetch_time: "04:00"
  day_switch_time: "10:00"
```

But the following sensor config doesn't work:

```
- platform: waste_collection_schedule
  name: AbfallRestmuell
  details_format: "upcoming"
  value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
  types:
    - rest
```

Thanks for helping
