### ISSUE TITLE
[Bug]: Calgary: no/missing dates

### ISSUE THREAD

**Issue by wooky** [mampfes/hacs_waste_collection_schedule#1659]
### I Have A Problem With:

A specific source

### What's Your Problem

The Calgary source is missing dates for some addresses, and completely not reporting for other addresses. The issue appears to be with the endpoint itself.

Since Calgary's website is using ReCollect, I propose deprecating the calgary_ca source and adding documentation on how to migrate to recollect instead.

### Source (if relevant)

calgary_ca

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
No data:

waste_collection_schedule:
  sources:
    - name: calgary_ca
      args:
        street_address: 42 AUBURN WY SE

Missing data (no black carts):

waste_collection_schedule:
  sources:
    - name: calgary_ca
      args:
        street_address: 924 19 ST NE
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by d-allin** [comment]
Don't think it's of any value, but I'll add that the Green type sensor is still picking up dates for my address (and next_collection sees them fine), but Black and Blue are right gone. Glad to hear it isn't just me.

Thanks for the Recollect recommendation; I'll check that out.

**Comment by 5ila5** [comment]
I could not find the original search interface which probably communicated with https://data.calgary.ca/resource/jq4t-b745.json (url fetched by the source). Therefore I can not fin an potentiall error with the current code.

They now display a recollect form. You can use the ICS source for recollect ([Recollect specific ICS documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/recollect.md))

**Comment by kenwiens** [comment]
I get blue and green but no black. I'm not sure where to make the changes to recollect as mentioned above.  Can someone point me in the right direction please?

**Comment by 5ila5** [comment]
The following works for    42 AUBURN SHORES WY SE, Calgary:

1. go to https://www.calgary.ca/waste/residential/garbage-schedule.html
2. search your address
3. click on `Get a calendar`
4. click on  `Add to Google Calendar`
5. copy ULR

use configruation (replace url)

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        split_at: '\, (?:and )?|(?: and )' # Splits events containing and into two events
        url: https://recollect.a.ssl.fastly.net/api/places/436C8528-D242-11E6-B825-04DB357E412A/services/298/events.en.ics?client_id=B88BF940-47E0-11EE-9B46-1C2A0824637C


        # OPTIONAL DO not use BOTH
        # if not used collections will be returned like "Green Cart - Food & Yard Waste"
        regex: (.*) -.* # will return events like "Green Cart"
        regex: .* - (.*) # will return events like "Food & Yard Waste"
```
