### ISSUE TITLE
[Bug]: Harborough District (https://www.fccenvironment.co.uk/) - No longer returning dates

### ISSUE THREAD

**Issue by misterpeee** [mampfes/hacs_waste_collection_schedule#1672]
### I Have A Problem With:

A specific source

### What's Your Problem

Integration is no longer reporting the collection dates for Haborough District - Sensor are as reported with the value 'unknown'.

I've attempted to call the api used in the code via postman, but it appears to return the fccenvironment search page or returns nothing?

### Source (if relevant)

https://www.fccenvironment.co.uk/

### Logs

```Shell
This error originated from a custom integration.

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 9:00:00 AM (1 occurrences)
Last logged: 9:00:00 AM

fetch failed for source FCC Environment: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/fccenvironment_co_uk.py", line 131, in fetch return self.harborough() ^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/fccenvironment_co_uk.py", line 110, in harborough ).find_all("li") ^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'find_all'
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: fccenvironment_co_uk
      args:
        uprn: <removed for privacy>
        region: harborough
      customize:
        - type: NON-RECYCLABLE WASTE BIN COLLECTION
          alias: Black bin
        - type: GARDEN WASTE COLLECTION
          alias: Green bin
        - type: RECYCLING COLLECTION
          alias: Blue bin
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
