### ISSUE TITLE
Types with multiple words are not working

### ISSUE THREAD

**Issue by fuuman** [mampfes/hacs_waste_collection_schedule#168]
Home Assistant Version: core-2021.12.10
```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://www.mycity.de/waste.ics"
        split_at: '/'
      customize:
        - type: Bio
          alias: bio
          icon: mdi:trash-can
        - type: Rest
          alias: rest
          icon: mdi:trash-can
        - type: gelbe Tonne
          alias: gelb
          icon: mdi:trash-can
        - type: blaue Tonne
          alias: altpapier
          icon: mdi:trash-can
        - type: Grün
          alias: gruen
          icon: mdi:trash-can
```
It's interesting that `rest`, `bio`and `gruen` are working perfectly fine. `gelb`and `altpapier` are not working. The sensors' values are `unknown`. So I am pretty sure that it has something to with the format of the type. `gelbe Tonne` and `blaue Tonne`has a whitespace, all working types have not.

**Comment by mampfes** [comment]
Could you share an ICS example?

**Comment by mampfes** [comment]
I checked your example. It is working on my machine.

I assume that your service provider is not sending a standard space character but something different (there are a lot of spaces in Unicode). To verify this, you can add a sensor **without** a `types` filter. If I'm right, then this sensor should show also the entries with the space character. You then you have to adjust the `type` field in the customize section.

**Comment by fuuman** [comment]
Thanks for taking a look into it.

Ah, again an encoding fail, hate it :D You are 100% right. If I setup a sensor without any filter it shows all entries, even the ones with "spaces". 

But what do you mean with "adjust the `type` field"? How? I mean how I am able to figure out which Unicode-space was used by my service provider?

**Comment by mampfes** [comment]
Ok, strange, but also interesting :-).

Yes, U+0020 is the standard space character. And I don't think that the Windows clipboard changes whitespaces internally - but who knows...

Could you give me access to original ICS source data?
And please share your sensor configuration(s).

**Comment by fuuman** [comment]
Original Link to ICS: https://www.bergheim.de/html/ics/Bergheim-2022.ics

Sensor Config: https://pastebin.com/T5MPGvwG

**Comment by mampfes** [comment]
I found the issue: The ICS source "normalizes" all waste types to [title case](https://www.w3schools.com/python/ref_string_title.asp) if the `split_at` option is set. This is necessary because there are service providers which use different case styles for the same waste type depending on the position within the joined waste type string. If you use the following config it should work:

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://www.bergheim.de/html/ics/Bergheim-2022.ics"
        split_at: "/"
      customize:
        - type: Bio
          alias: bio
          icon: mdi:trash-can
        - type: Rest
          alias: rest
          icon: mdi:trash-can
        - type: Gelbe Tonne
          alias: gelb
          icon: mdi:trash-can
        - type: Blaue Tonne
          alias: altpapier
          icon: mdi:trash-can
        - type: Grün
          alias: gruen
          icon: mdi:trash-can

```
