### ISSUE TITLE
[Bug]: AWSH not working anymore

### ISSUE THREAD

**Issue by nocin** [mampfes/hacs_waste_collection_schedule#1688]
### I Have A Problem With:

A specific source

### What's Your Problem

With the new year 2024, it seems like the AWSH integration stopped working. At least for me, all sensors are suddenly unavailable.
Their website is online: https://www.awsh.de/service/abfuhrtermine/

### Source (if relevant)

awsh_de

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: awsh_de
      args:
        city: Ammersbek
        street: Bornkamp
      customize:
        # my waste types I ordered
        - type: Restabfall 40L-240L(2-wöchentlich)
          alias: Restabfall
          icon: mdi:trash-can
        - type: Bioabfall(2-wöchentlich)
          alias: Bioabfall
          icon: mdi:leaf-circle
        - type: Wertstoff/LVP(2-wöchentlich)
          alias: Wertstoff
          icon: mdi:recycle
        - type: Papiertonne(monatlich)
          alias: Papier
          icon: mdi:trash-can
sensor:

  - platform: waste_collection_schedule
    name: Papierabfall_date
    value_template: '{{value.date.strftime("%d.%m.%Y")}}'
    types:
      - Papier

  - platform: waste_collection_schedule
    name: Papierabfall_collection
    value_template: "{{value.daysTo}}"
    types:
      - Papier

...
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
