### ISSUE TITLE
[Bug]: Daten von Bonn Orange werden zwar im Kalender angezeigt, aber nicht mehr als Entität unterstütz

### ISSUE THREAD

**Issue by wobeco** [mampfes/hacs_waste_collection_schedule#1762]
### I Have A Problem With:

A specific source

### What's Your Problem

Die bis Ende JAN24 fehlerfrei laufende Installation liefert zwar Daten im Kalender, verwendet aber die zugehörigen Entitäten seit einigen Tagen nicht mehr: "Diese Entität wird nicht mehr von der Integration waste_collection_schedule bereitgestellt. Wenn die Entität nicht mehr verwendet wird, lösche sie in den Einstellungen."

### Source (if relevant)

de.k4systems.bonnorange

### Logs

```Shell
keine relevanten Protokolle
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
Reason: Change from AbfallApp to something like "Abfallwirtschaft Pforzheim" (Athos, WasteManagementServlet)

**Comment by 5ila5** [comment]
Ich glaube nicht das die Source hier das Problem ist sie gibt mir immer noch Daten zurück. Wenn Termine im Kalender angezeigt werden, muss es dazu eigentlich auch eine calendar Identität geben. Bezieht sich die Meldung auf die calendar Identität oder auf einen Sensor? Wurde vielleicht eine neue Identität mit anderer ID erstellt?

**Comment by wobeco** [comment]
"Wenn Termine im Kalender angezeigt werden, muss es dazu eigentlich auch eine calendar Identität geben."
durch Klick auf den Kalendereintrag erhalte ich folgende Anzeige: 
![Screenshot 2024-02-06 093235](https://github.com/mampfes/hacs_waste_collection_schedule/assets/83753522/4137097b-1e99-4813-a268-6ce65a54fd9f)

"Bezieht sich die Meldung auf die calendar Identität oder auf einen Sensor?" 
bei Klick auf (bspw.) sensor.bioabfallbehalter erscheint ""Diese Entität wird nicht mehr von der Integration waste_collection_schedule bereitgestellt. Wenn die Entität nicht mehr verwendet wird, lösche sie in den Einstellungen." 

Ein Filtern nach 'bio' ergibt folgende Anzeige: 
![Screenshot 2024-02-06 093355](https://github.com/mampfes/hacs_waste_collection_schedule/assets/83753522/498c774e-424f-479f-a08f-64e5695e354b)

"Wurde vielleicht eine neue Identität mit anderer ID erstellt?"
bewußt wurde (außer HA-core Updates) nichts verändert ... wie kann ich die Fragestellung überprüfen?

**Comment by 5ila5** [comment]
Da der Kalender befüllt wird, denke ich, dass irgendwas mit deiner Sensorkonfiguration nicht stimmt. "unavialable" deutet darauf hin, dass du entweder die Sensorkonfiguration für diesen Sensor gelöscht hast oder beim Konfigurieren/Initialisieren ein Fehler aufgetreten ist. Könntest du die Konfiguration für deinen Sensor hier reinposten.

Die Kalender Identität sollte calendar.apps_by_abfall oder so heißen

**Comment by wobeco** [comment]
als Kalender Identität finde ich folgende
![Screenshot 2024-02-06 130745](https://github.com/mampfes/hacs_waste_collection_schedule/assets/83753522/9bfa83f7-ac2e-4a1a-9c5f-8c290d88cdba)

Ich ahne, dass deine Vermutung richtig sein könnte; da ich aber in der Konfiguration nichts angefasst hatte, denke ich an Fehler durch die letzten HA-core Aktualisierungen :-(

unter sensors.yaml sind die Sensoren aufgeführt; bspw. 
`# ------- Garbage Collection -------
# Nächste Abholung Gelber Behälter
- platform: waste_collection_schedule
  name: "Gelbe Behälter"
  value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
  types:
    - Gelbe Behälter`

ich sehe unter 'custom_components' auch das Verzeichnis 'waste_collection_schedule' mit zahlreichen weiteren Dateien - in welcher Datei sind welche Einträge für die Fehlersuche hier relevant?

**Comment by 5ila5** [comment]
Das Ändern der Identität scheint das gleiche Problem zu sein wie hier: #1476. Ich bin mir leider nicht sicher, woran das liegt (unter anderem, da ich nicht an der Entwicklung des Kerns dieser Integration beteiligt war). Das sollte aber eigentlich nicht die Sensoren beeinflussen. Du könntest mal probieren, bei der Source den `source_index` auf `1` zu setzen (oder `[0,1]`). Die Dateien in custom_components/waste_collection_schedule sollten die gleichen sein [wie die hier in diesem Repository](https://github.com/mampfes/hacs_waste_collection_schedule/tree/master/custom_components/waste_collection_schedule). Sie sind der Quellcode der Integration und beinhalten keinerlei Konfiguration oder Code, der vom User verändert werden sollte. Aber generell alles, was direkt in custom_components/waste_collection_schedule liegt, ist für die Integration zuständig. Alles was in custom_components/waste_collection_schedule/waste_collection_schedule ist im Großen und Ganzen für die Beschaffung und Verwaltung der Termine zuständig

**Comment by 5ila5** [comment]
In der [Sensor Konfiguration](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#configuring-sensors) kanst du den source_index wert mal auf 1 oder [0,1] setzen 

z.B:

```yaml
# ------- Garbage Collection -------
# Nächste Abholung Gelber Behälter
- platform: waste_collection_schedule
  name: "Gelbe Behälter"
  value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
  source_index: [0,1]
  types:
    - Gelbe Behälter
```

**Comment by wobeco** [comment]
Ich habe jetzt die Sensor-Definition wie folgt angepasst (Platzierung gem. [hier](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#combine-data-from-multiple-sources))

```
# ------- Garbage Collection -------
# Nächste Abholung Gelber Behälter
- platform: waste_collection_schedule
  source_index: [0,1]
  name: "Gelbe Behälter"
  value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
  types:
    - Gelbe Behälter
```

Auch nach mehrfachem Neustart und Warten keine Veränderung im reklamierten Verhalten.

**Comment by 5ila5** [comment]
Ist das der einzige Sensor, den du konfiguriert hast? Der Sensor oben aus deinem Bild bezieht sich auf den Bioabfallbehälter Sensor. Ist auch der gelbe Behälter Sensor betroffen? Kannst du mal bitte nachprüfen, ob du auch die sensor.yaml in deiner config einbindest `sensor: !include sensor.yaml`

**Comment by mampfes** [comment]
Hi, ich denke es gibt 2 Probleme:
1. Nicht mehr bereitgestellte Entitaeten (Bioabfallbehälter): Das passiert wenn man die Namen der Waste-Collection-Schedule Sensoren aendert. Ich vermute also dass es mal einen Sensor "Bioabfallbehälter" gab, der aber in der aktuellen config nicht mehr drin ist (oder anders heisst).
2. Der doppelte Eintrag fuer den Kalender. Das könnte das gleiche Problem sein wie #1476.

@wobeco Können Sie bitte ihre komplette Konfiguration hier teilen?

**Comment by wobeco** [comment]
@5ila5 hier der zugehörige Aufruf in der configuration.yaml (<..> sind natürlich mit realen Daten gefüllt):


```
# beziehe im File sensor.yaml definierte Sensoren mit ein
sensor: !include sensor.yaml
...

waste_collection_schedule:
# Abfallkalender für Bonn Orange
    sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.bonnorange
        strasse: <STRASSE>
        hnr: <HAUSNUMMER>


```

und hier die zugehörigen Einträge in der sensor.yaml

```
# ------- Garbage Collection -------
# Nächste Abholung Gelber Behälter
- platform: waste_collection_schedule
  source_index: [0,1]
  name: "Gelbe Behälter"
  value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
  types:
    - Gelbe Behälter
# Nächste Abholung Restabfallbehälter
- platform: waste_collection_schedule
  source_index: [0,1]
  name: "Restabfallbehälter"
  value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
  types:
    - Restabfallbehälter (verlegt)
    - Restabfallbehälter
# Nächste Abholung Papierbehälter
- platform: waste_collection_schedule
  source_index: [0,1]
  name: "Papierbehälter"
  value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
  types:
    - Papierbehälter
# Nächste Abholung Bioabfallbehälter
- platform: waste_collection_schedule
  source_index: [0,1]
  name: "Bioabfallbehälter"
  value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
  types:
    - Bioabfallbehälter
# Nächste Abholung Sperrmüll
- platform: waste_collection_schedule
  source_index: [0,1]
  name: "Sperrmüll"
  value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
  types:
    - Sperrmüll
```

Wie gesagt: die Konfiguration lief ja bis Ende JAN24 einwandfrei - jedenfalls bis zu den HA-core Update(s).

btw: in sensor.py gibt es folgenden Eintrag (Ausschnitt)
```
class ScheduleSensor(SensorEntity):
    """Base for sensors."""
```

ist der Unterschied zwischen '_sensor**s**.*_' und '_sensor.*_' hier möglicherweise relevant?
