### ISSUE TITLE
[Source Request]: tonnenleerung.de

### ISSUE THREAD

**Issue by xaquib666** [mampfes/hacs_waste_collection_schedule#1767]
### Municipality / Region

Langenmosen Germany

### Collection Calendar Webpage

https://tonnenleerung.de/nd-sob/langenmosen/

### Example Address

Streetname 10, 86571 Langenmosen

### Collection Data Format

As ICS/ICAL file, As html on a webpage

**Comment by ReneNulschDE** [comment]
There is already a solution available: [Awido source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/awido_de.md)

Configuration example:
```
    - name: awido_de
      args:
        customer: landkreisbetriebe
        city: Langenmosen
        street: Am Sommerfeld
```
