### ISSUE TITLE
[Bug]: WAS - Wolfsburger Abfallwirtschaft u. Straßenreinigung did no longer collects the waste appointments

### ISSUE THREAD

**Issue by dp20eic** [mampfes/hacs_waste_collection_schedule#1778]
### I Have A Problem With:

A specific source

### What's Your Problem

Since February 8th, 2024, I no longer see any appointments displayed in the calendar and therefore no more appointments are shown to me in the automations.

## my configuration
```
# Abfallkallender
waste_collection_schedule:
  sources:
    - name: was_wolfsburg_de
      args:
        city: my district
        street: my street
  fetch_time: "04:00"
  day_switch_time: "10:00"
sensor:
  # ------- Garbage Collection -------
  # next collection
  - platform: waste_collection_schedule
    name: "Nächste Abholung"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{valu
  # Nächste Bioabfall Abholung
  - platform: waste_collection_schedule
    name: "Bioabfall"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{valu
    types:
      - Bioabfall
  # Nächste gelber-Sack Abholung
  - platform: waste_collection_schedule
    name: "Gelber Sack"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{valu
    types:
      - Gelber Sack
  # Nächste Papierabfall Abholung
  - platform: waste_collection_schedule
    name: "Altpapier"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{valu
    types:
      - Altpapier
  # Nächste Restabfall-Abholung
  - platform: waste_collection_schedule
    name: "Restabfall "
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{valu
    types:
      - Restabfall
```

### Relevant Configuration

```YAML
I saw that WAS changed the website, that could be the reason that the data can no longer be found.
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
