### ISSUE TITLE
[Feature]: Subtract 1 day for Putting Bins out the night before

### ISSUE THREAD

**Issue by DrewXT** [mampfes/hacs_waste_collection_schedule#1788]
### I propose a feature for:

The integration in general

### Describe your wanted feature

In our household, we put the bins out the night before collection day.  We live in the City of Kingston in Australia, for which I have the integration working nicely.  The council displays the "actual" bin day, but would it be possible to have a configurable option on the integration to allow it to knock a day off?

I can do it with value_templating, however when it's the "actual" bin day, I get 0 days, rather than 13 days until the next fortnightly collection or 6 until the next weekly.

I have the integration configured per below:

```
waste_collection_schedule:
  sources:
    - name: kingston_vic_gov_au
      args:
        post_code: !secret postcode
        suburb: !secret suburb
        street_name: !secret street
        street_number: !secret house_number
      customize: 
        - type: General waste (landfill)
          alias: Rubbish
          icon: mdi:delete-empty
        - type: Recycling
          alias: Recycling
          icon: mdi:recycle
        - type: Food and garden waste
          alias: Garden Waste
          icon: mdi:leaf
  day_switch_time: "23:59"
```

and the sensors look like this:

```
- platform: waste_collection_schedule
  name: Rubbish
  source_index: 0
  details_format: upcoming
  value_template: "{% if value.daysTo == 1 %}Today{% elif value.daysTo == 2 %}Tomorrow{% else %}in {{value.daysTo - 1}} days{% endif %}"
  types:
    - Rubbish
```

It's highly likely there's a better way of doing it than I'm asking, but it's got me stumped

**Comment by 5ila5** [comment]
I think you want to change the day_switch_time to something like 1:00, so this integration will dismiss the events from "TODAY" at 1:00 AM and display the next one (I did not test this).

**Comment by DrewXT** [comment]
Cheers, I'll give it a go :)

**Comment by Whizzykid** [comment]
I'm also keen to understand how to do this, has anybody found a working solution?

**Comment by DrewXT** [comment]
I ended up configuring my bin collection days as a static calendar like the bruxy integration worked, as I couldn't get the day entity to stop slowing unknown for the day of collection

**Comment by Dreanaught** [comment]
If you want to be notified by Home Assistant e.g. through a notification on your phone you can use an automation like this one:
```
description: "Waste collection notification to phone"
trigger:
  - platform: calendar
    event: start
    offset: "-24:15:0"
    entity_id: calendar.waste_collection
condition: []
action:
  - device_id: ###
    domain: mobile_app
    type: notify
    message: >-
      Event {{ trigger.calendar_event.summary }} @ {{
      trigger.calendar_event.start }}
  mode: single
```

**Comment by 5ila5** [comment]
@Dreanaught this does not really belong here as it has nothing to do with this issue, also note this might not show all notifications if there are multiple collections on one day

**Comment by b2un0** [comment]
@Dreanaught thanks, for me this example works.

**Comment by BenBarat** [comment]
> it shows Unknown from **10:00** on the day of collection until 01:00 (give or take a few minutes) the next day, irrespective of how I configure day_switch_time, which leads me to think that it's ignoring the parameter - my data source is valid when it's retrieving "Unknown" as well, which I don't really get...
> 
> ![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/61401526/5d5946c6-22f9-4a40-9d47-0cbbc56513e7)

Just wondering if this is related to GMT vs your local time zone (about 10 hours difference in Eastern Australia)? Just too co-incidental to be an underlying bug in the waste collection software or your integration code..

**Comment by danielbrunt57** [comment]
@DrewXT Have you tried `day_offset: -1` in the source configuration?
What about `add_days_to: -1`  in the sensor??  Not sure if it accepts a negative number...

**Comment by markvp** [comment]
Thanks for raising this, and thanks to everyone who contributed workarounds in the thread.

The good news is that this is already supported via the `day_offset` parameter on your source configuration. Setting it to `-1` shifts all collection dates back by one day, which is exactly what you need for putting bins out the night before:

```yaml
waste_collection_schedule:
  sources:
    - name: kingston_vic_gov_au
      args:
        post_code: !secret postcode
        suburb: !secret suburb
        street_name: !secret street
        street_number: !secret house_number
      day_offset: -1
      customize:
        - type: General waste (landfill)
          alias: Rubbish
          icon: mdi:delete-empty
        - type: Recycling
          alias: Recycling
          icon: mdi:recycle
        - type: Food and garden waste
          alias: Garden Waste
          icon: mdi:leaf
  day_switch_time: "23:59"
```

Full documentation is in [doc/installation.md](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#configuration-variables).

On the "Unknown" issue you saw earlier — the default `day_switch_time` of `10:00` is in your Home Assistant's local time, so that shouldn't be a problem. If you do still see "Unknown" after adding `day_offset: -1`, double-check that your HA timezone is set correctly (Configuration → System → General).

Closing this as the requested functionality is already available.
