### ISSUE TITLE
recycleapp_be not working for some addresses

### ISSUE THREAD

**Issue by Maarten-VanBriel** [mampfes/hacs_waste_collection_schedule#180]
when I enter my address into the configuration.yaml I receive this error on restart:
```
fetch failed for source Recycle!: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", 
line 116, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/recycleapp_be.py", 
line 79, in fetch entries.append(Collection(date, item["fraction"]["name"]["en"])) KeyError: 'name'
```
when I use the example address or some other addresses everything works fine. Is it a problem with my city? Because other addresses of this city also don't work, even though those addresses work on [Recycle!](https://recycleapp.be/home).
this is what I have in configuration.yaml
```
waste_collection_schedule:
  sources:
    - name: recycleapp_be
      args:
        postcode: 3001
        street: Waversebaan
        house_number: 276
```
