### ISSUE TITLE
[Bug]: Source Ronneby Miljöteknik Sophämtning does not seem to work

### ISSUE THREAD

**Issue by mingan666** [mampfes/hacs_waste_collection_schedule#1804]
### I Have A Problem With:

A specific source

### What's Your Problem

I've tried to integrate through HACS according to the documentation, but I do not seem to get any data.
I've tried to increase logging, but no logs are generated related to this component at all.
The sensor state is always set to "unknown" and the calendar remains empty.

### Source (if relevant)

doc/source/miljoteknik_se.md

### Logs

```Shell
No relevant log info found. I tried to change HACS to debug, but it didn't give much.
If there is anyway to force more logs from the component, please let me know how...
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: miljoteknik_se
      args:
        street_address: "xxx"
  fetch_time: "10:40"

sensor:
  - platform: waste_collection_schedule
    name: Miljöteknik
    count: 2

logger:
  default: info
  logs:
    custom_components.hacs: debug
    aiogithubapi: debug
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
