### ISSUE TITLE
Leeds City Council, UK[Source Request]: 

### ISSUE THREAD

**Issue by BillyRichards** [mampfes/hacs_waste_collection_schedule#1807]
### Municipality / Region

Leeds City Council, UK

### Collection Calendar Webpage

https://www.leeds.gov.uk/residents/bins-and-recycling/check-your-bin-day

### Example Address

1 Oakroyd, Rothwell, Leeds, LS26 0BL

### Collection Data Format

As html on a webpage, Dedicated IOS/Android APP

**Comment by avocadio** [comment]
For reference: 
- https://github.com/joemcc-90/leeds-bins-hass/ 
The data has been compiled by the following repo who also provide a mobile app:
- https://github.com/odileeds/bins

**Comment by markvp** [comment]
Thanks for the request, @BillyRichards! Leeds City Council is already supported via the **Apps by imactivate** source, which was added in July 2024.

You can set it up using `apps_imactivate_com` with your postcode, street, and house number. Full details and a Leeds-specific example are in the docs:

https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/apps_imactivate_com.md

Example configuration for Leeds:

```yaml
waste_collection_schedule:
    sources:
    - name: apps_imactivate_com
      args:
        postcode: LS26 0BL
        town: Leeds
        street: Oakroyd
        number: 1
```

Closing as already supported.
