### ISSUE TITLE
[Bug]: abfall_io returns only paert of the Data

### ISSUE THREAD

**Issue by Pinky007** [mampfes/hacs_waste_collection_schedule#1830]
### I Have A Problem With:

A specific source

### What's Your Problem

I have my setup setup for the Böblingen area fro more than 2 years and it was working fine.
`waste_collection_schedule:
  sources:
    - name: abfall_io
      args:
        key: !secret waste_collection_key
        f_id_kommune: 2990
        f_id_bezirk: 17,18,19,20
        f_id_strasse: 522
        f_abfallarten:
          - 50
          - 53
          - 31
          - 299`
          
However, it seems that since 2024, the Paper (53) and recyclable (werkstoff) (299) are not read anymore.
If I go to the website https://www.awb-bb.de/Abfuhrtermine, I can see that they are still available.

I tried to check if the "abfallarten" numbers changed but my reasearch pointed to the fact that there was no change.
The key seems also to be the same as it is still working for the general waste as well as for Organics.

I am not sure where it could come from and would be happy for any help.

Thank you!

### Source (if relevant)

abfall_io

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
`waste_collection_schedule:
  sources:
    - name: abfall_io
      args:
        key: !secret waste_collection_key
        f_id_kommune: 2990
        f_id_bezirk: 17,18,19,20
        f_id_strasse: 522
        f_abfallarten:
          - 50
          - 53
          - 31
          - 299`
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
I cannot reproduce this issue as

```yaml
waste_collection_schedule:
  sources:
    - name: abfall_io
      args:
        key: "8215c62763967916979e0e8566b6172e"
        f_id_kommune: 2990
        f_id_bezirk: 17,18,19,20
        f_id_strasse: 522
        f_abfallarten:
          - 50
          - 53
          - 31
          - 299
```
returns Papier collection (next 2024-03-02) and Wertstoffe (next 2024-03-14)
