### ISSUE TITLE
[Request] ASP Paderborn

### ISSUE THREAD

**Issue by LooneyN** [mampfes/hacs_waste_collection_schedule#184]
Hello!

Would it be possible to add as ASP (Paderborn) as a source?

It works fine by adding the ICS but it would be nice if it'd be supported out of the box (if possible) :)

Link:
https://www.paderborn.de/microsite/asp/abfallentsorgung/abfuhrtermine_pb.php

Example Street: 
Marienloher Straße

Its available as PDF, Online View and iCal

Thank you :)

**Comment by mampfes** [comment]
Your hometown is using MyMuell (by Jumomind) as service provider. There is already a source for that. The config for "Marienloher Strasse" is:

```yaml
waste_collection_schedule:
  sources:
    - name: jumomind_de
      args:
        service_id: mymuell
        city_id: 48001
        area_id: 1316

```
