### ISSUE TITLE
[Bug]: sensor show unknown after home assistant update 2024.2.5

### ISSUE THREAD

**Issue by whoamihe** [mampfes/hacs_waste_collection_schedule#1847]
### I Have A Problem With:

The integration in general

### What's Your Problem

all sensors worked before the core update 2024.2.5, after that all sensors show unknown state
Here one example of my configuration.yaml
```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/AbfallkalenderGelb.ics"
      customize:
        - type: Gelb
          alias: GelberTonne
          icon: mdi:recycle
      calendar_title: Muell_Gelb
```
and the configuration in sensor.yaml

```
  - platform: waste_collection_schedule
    source_index: 0
    name: Gelber Sack
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - GelberTonne
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
