### ISSUE TITLE
[Bug]: Customization of Sensors Names are not possible

### ISSUE THREAD

**Issue by BMWfan** [mampfes/hacs_waste_collection_schedule#1849]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

I had specific aliases for the different types of wastes and was trying to change them 
(Relevant Configuration Section)

After a restart of Homeassistant are all the old aliases still existing and the new once not present:
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/5577540/fd9a0ecf-d5c6-467d-8008-9915a3d849cf)

I deleted waste_collection_schedule folder already out of the custom_components folder rebooted my homeassistant and readded it with a reboot afterwards without success.

### Relevant Configuration

```YAML
customize:
        - type: residual_2
          alias: "Restmüll"
        - type: bio_2
          alias: "Biomüll"
        - type: light-packaging
          alias: "Gelber Sack"
        - type: paper
          alias: "Papier"
        - type: paper_big_1
          show: False
        - type: residual_big_1
          show: False
        - type: residual_big_2
          show: False
        - type: paper_bi_4
          show: False
        - type: paper_big_1
          show: False
        - type: paper_big_2
          show: False
        - type: residual_big_1_2
          show: False
        - type: paper-bundle
          show: False
        - type: green
          show: False
        - type: residual_4
          show: False
        - type: paper_big_4
          show: False
```
and tried to change it to

```
      customize:
        - type: residual_2
          alias: "Schwarze Tonne"
        - type: bio_2
          alias: "Braune Tonne"
        - type: light-packaging
          alias: "Gelbe Tonne"
        - type: paper
          alias: "Blaue Tonne"
        - type: paper_big_1
          show: False
        - type: residual_big_1
          show: False
        - type: residual_big_2
          show: False
        - type: paper_bi_4
          show: False
        - type: paper_big_1
          show: False
        - type: paper_big_2
          show: False
        - type: residual_big_1_2
          show: False
        - type: paper-bundle
          show: False
        - type: green
          show: False
        - type: residual_4
          show: False
        - type: paper_big_4
          show: False
```
```


### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
