### ISSUE TITLE
Not Able to Pull data for Auckland

### ISSUE THREAD

**Issue by kiwilarka** [mampfes/hacs_waste_collection_schedule#185]
Hi, What a wonderful idea to automatically update it. Great concept. I think Documentation is lacking for new users. Probably would be ideal to have more step by step guides.

I have got the following config in YAML, took ages to generate it without errors. My sensors show up but they are blank, no information is getting pulled. Any help will be much appreciated.

`waste_collection_schedule:
  sources:
    - name: aucklandcouncil_govt_nz
      args:
        area_number: 12342560766
      customize:
        - type: brown bin
          show: no
        - type: Rubbish
        - type: Recycling
sensor:
  # next collection
  - platform: waste_collection_schedule
    name: next_collection
    
  # next yard waste collection
  - platform: waste_collection_schedule
    name: next_yard_collection
    types:
      - Rubbish
    
  # next garbage collection
  - platform: waste_collection_schedule
    name: next_garbage_collection
    types:
      - Recycling`

**Comment by mampfes** [comment]
Try (note that yaml is case sensitive and that indentation counts!):

```yaml
waste_collection_schedule:
  sources:
    - name: aucklandcouncil_govt_nz
      args:
        area_number: 12342560766
      customize:
        - type: brown bin
          show: no

sensor:
  - platform: waste_collection_schedule
    name: next_collection
  - platform: waste_collection_schedule
    name: next_yard_collection
    types:
      - rubbish
  - platform: waste_collection_schedule
    name: next_garbage_collection
    types:
      - recycle
```

Could you explain the problems you had? This would be helpful to improve to documentation. Or even better: Provide a suggestion :-)

**Comment by kiwilarka** [comment]
Sorry my code was right the formatting got stuffed when i pasted here. So its exactly same as you have mentioned above, configurations check out.
But when i insert the sensor in a button , it shows as Next Garbage collection (Unknown)
it means its not picking up the values from the website, how do i test or confirm that.
I will create a video for step by step to help you out. instead of suggestions.

**Comment by mampfes** [comment]
I had to adjust `rubbish `and `recycle` to get it working! Please check if you use exactly the same values.

**Comment by kiwilarka** [comment]
Hi, Thanks for the prompt reply, I used it exactly as mentioned above but when i put the sensor to home screen it has unknown value. How to Troubleshoot ?
how do i confirm if its picked up the value from that site ? and what variables or names its using.

Below is a copy paste from my Configuration.Yaml and attached is my button

````
waste_collection_schedule:
  sources:
    - name: aucklandcouncil_govt_nz
      args:
        area_number: 12342560766
      customize:
        - type: brown bin
          show: no

sensor:
  - platform: waste_collection_schedule
    name: next_collection
  - platform: waste_collection_schedule
    name: next_yard_collection
    types:
      - rubbish
  - platform: waste_collection_schedule
    name: next_garbage_collection
    types:
      - recycle
````
![image](https://user-images.githubusercontent.com/74592813/159843979-c84e25bf-c31a-4a7f-8192-352de67acd06.png)

**Comment by mampfes** [comment]
Ok, strange. Here is a small step-by-step instruction:

1. Check that there are no errors in the HA logs.
2. Check that the dates appear in the HA calendar. It should look like this with your configuration:
![image](https://user-images.githubusercontent.com/375950/159855180-1c036c52-b720-49de-b146-f25520067fdd.png)
3. Open the HA Developer Tools and check the state of the 3 sensors. They should look like this:
![image](https://user-images.githubusercontent.com/375950/159855345-2fab0364-b977-426b-9ce9-a0f1a7f2b6ed.png)

If I use the configuration above, the entity cards look like this:
![image](https://user-images.githubusercontent.com/375950/159855691-157bc627-37a8-4f7d-9d15-63d473d3e3bf.png)

**Comment by kiwilarka** [comment]
Excellent Help, At least now i know where to go and find the info.
so I have it half working. Its only pulling the rubbish and rubbish, recycle both under same sensor.
how do i fix it or do i just leave that as is.

![image](https://user-images.githubusercontent.com/74592813/159857591-2a3b8eff-a31c-473a-b2ed-483a167cfc19.png)

**Comment by kiwilarka** [comment]
All working now, guess took a while to pull that through. 
We can close this now please.
Thanks

**Comment by kellyatkinson** [comment]
I wish I'd seen this sooner @kiwilarka as I could have helped too. Here is what I am using myself:

In configuration.yaml:
```
waste_collection_schedule:
  sources:
    - name: aucklandcouncil_govt_nz
      args:
        area_number: 12343981102 
        # from https://www.aucklandcouncil.govt.nz/rubbish-recycling/rubbish-recycling-collections/Pages/rubbish-recycling-collection-days.aspx
      customize:
        - type: rubbish
          alias: Rubbish
          icon: mdi:trash-can
        - type: recycle
          alias: Recycling
          icon: mdi:recycle
      calendar_title: Auckland Council Rubbish & Recycling Collections
  day_switch_time: "17:00"
```

In my sensors file (I have sensors in a separate .yaml file, but you could have these in configuration.yaml under `sensors:`)
They are all slight tweaks on the same data so I can display it in different formats for different purposes - the "this week" set is what I use the most.

```
- platform: waste_collection_schedule
  name: Next Rubbish Collection Date
  types:
    - Rubbish
  value_template: '{{value.date.strftime("%d %b")}}'

- platform: waste_collection_schedule
  name: Next Recycling Collection Date
  types:
    - Recycling
  value_template: '{{value.date.strftime("%d %b")}}'

- platform: waste_collection_schedule
  name: Next Rubbish Collection Days
  types:
    - Rubbish
  value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'

- platform: waste_collection_schedule
  name: Next Recycling Collection Days
  types:
    - Recycling
  value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'

- platform: waste_collection_schedule
  name: Next Rubbish Collection This Week
  types:
    - Rubbish
  value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% elif value.daysTo <= 6 %}This {{value.date.strftime("%A")}}{% else %}in {{value.daysTo}} days{% endif %}'

- platform: waste_collection_schedule
  name: Next Recycling Collection This Week
  types:
    - Recycling
  value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% elif value.daysTo <= 6 %}This {{value.date.strftime("%A")}}{% elif value.daysTo < 13 %}Next {{value.date.strftime("%A")}}{% else %}in {{value.daysTo}} days{% endif %}'
```

Glad you have it working now!
