### ISSUE TITLE
Data from sector27.de missing 

### ISSUE THREAD

**Issue by Elbredde** [mampfes/hacs_waste_collection_schedule#1876]
### I Have A Problem With:

A specific source

### What's Your Problem

I installed the repository and alos added the data to configuration.yaml. I live in Datteln which I found under sector27. However  there is no synchronization, neither if i change to other streets and /or cities in sector27:

```yaml
waste_collection_schedule:
  sources:
    - name: sector27_de
      args:
        city: City
        street: street
```

is there an other possibility then sector27
can anyone help?
kind regards
elmar

### Source (if relevant)

sector27_de.md

### Logs

```Shell
no relevant logs
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
```yaml
waste_collection_schedule:
  sources:
    - name: sector27_de
      args:
        city: Datteln
        street: Am Bahnhof
```

Works on my side.

What exactly do you mean with "_However there is no synchronization_". Is your calendar populated with events? Did you write the street exactly like autocompleted by the form: https://www.datteln.de/muellabfuhrkalender?
