### ISSUE TITLE
[Bug]: source not found: n-kesteven_org_uk

### ISSUE THREAD

**Issue by danmiles86** [mampfes/hacs_waste_collection_schedule#1885]
### I Have A Problem With:

A specific source

### What's Your Problem

I keep getting the error;

"Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:192
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 00:59:52 (1 occurrences)
Last logged: 00:59:52
source not found: n-kesteven_org_uk"

yaml for setup;
```
waste_collection_schedule:
    sources:
    - name: n-kesteven_org_uk
      args:
        uprn: "1000320****"
```

### Source (if relevant)

n-kesteven_org_uk

### Logs

```Shell
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:192
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 00:59:52 (1 occurrences)
Last logged: 00:59:52
source not found: n-kesteven_org_uk
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: n-kesteven_org_uk
      args:
        uprn: "1000320****"

sensor:
  - platform: waste_collection_schedule
    name: Home Waste Collection
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
