### ISSUE TITLE
[Bug]: No time&date anymore

### ISSUE THREAD

**Issue by Surfer2010** [mampfes/hacs_waste_collection_schedule#1901]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

My sensors don't show any date for the next collection anymore:
![grafik](https://github.com/mampfes/hacs_waste_collection_schedule/assets/5108376/0df558dc-6b50-442a-929c-96d202ab8881)

it worked before as you can see here:
![grafik](https://github.com/mampfes/hacs_waste_collection_schedule/assets/5108376/e4112867-01c1-43c6-b1c0-e0ac9aa37454)

this also works:
![grafik](https://github.com/mampfes/hacs_waste_collection_schedule/assets/5108376/74379ad0-184a-478a-8ce2-2377b5ed5e6c)

this does not:
![grafik](https://github.com/mampfes/hacs_waste_collection_schedule/assets/5108376/ad87e197-fb65-4410-8d75-5f818e852c99)
![grafik](https://github.com/mampfes/hacs_waste_collection_schedule/assets/5108376/3558b4ac-8f06-40db-b30c-3078f29f617c)

there should be results:
![grafik](https://github.com/mampfes/hacs_waste_collection_schedule/assets/5108376/61b68ff1-e3dd-4006-92fe-a0436c7764d3)
![grafik](https://github.com/mampfes/hacs_waste_collection_schedule/assets/5108376/4cc64e86-35e6-48b2-a5eb-6ede6435f10b)

thanks for helping

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Not sure, looks fine on first sight. Are there any entries in your logs?

**Comment by Surfer2010** [comment]
> Not sure, looks fine on first sight. Are there any entries in your logs?

no entries in my log, that's my problem, I have no idea whatsoever what the problem could be since it did work for some days.

**Comment by 5ila5** [comment]
Could you please send your whole configuration (as text not as image) (maybe replace your address with the example address of the source)

**Comment by albundy0815** [comment]
as I'm not a scripting guy, attached you can find my config.yaml

[config.txt](https://github.com/mampfes/hacs_waste_collection_schedule/files/14772551/config.txt)
for me, it seems, that the sensors are configured correct, because:
"Gelber Sack" is working fine 
"Altpapier" and "Restmüll" not via entity, only via Calendar.

**Comment by 5ila5** [comment]
As far as I can tell from your Image of your calendar, the `types` parameter of Restmüll should be `Grauen Tonne` not Restmüll? Or am I missing something? (Probably something similar with Altpapier? Not part of your calendar Image)

**Comment by albundy0815** [comment]
> As far as I can tell from your Image of your calendar, the `types` parameter of Restmüll should be `Grauen Tonne` not Restmüll? Or am I missing something? (Probably something similar with Altpapier? Not part of your calendar Image)

you point me, into the right direction ;-)

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/97403164/e8fa9ec1-bdb6-4d9a-80ed-6dbd9ded70e1)
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/97403164/6823c3e7-6c47-4e83-8f2e-6a12e9a45055)

**Comment by HHoppenstock** [comment]
@5ila5 I have the same issues but no clue how to solve it. Can you please take a look on it ?
That's the entry in the calendar:
<img width="313" alt="image" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/57133773/445ae297-530e-4546-b72b-82f3c60bde0b">

This is the config for the  waste sensor:
  # Nächste Restmüll-Abholung
  - platform: waste_collection_schedule
    name: "Restmüll"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    types:
      - Restmüll

that's the result:
<img width="784" alt="image" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/57133773/5a36dc77-53d4-482f-9d2a-8721be44390e">

the calendar sensor shows the right entry for the next "Restmüll":
<img width="788" alt="image" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/57133773/364dccb8-7bad-45d7-afdf-35904af0cf93">

**Comment by 5ila5** [comment]
Most occuring problem (probably not @HHoppenstock problem):  You defined `types: - Restmüll` which means this sensor will only look into events taht are named `Restmüll`. Check your calendar if the Restmüll events are actually named Restmüll (written exactly the same)

@HHoppenstock:

Do you use multiple waste_collection_shedule calendars? You then need to use the [source_index](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#configuring-sensors) parameter.

Did you look in your logs?

**Comment by HHoppenstock** [comment]
@5ila5 i have only one active calendar:
<img width="656" alt="image" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/57133773/2c199e54-9fd0-4786-8007-63df584fd779">
No entries in my log:
<img width="361" alt="image" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/57133773/c9f27d4a-6537-4204-ae34-2d42b8790d9f">

**Comment by 5ila5** [comment]
looks fine on first sight. Could you please send your full configuration source + sensor So I can have a look in my own HA instace later? (best to replace your address with an example address from the README.md)

**Comment by HHoppenstock** [comment]
[config_waste_management.txt](https://github.com/mampfes/hacs_waste_collection_schedule/files/14791419/config_waste_management.txt)
@5ila5 please see my attached config.
Thanks a lot.

**Comment by 5ila5** [comment]
I'm not quite sure what's should be wrong with your configuration. I needed to adjust the types argument to match the returned waste types of the example address, but this works fine for me (except : Baum- und Strauchschnitt as it's not offered in this Region):
```yaml
waste_collection_schedule:
  sources:
    - name: muellabfuhr_de
      args:
        client: "Landkreis Hildburghausen"
        city: "Gompertshausen"
            
      
sensor:
  # ------- Garbage Collection ------- 
  # next collection
  - platform: waste_collection_schedule
    name: "Nächste Abholung"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
  # Nächste Restmüll-Abholung
  - platform: waste_collection_schedule
    name: "Restmüll"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    types:
      - Restabfall

  # Nächste Biomüll Abholung
  - platform: waste_collection_schedule
    name: "Biotonne"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Biomüll
  # Nächste gelber-Sack Abholung
  - platform: waste_collection_schedule
    name: "Gelbe Tonne"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
    types:
      - gelbe Tonne/Leichtverpackungen
  # Nächste Papiermüll Abholung
  - platform: waste_collection_schedule
    name: "Papier"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Papier
  # Nächste Papiermüll Abholung
  - platform: waste_collection_schedule
    name: "Container für Baum- und Strauchschnitt"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Container für Baum- und Strauchschnitt
  # Nächste Papiermüll Abholung
  - platform: waste_collection_schedule
    name: "Schadstoffmobil"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Schadstoffmobil
```

Please try to run exactly this config and check whether you can now see your sensors. If errors still persist, try reinstalling this integration. Maybe there is a weird space in the returned waste type? Double check every waste type is spelled exactly the same as shown in the calendar (copy paste?)
