### ISSUE TITLE
[Bug]: Ashford [UK] - Page layout changed, parser fails

### ISSUE THREAD

**Issue by Mustek** [mampfes/hacs_waste_collection_schedule#1914]
### I Have A Problem With:

A specific source

### What's Your Problem

Council has updated their page layout slightly after contracting a new waste collector.

The `table` the parser is looking for is no longer present. All data is still available on the page.

### Source (if relevant)

ashford_gov_uk

### Logs

```Shell
failed for source Ashford Borough Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ashford_gov_uk.py", line 85, in fetch raise Exception( Exception: could not get valid data from ashford.gov.uk. is your UPRN (<UPRN REMOVED>) correct for postcode (<POSTCODE REMOVED>)? check https://uprn.uk/<UPRN REMOVED> and https://secure.ashford.gov.uk/wastecollections/collectiondaylookup/
```

### Relevant Configuration

```YAML
# Waste Collection
waste_collection_schedule:
    sources: 
    - name: ashford_gov_uk
      args: 
        uprn: <UPRN REMOVED>
        postcode: <POSTCODE REMOVED>
      customize:
        - type: Recycling (green bin / clear sacks)
          alias: Recycling
        - type: Food waste (black container with orange lid)
          alias: Food Waste
        
sensor:
    - platform: waste_collection_schedule
      name: ashford_gov_uk
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
