### ISSUE TITLE
[Bug]: Montreal (QC)

### ISSUE THREAD

**Issue by lit-af** [mampfes/hacs_waste_collection_schedule#1919]
### I Have A Problem With:

A specific source

### What's Your Problem

If have the following issue, I'm in a neighborhood where there's two codes, one for waste and one for recycling and compost.

I can't add more than one at the moment. When I add two sources, it creates two empty calendars.

### Source (if relevant)

montreal_ca

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: montreal_ca
      args:
        sector:
          - MHM_42-5_A
    - name: montreal_ca
      args:
        sector:
          - MHM-42-S
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Thats not a problem of the source your configuration is wrong you provide the sectors as list (using the `-` means list in yaml)

so the configuration 
```yaml
waste_collection_schedule:
  sources:
    - name: montreal_ca
      args:
        sector: MHM_42-5_A
    - name: montreal_ca
      args:
        sector: MHM-42-S
```
should work.

If you want to combine these two in one calendar, you can use the newly introduced [`multiple`](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/multiple.md) wrapper like this:

```yaml
waste_collection_schedule:
  sources:
    - name: multiple
      args:
        montreal_ca: 
          - sector: MHM_42-5_A
          - sector: MHM-42-S
```
