### ISSUE TITLE
[Bug]: Apps by Abfall+ "Street not found"

### ISSUE THREAD

**Issue by Ranzmann** [mampfes/hacs_waste_collection_schedule#1944]
### I Have A Problem With:

The integration in general

### What's Your Problem

Since yesterday data can not be fetched "street not found". First a friend had this issue. Then I tested his street name and could not receive data either. After switching back to my street name there is still no data available.

### Source (if relevant)

de.k4systems.bonnorange

### Logs

```Shell
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 11:42:18 AM (1 occurrences)
Last logged: 11:42:18 AM
fetch failed for source Apps by Abfall+: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py", line 124, in fetch for d in self._app.generate_calendar(): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 756, in generate_calendar self.select_street() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 589, in select_street raise Exception(f"Street {self._strasse_search} not found.") Exception: Street Bornheimer Str. not found.
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.bonnorange
        strasse: Bornheimer Str.
        hnr: 75
      customize:
        - type: Restabfallbehälter
          alias: Restmüll
          icon: mdi:trash-can
        - type: Papierbehälter
          alias: Papier & Gelber Sack
          icon: mdi:trash-can
        - type: Sperrmüll
        - type: Gelbe Behälter
          show: false
        - type: Bioabfallbehälter
          show: false
        - type: Gelbe Großbehälter
          show: false
    fetch_time: "04:00"
    day_switch_time: "10:00"
```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
