### ISSUE TITLE
ZAS Abfallwirtschaft

### ISSUE THREAD

**Issue by baldisos** [mampfes/hacs_waste_collection_schedule#195]
I'm trying to integrate the ZAS Abfallwirtschaft ICS. But i can't seem to get it to work.
Is there anything i need to configure specifically?

The Website is
https://www.za-sws.de/abfallkalender.cfm

And the generated ICS is
https://online-portal.za-sws.de/WasteManagementSuedwestsachsen/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=52554001&AboID=33626&Fra=R;P;B;W;L;C;S
_(The adress used is a random one, not mine of course)_

My configuration looks like this:

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://online-portal.za-sws.de/WasteManagementSuedwestsachsen/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=52554001&AboID=33626&Fra=R;P;B;W;L;C;S
        customize:
        - type: Restmuelltonne 02-woechentl.
          alias: Restmüll
          icon: mdi:trash-can
        - type: Biotonnenwaesche
          alias: Biotonnenwäsche
          show: false
          icon: mdi:flower-outline
        - type: Papiertonne 04-woechentl.
          alias: Papiertonne
          icon: mdi:trash-can-outline
        - type: LVP
          alias: Gelbe Tonne
          icon: mdi:recycle
```

Thanks in advance.
