### ISSUE TITLE
[Bug]: Umlaute werden nicht erkannt

### ISSUE THREAD

**Issue by JayFaii** [mampfes/hacs_waste_collection_schedule#1950]
### I Have A Problem With:

A specific source

### What's Your Problem

I was struggeling to integrate WCS with the new AHA-Region-Hannover Add_on, until i realised it has something to do with the "ü" in the streetname:

(not working)
        strasse: Müdener Weg / Heideviertel 
vs.
(working)
        strasse: Wilseder Weg / Heideviertel 

tried a street nearby with similar waste collection schedule, works fine now.

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: aha_region_de
      args:
        gemeinde: Hannover
#        strasse: Müdener Weg / Heideviertel
        strasse: Wilseder Weg / Heideviertel
        hnr: "1"
        zusatz: ""
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
