### ISSUE TITLE
[Bug]: Haringey Waste Collection sensor returning 'Unknown'

### ISSUE THREAD

**Issue by TomAnks** [mampfes/hacs_waste_collection_schedule#1952]
### I Have A Problem With:

A specific source

### What's Your Problem

I am having an issue adding the Haringey council (UK) Waste Collection sensor into HA. The sensor value shows as 'Unknown'.

I have added this code to my configuration.yaml (replacing "My UPRN" with my actual UPRN):

```
  sources:
    - name: haringey_gov_uk
      args:
        uprn: "My UPRN"

sensor:
  - platform: waste_collection_schedule
    name: "Haringey Waste Collection"
    details_format: upcoming
    value_template: 'in {{value.daysTo}} days'
```

![haringeywastecollection](https://github.com/mampfes/hacs_waste_collection_schedule/assets/26800901/41d18b20-8922-48b1-94dc-865ae9ac568c)

I have tested with other configs for other councils I found online and those work as expected. Is there something wrong with the Haringey data feed? The URL mentioned in the documentation is still correct, and I can see the correct information on the Haringey website.

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
