### ISSUE TITLE
[Bug]: Auckland City Council stopped working around update to HA 2024.4.2 or 1.47.0

### ISSUE THREAD

**Issue by xbmcnut** [mampfes/hacs_waste_collection_schedule#1962]
### I Have A Problem With:

A specific source

### What's Your Problem

All sensors for `aucklandcouncil_govt_nz` now show unavailable. Seems to have stopped working around either my recent update to 1.47.0 or HA 2024.4.2. Configuration has not changed at all. Tried downgrading to 1.45.0 and 1.46.0, still the same. Reinstalled 1.47.0 and still no go.

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/1492137/44bc1f6d-4a70-46ea-be25-7db66dcae72b)

### Source (if relevant)

aucklandcouncil_govt_nz

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: aucklandcouncil_govt_nz
      args:
        area_number: redacted
        # from https://www.aucklandcouncil.govt.nz/rubbish-recycling/rubbish-recycling-collections/Pages/rubbish-recycling-collection-days.aspx
      customize:
        - type: rubbish
          alias: Rubbish
          icon: mdi:trash-can
        - type: recycle
          alias: Recycling
          icon: mdi:recycle
      calendar_title: Auckland Council Rubbish & Recycling Collections
  day_switch_time: "17:00"
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
