### ISSUE TITLE
[Bug]:  Sheffield not showing green bins

### ISSUE THREAD

**Issue by danwall8585** [mampfes/hacs_waste_collection_schedule#1969]
### I Have A Problem With:

A specific source

### What's Your Problem

Green bin sensor is no longer available despite green bin collection showing on the website.
I know the green bin only shows conditionally on the site based on if an address has paid for the year if that makes any difference (we have paid).

### Source (if relevant)

sheffield_gov_uk

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
Version 1.47.0, using HACS.


:
  sources:
    - name: sheffield_gov_uk
      args:
        uprn: xxxxxxxxxxxx
      customize:
        - type: Black Bin
          alias: Black bin (General)
          icon: mdi:trash-can
        - type: Brown Bin
          alias: Brown bin (Bottles)
          icon: mdi:trash-can
        - type: Blue Bin
          alias: Blue bin (Paper)
          icon: mdi:trash-can
        - type: Green Bin
          alias: Green bin (Garden)
          icon: mdi:trash-can

sensor:
  #bins
  - platform: waste_collection_schedule
    source_index: 0
    name: Home bins
    #details_format: upcoming
    #count:
    #leadtime:
    #value_template: 'in {{value.daysTo}} days'
    #date_template:
    add_days_to: true
    #event_index:
    #types:
    #  -
  - platform: waste_collection_schedule
    source_index: 0
    name: Next bin
    details_format: upcoming
    add_days_to: true
    #
  - platform: waste_collection_schedule
    source_index: 0
    name: Black Bin
    details_format: upcoming
    add_days_to: true
    types:
      - Black Bin
      #
  - platform: waste_collection_schedule
    source_index: 0
    name: Green Bin
    details_format: upcoming
    add_days_to: true
    types:
      - Green Bin
    #
  - platform: waste_collection_schedule
    source_index: 0
    name: Brown Bin
    details_format: upcoming
    add_days_to: true
    types:
      - Brown Bin
    #
  - platform: waste_collection_schedule
    source_index: 0
    name: Blue Bin
    details_format: upcoming
    add_days_to: true
    types:
      - Blue Bin
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
