### ISSUE TITLE
[Bug]: Auckland City Council pull seems to be broken.

### ISSUE THREAD

**Issue by Zetto12** [mampfes/hacs_waste_collection_schedule#1983]
### I Have A Problem With:

A specific source

### What's Your Problem

Auckland City Council pull seems to be broken. The last data I have is from the 10th of April

It used to work for months flawlessly but for the last few days it just shows unknown. I checked if my area code changed or if there is no data on their website but it hasn't changed. Almost missed the rubbish this morning because I am so reliant on the notification now.

I still have the calendar called "Auckland Council" in my Calendar integration but it has no entries.

![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/95339767/66c0e7d6-ee0e-46c8-ae75-437afe0470a5)

### Source (if relevant)

aucklandcouncil.govt.nz

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: aucklandcouncil_govt_nz
      args:
        area_number: 12346271874
      customize:
        - type: Rubbish
          show: yes
        - type: Recycling
          show: yes
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
