### ISSUE TITLE
[Bug]: Source Auckland, New Zealand has stopped working

### ISSUE THREAD

**Issue by deanfourie1** [mampfes/hacs_waste_collection_schedule#1985]
### I Have A Problem With:

A specific source

### What's Your Problem

The sources now just reports "unknown". Has been working well for about 1 year.. :(

### Source (if relevant)

aucklandcouncil_govt_nz

### Logs

```Shell
Not sure where to find?
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: aucklandcouncil_govt_nz
      args:
        area_number: xxxxxxxxxxxxx
      customize:
        - type: recycle
          icon: mdi:recycle
    - name: static
      args:
        type: rubbish
        frequency: WEEKLY
        interval: 4
        start: '2023-01-14'
        until: '2025-01-14'
      customize:
        - type: rubbish
          icon: mdi:bin

sensor:
  - platform: waste_collection_schedule
    name: all_waste_types
    source_index: [0, 1]

  - platform: waste_collection_schedule
    name: recycle
    source_index: 0
    types:
      - recycle

  - platform: waste_collection_schedule
    name: rubbish
    source_index: 1
    types:
      - rubbish
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
