### ISSUE TITLE
[Bug]: Fetch stopped working

### ISSUE THREAD

**Issue by SvenJ76** [mampfes/hacs_waste_collection_schedule#1992]
### I Have A Problem With:

A specific source

### What's Your Problem

Suddenly, beginning today, the fetch stopped working. No config changes were made. My config is from Bugreport #1845

### Logs

```Shell
fetch failed for source Apps by Abfall+: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py", line 140, in fetch for d in self._app.generate_calendar(): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 786, in generate_calendar self.select_kommune() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 502, in select_kommune raise Exception(f"Region {self._region_search} not found.") Exception: Region Haundorf not found.
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.abfallappwug
        city: Haundorf
        bezirk: Obererlbach
      customize:
        - type: braune Biotonne
          alias: biotonne
          icon: mdi:trash-can
        - type: graue Restmülltonne
          alias: restmuell
          icon: mdi:trash-can
        - type: Gelber Sack
          alias: gelbersack
          icon: mdi:recycle
        - type: grüne Papiertonne und grüner 1,1m³ Papiercontainer
          alias: papier
          icon: mdi:trash-can
  fetch_time: "04:00"
  day_switch_time: "11:00"
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
