### ISSUE TITLE
[Bug]: Waste Collection Schedule: Stadtreinigung Leipzig

### ISSUE THREAD

**Issue by bj790266** [mampfes/hacs_waste_collection_schedule#1994]
### I Have A Problem With:

The integration in general

### What's Your Problem

Die Stadtreinigung Leipzig hat ihr Webseite geändert und dadurch funktioniert der Ereignisabruf im Kalender nicht mehr.
Hat jemand eine Idee dies  zu fixen?

![ics](https://github.com/mampfes/hacs_waste_collection_schedule/assets/150963564/4ee5214c-70bd-4f39-932d-8564f1c3ae45)

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by ReneNulschDE** [comment]
My config works well and I moved out the garden waste today...

```
waste_collection_schedule:
  sources:
    - name: stadtreinigung_leipzig_de
      args:
        street: Eisenacher Straße
        house_number: xx
```

Please share your detailed config.

**Comment by bj790266** [comment]
ich habe bis jetzt die andere Konfiguration genutzt.
wie Beispiel:

waste_collection_schedule:
  sources:
    - name: ics
      args:
        regex: (.*), .*
        url: https://stadtreinigung-leipzig.de/wir-kommen-zu-ihnen/abfallkalender/ical.ics?position_nos=38296&name=Sandgrubenweg&mode=download

Auf der Webseite gibt es jetzt keinen "Download" - mehr sondern einen "Exportieren" Button

**Comment by 5ila5** [comment]
The ICS version should work as well. I updated the `how to` section in #1999

**Comment by s3e1f** [comment]
Stadtreinigung Leipzig does not work with both variants

**Comment by 5ila5** [comment]
@s3e1f what do you mean with both variables:

just tested and works fine:

```yaml
waste_collection_schedule:
  sources:
    - name: stadtreinigung_leipzig_de
      args:
        street: Bahnhofsallee
        house_number: 7

# and

waste_collection_schedule:
  sources:
    - name: stadtreinigung_leipzig_de
      args:
        street: Eisenacher Straße
        house_number: 1
```

**Comment by s3e1f** [comment]
i mean both variants, not variables:

waste_collection_schedule:
  sources:
    - name: stadtreinigung_leipzig_de
      args:
        street: Bahnhofsallee
        house_number: 7

# and

waste_collection_schedule:
  sources:
    - name: ics
      args:
        regex: (.*), .*
        url: ....
url according to the instructions in #1999. For me, the two variants do not work

**Comment by ReneNulschDE** [comment]
I checked again your config:
```
waste_collection_schedule:
  sources:
    - name: stadtreinigung_leipzig_de
      args:
        street: Bahnhofsallee
        house_number: 7
```
this is working. Are you sure that you have the latest version of this component installed? If remember right, I made a fix in one of the last releases. (the fix is not listed in the release notes.)
