### ISSUE TITLE
[Bug]: ecoharmonogram.pl some streets are not working

### ISSUE THREAD

**Issue by ryrzy** [mampfes/hacs_waste_collection_schedule#2066]
### I Have A Problem With:

A specific source

### What's Your Problem

Hello, 
i have problem with some streets in city 'Zabrze', for example Zabrze/Zabrze/Łąkowa/1 Zabrze/Zabrze/Mickiewicza/1 - both shows 2 extra args when i use EcoHarmonogramPL.py script, and they are that same! :) i think one is for houses second for flats. 
But the best is for Leśna street... there are 2 extra args and they are empty! :D 
All streets are working on city official www - https://miastozabrze.pl/dla-mieszkancow/odpady-komunalne/wyszukiwarki-ecoharmonogram-harmonogram-odbioru-odpadow-jak-segregowac/

### Source (if relevant)

ecoharmonogram.pl

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: ecoharmonogram_pl
      args:
        town: Zabrze
        district: Zabrze
        street: Leśna
        house_number: xyz
        additional_sides_matcher:
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
