### ISSUE TITLE
[Bug]: day_switch_time does not seem to be working correctly

### ISSUE THREAD

**Issue by Jaykurb** [mampfes/hacs_waste_collection_schedule#2067]
### I Have A Problem With:

The integration in general

### What's Your Problem

I have day switch time set to `20:00` but the day switches at `01:19`

<img width="228" alt="Screenshot 2024-05-08 at 07 24 31" src="https://github.com/mampfes/hacs_waste_collection_schedule/assets/49797976/c84d1086-1fd8-462a-a206-77ed846838a0">

config:

```
waste_collection_schedule:
  sources:
    - name: maldon_gov_uk
      args:
        uprn: "uprn"
      customize:
        - type: Refuse Collection
        - type: Recycling
  day_switch_time: "20:00"
  fetch_time: 01:00
```

### Source (if relevant)

Maldon District Council / maldon.gov.uk

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: maldon_gov_uk
      args:
        uprn: "uprn"
      customize:
        - type: Refuse Collection
        - type: Recycling
  day_switch_time: "20:00"
  fetch_time: 01:00
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
