### ISSUE TITLE
Source jumomind_de: sensors with type filtering without data

### ISSUE THREAD

**Issue by LinusHoppe** [mampfes/hacs_waste_collection_schedule#210]
**Environment:**
Waste Collection Schedule 1.18.0 (HACS)
Home Assistant core-2022.4.5

**My garbage data:**
https://mymuell.jumomind.com/webservice.php?idx=termins&city_id=64111&area_id=64111

**My configuration:**
```
waste_collection_schedule:
  sources:
    - name: jumomind_de
      args:
        service_id: mymuell
        city_id: 64111
        area_id: 64111
      customize:
        - type: PAD_BIO
          alias: Bio
        - type: PAD_P
          alias: Papier
        - type: PAD_WERT
          alias: Gelbetonne
        - type: PAD_REST
          alias: Rest
        - type: PAD_EKG
          alias: elektro
          show: false
        - type: PAD_SCHAD
          alias: schad
          show: false
      calendar_title: Abfall

sensor:
  - platform: waste_collection_schedule
    name: Abfall
    value_template: '{{ value.daysTo }}'

  - platform: waste_collection_schedule
    name: Abfallbio
    value_template: '{{ value.daysTo }}'
    types:
      - Bio

  - platform: waste_collection_schedule
    name: Abfallpapier
    value_template: '{{ value.daysTo }}'
    types:
      - Papier

  - platform: waste_collection_schedule
    name: Abfallgelb
    value_template: '{{ value.daysTo }}'
    types:
      - Gelbetonne

  - platform: waste_collection_schedule
    name: Abfallrest
    value_template: '{{ value.daysTo }}'
    types:
      - Rest
```

**What is working:**

- retrieve data into calendar (every collection is shown correctly)
- sensor `Abfall` has data (of all garbage types). This sensor is just for testing purposes, I want to have type-specific sensors

**What is not working:**

- all type-filtering sensors do not have data (state `unknown`)
