### ISSUE TITLE
[Feature]: Expose collection type and days to next collection as sensors

### ISSUE THREAD

**Issue by shaftspanner** [mampfes/hacs_waste_collection_schedule#2114]
### I propose a feature for:

Sensors

### Describe your wanted feature

Currently I have a single sensor that contains a text value such as Food, Recycling in 3 days.  If these could be exposed as separate sensors e.g "Food, Recycling" and "3" then I could make automations based on the number of days to the next collection

**Comment by 5ila5** [comment]
you can allready do this with the value_template parameter:

```yaml
  - platform: waste_collection_schedule
    name: next_collection_days
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    add_days_to: true
  - platform: waste_collection_schedule
    name: next_collection_types
    details_format: appointment_types
    value_template: "{{ value.types|join(', ') }}"
    add_days_to: true
```
