### ISSUE TITLE
[Bug]: Landkreis Hameln-Pyrmont isn't working anymore

### ISSUE THREAD

**Issue by svzi** [mampfes/hacs_waste_collection_schedule#2116]
### I Have A Problem With:

A specific source

### What's Your Problem

A few days ago I updated to the current version (1.48.0) of this awesome integration. Since then I get the following error message, when I try to fetch the waste schedule for Hameln. I've also tried with the sample provided in the docs (https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/hameln_pyrmont_de.md). But it doesn't work either.

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:192
Integration: waste_collection_schedule (Dokumentation)
Erstmals aufgetreten: 09:50:48 (1 Vorkommnisse)
Zuletzt protokolliert: 09:50:48

source not found: ics
```

I validated that the provided URL is valid. This is the URL from the official documentation:
webcal://om.kaw-hameln.de/WasteManagementHameln/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=26881528001&AboID=355061&Fra=P;C4;R;B;S;V;G;M;C1;C2

I can download the file and looks like a valid ICS to me (but I'm no ICS expert). So I have no idea why this error occurs.

Any idea what's happening here?

Best,
Sven

### Source (if relevant)

ics

### Logs

```Shell
see my description
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: webcal://om.kaw-hameln.de/WasteManagementHameln/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=26881528001&AboID=355061&Fra=P;C4;R;B;S;V;G;M;C1;C2
        verify_ssl: false
      customize:
        - type: Restmüll
          icon: mdi:trash-can-outline
        - type: Gelber Sack
          icon: mdi:recycle
        - type: Altpapier
          icon: mdi:newspaper-variant-multiple-outline
        - type: Biotonne
          icon: mdi:flower-outline
        - type: Grünschnitt
          icon: mdi:tree-outline
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
