### ISSUE TITLE
A-Region only works for Andwil

### ISSUE THREAD

**Issue by dawiinci** [mampfes/hacs_waste_collection_schedule#214]
Thanks for supporting this source.

However, I can't get the sources for example for municipality Rorschach - it only works for Andwil. Other places aren't working as well.

```
waste_collection_schedule:
  sources:
    - name: a_region_ch
      args:
        municipality: Rorschach
```

`fetch failed for source A-Region: Traceback (most recent call last): File "/Users/server/.homeassistant/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 122, in fetch entries = self._source.fetch() File "/Users/server/.homeassistant/custom_components/waste_collection_schedule/waste_collection_schedule/source/a_region_ch.py", line 25, in fetch raise Exception(f"municipality '{self._municipality}' not found") Exception: municipality 'Rorschach' not found`
