### ISSUE TITLE
Support for German language

### ISSUE THREAD

**Issue by dawiinci** [mampfes/hacs_waste_collection_schedule#216]
I didn't find any way to change the language. How can I help to translate this plugin to German?

**Comment by buffcode** [comment]
Use the templating and translate the output: https://github.com/mampfes/hacs_waste_collection_schedule#3-how-do-i-show-today--tomorrow-instead-of-in-01-days

Eg. I use:
```yaml
- platform: waste_collection_schedule
  name: Papiertonne
  add_days_to: true
  value_template: "{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}"
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
    - Papiertonne
```
