### ISSUE TITLE
[Bug]: ICS Sensor Not longer working

### ISSUE THREAD

**Issue by bluenazgul** [mampfes/hacs_waste_collection_schedule#2180]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

Waste Collection ICS Sensor stopped working

Sadly i dont know since when it is Not working, but it worked Like this for a Long time

### Source (if relevant)

Stadt Detmold - Abfuhrkalender

### Logs

```Shell
HA Error Log:
`Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:366
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 15:49:36 (10 Vorkommnisse)
Zuletzt protokolliert: 15:49:36

Error while setting up waste_collection_schedule platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/waste_collection_schedule/sensor.py", line 82, in async_setup_platform
    raise ValueError(
ValueError: source_index 0 out of range (0--1) please check your sensor configuration`


Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:208
Integration: waste_collection_schedule (Dokumentation)
Erstmals aufgetreten: 16:10:03 (1 Vorkommnisse)
Zuletzt protokolliert: 16:10:03

source not found: ics
```

### Relevant Configuration

```YAML
Sensor Configuration (Main Sensor):
`waste_collection_schedule:
  sources:
    - name: ics
      args:
        regex: "Müllabfuhr: (.*)"
        url: "https://abfuhrkalender.detmold.de/icsmaker.php?strid=176&year={%Y}"


Even the older Sensor isnt working:
`waste_collection_schedule:
  sources:
    - name: ics
      args:
        regex: "Müllabfuhr: (.*)"
        url: https://abfuhrkalender.detmold.de/icsmaker.php
       #file: "abfall2021.ics"
        params:
          strid: 176
          year_field: year
`
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
