### ISSUE TITLE
[Bug]: Mansfield District Council not showing Brown (Garden Waste) bin

### ISSUE THREAD

**Issue by gonzoweb-git** [mampfes/hacs_waste_collection_schedule#2202]
### I Have A Problem With:

A specific source

### What's Your Problem

The calendar has now stopped showing the Brown Garden Waste bin collection date.
Other than HA updates, I haven't needed to change any settings to my knowledge.

### Source (if relevant)

mansfield_gov_uk

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: mansfield_gov_uk
      args:
        uprn: "100031420572"
      customize:
        - type: Recycling
          alias: Blue Bin
        - type: General
          alias: Green Bin
        - type: Garden
          alias: Brown Bin
        - type: Glass
          alias: Teal Bin
#          show: SHOW
#          icon: ICON
#          picture: PICTURE
#          use_dedicated_calendar: USE_DEDICATED_CALENDAR
#          dedicated_calendar_title: DEDICATED_CALENDAR_TITLE
#      calendar_title: CALENDAR_TITLE
#fetch_time: FETCH_TIME
#random_fetch_time_offset: RANDOM_FETCH_TIME_OFFSET
#day_switch_time: DAY_SWITCH_TIME
#separator: SEPARATOR

sensor:
  - platform: waste_collection_schedule
#    source_index: SOURCE_INDEX
    name: MDC_Waste
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
