### ISSUE TITLE
[Bug]: Exception: city not found: rödental

### ISSUE THREAD

**Issue by Bankaifan** [mampfes/hacs_waste_collection_schedule#2209]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

How to add a city and street name, that contain "ö"? Seems like thats a problem.

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
What source are you using?
Could you please provide the full log?

This sounds like an exception thrown by a source script, so I need at least a place where I can search, mostly umlauts aren't a problem and should just work, but I need to check.

**Comment by Bankaifan** [comment]
Hi, 

first, thats my code - I use awido_de
```
waste_collection_schedule:
  sources:
    - name: awido_de
      args:
        customer: coburg
        city: rödental
        street: krötenleite
        housenumber: 4
```

And here is the Log - forgot to add it yesterday, sorry.

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
Integration: waste_collection_schedule (Dokumentation)
Erstmals aufgetreten: 04:00:52 (1 Vorkommnisse)
Zuletzt protokolliert: 04:00:52

fetch failed for source AWIDO Online: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/awido_de.py", line 298, in fetch raise Exception(f"city not found: {self._city}") Exception: city not found: rodental
```

Hope that helps.

**Comment by 5ila5** [comment]
awido_de seems to be case-sensitive, and city and street seem to start with an upper case letter.
I will change awido_de to be case-insensitive.

But this works for me (you need to not provide the house number for this address)

```yaml
waste_collection_schedule:
  sources:
    - name: awido_de
      args:
        customer: coburg
        city: Rödental
        street: Krötenleite
```
