### ISSUE TITLE
[Bug]: de.biberach.abfallapp throws 401

### ISSUE THREAD

**Issue by Kimotu** [mampfes/hacs_waste_collection_schedule#2210]
### I Have A Problem With:

A specific source

### What's Your Problem

[Kreis Biberach](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/app_abfallplus_de.md) / Abfall+ App: abfallapp returns 401. Is there any API key missing?
```
# Abfallkalender
waste_collection_schedule:
  sources:
    - name: app_abfallplus_de
      args:
        app_id: de.biberach.abfallapp
        strasse: Karlstrasse
        hnr: 1
```

### Logs

```Shell
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
Integration: waste_collection_schedule (Dokumentation)
Erstmals aufgetreten: 17:50:02 (1 Vorkommnisse)
Zuletzt protokolliert: 17:50:02

fetch failed for source Apps by Abfall+: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/app_abfallplus_de.py", line 183, in fetch for d in self._app.generate_calendar(): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 929, in generate_calendar self.select_street() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 690, in select_street streets = self.get_streets() ^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/AppAbfallplusDe.py", line 669, in get_streets r.raise_for_status() File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://app.abfallplus.de/assistent/strasse/
```

### Relevant Configuration

```YAML
# Abfallkalender
waste_collection_schedule:
  sources:
    - name: app_abfallplus_de
      args:
        app_id: de.biberach.abfallapp
        strasse: Karlstrasse
        hnr: 1
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
