### ISSUE TITLE
[Bug]:  No Calendar Entries get loaded

### ISSUE THREAD

**Issue by MacVille** [mampfes/hacs_waste_collection_schedule#2227]
### I Have A Problem With:

The integration in general

### What's Your Problem

Since a few days the no Data get pulled for any kind of trash

### Source (if relevant)

app_abfallplus_de

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
waste_collection_schedule
  sources:
    - name: app_abfallplus_de
      args:
        app_id: de.abfallwecker
        city: Stühlingen
        strasse: Kalvarienbergstr.
        hnr: XX
        bundesland: Baden-Württemberg
        landkreis: Kreis Waldshut
fetch_time: "01:00"
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
