### ISSUE TITLE
[Bug]:  Kreis Heinsberg

### ISSUE THREAD

**Issue by Nolle18o1** [mampfes/hacs_waste_collection_schedule#2285]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

Hey, I just updated to v2.0, sadly 'Kreis Heinsberg' is not working anymore
My sensor from configuration.yaml is not working anymore either. Before no issues.

```yaml
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: krhs
        ort: Kreis Heinsberg
        strasse: Talstraße
        hausnummer: (select any)
```

Thanks in advance!

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
