### ISSUE TITLE
[Feature]: simplified UI configuration

### ISSUE THREAD

**Issue by Santanachia** [mampfes/hacs_waste_collection_schedule#2309]
### I propose a feature for:

The integration in general

### Describe your wanted feature

At the moment, my configuration in YAML looks like this:
```yaml
waste_collection_schedule:
  sources:
    - name: ecoharmonogram_pl
      args:
        town: ***
        street: ***
```
during configuration by the UI, it requires me to fill in many other values that were not required before. On top of that, in the end I still failed to get exactly the same result as using yaml.

Please simplify the configuration so that after specifying sources.name and sources.args, all further configuration can be skipped.
