### ISSUE TITLE
[Feature]: Integrate new app for the Landkreis Miltenberg

### ISSUE THREAD

**Issue by GamingForLive** [mampfes/hacs_waste_collection_schedule#2343]
### I propose a feature for:

Sources

### Describe your wanted feature

The Landkreis miltenberg has gotten its own app called AbfallAppMIL. Why am i writing this? I tried the setup using the abfallappmil source but it wouldnt work and i also cannot configure my addres in the app as it redirects me to the new app hence my belive that they have removed Miltenberg from theyre system.

Please correct me if im wrong. In that case i would appreciate a bit of guidance to set it up as we dont have a Bezirk, and i tried using the name of my village in the field and ive also tried leaving it empty but both resulted in a error message.

**Comment by 5ila5** [comment]
I could not find another app than the AbfallPlus one.
You only need the arguments asked by the app, so this configuration works:

```yaml
waste_collection_schedule:
    sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.abfallappmil
        city: Collenberg
        strasse: Am Bildstock_(Kirschfurt)
        hnr: 11
```


But you can also use the website to get an ical link and use this one with the [ICS source ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) I added dedicated documentation in #2346 you can find it [here](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/landkreis_miltenberg_de.md)
