### ISSUE TITLE
aha_region_de broken

### ISSUE THREAD

**Issue by 5ila5** [mampfes/hacs_waste_collection_schedule#2367]
### Discussed in https://github.com/mampfes/hacs_waste_collection_schedule/discussions/2364

<div type='discussions-op-text'>

<sup>Originally posted by **Expello** August  1, 2024</sup>
Hi,

this is the error:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 31. Juli 2024 um 01:46:44 (2 Vorkommnisse)
Zuletzt protokolliert: 01:26:21

fetch failed for source Zweckverband Abfallwirtschaft Region Hannover: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/aha_region_de.py", line 103, in fetch raise Exception( Exception: Invalid response from server, check you configuration if it is correct.
```

Config is:

```yaml
waste_collection_schedule:
  sources:
    - name: aha_region_de
      args:
        gemeinde: Neustadt a. Rbge.
        strasse: Kornstr. / Neustadt
        hnr: "26"
        zusatz: ""
```

   
Anyone have an idea to solve the problem?

Thanks a lot!
        

![image](https://github.com/user-attachments/assets/451c71b3-954d-4dde-b49d-88b302e5a6cd)

        </div>

**Comment by EBobbbele** [comment]
Good morning, i have the same issue. Thanks a lot

**Comment by iamunfriendly** [comment]
Hello, i have the same issue.

**Comment by mreinhold21** [comment]
Leider muss ich dieses ebenfalls so bestätigen. "Hannover", "Marthastr. / Wülfel", "x"

**Comment by 5ila5** [comment]
They moved some buttons and changed some behavior. I fixed it in #2374 Some (limited) addresses now require the additional `ladeort` parameter if the website form asks for a `Abholplatz`. 

This will be part of the next release or is available now as master (git) version (3-dot menu -> redownload -> change version to master -> fully restart HA (this will increase update cycle by a lot)

**Comment by EBobbbele** [comment]
Guten Morgen alle Hannoveraner und Region, ich habe mit den neuen Einstellungen kein Erfolg gehabt. Hat jemand eine Lösung für mich, der sich mit der neuen Systematik schon beschäftigt hat. Vielen Dank. Gerne Hilfestellungen an borisr@mek8.de. Die Adresse lautet Redener Str. 7, 30966 Hemmingen OT Harkenbleck.

**Comment by 5ila5** [comment]
Das funktioniert bei mir (schau, dass du auf der master Version bist oder den Patch (#2374) händisch angewendet hast)

```yaml
waste_collection_schedule:
    sources:
    - name: aha_region_de
      args:
        gemeinde: Hemmingen
        strasse: Redener Str. / Harkenbleck
        hnr: "7"
```
