### ISSUE TITLE
[Source Request]: City of Kawartha Lakes, Ontario, Canada

### ISSUE THREAD

**Issue by angus123321** [mampfes/hacs_waste_collection_schedule#2371]
### Municipality / Region

City of Kawartha Lakes, Ontario, Canada

### Collection Calendar Webpage

https://www.kawarthalakes.ca/en/living-here/recycling-and-waste-collection-calendar.aspx

### Example Address

67 Baseline Rd Coboconk, ON

If you use the PDF I'm in the Monday zone

### Collection Data Format

Dedicated IOS/Android APP, As PDF Download

**Comment by 5ila5** [comment]
Kawartha Lakes is supported by the recyclecoach_com source you can use a configuration like:

```yaml
waste_collection_schedule:
    sources:
    - name: recyclecoach_com 
      args:
        street: 67 Baseline Rd
        city: Coboconk
        state: Ontario
```

I added Kawartha Lakes to the README.md in #2372
