### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by apfelflo89** [mampfes/hacs_waste_collection_schedule#24]
Hi,

could you implement any kind of language support or localization? I would love to see a "in Tagen" instead of "days".
I´m changing the string in the sensor.py with every release.

Thanks in advance

**Comment by mampfes** [comment]
Hi,
please use the `value_template` option of your sensor(s) to customize the sensor state string:
```
sensor:
  - platform: waste_collection_schedule
    name: NAME
    value_template: '{{value.types|join(", ")}} in {{value.daysTo}} Tagen'
```
BTW: If you customize the sensor state string within your Lovelace widget, you can also do thinks like:
- Restmüll morgen
- Biomüll heute
- Altpapier in 3 Tagen

Please have a look at the examples in the documentation.
