### ISSUE TITLE
Set default state format to be the next collection date

### ISSUE THREAD

**Issue by skipishere** [mampfes/hacs_waste_collection_schedule#243]
One thing I remember reading in the Home Assistant forum/documents (sorry haven't been able to find the page to link to it here) mentioned that timer/countdowns and other date related sensors should store the date/time instead of a 'days until X' style state as it's better practice to let the UI/automations work out time remaining (and removes extra history bloat when a value hasn't really changed)

This enhancement as a bonus could also mean the device_class could be set to be timestamp

**Comment by mampfes** [comment]
Not to be fixed. Dates are available via calendars.

**Comment by sshaikh** [comment]
I'm struggling with this also, although happy to concede that it's my inexperience with HA calendars. When creating a time based trigger, it expects `Value of a date/time helper or timestamp-class sensor`, but this integration doesn't seem to provide these.

Perhaps an example in the readme might help? For example a simple automation to trigger the night before a collection, with details of the collection?

**Comment by markvp** [comment]
Hi @sshaikh — the integration exposes a calendar entity for each configured source (and optionally per waste type). You can use the `calendar.get_events` action or a calendar trigger to fire automations based on upcoming collections.

A common pattern for a "night before" reminder:

```yaml
automation:
  - alias: Bin night reminder
    trigger:
      - platform: time
        at: "20:00:00"
    condition:
      - condition: template
        value_template: >
          {{ state_attr('calendar.waste_collection', 'start_time')[:10]
             == (now() + timedelta(days=1)).strftime('%Y-%m-%d') }}
    action:
      - service: notify.mobile_app_your_phone
        data:
          message: >
            Bin out tonight:
            {{ state_attr('calendar.waste_collection', 'message') }}
```

Replace `calendar.waste_collection` with the actual entity ID from your installation. You can find it in **Settings → Devices & Services → Entities**, filtering for `calendar`.

Alternatively, the newer [Calendar trigger](https://www.home-assistant.io/docs/automation/trigger/#calendar-trigger) (HA 2023.3+) makes this even simpler:

```yaml
automation:
  - alias: Bin night reminder
    trigger:
      - platform: calendar
        event: start
        offset: "-12:00:00"
        entity_id: calendar.waste_collection
    action:
      - service: notify.mobile_app_your_phone
        data:
          message: "Bin out tonight: {{ trigger.calendar_event.summary }}"
```

The original request to surface a timestamp sensor was declined in favour of the calendar approach — but I agree a worked example in the README would help. Feel free to open a documentation PR if you'd like to contribute one!
