### ISSUE TITLE
[Bug]: Setup of waste_collection_schedule is taking over 10 seconds.

### ISSUE THREAD

**Issue by stefan1495** [mampfes/hacs_waste_collection_schedule#2444]
### I Have A Problem With:

A specific source, The integration in general

### What's Your Problem

Hey,

i was unsure if this is actually a bug or related to a discussion topic, but every time i restart my Home-Assistant, i do receive the Warning

`2024-08-13 16:35:35.917 WARNING (MainThread) [homeassistant.setup] Setup of waste_collection_schedule is taking over 10 seconds.`

I am using the ICS Source with an ics from "https://www.abfalltermine-bamberg.de" (Wont share exact Link for privacy reasons).

My Configuration looks like that:
```
waste_collection_schedule:
  sources:
  - name: ics
    calendar_title: "Abfall XYZ"
    args:
      url: https://www.abfalltermine-bamberg.de/someCityPart/ics?RESTMUELL=true&BIO=true&YELLOW_SACK=true&PAPER=true&SPERRMUELL=true&PROBLEMMUELL=true
    customize:
      - type: "Restmülltonne"
        icon: mdi:trash-can
      - type: "Papiertonne"
        icon: mdi:trash-can
      - type: "Biotonne"
        icon: mdi:trash-can
      - type: "Gelber Sack"
        icon: mdi:trash-can
      - type: "Problemmüll"
        icon: mdi:trash-can
 ```

I tried Master and used Default ICS Config for my Provider - but the Problem/Warning remains the same. 

### Source (if relevant)

ICS Source

### Logs

```Shell
no relevant logs (beside the one in Issue-Text)
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
  - name: ics
    calendar_title: "Abfall XYZ"
    args:
      url: https://www.abfalltermine-bamberg.de/someCityPart/ics?RESTMUELL=true&BIO=true&YELLOW_SACK=true&PAPER=true&SPERRMUELL=true&PROBLEMMUELL=true
    customize:
      - type: "Restmülltonne"
        icon: mdi:trash-can
      - type: "Papiertonne"
        icon: mdi:trash-can
      - type: "Biotonne"
        icon: mdi:trash-can
      - type: "Gelber Sack"
        icon: mdi:trash-can
      - type: "Problemmüll"
        icon: mdi:trash-can
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
