### ISSUE TITLE
[Bug]: GWA Kreis Unna

### ISSUE THREAD

**Issue by marcusoct** [mampfes/hacs_waste_collection_schedule#2463]
### I Have A Problem With:

The integration in general

### What's Your Problem

In the GWA App are 2 sources for 1 Street. 
The Street Unnaerstrasse in Kamen have 2 different shedules. 
one for Unnaerstraße 93-97 and one for the Rest.  

In the Addon, i can‘t select the source. 

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
You can use 
```yaml
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: unna
        ort: Kamen
        strasse: Unnaer Straße, Hausnummern 91 bis 97
```
or
```yaml
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: unna
        ort: Kamen
        strasse: Unnaer Straße
```
