### ISSUE TITLE
[Bug]: waste_collection_schedule.fetch_data is NOT updating the sensor generic atributes

### ISSUE THREAD

**Issue by thecem** [mampfes/hacs_waste_collection_schedule#2472]
### I Have A Problem With:

The integration in general

### What's Your Problem

After rebooting home assistant the sensor atributes are gone only daysto are show´n.
So I try to actualise with waste_collection_schedule.fetch_data, but it is not updating the sensor generic atributes.
Only if I reconfigure the service, the dat will be there.

configuration via UI is:

```
url: https://sperrmuell.erlensee.de/?type=reminder
method: POST
options:
{
"street": 8,
"eventType[]": [23, 19, 20, 21, 24, 22, 25, 26],
"timeframe": 23,
"download": "ical",
}
Value Template:
{{value.types|join(",")}} {% if value.daysTo == 0 %}heute{% elif value.daysTo == 1 %}morgen{% else %}in {{value.daysTo}} Tagen{% endif %}
Date Template:
20.03.2020: {{value.date.strftime("%d.%m.%Y")}}

```
After a reboot of ha values for "Upcoming" are gone, fetch_data doesn´t help. only configure -> check change sensor -> save brings the attribute Upcoming back.

thanks for your help! 

### Relevant Configuration

```YAML
UI:

url: https://sperrmuell.erlensee.de/?type=reminder
method: POST
options:
{
"street": 8,
"eventType[]": [23, 19, 20, 21, 24, 22, 25, 26],
"timeframe": 23,
"download": "ical",
}
Value Template:
{{value.types|join(",")}} {% if value.daysTo == 0 %}heute{% elif value.daysTo == 1 %}morgen{% else %}in {{value.daysTo}} Tagen{% endif %}
Date Template:
20.03.2020: {{value.date.strftime("%d.%m.%Y")}}

```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
