### ISSUE TITLE
[BUG] Unable to restart HA after adding waste_collection_schedule: to configuration.yaml

### ISSUE THREAD

**Issue by mbrammer** [mampfes/hacs_waste_collection_schedule#254]
After adding the `waste_collection_schedule:` to my `configuration.yaml`, I am not able to do a config check or a restart of HA.
The config check request (`/api/config/core/check_config`) stagnates in the pending state.
I also did a `hass --script check_config` via console, but this script finished successfully. Not sure if it does exactly the same as the API script.

I installed waste_collection_schedule from **master** via HACS.
My HA version is **2022.6.3**, running in a Docker container.

My config:
```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://www.landkreis-harburg.de/abfallkalender/icalendar/ical.html?id=900000123&gebietOwner=20100&strukturID=1100&year={%Y}"
      customize:
        - type: Gelber Sack
          alias: Gelber Sack
          icon: mdi:recycle
        - type: Hausmüll 14-täglich
          alias: Hausmüll
          icon: mdi:trash-can
        - type: Altpapier
          alias: Altpapier
          icon: mdi:newspaper
        - type: Grünabfall
          alias: Grünabfall
          icon: mdi:tree
        - type: Biotonne
          alias: Biotonne
          icon: mdi:bio
      calendar_title: Abfall
  fetch_time: "04:00"
  day_switch_time: "16:00"
```
