### ISSUE TITLE
[Bug]: Issue adding Town - get bad schedule

### ISSUE THREAD

**Issue by misterymisery** [mampfes/hacs_waste_collection_schedule#2544]
### I Have A Problem With:

The integration in general

### What's Your Problem

After new HA upgrade I lost ability to add new town with additional_side_matcher It is showing bad schedule (while Android app and calendar synchronised to google shows good schedule).

In the past it was enough to give Town, Street, Number of house and ZABUDOWA JEDNORODZINNA. Now whatever I choose I get wrong schedule.

### Source (if relevant)

ecoharmonogram.pl

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: ecoharmonogram_pl
      args:
        town: AAAAAA
        street: BBBBBBB
        house_number: CC
        additional_sides_matcher: ZABUDOWA JEDNORODZINNA
```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
