### ISSUE TITLE
[Source Request]: Vaterstetten, Germany

### ISSUE THREAD

**Issue by cgarske** [mampfes/hacs_waste_collection_schedule#2570]
### Municipality / Region

Vaterstetten

### Collection Calendar Webpage

https://www.vaterstetten.de/bauen-umwelt/abfallwirtschaft/abfallkalender/

### Example Address

Gebiet 1 | Gebiet 2 | Gebiet 3 | Gebiet 4 | Gebiet 5 <<-- Biomüll (Organic waste)

Gebiet A | Gebiet B | Gebiet C | Gebiet D | Gebiet E | Gebiet F <<-- Restmüll (Residual waste)

### Collection Data Format

As ICS/ICAL file

**Comment by bbr111** [comment]
Vaterstetten is now supported via the `awido_de` source (Landkreis Ebersberg's AWIDO instance, `service_id: "ebe"`), added on 2026-01-28.

Example configuration:
```yaml
waste_collection_schedule:
  sources:
    - name: awido_de
      args:
        customer: ebe
        city: Vaterstetten
```

Please try this configuration and let us know if it resolves your request. Closing this issue as already supported — feel free to reopen if you run into any problems.
