### ISSUE TITLE
[Bug]: Apps_AbfallIO, Cant Create for "Nordsachsen" (Schkeuditz - District)

### ISSUE THREAD

**Issue by MickLesk** [mampfes/hacs_waste_collection_schedule#2580]
### I Have A Problem With:

A specific source

### What's Your Problem

1.) I go to the following page: https://www.asg-nordsachsen.de/entsorgung/abfalltermine.html
2.) Select city/municipality (%auswahl_kommune_set) “Schkeuditz”
3.) Select “City/District” (%auswahl_bezirk_set) “Radefeld”
4.) Street automatically set to “all streets” | House number automatically set to “all house numbers”. 

The API queries come from: “api.abfall.io” 

My current solution has always been to download the ics calendar and integrate it into Home Assistant. Unfortunately, I have often failed to set up the “Waste Collection Schedule”, but never had time to create an issue.

Here is my current config:
```yaml
ics_calendar:
  calendars:
    - name: “Waste Collection Schedule”
      url: “http://localhost:8123/local/abfall.ics”
      include_all_day: True
```

No matter what I have tried, e.g. “Bezirk” -> “Schkeuditz” then I get the following error: “The source returned an invalid response: ‘Bezirk Schkeuditz not found.’. Please check the arguments and try again.” 

If I still enter the district “Radefeld” I get the following message: 
“The source has returned an invalid response: “Region Radefeld not found.”. Please check the arguments and try again.”

To be honest, I no longer know what I have to enter to make it work. :-D 

<img width="676" alt="image" src="https://github.com/user-attachments/assets/0fcdbecd-719c-4ead-b354-553ee4eb0040">

### Source (if relevant)

de.abfallwecker

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
Configuring this is really not ideal, and we probably need to create a wizard and integrate them into the GUI, looks like you need to specify `bundesland` and `landkreis` for `abfallwecker`

Did some testing and this configuration works:

        "app_id": "de.abfallwecker",
        "city": "Schkeuditz",
        "bezirk": "Radefeld",
        "bundesland": "Sachsen",
        "landkreis": "Landkreis Nordsachsen",

**Comment by 5ila5** [comment]
Alternatively, you can use the [abfall_io source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfall_io.md) with 

```yaml
# Output of wizard/abfall_io.py with ASG Nordsachsen -> Schkeuditz -> Radefeld -> alle Straßen -> Alle Hausnummern
# waste_collection_schedule source configuration
waste_collection_schedule:
  sources:
    - name: abfall_io
      args:
        key: 1d78841c5d7fc43ebe52b9dc01f6b962
        f_id_kommune: 4398
        f_id_bezirk: 360309
        f_id_strasse: 487
        f_id_strasse_hnr: 360401
```

As i added it to the python script in #2583
