### ISSUE TITLE
[Source Request]: Gemeinde Gründau

### ISSUE THREAD

**Issue by 0xvisualiris** [mampfes/hacs_waste_collection_schedule#2606]
### Municipality / Region

Gründau Gettenbach, Hessen

### Collection Calendar Webpage

https://www.gruendau.info/kalender/de/gemeinde/-/2/calendar_show

### Collection Data Format

As ICS/ICAL file

**Comment by markvp** [comment]
Thanks for the report! The old `calendar_show` URL has been retired — Gründau's waste calendar now lives on the [Heimat-Info](https://www.heimat-info.de) platform, which also serves around 25 other German municipalities.

A new source `heimat_info_de` has been implemented and a PR is open. Once merged, you can configure it like this:

```yaml
waste_collection_schedule:
  sources:
    - name: heimat_info_de
      args:
        commune: gruendau
        area: Gettenbach   # or Breitenborn, Lieblos, Rothenbergen, etc.
```

The available areas for Gründau are: Breitenborn, Gettenbach, Lieblos, Rothenbergen, Mittel-Gründau, Niedergründau, Hain-Gründau.
