### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by noschic** [mampfes/hacs_waste_collection_schedule#2613]
### Municipality / Region

Amöneburg-Mardorf, Germany

### Collection Calendar Webpage

https://www.amoeneburg.de/kalender/de/stadt/-/2/calendar_show

### Example Address

Flurscheide 18, 35287 Amöneburg

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
They seem to use the same system as #2606

**Comment by markvp** [comment]
Thanks for the report! Good news — Amöneburg-Mardorf is already supported via the [\`buergerportal_de\`](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/buergerportal_de.md) source, which covers the Müllabfuhrzweckverband Biedenkopf.

The calendar URL in the issue (`/kalender/de/stadt/-/2/calendar_show`) was part of an old municipal platform that has since been decommissioned — MZV Biedenkopf now uses the Bürgerportal system.

**Configuration:**

```yaml
waste_collection_schedule:
  sources:
    - name: buergerportal_de
      args:
        operator: biedenkopf
        district: Amöneburg
        subdistrict: Mardorf
        street: <your street name>
        number: <your house number>
```

You can find available streets by omitting `street` first — the source will raise an error listing all valid streets for your subdistrict.
