### ISSUE TITLE
[Source Request]: Add Langenzersdorf in Austria to waste collection schedule

### ISSUE THREAD

**Issue by glischka** [mampfes/hacs_waste_collection_schedule#2614]
### Municipality / Region

Langenzersdorf

### Collection Calendar Webpage

https://www.langenzersdorf.gv.at/Buergerservice/Muell-Entsorgung/Muellabfuhrplaene

### Example Address

Wienerstrasse 1, 2103 Langenzersdorf

### Collection Data Format

As PDF Download

### Additional Information

After statinge the address a pdf can be downlaoded, and the upcoming dates are also listed on the website

**Comment by 5ila5** [comment]
seems to be same backend as #2618

**Comment by markvp** [comment]
This municipality is already supported via the existing **citiesapps_com** source (App CITIES platform). See documentation: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/citiesapps_com.md

Configure with:
```yaml
waste_collection_schedule:
  sources:
    - name: citiesapps_com
      args:
        city: "Langenzersdorf"
        calendar: "<your calendar name>"
        email: "<email>"
        password: "<password>"
```

Closing as already supported — feel free to reopen if you hit a specific issue with this source.
