### ISSUE TITLE
[Source Request]: LItvínovice

### ISSUE THREAD

**Issue by Alloc186** [mampfes/hacs_waste_collection_schedule#2632]
### Municipality / Region

LItvínovice

### Collection Calendar Webpage

https://calendar.google.com/calendar/u/0/embed?src=svozyodpadu@gmail.com&ctz=Europe/Prague&pli=1

### Example Address

https://www.litvinovice.cz/index.php?id=840913&action=detail&oid=42234&nid=783

### Collection Data Format

As html on a webpage

**Comment by markvp** [comment]
Thanks for the request! Good news -- this one can be configured right now using the existing generic `ics` source, no new module needed.

Litvínovice (including Šindlovy Dvory and Mokré) publishes its waste collection calendar as a publicly accessible Google Calendar ICS feed. You can use it directly in your Home Assistant configuration:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://calendar.google.com/calendar/ical/svozyodpadu%40gmail.com/public/basic.ics"
```

That's it -- no address lookup needed. The feed contains events labelled PLASTY, PAPÍR, BIO, etc. which map to the waste types shown on your collection schedule.

Closing this as the provider is already supported via the generic ICS source. If you run into any trouble getting it working, feel free to reopen.
