### ISSUE TITLE
[Bug]: muellmax_de

### ISSUE THREAD

**Issue by froggi1930** [mampfes/hacs_waste_collection_schedule#2640]
### I Have A Problem With:

A specific source

### What's Your Problem

Hi there,
since a couple of days the data for muellmax_de does not show up anymore in the calendar and also the sensors do not receive any value. Awista through monaloga_de works without any issue.
HA version: 2024.9.1
Integration: 2.1.0

### Source (if relevant)

muellmax_de

### Logs

```Shell
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:147
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 19:05:28 (1 Vorkommnisse)
Zuletzt protokolliert: 19:05:28

fetch failed for source Müllmax: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/icalendar/parser.py", line 340, in parts validate_token(name) File "/usr/local/lib/python3.12/site-packages/icalendar/parser.py", line 128, in validate_token raise ValueError(name) ValueError: <?xml version="1.0" encoding="UTF-8"?> During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/muellmax_de.py", line 151, in fetch dates = self._ics.convert(r.text) ^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert events: List[Any] = icalevents.events( ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalevents/icalparser.py", line 288, in parse_events calendar = Calendar.from_ical(content) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalendar/cal.py", line 330, in from_ical name, params, vals = line.parts() ^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/icalendar/parser.py", line 352, in parts raise ValueError( ValueError: Content line could not be parsed into parts: '<?xml version="1.0" encoding="UTF-8"?>': <?xml version="1.0" encoding="UTF-8"?> The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 145, in fetch entries = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/muellmax_de.py", line 153, in fetch raise ValueError( ValueError: Got invalid response from the server, please recheck your arguments
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: muellmax_de
      args:
        service: Tbr
        mm_frm_ort_sel: Remscheid
        mm_frm_str_sel: Nordstraße
        mm_frm_hnr_sel: 42853;Mitte;xx
      customize:
        - type: TBR Restmülltonne 2-wöchentlich
          alias: Restmüll
          icon: mdi:trash-can-outline
        - type: TBR Altpapiertonne
          alias: Altpapier
          icon: mdi:package-variant-closed
    - name: monaloga_de
      args:
        street: Nordstraße
        plz: "42853"
      customize:
        - type: Leichtverpackungen
          alias: Gelbe Tonne
          icon: mdi:recycle
  day_switch_time: "10:00"
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
