### ISSUE TITLE
[Bug]: api_golemio_cz failing for at least one area

### ISSUE THREAD

**Issue by ond000** [mampfes/hacs_waste_collection_schedule#2670]
### I Have A Problem With:

A specific source

### What's Your Problem

During configure new source I just see this error:

`The source returned an invalid response: "2 is not in list". Please check the provided arguments and try again.`

But only for my location, if I use location from example, it works, but I don't know why. If I try my input at source web page directly, it works and data seems OK and very similar as data from example.

### Source (if relevant)

api_golemio_cz

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
Country: Czech Republic
Source: Praha (api_golemio_cz)

Latitude: 50.0148303
Longitude: 14.4274233
Radius: 50
Api Key: **my secret key***
Only Monitored: no
Auto Suffix: yes
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
