### ISSUE TITLE
[Source Request]: Madison, Alabama 

### ISSUE THREAD

**Issue by BKarma22** [mampfes/hacs_waste_collection_schedule#2682]
### Municipality / Region

Madison, Alabama

### Collection Calendar Webpage

https://www.madisonal.gov/226/GarbageTrash-Service

### Example Address

350 Saint Louis St., Madison, AL 35758

### Collection Data Format

As html on a webpage

**Comment by dt215git** [comment]
I don't see any schedule on that website other than a map you can use to find which day of the week your collection is on.
If that's the case, you can use the [static source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md) to configure a schedule, for example:

```yaml
waste_collection_schedule:
  sources:
    - name: static
      args:
        type: Garbage
        frequency: WEEKLY
        weekdays: WE
```
Yard Waste seems to be subcontracted to Republic Services, which is already supported. See  [Republic Services](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/republicservices_com.md)

**Comment by markvp** [comment]
The situation for Madison, AL has two separate collection services, each with a different solution:

**Household garbage** (Madison County Sanitation) is collected every Thursday for all residents — there is no per-address API or calendar feed. The `static` source handles this perfectly:

```yaml
waste_collection_schedule:
  sources:
    - name: static
      args:
        type: Garbage
        frequency: WEEKLY
        weekdays: TH
```

**Trash/yard debris** (Republic Services) uses a zone-based map (PDF). The existing `republicservices_com` source can look up your schedule by address — try:

```yaml
waste_collection_schedule:
  sources:
    - name: republicservices_com
      args:
        street_address: "350 Saint Louis St., Madison, AL 35758"
```

See the [Republic Services source docs](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/republicservices_com.md) for full configuration options. Thanks to dt215git for the earlier guidance on this!

Since there is no machine-readable schedule data available for a dedicated Madison, AL source, I'll close this as not planned. If Madison County or Republic Services ever publishes a structured calendar feed for this area, feel free to reopen.
