### ISSUE TITLE
Support calender entries with multiple waste types

### ISSUE THREAD

**Issue by smoki3** [mampfes/hacs_waste_collection_schedule#271]
Hi, 

our I have the problem that my service provider will combine different waste types into one calender entry. (ICS file)

this will look like this: Gelber Sack+Papiertonne Bereitstellung
Which means on a specific day "Gelber Sack" and "Papiertonne" is emptied.

So is it possible to look in the kalender entry just for the keyword "Gelber Sack" and "Papiertonne"?

**Comment by dt215git** [comment]
Can't this already be achieved using the **split_at** option that's described on the [ICS/iCal](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) page?

> split_at
(string) (optional, default: None)
Delimiter to split event summary into individual collection types. If your service puts multiple collections types which occur at the same day into a single event, this option can be used to separate the collection types again.

**Comment by smoki3** [comment]
I tried ``` split_at: "+"``` but this doesnt work. Then I dont get any results

**Comment by dt215git** [comment]
The [ICS](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS_v1.py) module looks like it's using regex, so maybe it needs to be  `split_at: "\+"`?

**Comment by smoki3** [comment]
Unfortunately not working

**Comment by smoki3** [comment]
got it now. the problem was I used ```split_at: "\+"``` instead of ```split_at: '\+'```

**Comment by smoki3** [comment]
But there is still a problem. 
My ICS entry:
```Gelber Sack+Papiertonne Bereitstellung```

After split_at I get:
```Gelber Sack``` and ```Papiertonne Bereitstellung```

But normaly I also have:
```Gelber Sack Bereitstellung```

So Gelber Sack is not combiened together.

**Comment by dt215git** [comment]
Perhaps you also need the split to take into account the end of the line?
`split_at: '\+|\n'` or `split_at: '\+|\r'` or `split_at: '\+|\n|\r'`

**Comment by smoki3** [comment]
Nice :) 

Its working now!

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/Abfall.ics"
        #split_at: '\+'
        regex: "(.*) Bereitstellung"
        split_at: '\+'
      customize:
        - type: Biomüll
          alias: biotonne
          icon: mdi:flower-outline
        - type: Gelber Sack
          alias: gelbersack
          icon: mdi:recycle
        - type: Restmüll
          alias: restmuell
          icon: mdi:trash-can
        - type: Papiertonne
          alias: papiertonne
          icon: mdi:trash-can-outline
        - type: Altpapier
          alias: altpapier
          icon: mdi:trash-can-outline
        - type: Gartenabfälle
          alias: gartenabfall
          icon: mdi:flower-outline
```

**Comment by dt215git** [comment]
Does it work if you change DESCRIPTION to SUMMARY in the ICS file?
Not a long-term solution, but might help work out if it's the ICS file structure that's different to what's expected.

**Comment by clipse2004** [comment]
Unfortunately no, I just noticed that both are already included in the ICS :/ 
Here is an excerpt:

BEGIN:VEVENT
DESCRIPTION:Papiertonne / gelber Sack
DTEND;VALUE=DATE:20220117
DTSTAMP:20221202T091704Z
DTSTART;VALUE=DATE:20220117
SEQUENCE:0
STATUS:Confirmed
SUMMARY:Papiertonne / Papiercontainer / gelber Sack
UID:99d65d7e-1dfe-4212-a3fa-f1b4d3d262ed
BEGIN:VALARM
ACTION:Display
DESCRIPTION:Papiertonne / Papiercontainer / gelber Sack
TRIGGER:PT4H
END:VALARM
END:VEVENT

**Comment by dt215git** [comment]
If it take an ics file generated by my local service and change the SUMMARY to match what you have, I get the following:
```
BEGIN:VCALENDAR
PRODID:-//000.000.000.000//Waste Calendar Generator//
VERSION:3.02
X-WR-CALNAME:Bins Schedule
X-WR-CALDESC:Bins Schedule
X-WR-TIMEZONE:Europe/nnn
BEGIN:VEVENT
UID:ccabb0ec-3cf8-4ac8-b186-ff9661b5a48c@000.000.000.000
DTSTAMP:20221203T083513Z
DTSTART;VALUE=DATE:20221206
SUMMARY:Papiertonne / Papiercontainer / gelber Sack
END:VEVENT
END:VCALENDAR
```


To process this, I used the following settings
```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "./MyStuff/testcal.ics"
        split_at: '\s\/\s'
        version: 2
```
```yaml
sensor:
  - platform: waste_collection_schedule
    source_index: 0
    name: ICStest
    details_format: appointment_types
    date_template: '{{value.date.strftime("%A %d %B %Y")}}'
    add_days_to: true
```
The following calendar entries get generated - the difference between them is whether the `split-at: '\s\/\s'` line is included or deleted
![image](https://user-images.githubusercontent.com/86194065/205436460-684f8de6-5b57-4da5-84dc-293aaf0179c7.png)

In your ics extract, the `DTSTART` field is in the past so I doubt they'd generate calendar entries. In the full ics file, are any of them in the future? Or are the collection dates appearing under one of the other fields?
