### ISSUE TITLE
[Source Request]: City of Port Phillip, 

### ISSUE THREAD

**Issue by agilityprop** [mampfes/hacs_waste_collection_schedule#2717]
### Municipality / Region

City of Port Phillip

### Collection Calendar Webpage

https://www.portphillip.vic.gov.au/council-services/waste-recycling-and-rubbish/bins-and-collection-services

### Example Address

9 Spray Street, Elwood Vic 3184, Australia

### Collection Data Format

As html on a webpage

**Comment by bbr111** [comment]
Thanks for the request! I've added support for City of Port Phillip in #6900.

The council's bin-day lookup map (the one embedded on the collection services page) is backed by a public IntraMaps API, so I was able to implement this directly. Note that Port Phillip collects general waste, recycling, and FOGO bins together on the same day each week (per the council's own page text), so the sensor will report all three waste types on the same weekly date.

Once the PR is merged you'll be able to configure it with:

```yaml
waste_collection_schedule:
  sources:
    - name: portphillip_vic_gov_au
      args:
        address: "9 Spray Street Elwood"
```
