### ISSUE TITLE
[Source Request]: Waste collection for Taupo, New Zealand

### ISSUE THREAD

**Issue by Snowy486** [mampfes/hacs_waste_collection_schedule#2735]
### Municipality / Region

Taupo, New Zealand

### Collection Calendar Webpage

https://www.taupodc.govt.nz/property-and-rates/rubbish-and-recycling/kerbside-refuse-and-recycling-collection

### Example Address

Richmond Heights, Taupo. Thursday Pickup

### Collection Data Format

As html on a webpage

**Comment by 5ila5** [comment]
Looks like you can use the [static source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md)

**Comment by markvp** [comment]
Thanks for the request! This is now implemented — the Taupō District Council exposes a public ArcGIS REST API that makes a proper source possible.

You can configure it in `configuration.yaml` like this:

```yaml
waste_collection_schedule:
  sources:
    - name: taupodc_govt_nz
      args:
        address: "9 Richmond Avenue Taupo"
```

Use your address exactly as it appears in the [TDC collection day map](https://taupo.maps.arcgis.com/apps/instant/lookup/index.html?appid=5a763f92dc6e4d09aa06fcdf5476591f) search field. A PR is on its way.
