### ISSUE TITLE
0 entries for MÜLLALARM/Schoenmackers

### ISSUE THREAD

**Issue by GerdRuetten** [mampfes/hacs_waste_collection_schedule#279]
Thank's for this great component!

I use it with source "abfall_io" for MÜLLALARM/Schoenmackers.

I get no result.

If i use the "test_sources.py -s abfall_io -l -i" i get the message:

<img width="291" alt="image" src="https://user-images.githubusercontent.com/97361636/177575504-847aa02b-dddc-476d-b5de-3429c321cdd1.png">

Is there a problem with my customizing or with the API generell?

Best regards

Gerd

**Comment by GerdRuetten** [comment]
**1. Configuration source**

```
# Integration Abfallkalender
  sources:
    - name: abfall_io
      args:
        key: !secret waste_key
        f_id_kommune: !secret waste_id_kommune
        f_id_bezirk: !secret waste_id_bezirk
        f_id_strasse: !secret waste_id_strasse
        f_id_strasse_hnr: !secret waste_id_strasse_hnr
      customize:
        - type: Bioabfall
          alias: Bioabfall
          icon: mdi:flower-outline
        - type: Leichtverpackungen
          alias: Leichtverpackungen
          icon: mdi:recycle
        - type: Restabfall
          alias: Restabfall
          icon: mdi:trash-can
        - type: Papier
          alias: Papier
          icon: mdi:trash-can-outline
        - type: Schadstoffe
          alias: Schadstoffe
          icon: mdi:trash-can-outline                  
        - type: Grünbündel
          alias: Grünbündel
          icon: mdi:trash-can-outline 
  fetch_time: "03:00"
  day_switch_time: "12:00"
```

**2. Configuration sensor:**

```
# Müll Termine
# - type: Bioabfall
# - type: Leichtverpackungen
# - type: Restabfall
# - type: Papier
# - type: Schadstoffe
# - type: Grünbündel

  - platform: waste_collection_schedule
    name: AbfallRestabfall
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Restabfall

  - platform: waste_collection_schedule
    name: AbfallPapier
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Papier

  - platform: waste_collection_schedule
    name: AbfallLeichtverpackungen
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Leichtverpackungen

  - platform: waste_collection_schedule
    name: AbfallBioabfall
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Bioabfall

  - platform: waste_collection_schedule
    name: AbfallSchadstoffe
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Schadstoffe

  - platform: waste_collection_schedule
    name: AbfallGrünbündel
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Grünbündel

#------------------------

  - platform: waste_collection_schedule
    name: AbfallRestabfallnext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - Restabfall

  - platform: waste_collection_schedule
    name: AbfallPapiernext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - Papier

  - platform: waste_collection_schedule
    name: AbfallLeichtverpackungennext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - Leichtverpackungen

  - platform: waste_collection_schedule
    name: AbfallBioabfallnext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - Bioabfall

  - platform: waste_collection_schedule
    name: AbfallSchadstoffenext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - Schadstoffe

  - platform: waste_collection_schedule
    name: AbfallGrünbündelnext
    details_format: "upcoming"
    value_template: 'am: {{value.date.strftime("%d.%m.%Y")}}'
    types:
      - Grünbündel

#-----------------

  - platform: waste_collection_schedule
    name: AbfallNaechster
    details_format: "upcoming"
    value_template: ' {{ value.daysTo }} '
```

If you need more information, let me know.
