### ISSUE TITLE
abfallv.zerowaste.io how to add ?

### ISSUE THREAD

**Issue by zibous** [mampfes/hacs_waste_collection_schedule#282]
Congratulations for the great application. I can't find a way to embed the wastev.zerowaste.io calendar.

```
BEGIN:VCALENDAR
PRODID:Müllkalender
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
UID:783554690c85b21592fc5c3952837fb5
DTSTAMP:20220708T172630Z
SUMMARY:Restabfall
DESCRIPTION:Abholtermin für Restabfall. \n\nDieser Eintrag wurde von der A
 bfall App erstellt! \nMehr Infos auf www.abfallv.at\n\nDie Abfall App gibt
  es auch für das Smartphone \nfürs iPhone & Android.
URL:https://abfallv.zerowaste.io/
DTSTART:20220712
END:VEVENT
BEGIN:VEVENT
UID:3f0050d9de870e0dcd5c3552c9751fbc
DTSTAMP:20220708T172630Z
SUMMARY:Restabfall
DESCRIPTION:Abholtermin für Restabfall. \n\nDieser Eintrag wurde von der A
 bfall App erstellt! \nMehr Infos auf www.abfallv.at\n\nDie Abfall App gibt
  es auch für das Smartphone \nfürs iPhone & Android.
URL:https://abfallv.zerowaste.io/
DTSTART:20220726
END:VEVENT
BEGIN:VEVENT
UID:10da5c6ea2bc611e4f091bac71e486cd
DTSTAMP:20220708T172630Z
SUMMARY:Restabfall
DESCRIPTION:Abholtermin für Restabfall. \n\nDieser Eintrag wurde von der A
 bfall App erstellt! \nMehr Infos auf www.abfallv.at\n\nDie Abfall App gibt
  es auch für das Smartphone \nfürs iPhone & Android.
URL:https://abfallv.zerowaste.io/
DTSTART:20220809
END:VEVENT
```

[Muellkalender.ics.zip](https://github.com/mampfes/hacs_waste_collection_schedule/files/9074113/Muellkalender.ics.zip)

url: https://abfallv.zerowaste.io/ical/9710?area_filter=619%2C620%2C621%2C622%2C1474%2C1535%2C2066%2C2421%2C2862&reminder

How can I do that ?

**Comment by dt215git** [comment]
Couldn't this be implemented using the [ICS / iCal](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md#configuration-via-configurationyaml) option?

**Comment by zibous** [comment]
@dt215git 
Thanks for the information, I tried and it seems to work. But I'm not quite sure about the entries `type`.

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://abfallv.zerowaste.io/ical/9710?area_filter=619%2C620%2C621%2C622%2C1474%2C1535%2C2066%2C2421%2C2862&reminder
      customize:
        - type: Restmüll 2-wöchentlich
          alias: Restmüll
          icon: mdi:trash-can
        - type: Bioabfall 1-wöchentlich
          alias: Bioabfall
          icon: mdi:flower-outline
        - type: Papier 4-wöchentlich
          alias: Papierabfall
          icon: mdi:trash-can-outline
        - type: Gelber Sack
          icon: mdi:recycle
```
```yaml
  - platform: waste_collection_schedule
    name: Abfall Termine
    details_format: appointment_types
    add_days_to: true
    count: 6
    date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  
  - platform: waste_collection_schedule
    name: Abfall Termin
    count: 6
    value_template: 'Termin Abfall für {{value.types|join(", ")}}  {% if value.daysTo == 0 %}ist Heute{% elif value.daysTo == 1 %}ist Morgen{% else %}in {{value.daysTo}} ist Tagen{% endif %}'
    date_template: '{{value.date.strftime("%d.%m.%Y")}}'
```

![Bildschirmfoto 2022-07-12 um 15 44 31](https://user-images.githubusercontent.com/30198737/178504900-46e3c36b-7b22-427a-9d79-3c6f60d244b7.png)

**Comment by zibous** [comment]
now it is working.., thanks

```yaml
## #####################################
## Abfall Kalender
## #####################################
## ICS SUMMARY:Restabfall
## ICS SUMMARY:Bioabfall
## ICS SUMMARY:Altpapier monatlich
## ICS SUMMARY:Gelber Sack
## ICS SUMMARY:Biotonne Reinigung
## #####################################
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://abfallv.zerowaste.io/ical/9710?area_filter=619%2C620%2C621%2C622%2C1474%2C1535%2C2066%2C2421%2C2862&reminder
      customize:
        - type: Restabfall
          icon: mdi:trash-can
          show: true
        - type: Bioabfall
          icon: mdi:flower-outline
          show: true
        - type: Altpapier monatlich
          icon: mdi:trash-can-outline
          show: true
        - type: Gelber Sack
          icon: mdi:recycle
          show: true
        - type: Biotonne Reinigung
          icon: mdi:flower-outline
          show: false
```
