### ISSUE TITLE
[Bug]: Landkreis Giessen is now using awido_de not muellmax_de

### ISSUE THREAD

**Issue by 6uy5rush** [mampfes/hacs_waste_collection_schedule#2822]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

Landkreis Giessen is now using awido_de not muellmax_de anymore.
You have to use lkgi as customer as stated here in the following link on their homepage:

[(https://awido.cubefour.de/customer/lkgi/mobile/#load)]

Using it on my system using the following configuration, which is working correctly:

```yaml
waste_collection_schedule:
  sources:
    - name: **awido_de**
      args:
        customer: **lkgi**
        city: xxx
        street: xxx
      calendar_title: Abfall
      customize:
        - type: Restabfall 2-wöchentlich
          alias: Graue Tonne
        - type: Bioabfall
          alias: Grüne Tonne
        - type: Gelbe Tonne
          alias: Gelbe Tonne
        - type: Altpapier
          alias: Blaue Tonne
```

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: awido_de
      args:
        customer: lkgi
        city: xxx
        street: xxx
      calendar_title: Abfall
      customize:
        - type: Restabfall 2-wöchentlich
          alias: Graue Tonne
        - type: Bioabfall
          alias: Grüne Tonne
        - type: Gelbe Tonne
          alias: Gelbe Tonne
        - type: Altpapier
          alias: Blaue Tonne
new tested and OK config
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by 5ila5** [comment]
They seem to support both and even link to both: https://www.lkgi.de/kalender-app-und-abfall-abc/
![image](https://github.com/user-attachments/assets/fe20868c-950c-48d1-8368-0f6d245fc193)

and this still works:

```yaml
waste_collection_schedule:
  sources:
    - name: muellmax_de
      args:
        service: Lkg
        mm_frm_ort_sel: Langgöns
        mm_frm_str_sel: Hauptstraße
```

but I added LK Gießen to the AWIDO documentation in #2830
