### ISSUE TITLE
[Source Request]: Abfuhrkalender Wiefelstede

### ISSUE THREAD

**Issue by S13m3r1ng** [mampfes/hacs_waste_collection_schedule#2887]
### Municipality / Region

Wiefelstede

### Collection Calendar Webpage

https://www.appfuhr.de/

### Example Address

Haferweg 5

### Collection Data Format

As documented API

**Comment by Tenosiey** [comment]
See #4312

**Comment by bbr111** [comment]
Good news — Wiefelstede is now supported! A source for appfuhr.de / AWB Ammerland (Abfallwirtschaftsbetrieb Landkreis Ammerland), which covers Wiefelstede along with Apen, Bad Zwischenahn, Edewecht, Rastede and Westerstede, was added in #5664 and is available on `master` as `awb_ammerland_de`.

Example configuration for Wiefelstede:

```yaml
waste_collection_schedule:
  sources:
    - name: awb_ammerland_de
      args:
        city: Wiefelstede
        street: Ahlerskamp
        four_weekly_rest: true  # optional, only if your residual waste bin is on a 4-weekly schedule
```

See the docs for full details: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/awb_ammerland_de.md

Closing this as resolved — please reopen if the source doesn't work for your street.
