### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by rskerns** [mampfes/hacs_waste_collection_schedule#2890]
### Municipality / Region

Abilene, TX

### Collection Calendar Webpage

https://abilenetx.gov/426/Solid-Waste-Recycling

### Example Address

3601 Chimney Rock RD

### Collection Data Format

As html on a webpage

**Comment by markvp** [comment]
Thanks for the request! This is now implemented and a PR has been submitted.

The source (`abilene_tx_us`) uses the City of Abilene's public ArcGIS feature services to look up your collection zone by address and returns:

- **Trash** — twice-weekly pickup (Monday/Thursday or Tuesday/Friday depending on your zone)
- **Yard Waste** — monthly curbside brush & bulky pickup (odd months; specific week varies by zone)

Configuration example:

```yaml
waste_collection_schedule:
  sources:
    - name: abilene_tx_us
      args:
        address: "3601 Chimney Rock Rd, Abilene, TX"
```
