### ISSUE TITLE
[Source Request]: Zillingdorf (Austria)

### ISSUE THREAD

**Issue by stju-ard** [mampfes/hacs_waste_collection_schedule#2906]
### Municipality / Region

Zillingdorf, Austria

### Collection Calendar Webpage

https://calendar.google.com/calendar/ical/v60bh2s8sl7tg2khv1kgg3qu5c%40group.calendar.google.com/public/basic.ics

### Collection Data Format

As ICS/ICAL file, As html on a webpage

**Comment by bbr111** [comment]
Thanks for the request! Zillingdorf is now supported via the existing `ics` source using the Google Calendar ICS feed you provided. A PR has been submitted (#6698).

Once merged, configure it like this:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://calendar.google.com/calendar/ical/v60bh2s8sl7tg2khv1kgg3qu5c%40group.calendar.google.com/public/basic.ics
```

You can also configure it via the Home Assistant UI by selecting **ICS** as the source and pasting the URL above.
