### ISSUE TITLE
[Source Request]: Stadt und Landkreis Straubing-Bogen

### ISSUE THREAD

**Issue by faltinho** [mampfes/hacs_waste_collection_schedule#2935]
### Municipality / Region

Stadt und Landkreis Straubing-Bogen

### Collection Calendar Webpage

https://www.zaw-sr.de/abfuhrkalender

### Example Address

94315 Straubing, Hasenweg 5

### Collection Data Format

As ICS/ICAL file

### Additional Information

https://straubing.zaw-sr.de/WasteManagementStraubing/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=1110711001&AboID=159073&Fra=R2;B2;P2;P4;R1

**Comment by bbr111** [comment]
This is now supported — a dedicated source for ZAW-SR (Zweckverband Abfallwirtschaft Straubing Stadt und Land) was added in #6512 as `zaw_sr_de`, covering the city and Landkreis Straubing-Bogen via the same calendar system linked in this issue (https://www.zaw-sr.de/abfuhrkalender).

Configuration example:
```yaml
waste_collection_schedule:
  sources:
    - name: zaw_sr_de
      args:
        city: Straubing
        street: Hasenweg
        hnr: "5"
```
See the docs for full details: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/zaw_sr_de.md

Closing as resolved. Thanks for the request, and apologies for the long delay.
