### ISSUE TITLE
[Source Request]: Landkreis Dingolfing-Landau

### ISSUE THREAD

**Issue by faltinho** [mampfes/hacs_waste_collection_schedule#2936]
### Municipality / Region

Landkreis Dingolfing-Landau

### Collection Calendar Webpage

https://www.awv-isar-inn.de/informationen/abfuhrkalender/

### Example Address

Falkenweg, Dingolfing

### Collection Data Format

As ICS/ICAL file

**Comment by bbr111** [comment]
Thanks for the request! Good news — this is already supported. AWV Isar-Inn (Landkreis Dingolfing-Landau) uses the AWIDO by CubeFour platform, which this integration already covers via the `awido_de` source, and the "Abfallwirtschaft Isar-Inn" customer is already registered.

You can configure it like this:

```yaml
waste_collection_schedule:
  sources:
    - name: awido_de
      args:
        customer: awv-isar-inn
        city: Dingolfing
        street: Falkenweg
```

I verified against the live AWIDO API that both "Dingolfing" (as city) and "Falkenweg" (as street) resolve correctly, so this should work out of the box. See the docs for more details: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/awido_de.md

Closing as already supported — feel free to reopen if you run into any issues configuring it.
