### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by Matty1080** [mampfes/hacs_waste_collection_schedule#2969]
### Municipality / Region

Northumberland, UK

### Collection Calendar Webpage

https://www.northumberland.gov.uk/Waste/Household-waste/Household-bin-collections/Bin-Calendars.aspx

### Example Address

30, NE46 1UF

### Collection Data Format

As html on a webpage

**Comment by AndyMillne** [comment]
+1 please

**Comment by markvp** [comment]
Good news — this is now supported! The `northumberland_gov_uk` source was added in PR #6418. You'll need your UPRN: enter your postcode at https://bincollection.northumberland.gov.uk/postcode and select your address (the UPRN is the dropdown option value), or look it up at https://www.findmyaddress.co.uk/. Then:

```yaml
waste_collection_schedule:
  sources:
    - name: northumberland_gov_uk
      args:
        uprn: "YOUR_UPRN"
```

Docs: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/northumberland_gov_uk.md . Closing as supported.
