### ISSUE TITLE
[Bug]: Version 2.4.0 broken (No module named 'icalendar.windows_to_olson')

### ISSUE THREAD

**Issue by BoGnY** [mampfes/hacs_waste_collection_schedule#2987]
### I Have A Problem With:

The integration in general

### What's Your Problem

The version 2.4.0 which try to fix icalendar v6 error get "No module named 'icalendar.windows_to_olson'"

Version 2.3.0 with ics calendar 5.0.3 (not 5.0.4) works without problem.

Not tested 'master' because there isn't `master` selectable:
![image](https://github.com/user-attachments/assets/60e76878-9c79-4099-ab9e-372c87f8096e)

### Source (if relevant)

contarina_it

### Logs

```Shell
error loading source ics: No module named 'icalendar.windows_to_olson' Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 217, in create source_module: SourceModule = importlib.import_module( ^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module return _bootstrap._gcd_import(name[level:], package, level) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap>", line 1387, in _gcd_import File "<frozen importlib._bootstrap>", line 1360, in _find_and_load File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 935, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 995, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 15, in <module> from waste_collection_schedule.service.ICS import ICS File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 7, in <module> from icalevents import icalevents File "/usr/local/lib/python3.12/site-packages/icalevents/icalevents.py", line 3, in <module> from .icalparser import parse_events, Event File "/usr/local/lib/python3.12/site-packages/icalevents/icalparser.py", line 18, in <module> from icalendar.windows_to_olson import WINDOWS_TO_OLSON ModuleNotFoundError: No module named 'icalendar.windows_to_olson'
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: ics
      args:
        regex: '.*: (.*)'
        split_at: ', '
        url: https://contarina.it/ajax/moduli/appbugfixapi/genera_ics_calendari?id_zona=19
      customize:
        - type: Carta
          icon: mdi:package-variant
        - type: Secco
          icon: mdi:dump-truck
        - type: Umido
          icon: mdi:compost
        - type: Vegetale
          icon: mdi:leaf
        - type: Vpl
          icon: mdi:bottle-wine
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
