### ISSUE TITLE
[Bug]: Source stopped working ... sensor now 'unknown'

### ISSUE THREAD

**Issue by FS1961** [mampfes/hacs_waste_collection_schedule#3084]
### I Have A Problem With:

A specific source

### What's Your Problem

My source city Erdesbach which has worked for more than a year, has suddenly stopped working and gone to 'unknown'. I'm using 2.4.0 but have gone back to 2.0.0 to see if it's a version issue. No joy.

The source is working and I've verified it manually.

### Source (if relevant)

landkreis_kusel_de

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
- platform: waste_collection_schedule
    name: Trash
    details_format: upcoming
    count: 1
    leadtime: 2
    value_template: '{{value.types|join(", ")}} {% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tonight{% else %}in {{value.daysTo}} Days{% endif %}'

waste_collection_schedule:
  sources:
    - name: landkreis_kusel_de
      args:
        ortsgemeinde: Erdesbach
      calendar_title: "Trash Pickup"
      customize:
        - type: "Glas (Weisse Säcke)"
          alias: "Glass"
          icon: mdi:sack-outline
        - type: "Bioabfall"
          alias: "Bio"
        - type: "Restmüll"
          alias: "Trash"
        - type: "LVP-Abfälle (Gelbe Säcke)"
          alias: "Yellow bag"
          icon: mdi:recycle
        - type: "Papier (Blaue Tonne)"
          alias: "Paper Bin"
          icon: mdi:recycle
        - type: "Umweltmobil"
          alias: "Recycling van"
          icon: mdi:truck
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
