### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by Popey22** [mampfes/hacs_waste_collection_schedule#3087]
### Municipality / Region

Germany/ Badenwürttemberg/Rottweil

### Collection Calendar Webpage

https://www.abfallplus.de/  https://www.landkreis-rottweil.de/eigenbetrieb-abfallwirtschaft

### Example Address

Schulbergstraße 6, 72172 Sulz am Neckar  (Ortsteil Mühlheim)
![Bildschirmfoto 2024-11-25 um 08 56 35](https://github.com/user-attachments/assets/ece08c88-d2df-4404-8166-adae32de7bfa)

### Collection Data Format

Something different (add to additional information)

### Additional Information

![Bildschirmfoto 2024-11-25 um 08 56 35](https://github.com/user-attachments/assets/b79d0a81-2d33-4ebd-b4b7-1db49920c130)

**Comment by 5ila5** [comment]
the config for [app_abfallplus_de](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/app_abfallplus_de.md) is

```yaml
app_id: de.abfallwecker
city: Sulz
bezirk: Mühlheim
strasse: Schulbergstr.
bundesland: Baden-Württemberg
landkreis: Kreis Rottweil
```

the configuration for the [abfall_io source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfall_io.md) is



```yaml
key: d287412901d68d66825e588a60c94641
f_id_kommune: 124
f_id_bezirk: 873
f_id_strasse: 2580
f_id_strasse_hnr: 20888
```
