### ISSUE TITLE
[Bug]: Not colecting data from warszawa19115.pl

### ISSUE THREAD

**Issue by Tomkee** [mampfes/hacs_waste_collection_schedule#3095]
### I Have A Problem With:

A specific source

### What's Your Problem

Not collecting data for addon.

I can get proper data from terminal by using terminal and 

curl -X GET "https://warszawa19115.pl/harmonogramy-wywozu-odpadow?p_p_id=portalCKMjunkschedules_WAR_portalCKMjunkschedulesportlet_INSTANCE_o5AIb2mimbRJ&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_resource_id=ajaxResource&p_p_cacheability=cacheLevelPage&_portalCKMjunkschedules_WAR_portalCKMjunkschedulesportlet_INSTANCE_o5AIb2mimbRJ_addressPointId=xxxxxxx" -H "Accept: application/json"

I am not programer myself by tried to:
- Use Chat GPT to fix isue
- Recover old HA instalation with old configuration
- Downgrade to 2.0 Wast colection schedule addon
- Inserting street adress and geoid
- Changing city to MPGK Katowice and data is downloading normally

Nothing worked for me. 

### Source (if relevant)

warszawa19115.pl

### Logs

```Shell
This error originated from a custom integration.

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
integration: Waste Collection Schedule (documentation)
First occurred: 12:39:55 AM (2 occurrences)
Last logged: 1:17:40 AM

fetch failed for source Warsaw: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/warszawa19115_pl.py", line 127, in fetch or len(calendar_result[0]["harmonogramy"]) <= 0 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: object of type 'NoneType' has no len()
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: warszawa19115_pl
      args:
        geolocation_id: xxxxxx
      customize:
        - type: Szkło
          alias: Szkło
        - type: Zielone
          alias: Zielone
        - type: Bio
          alias: Bio
        - type: Metale i tworzywa sztuczne
          alias: Metale i plastik
        - type: Papier
          alias: Papier
        - type: Odpady zmieszane
          alias: Odpady zmieszane
        - type: Odpady wielkogabarytowe
          alias: Odpady wielkogabarytowe
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
