### ISSUE TITLE
Lost with Cards

### ISSUE THREAD

**Issue by GLehnhoff** [mampfes/hacs_waste_collection_schedule#31]
I am completely lost. I would like to start with a lovelace card like that one below but do not find any in my lovelace.

[Pic](https://raw.githubusercontent.com/mampfes/hacs_waste_collection_schedule/master/doc/appointment_types_details.png)

https://raw.githubusercontent.com/mampfes/hacs_waste_collection_schedule/master/doc/appointment_types_details.png

**Comment by mampfes** [comment]
The picture you are refering to, is the details view of an entity - which shows up if you click on an entity. I don't know if you can show this view directly within a lovelace card.

**Comment by GLehnhoff** [comment]
Ok, Thanks, got it.

I tried hard but I did not mange to get a Card with the information of the next three collections like the detail view (though I know how to get a list of the next three entries only with "count: 3"):

- date - collection type
- date - collection type
- date - collection type

I managed to get a lot of other views, but not this one. Any hint?

**Comment by GLehnhoff** [comment]
Well, I am speeding up. I solved the third challenge:
```
`waste_collection_schedule:  
  sources:  
    - name: muellmax_de  
      args:  
        service: His  
        mm_frm_str_sel: xxx  
      customize:  
        - type: HIS Restmüll, wöchentliche Abfuhr  
          show: no`
```

**Comment by GLehnhoff** [comment]
And I solved the second challenge:
```
waste_collection_schedule:
  sources:
    - name: muellmax_de
      args:
        service: His
        mm_frm_str_sel: xxx
      customize:
        - type: HIS Restmüll, wöchentliche Abfuhr
          show: no
        - type: HIS Restmüll, 2-wöchentliche Abfuhr
          alias: Restmüll
        - type: HIS Papier
          alias: Papier
        - type: HIS GS/Leichtverpackungen
          alias: Gelbe Tonne
        - type: HIS Biomüll
          alias: Biomüll
```
So for now only the first challenge is left.

**Comment by mampfes** [comment]
Great to hear that you already solved most of your problems.

Regarding the first "challenge": In the end this issue can't be solved by the Waste Collection Schedule integration itself, but only in combination with a matching lovelace card.

Here are some suggestions:

If you really want to see the next (3) upcoming events, regardless of the waste type, you could use the https://github.com/thomasloven/lovelace-more-info-card to display to content of the details view. This card can be easily installed via HACS.

If you instead want to see the upcoming events of 3 dedicated waste types (like Restmuell + Papier + Gelber Sack) you could setup 3 discrete sensors - 1 per waste type - and use the "Entities" card to display the entities in one frame.

**Comment by GLehnhoff** [comment]
Thanks, Steffen, I have done both. And just in case it is display in "...in 1 days" rep. "...in 0 days", which I do not know yet but assume, I have a solution for that also which shows "tomorrow", resp. "today".

I am speeding up. 

PS: A few more examples in your description would have make my life a bit easier. If you would like me to deliver one, I will do that.

**Comment by GLehnhoff** [comment]
```
#--------------------------
# Müllabfuhr His
# https://github.com/mampfes/hacs_waste_collection_schedule
    
# Nächste Leerung    
  - platform: waste_collection_schedule
    name: Nächste Leerung
    details_format: upcoming
    value_template: '{{value.types|join(", ")}} in {{value.daysTo}} Tagen ({{value.date.strftime("%d.%m.%Y")}})'   
    count: 4
    
 # Nächste Biomüll-Leerung   
  - platform: waste_collection_schedule
    name: Biomüll
    details_format: upcoming
    value_template: 'in {{value.daysTo}} Tagen ({{value.date.strftime("%d.%m.%Y")}})'
    count: 1
    types:
      - Bio Tonne
    
 # Nächste Gelbe Tonne   
  - platform: waste_collection_schedule
    name: Gelbe Tonne
    details_format: upcoming
    value_template: 'in {{value.daysTo}} Tagen ({{value.date.strftime("%d.%m.%y")}})'
    count: 1
    types:
      - Gelbe Tonne
     
 # Nächste Papier-Leerung   
  - platform: waste_collection_schedule
    name: Papier
    details_format: upcoming
    value_template: 'in {{value.daysTo}} Tagen ({{value.date.strftime("%d.%m.%y")}})'
    count: 1
    types:
      - Papier

 # Nächster Restmüll   
  - platform: waste_collection_schedule
    name: Restmüll
    details_format: upcoming
    value_template: 'in {{value.daysTo}} Tagen ({{value.date.strftime("%d.%m.%y")}})'
    count: 1
    types:
      - Restmüll

waste_collection_schedule:
  sources:
    - name: muellmax_de
      args:
        service: His
        mm_frm_str_sel: Hadrianstraße
      customize:
        - type: HIS Restmüll, wöchentliche Abfuhr
          show: no
        - type: HIS Restmüll, 2-wöchentliche Abfuhr
          alias: Restmüll
        - type: HIS Papier
          alias: Papier
        - type: HIS GS/Leichtverpackungen
          alias: Gelbe Tonne
        - type: HIS Biomüll
          alias: Bio Tonne

#--------------------------
```
This is the more-info-card I loaded from HACS:
![grafik](https://user-images.githubusercontent.com/5453201/108533738-9ba9d380-72d9-11eb-9e6d-4d87dbb5716e.png)
These are lovelace standrad cars:
![grafik](https://user-images.githubusercontent.com/5453201/108533832-b714de80-72d9-11eb-9fd3-47c3a7255355.png)

What is left is changing the dates format in the first card to German format. Currently I do not know how to do it.

**Comment by mampfes** [comment]
Hi,

you can use the following template which displays "today"/"tomorrow" instead of "in 0 days" / "in 1 days":
`value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'`

Regarding your offering with the examples:
I decided to tidy the whole documentation a little bit. I would really appreciate your feedback once I have the first draft. May I ask you to review it?

**Comment by mampfes** [comment]
> What is left is changing the dates format in the first card to German format. Currently I do not know how to do it.

Use `date_template` (in addition to `value_template`), e.g.

`date_template: '{{value.date.strftime("%d.%m.%y")}}'`

**Comment by GLehnhoff** [comment]
> May I ask you to review it?  

Yes, of course. If you drop me an mail to Temp2021@habmalnefrage.de, I will reply with my real one.

**Comment by GLehnhoff** [comment]
> date_template: '{{value.date.strftime("%d.%m.%y")}}'

Very good. Worked. All done.

**Comment by GLehnhoff** [comment]
Just in case, anybody is interested in, here again the modified yaml and pics:


```
#--------------------------
# Müllabfuhr His
# https://github.com/mampfes/hacs_waste_collection_schedule
    
# Nächste Leerung    
  - platform: waste_collection_schedule
    name: Nächste Leerung
    details_format: upcoming
    value_template: '{{value.types|join(", ")}} {% if value.daysTo == 0 %}heute{% elif value.daysTo == 1 %}morgen{% else %}in {{value.daysTo}} Tagen{% endif %} ({{value.date.strftime("%d.%m.%y")}})'   
    count: 4
    date_template: '{{value.date.strftime("%d.%m.%y")}}'
    
 # Nächste Biomüll-Leerung   
  - platform: waste_collection_schedule
    name: Biomüll
    details_format: upcoming
    value_template: '{% if value.daysTo == 0 %}heute{% elif value.daysTo == 1 %}morgen{% else %}in {{value.daysTo}} Tagen{% endif %} ({{value.date.strftime("%d.%m.%y")}})'
    count: 1
    types:
      - Bio Tonne
    
 # Nächste Gelbe Tonne   
  - platform: waste_collection_schedule
    name: Gelbe Tonne
    details_format: upcoming
    value_template: '{% if value.daysTo == 0 %}heute{% elif value.daysTo == 1 %}morgen{% else %}in {{value.daysTo}} Tagen{% endif %} ({{value.date.strftime("%d.%m.%y")}})'    
    count: 1
    types:
      - Gelbe Tonne
     
 # Nächste Papier-Leerung   
  - platform: waste_collection_schedule
    name: Papier
    details_format: upcoming
    value_template: '{% if value.daysTo == 0 %}heute{% elif value.daysTo == 1 %}morgen{% else %}in {{value.daysTo}} Tagen{% endif %} ({{value.date.strftime("%d.%m.%y")}})'    
    count: 1
    types:
      - Papier

 # Nächster Restmüll   
  - platform: waste_collection_schedule
    name: Restmüll
    details_format: upcoming
    value_template: '{% if value.daysTo == 0 %}heute{% elif value.daysTo == 1 %}morgen{% else %}in {{value.daysTo}} Tagen{% endif %} ({{value.date.strftime("%d.%m.%y")}})'    
    count: 1
    types:
      - Restmüll

waste_collection_schedule:
  sources:
    - name: muellmax_de
      args:
        service: His
        mm_frm_str_sel: <my_street>
      customize:
        - type: HIS Restmüll, wöchentliche Abfuhr
          show: no
        - type: HIS Restmüll, 2-wöchentliche Abfuhr
          alias: Restmüll
        - type: HIS Papier
          alias: Papier
        - type: HIS GS/Leichtverpackungen
          alias: Gelbe Tonne
        - type: HIS Biomüll
          alias: Bio Tonne
# Ende Müllabfuhr
#--------------------------
```
![grafik](https://user-images.githubusercontent.com/5453201/108730393-c723fc80-752b-11eb-9cbb-24b05bf26be4.png)
![grafik](https://user-images.githubusercontent.com/5453201/108730463-d86d0900-752b-11eb-9f4a-3ffa4de517b6.png)

As this ticket is solved, I will close it.
