### ISSUE TITLE
[Bug]: cherwell_gov_uk "The source returned an empty response"

### ISSUE THREAD

**Issue by RedNo7** [mampfes/hacs_waste_collection_schedule#3119]
### I Have A Problem With:

A specific source

### What's Your Problem

Hi,
This was working perfectly but stopped a couple of days ago..

- I had it configured  in yaml and tried the UI which gave me the response:
"The source returned an empty response"
![Screenshot 2024-11-30 at 10 35 47](https://github.com/user-attachments/assets/48fd2f2a-2287-4882-8e9c-fd9c304d6535)
I removed my UPRN for privacy but it was the right one:

- Settings ➜ actions: `action: waste_collection_schedule.fetch_data` makes no difference
- restarting made no difference
- If I go online, I can see the data from the CDC website (using my UPRN).
https://www.cherwell.gov.uk/homepage/129/bin-collection-search?uprn=<11-digit-UPRN>
![Screenshot 2024-11-30 at 10 42 29](https://github.com/user-attachments/assets/4b6c2676-6ae6-4e3a-ae46-e34c6af14f47)

### Source (if relevant)

cherwell_gov_uk

### Logs

```Shell
no errors
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: cherwell_gov_uk
      args:
        uprn: !secret uprn
      customize:
        - type: "Blue Bin"
          alias: Blue
        - type: "Brown Bin"
          alias: Brown
        - type: "Green Bin"
          alias: Green
      calendar_title: CDC waste collection
  day_switch_time: "23:00"
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by frostaholic** [comment]
I am getting the same error. I get unknown manually setup. (working before) then The source returned an empty response through the UI

**Comment by RedNo7** [comment]
I’m scraping the website myself now if you want the yaml to do it?

**Comment by frostaholic** [comment]
oh yes pls, that would be great

**Comment by ReneNulschDE** [comment]
Could you share a UPRN? I just tested the testcase 100120758315 - and this is working without any error.

**Comment by frostaholic** [comment]
100120791546

**Comment by RedNo7** [comment]
> oh yes pls, that would be great

In the interim, as I would prefer this HACS to work, here is my package that scrapes.  It created a bunch of binary sensors for the day before (put on the bin the night before) the day itself (bring in the bin after collection) and which bins are next.  bin_3 never has a next.

Because it scrapes the website and the bins change positions there (soonest is always first), the sensors are `sensor.bin_x_colour` tells you which one is which. 

I then display the bins in the same order as on the website (so soonest first) and use these sensors to tell me the the colour, date and highlight if it is today, tomorrow etc..  I will share one of those in a short while.

```yaml
scrape:
  - resource:  !secret cdc
    scan_interval: 86400 # 24+60+60 secs # default is 600
    sensor:
      - name: "Bin 1 date"
        icon: mdi:delete
        select: "#content > div:nth-child(1) > div > div > div > div > div > ul > li:nth-child(1) > div > div > p.bin-collection-tasks__date"
        value_template: '{{ value }}'
      - name: "Bin 1 colour"
        icon: mdi:delete
        select: "#content > div:nth-child(1) > div > div > div > div > div > ul > li:nth-child(1) > div > h3"
        value_template: "{{ value|regex_findall_index(find='Green|Blue|Brown',index=0) }}"
      - name: "Bin 2 date"
        icon: mdi:delete
        select: "#content > div:nth-child(1) > div > div > div > div > div > ul > li:nth-child(2) > div > div > p.bin-collection-tasks__date"
        value_template: '{{ value }}'
      - name: "Bin 2 colour"
        icon: mdi:delete
        select: "#content > div:nth-child(1) > div > div > div > div > div > ul > li:nth-child(2) > div > h3"
        value_template: "{{ value|regex_findall_index(find='Green|Blue|Brown',index=0) }}"
      - name: "Bin 3 date"
        icon: mdi:delete
        select: "#content > div:nth-child(1) > div > div > div > div > div > ul > li:nth-child(3) > div > div > p.bin-collection-tasks__date"
        value_template: '{{ value }}'
      - name: "Bin 3 colour"
        icon: mdi:delete
        select: "#content > div:nth-child(1) > div > div > div > div > div > ul > li:nth-child(3) > div > h3"
        value_template: "{{ value|regex_findall_index(find='Green|Blue|Brown',index=0) }}"

template: #---------------------------------------------------------------------
  - binary_sensor:
      # today
      - name: "bin 1 day"
        state: >
          {% set day = states('sensor.bin_1_date').split('t')[0] %}
          {% set today = now().day|regex_replace(find='^0+', replace='') %}
          {{ day == today }}
      - name: "bin 2 day"
        state: >
          {% set day = states('sensor.bin_2_date').split('t')[0] %}
          {% set today = now().day|regex_replace(find='^0+', replace='') %}
          {{ day == today }}
      # tomorrow
      - name: "bin 1 tomorrow"
        state: >
          {% set day = states('sensor.bin_1_date').split('t')[0] %}
          {% set tomorrow = (now()+timedelta(hours = 24)).strftime('%d')|regex_replace(find='^0+', replace='') %}
          {{ day == tomorrow }}
      - name: "bin 2 tomorrow"
        state: >
          {% set day = states('sensor.bin_2_date').split('t')[0] %}
          {% set tomorrow = (now()+timedelta(hours = 24)).strftime('%d')|regex_replace(find='^0+', replace='') %}
          {{ day == tomorrow }}
      # next
      - name: "bin 1 next"
        state: >
          {% set date = states('sensor.bin_1_date').split('t')[0]|round(0) %}
          {% set t  = now().strftime('%d')|regex_replace(find='^0+', replace='')|int() %}
          {% set t2 = (now()+timedelta(hours = 24)).strftime('%d')|regex_replace(find='^0+', replace='')|int() %}
          {% set t3 = (now()+timedelta(hours = 48)).strftime('%d')|regex_replace(find='^0+', replace='')|int() %}
          {% set t4 = (now()+timedelta(hours = 72)).strftime('%d')|regex_replace(find='^0+', replace='')|int() %}
          {% set t5 = (now()+timedelta(hours = 96)).strftime('%d')|regex_replace(find='^0+', replace='')|int() %}
          {% set t6 = (now()+timedelta(hours = 120)).strftime('%d')|regex_replace(find='^0+', replace='')|int() %}
          {{ date in [t,t2,t3,t4,t5,t6]}}
      - name: "bin 2 next"
        state: >
          {% set date = states('sensor.bin_2_date').split('t')[0]|round(0) %}
          {% set t  = now().strftime('%d')|regex_replace(find='^0+', replace='')|int() %}
          {% set t2 = (now()+timedelta(hours = 24)).strftime('%d')|regex_replace(find='^0+', replace='')|int() %}
          {% set t3 = (now()+timedelta(hours = 48)).strftime('%d')|regex_replace(find='^0+', replace='')|int() %}
          {% set t4 = (now()+timedelta(hours = 72)).strftime('%d')|regex_replace(find='^0+', replace='')|int() %}
          {% set t5 = (now()+timedelta(hours = 96)).strftime('%d')|regex_replace(find='^0+', replace='')|int() %}
          {% set t6 = (now()+timedelta(hours = 120)).strftime('%d')|regex_replace(find='^0+', replace='')|int() %}
          {{ date in [t,t2,t3,t4,t5,t6]}}
```
