### ISSUE TITLE
Sensor for static source not working

### ISSUE THREAD

**Issue by Lampone** [mampfes/hacs_waste_collection_schedule#313]
I upgrade my installation to master and tried to add a static source, but the sensor for the static source only shows  `unknown` as the current state.
The calendar is showing the dates correctly. 

Do I have to do anything special with the sensor?

```YAML
waste_collection_schedule:
  sources:
   # removed other sources
    - name: static
      args:
        type: Papier
        frequency: WEEKLY
        interval: 4
        start: '2022-01-12'
        until: '2022-12-31'
```

```YAML
sensor:
  # removed other sensors
  - platform: waste_collection_schedule
    name: muell_papier
    details_format: "upcoming"
    value_template:  '{{ value.daysTo }}'
    types:
      - Papier
```
