### ISSUE TITLE
[Bug]: stpoeltenland.umweltverbaende.at stopped working

### ISSUE THREAD

**Issue by ThomasMeyer1970** [mampfes/hacs_waste_collection_schedule#3145]
### I Have A Problem With:

A specific source

### What's Your Problem

stpoeltenland.umweltverbaende.at stopped working

### Source (if relevant)

stpoeltenland.umweltverbaende.at

### Logs

```Shell
no log !!!
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: "stpoeltenland" # Sankt Pölten Land
        municipal: "Kirchstetten" # Kirchstetten
      customize:
        - type: "Einpersonenhaushalt: Restmüll"
          show: False
        - type: "Mehrpersonenhaushalt: Restmüll"
          alias: "Restmüll"
      calendar_title: "Müllkalender"

sensor:
  - platform: waste_collection_schedule
    name: Biotonne
    details_format: appointment_types
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    add_days_to: true 
    types:
      - Biotonne
  
  - platform: waste_collection_schedule
    name: Restmüll
    details_format: appointment_types
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    add_days_to: true 
    types:
      - Restmüll    
      
  - platform: waste_collection_schedule
    name: Nächste Abholung
    details_format: upcoming
    event_index: 0
    value_template: '{{value.daysTo}}'
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
