### ISSUE TITLE
[Bug]: fetch failed for source Abfallwirtschaftsbetrieb Esslingen

### ISSUE THREAD

**Issue by Timsche2210** [mampfes/hacs_waste_collection_schedule#3153]
### I Have A Problem With:

A specific source

### What's Your Problem

no update from soure AWB Esslingen

### Source (if relevant)

awb-es.de

### Logs

```Shell
Dieser Fehler stammt von einer Sonder-Integration

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 08:39:04 (1 Vorkommnisse)
Zuletzt protokolliert: 08:39:04

fetch failed for source Abfallwirtschaftsbetrieb Esslingen: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/awb_es_de.py", line 47, in fetch raise Exception("ics url not found") Exception: ics url not found
```

### Relevant Configuration

```YAML
code from config.yaml:

# Waste_collection_schedule source configuration
# Konfiguration unter Sensor-Folder
waste_collection_schedule:
    sources:
    - name: awb_es_de
      args:
        city: Filderstadt
        street: XXX (correct street name tested at homepage)
      customize:
      - type: Gelbe/r Sack/Tonne
        #picture: https://forms.cherwell.gov.uk/images/bin-collections/bin-collection-green.svg
        alias: "Gelber Sack"
      - type: Restmüll 4-wöchentlich
        #picture: https://forms.cherwell.gov.uk/images/bin-collections/bin-collection-green.svg
        alias: "Restmüll (4)"


Tested to integrate it with integrations and get the failure:
Die Quelle hat eine ungültige Antwort zurückgegeben: "ics url not found". Bitte überprüfe die Argumente und versuche es erneut.
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
