### ISSUE TITLE
[Bug]: Only one Week is diplayed / pulled from provider in calender

### ISSUE THREAD

**Issue by Metalingus93** [mampfes/hacs_waste_collection_schedule#3164]
### I Have A Problem With:

A specific source

### What's Your Problem

I managed to install and integrate my schedule for my City with python script "muellmax_de.py".
I get an entity, it seems to work in general but in my Calender the Schedule is only displayed for one week (see pictures for December and January.)
Not sure if there is missing data from the provider or a "just" a displaying issue.

(Sorry I am new to GitHub. If need more information, i am happy to provide anything you need to fix.)
![Dec](https://github.com/user-attachments/assets/f7ca1f55-ec7d-4ed8-9fb7-63f845b7a3b7)
![Jan](https://github.com/user-attachments/assets/560724a3-26b7-456d-a0ae-0006cafe05ac)

### Source (if relevant)

not relevant

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
# waste_collection_schedule source configuration
waste_collection_schedule:
  sources:
    - name: muellmax_de
      args:
        service: Ash
        mm_frm_str_sel: *****straße
        mm_frm_hnr_sel: 59077;Herringen;**;
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
