### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by MarWilpw** [mampfes/hacs_waste_collection_schedule#3168]
### Municipality / Region

Porta Westfalica

### Collection Calendar Webpage

https://www.portawestfalica.de/rathaus/verwaltung/baubetriebshof/abfall/abfall-navi/

### Example Address

Portastr , Porta Westfalica

### Collection Data Format

As ICS/ICAL file

**Comment by DanielL-80** [comment]
Hi - is this one working yet? I need it, too :-)

**Comment by fakerli** [comment]
Any updates @mampfes ?

**Comment by bbr111** [comment]
https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfallnavi_de.md

try abfallnavi

**Comment by markvp** [comment]
Thanks for the report — and good call from @bbr111 pointing at `abfallnavi_de`.

Porta Westfalica uses the regioit.de / AbfallNavi platform (the Abfall-Navi page embeds `https://abfallnavi.de/portawestfalica/`). The service ID `portawestfalica` is confirmed working against the live API. The entry just needs to be added to the shared service list, and a PR is now open to do that: https://github.com/mampfes/hacs_waste_collection_schedule/pull/6546

In the meantime you can already use it by configuring `abfallnavi_de` manually:

```yaml
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: portawestfalica
        ort: Porta Westfalica
        strasse: Portastraße   # adjust to your street
```
