### ISSUE TITLE
[Bug]: no entities available

### ISSUE THREAD

**Issue by DanielStockinger** [mampfes/hacs_waste_collection_schedule#3174]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

if no entities are available, because end of year, (source entities are only for one year)

configuration:
```
sources:
  - name: data_umweltprofis_at
    args:
      xmlurl: https://data.umweltprofis.at/opendata/AppointmentService/AppointmentService.asmx/GetTermineForLocationSecured?Key=TEMPKeyabvvMKVCic0cMcmsTEMPKey&StreetNr=102161&HouseNr=Alle&intervall=Alle
```

sensor configuration:
```
platform: waste_collection_schedule
name: "PapierNEU"
value_template: >
  {% if value is not defined or value == 'unknown' or value is none  %}
    Keine Abholung
  {% elif value.daysTo == 0 %}
    Heute
  {% elif value.daysTo == 1 %}
    Morgen
  {% else %}
    in {{ value.daysTo }} Tagen
  {% endif %}
types:
  - Papiertonne
```

i get status unknown
![image](https://github.com/user-attachments/assets/edc0d6b6-845c-4ab8-a4c4-19548a754953)

please add possibility to add fallback value if no entities are available.

Many Thanks

### Source (if relevant)

https://data.umweltprofis.at/opendata/AppointmentService/AppointmentService.asmx/GetTermineForLocationSecured?Key=TEMPKeyabvvMKVCic0cMcmsTEMPKey&StreetNr=102161&HouseNr=Alle&intervall=Alle

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
