### ISSUE TITLE
[Bug]: fetch failed for source Southampton City Council

### ISSUE THREAD

**Issue by hen-hick** [mampfes/hacs_waste_collection_schedule#3175]
### I Have A Problem With:

A specific source

### What's Your Problem

Southampton City Council (United Kingdom) now fails to fetch information from source. Been running the same configuration for over 2 years. Log provided below.

### Source (if relevant)

https://www.southampton.gov.uk/bins-recycling/bins/collections/

### Logs

```Shell
This error originated from a custom integration.

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
integration: Waste Collection Schedule (documentation)
First occurred: 03:01:29 (1 occurrences)
Last logged: 03:01:29

fetch failed for source Southampton City Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/southampton_gov_uk.py", line 42, in fetch calendar_view_only = re.search( ~~~~~~~~~~ r"#calendar1.*?listView", r.text, flags=re.DOTALL ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ )[0] ~^^^ TypeError: 'NoneType' object is not subscriptable
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: southampton_gov_uk
      args:
        uprn: "100062XXXXXX"    #uprn is for Flat 1 to include garden waste
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by GraemeDBlue** [comment]
came here to say the same thing

**Comment by hen-hick** [comment]
@dt215git I can see you originally created the Southampton council source code. Hope you may be able to help.

**Comment by dt215git** [comment]
Looks like the site has changed - the script will probably need to be reworked.
However, they now seem to offer an iCal download option, so that might be an easier alternative.

Using one of the test case URPN,  this seems to work:

```yaml
sources:
  - name: ics
    args:
      url: https://www.southampton.gov.uk/whereilive/waste-calendar?UPRN=100060731893
      method: POST
      params:
        ddlReminder: "0"
        btniCal: ""
        ufprt: "24033739E3B08743611951828AA6B7D0651D837AA74C482DAB2CD1218FB5C46E8E967B1982BDCDAAEB1D1219BB9C06FE44A66B568FF0199F2D7BDC1ACFD09F8F3E7F346CC3A2E241B5B25C136B619DF413BD476C61A874521090968A6A4D0FE2238B3B4C36E4D66D0A7649E35A4C95E55FD52953E1FFB060E9753F0EF814FD4995856A00A1C2031D7AB5EAF343B57268A6B787D3EF36D1AC62B47C9A5513A476D35B93A46AD94EDAFE7AE0E55A753E40"
```
![image](https://github.com/user-attachments/assets/0ef317bf-106f-43d9-a540-a76ff391a324)


You'll need to change the _UPRN_ number, but you needed that for the original script so should already have it. Guess we'll need to see if the _ufprt_ text is a constant, or changes over time.
