### ISSUE TITLE
Feature request: Make sensors config part of waste_collection_schedule

### ISSUE THREAD

**Issue by Sirs0ri** [mampfes/hacs_waste_collection_schedule#318]
Hi, would it be possible to move the sensor config in my homeassistant yaml file from the `sensor:` scope to the `waste_collection_schedule:` scope, similar to how for example the [rest platform](https://www.home-assistant.io/integrations/rest/) is set up?

ie, something like this:
```yaml
waste_collection_schedule:
  # "sources" remains unchanged:
  sources:
    - name: abfall_io
      args:
        # key, f_id_kommune, f_id_bezirk, f_id_strasse...
        f_abfallarten:
          - 17 # Recycling
  # this is new inside the waste_collection_schedule namespace:
  sensor:
    - name: Recycling
      count: 3
      value_template: '{{ value.date.strftime("%d.%m.%Y") }}'
      date_template: '{{ value.date.strftime("%a, %d.%m.%Y") }}'
      add_days_to: true
      types:
        - Recycling

# this would be no longer necessary:
sensor:
  - platform: waste_collection_schedule
    name: Recycling
    # Rest of the config...
```

It would make the YAML a bit easier to read since the config would no longer be partially in the `waste_collection_schedule:` namespace, and also part of `sensor:`

Thanks for considering!
