### ISSUE TITLE
[Bug]: Source "Abfallwirtschaft Neckar-Odenwald-Kreis" not working

### ISSUE THREAD

**Issue by Bomber-G** [mampfes/hacs_waste_collection_schedule#3181]
### I Have A Problem With:

A specific source

### What's Your Problem

The source "Abfallwirtschaft Neckar-Odenwald-Kreis" is not woring since the beginning of december

### Source (if relevant)

awn_de

### Logs

```Shell
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 08:10:29 (1 Vorkommnisse)
Zuletzt protokolliert: 08:10:29

fetch failed for source Abfallwirtschaft Neckar-Odenwald-Kreis: Traceback (most recent call last): File "/usr/local/lib/python3.13/site-packages/icalendar/parser.py", line 339, in parts validate_token(name) ~~~~~~~~~~~~~~^^^^^^ File "/usr/local/lib/python3.13/site-packages/icalendar/parser.py", line 128, in validate_token raise ValueError(name) ValueError: <!DOCTYPE HTML><HTML lang="de-DE"> During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/awn_de.py", line 133, in fetch dates = self._ics.convert(r.text) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert events: List[Any] = icalevents.events( ~~~~~~~~~~~~~~~~~^ start=start_date, end=end_date, string_content=ics_data.encode() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.13/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ~~~~~~~~~~~~^ content, start=start, end=end, tzinfo=tzinfo, sort=sort, strict=strict ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.13/site-packages/icalevents/icalparser.py", line 299, in parse_events calendar = Calendar.from_ical(content) File "/usr/local/lib/python3.13/site-packages/icalendar/cal.py", line 331, in from_ical name, params, vals = line.parts() ~~~~~~~~~~^^ File "/usr/local/lib/python3.13/site-packages/icalendar/parser.py", line 353, in parts raise ValueError( f"Content line could not be parsed into parts: '{self}': {exc}") ValueError: Content line could not be parsed into parts: '<!DOCTYPE HTML><HTML lang="de-DE"> ': <!DOCTYPE HTML><HTML lang="de-DE">
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: awn_de
      args:
        city: "Hardheim"
        street: "Gerleinsstr."
        house_number: 9
        address_suffix: ""
      customize:
        - type: Restmuell
          alias: Restmüll
          icon: mdi:trash-can
        - type: Verpackungstonne
          alias: Gelbe Tonne
          icon: mdi:trash-can
        - type: Altpapier, Papiertonne
          alias: Papiertonne
          icon: mdi:trash-can
        - type: Bioenergietonne
          alias: Biotonne
          icon: mdi:trash-can
        - type: Schadstoffe
          alias: Schadstoffe
          icon: mdi:trash-can
        - type: Altkleider/Schuhe
          alias: Altkleider/Schuhe
          icon: mdi:trash-can
  fetch_time: "04:00"
  day_switch_time: "10:00"
  separator: ","
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
