### ISSUE TITLE
[Bug]: GFA Lüneburg only shows dates for 2025 but there are still collections in 2024

### ISSUE THREAD

**Issue by meiersmarkus** [mampfes/hacs_waste_collection_schedule#3185]
### I Have A Problem With:

A specific source

### What's Your Problem

Automation:
```
alias: Müllabholung prüfen
description: Ruft die nächsten Müllabholungen ab und speichert sie in einer Variablen
triggers:
  - at: "06:00:00"
    trigger: time
actions:
  - target:
      entity_id: calendar.gfa_luneburg
    data:
      duration:
        hours: 0
        minutes: 0
        seconds: 0
    response_variable: muell_events
    action: calendar.get_events
mode: single
```

I added the blue dates manually, but that doesn't solve the problem. The calendar, which is filled by the extension, unfortunately only has the dates for 2025 onwards.
<img width="2025" alt="image" src="https://github.com/user-attachments/assets/d2233c8d-ad82-422c-b3bd-00e2500af712" />
On the GFA website, you can actually choose between 2024 and 2025. Could both years be loaded?
<img width="597" alt="image" src="https://github.com/user-attachments/assets/0c9bcc5f-61c3-4076-b3c7-120a809a79ca" />

### Source (if relevant)

gfa_lueneburg_de

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
