### ISSUE TITLE
[Bug]: Source "AWIGO Abfallwirtschaft Landkreis Osnabrück GmbH" not working

### ISSUE THREAD

**Issue by UR-86** [mampfes/hacs_waste_collection_schedule#3189]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

The sensors only provide a value every few days. As a rule, the sensor values are only available for a maximum of 1 day. The sensors are not updated for the next 2-3 days and therefore do not provide any values. 
However, the whole thing worked perfectly in an earlier version. Unfortunately, I can't say from which version the retrieval of sensor data stopped working.

### Source (if relevant)

awigo_de

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: awigo_de
      args:
        ort: Merzen
        strasse: Alte Heerstr.
        hnr: 15

sensor:
  # ------- Garbage Collectiion --------
  # next collection
  - platform: waste_collection_schedule
    name: "Nächste Leerung"
    details_format: "upcoming"
    value_template: '{{value.types|join(",")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} {{value.date.strftime("%A")}}, {{value.date.strftime("%d.%m.%Y")}}{% endif %}'
    add_days_to: True

  # Nächste Abholung Papiermülltonne
  - platform: waste_collection_schedule
    name: "Papiermülltonne"
    details_format: "upcoming"
    value_template: "{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} {{value.daysTo}} Tage{% endif %}"
    add_days_to: True
    types:
      - Papiermülltonne

  # Nächste Abholung Gelbe Tonne
  - platform: waste_collection_schedule
    name: "Gelbe Tonne"
    details_format: "upcoming"
    value_template: "{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} {{value.daysTo}} Tage{% endif %}"
    add_days_to: True
    types:
      - Gelbe Tonne/Gelben Sack

  # Nächste Abholung Bio-Tonne
  - platform: waste_collection_schedule
    name: "Bio-Tonne"
    details_format: "upcoming"
    value_template: "{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} {{value.daysTo}} Tage{% endif %}"
    add_days_to: True
    types:
      - Bio-Tonne

  # Nächste Abholung Restmüll
  - platform: waste_collection_schedule
    name: "Restmüll"
    details_format: "upcoming"
    value_template: "{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} {{value.daysTo}} Tage{% endif %}"
    add_days_to: True
    types:
      - Restmülltonne
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
