### ISSUE TITLE
[Source Request]: Güstrow, Germany

### ISSUE THREAD

**Issue by Ole01** [mampfes/hacs_waste_collection_schedule#3207]
### Municipality / Region

Güstrow, Germany

### Collection Calendar Webpage

https://www.abfall-lro.de/de/abfuhrtermine/guestrow.php

### Example Address

Bredentiner Weg 1, 18273 Güstrow

### Collection Data Format

As ICS/ICAL file

### Additional Information

It is actually the same source as in the district of Rostock (https://github.com/mampfes/hacs_waste_collection_schedule/issues/2700) but the town of Güstrow is subdivided into different streets. You cannot select “Güstrow” under the source “Landkreis Rostock”.

**Comment by bbr111** [comment]
Thanks for the report! This has already been resolved — the `abfall_lro_de` source now supports Güstrow's street-level lookup (added in #5867). You can configure it like this:

```yaml
waste_collection_schedule:
    sources:
    - name: abfall_lro_de
      args:
        municipality: Güstrow
        street: Werlestraße
        black_rhythm: "2w"
        green_rhythm: "2w"
```

I just re-ran the live test for Güstrow and confirmed it returns current, correct collection data. Closing as already implemented — please reopen (or file a new issue) if you run into any trouble configuring it for your specific street.
