### ISSUE TITLE
[Bug]: Burnley Council returning empty

### ISSUE THREAD

**Issue by ThatDeltaGuy** [mampfes/hacs_waste_collection_schedule#3212]
### I Have A Problem With:

A specific source

### What's Your Problem

Burnley Council has stopped working, it's now returning “The source returned an empty response. Please check the provided arguments and try again.” 

### Source (if relevant)

burnley_gov_uk

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: burnley_gov_uk
      args:
        uprn: UNIQUE_PROPERTY_REFERENCE_NUMBER

Also tried the gui way
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
