### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by Klicker15** [mampfes/hacs_waste_collection_schedule#3214]
### Municipality / Region

Gescher Deutschland

### Collection Calendar Webpage

https://www.egw.de/service/abfallberatung/abfall-app-im-web/

### Collection Data Format

As ICS/ICAL file

**Comment by markvp** [comment]
Thanks for the request! Great news — Gescher / EGW Westmünsterland is already supported via the **AbfallNavi (RegioIT.de)** source.

**Setup:**

```yaml
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: wml2
        ort: Gescher
        strasse: <your street name>
        hausnummer: <your house number>   # optional
```

You can find the full list of supported parameters in the [abfallnavi_de documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfallnavi_de.md).

Closing as already supported.
