### ISSUE TITLE
[Source Request]: Glashütten Taunus via Mymüll

### ISSUE THREAD

**Issue by jastBytes** [mampfes/hacs_waste_collection_schedule#3216]

**Comment by markvp** [comment]
Thanks for the report! Glashütten Taunus is supported by the existing `jumomind_de` source via the `mymuell` service. I've added it to the provider list in a PR — once merged it will be discoverable through the UI.

In the meantime you can already use it with:

```yaml
waste_collection_schedule:
  sources:
    - name: jumomind_de
      args:
        service_id: mymuell
        city: Glashütten
        street: YOUR_STREET
```

See the [jumomind_de docs](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/jumomind_de.md) for full configuration options.
