### ISSUE TITLE
Local .ics Source displayed in the calendar, but sensor does not work

### ISSUE THREAD

**Issue by masyfil** [mampfes/hacs_waste_collection_schedule#323]
Hi, i have a strange bug/issue... i use two sources in [waste_collection_schedule](https://github.com/mampfes/hacs_waste_collection_schedule). The first one is a URL Source and work perfect for me. The second one is a local .ics File.
The Calender show both sources. But the sensor "AbfallBlau" from the local .ics only show the status "unknown".

The ics File is from https://www.blauetonne-schlauetonne.de/

kraichtal_blauetonne.ics:
```
...
SUMMARY:Leerung der Blauen Tonne Schlauen Tonne
...
```

config.yaml:
```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: "www/kraichtal_blauetonne.ics"
      customize:
        - type: Leerung der Blauen Tonne Schlauen Tonne
          alias: Blauetonne
          icon: mdi:delete-variant
      calendar_title: "Blauetonne"
  fetch_time: "04:00"
  day_switch_time: "10:00"

```
sensor.yaml:
```
- platform: waste_collection_schedule
    name: AbfallBlau
    details_format: "upcoming"
    value_template: '{{ value.daysTo }}'
    types:
        - Blauetonne
```

Maybe someone has an idea?!
Thanks!

**Comment by mampfes** [comment]
Set the `source_index `attribute for the 2nd sensor of the second source (see documentation for details).

**Comment by masyfil** [comment]
> Set the `source_index `attribute for the 2nd sensor of the second source (see documentation for details).

Thank you so much!

**Comment by renarena** [comment]
i have the problem too. I have only one source and it stopped working anywhere back.
I think there was a breaking change in the past but i cannot find it now.
I have events in calendar, Buttoncard is working, but all other sensors say unknown.

```
waste_collection_schedule: 
  sources:
    - name: ics
      args:
        file: "www/Abfallkalender.ics"
        offset: 0

      customize:
      - type: Restmüll
        alias: schwarze Tonne
        show: True
```

from ics:
```
BEGIN:VEVENT
UID:20220826T0000002@62.116.171.148
DTSTAMP:20220826T010100Z
CLASS:PUBLIC
DTSTART;VALUE=DATE:20220826
SUMMARY:Restmüll
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:Restmüll
TRIGGER:-P1D
END:VALARM
END:VEVENT
```
and in sensor:
```
- platform: waste_collection_schedule
  source_index: 0
  name: waste_collection_Restmüll
  value_template: '{{value.types|join(" + ")}} in {{value.daysTo}} Tagen'
  date_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
    - Restmüll
```
