### ISSUE TITLE
4563 Micheldorf in OÖ Austria

### ISSUE THREAD

**Issue by aichingerk** [mampfes/hacs_waste_collection_schedule#3230]
### Municipality / Region

Micheldorf, Austria

### Collection Calendar Webpage

https://www.micheldorf.at/system/web/

### Example Address

Altpapier Micheldorf Ost

### Collection Data Format

As PDF Download

### Additional Information

it is an request from the webside e.g. 2023
![image](https://github.com/user-attachments/assets/e35bc22f-cf01-4c42-8ed0-cc5519c8046a)
e.g. 2025
![image](https://github.com/user-attachments/assets/c28f5751-4dab-4567-80b8-d5162b81a17f)

**Comment by bbr111** [comment]
https://www.micheldorf.at/system/web/kalender.aspx?sprache=1&menuonr=227975509&typids=227693817,227693820

**Comment by bbr111** [comment]
Thanks for the report, @aichingerk! And thanks @bbr111 for the helpful calendar URL.

This turned out not to be PDF-only after all. The `micheldorf.at` site runs the Austrian **RiSKommunal** CMS (same platform as Schärding, Piberbach, Fritzens, etc.), which exposes the schedule as a structured HTML table at `/system/web/kalender.aspx`.

I've implemented a new source `micheldorf_at` that resolves your street and house number to the correct collection zone. A PR has been opened: https://github.com/mampfes/hacs_waste_collection_schedule/pull/6677

Once merged you can configure it in Home Assistant like this:

```yaml
waste_collection_schedule:
  sources:
    - name: micheldorf_at
      args:
        strasse: "Adalbert-Stifter-Straße"   # your street name
        hausnummer: "1"                        # your house number
```

Open https://www.micheldorf.at/system/web/kalender.aspx?sprache=1&menuonr=227975509 to find your exact street and house number values from the dropdowns.
