### ISSUE TITLE
[Source Request]: Jerichower Land

### ISSUE THREAD

**Issue by Panthaera** [mampfes/hacs_waste_collection_schedule#3238]
### Municipality / Region

Genthin

### Collection Calendar Webpage

https://www.ajl-mbh.de/abfallkalender

### Example Address

ex. Friedenstraße 1, 39307 Genthin

### Collection Data Format

As html on a webpage

**Comment by bbr111** [comment]
https://www.ajl-mbh.de/abfallkalender/entsorgungstermine

**Comment by bbr111** [comment]
This is already supported. The AJL - Abfallwirtschaftsgesellschaft Jerichower Land mbH provider was implemented in #6529 (source `ajl_mbh_de`), which covers all towns in the Jerichower Land district, including Genthin.

Example configuration for Genthin (Genthin requires a street selection since it has multiple collection zones):

```yaml
waste_collection_schedule:
    sources:
    - name: ajl_mbh_de
      args:
        town: Genthin
        street: YOUR_STREET_NAME
```

See `doc/source/ajl_mbh_de.md` for full setup instructions. Closing as resolved — please reopen or comment if you run into any issues configuring it.
