### ISSUE TITLE
Wolfsburger Abfallwirtschaft und Straßenreinigung doesn't work anymore

### ISSUE THREAD

**Issue by standbrot** [mampfes/hacs_waste_collection_schedule#3242]
### Municipality / Region

Wolfsburg, Germany

### Collection Calendar Webpage

https://was-wolfsburg.de/ or https://abfuhrtermine.waswob.de/

### Example Address

City: Barnstorf
Street: Bahnhofspassage

### Collection Data Format

As html on a webpage

### Additional Information

Wolfsburg updated the way to search for your waste dates. It used the city or district (for paper, organic waste and residual waste) and the street (for plastic).
But since the update they are forwarding you to another domain were only the street ist used.

**Comment by standbrot** [comment]
I'm not a Programmer.
I just tinkerd around. To be honest i asked ChatGPT5 to help. After some try and error "we" came up with this code. It seems like it works fine.
Here the Code:

```
from datetime import date, datetime
import requests
from bs4 import BeautifulSoup, Tag
from waste_collection_schedule import Collection  # type: ignore[attr-defined]

TITLE = "Wolfsburger Abfallwirtschaft und Straßenreinigung"
DESCRIPTION = "Source for waste collections for WAS-Wolfsburg, Germany."
URL = "https://waswob.de"  # Neue URL
TEST_CASES = {
    "Kattowitzer Str.": {"street": "Kattowitzer Str."},
    "Heinrich-Nordhoff-Str.": {"street": "Heinrich-Nordhoff-Str."},
}

ICON_MAP = {
    "Gelber Sack": "mdi:recycle",
    "Bioabfall": "mdi:leaf",
    "Restabfall": "mdi:trash-can",
    "Altpapier": "mdi:file-document-outline",
}


class Source:
    def __init__(self, street: str | None):
        self._street = street
        if street is None:
            raise ValueError("Street must be set")

    def fetch(self) -> list[Collection]:
        """
        Fetch waste collection data for the specified street.
        """
        if not self._street:
            raise ValueError("Street must be provided to fetch data.")

        # URL der JSON-API
        url = f"https://abfuhrtermine.waswob.de/php/abfuhrtermineeingabe.php?k={self._street.replace(' ', '%20')}"

        try:
            # Daten abrufen
            response = requests.get(url)
            response.raise_for_status()  # Fehler prüfen
            data = response.json()  # JSON-Inhalt parsen
        except requests.RequestException as e:
            raise RuntimeError(f"Error fetching data: {e}")
        except ValueError:
            raise RuntimeError("Invalid JSON response from the server.")

        # Ergebnisse verarbeiten
        entries = []
        for entry in data:
            try:
                waste_type = entry.get("waste", "Unbekannt")
                date_str = entry.get("date", "01.01.1970")  # Fallback-Datum
                collection_date = datetime.strptime(date_str, "%d.%m.%Y").date()

                # Icon zuordnen
                icon = ICON_MAP.get(waste_type, "mdi:trash-can")

                # Sammlung hinzufügen
                entries.append(Collection(date=collection_date, t=waste_type, icon=icon))
            except Exception as e:
                print(f"Error processing entry: {entry}, {e}")

        return entries
```

**Comment by Fillip38** [comment]
Hello,

I have the same problem, for 2025 I am currently only shown appointments for the yellow bags...

Where did you change the code?

**Comment by Fillip38** [comment]
Bei mir scheint es nicht so zu funktionieren... Bin wie beschrieben vorgegangen, jedoch erhalte ich keine Daten zu den Abholungen und im Log stehen zwei fehler

`Logger: homeassistant.setup
Quelle: setup.py:497
Erstmals aufgetreten: 13:42:55 (4 Vorkommnisse)
Zuletzt protokolliert: 13:42:55

Unable to prepare setup for platform 'waste_collection_schedule.sensor': Unable to set up component.`

`Logger: homeassistant.setup
Quelle: setup.py:416
Erstmals aufgetreten: 13:42:55 (1 Vorkommnisse)
Zuletzt protokolliert: 13:42:55

Error during setup of component waste_collection_schedule
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/init_yaml.py", line 109, in async_setup
    await hass.async_add_executor_job(
    ...<6 lines>...
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/waste_collection_schedule/waste_collection_api.py", line 88, in add_source_shell
    new_shell = SourceShell.create(
        source_name=source_name,
    ...<3 lines>...
        day_offset=day_offset,
    )
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 232, in create
    source: Fetchable = source_module.Source(**source_args)  # type: ignore
                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: Source.__init__() got an unexpected keyword argument 'city'`

Unter der Integration bekomme ich auch den Hinweis "Nicht geladen" - Habe auch versucht die WAS neu einzunbinden, führt zum selben Ergebnis
![wcs](https://github.com/user-attachments/assets/0e9674f3-069f-4870-b96c-9b8bb46ba980)

**Comment by Fillip38** [comment]
Super danke 👍 Nun läuft es. Hatte zuvor noch Probleme gehabt, da ich von der damaligen Konfiguration noch was in der configuration.yaml stehen hatte, das musste noch gelöscht werden.

Frohes und gesundes Neues Jahr euch! Grüße aus Sülfeld ;-)

**Comment by yoda98mnt** [comment]
Ich hab den Code von standbrot oben genommen. und wie du beschrieben hat eingefügt und neu gestartet.
Bekomme aber folgenden Fehler:
Logger: homeassistant.setup
Quelle: setup.py:497
Erstmals aufgetreten: 17:00:13 (7 Vorkommnisse)
Zuletzt protokolliert: 17:00:13

Unable to prepare setup for platform 'waste_collection_schedule.sensor': Unable to set up component.

bzw. diesen:
Invalid config
The following integrations and platforms could not be set up:

[waste_collection_schedule](https://github.com/mampfes/hacs_waste_collection_schedule#readme) ([Show logs](https://xxxxxxx.cc/config/logs?filter=waste_collection_schedule))
waste_collection_schedule.sensor ([Show logs](https://xxxxxxx.cc/config/logs?filter=waste_collection_schedule.sensor))
Please check your config and [logs](https://xxxxxxxx.cc/config/logs).

Muss am code noch was geändert werden?

**Comment by Fillip38** [comment]
Hast du in der configuration.yaml etwas wegen dem Plugin konfiguriert? Wenn ja, lösch das mal raus, das war mein Fehler. Früher wurde die Integration über die yaml konfiguriert, nun geht das einfach über die GUI.

**Comment by standbrot** [comment]
Hab gar nicht mitbekommen, dass hier leben ist 😅
Aber freut mich, dass es größtenteils funktioniert

**Comment by standbrot** [comment]
Solltest du den Source Code ausgetauscht haben musst du die configuration.yaml Datei noch wie folgt anpassen:

```
waste_collection_schedule:
  sources:
    - name: was_wolfsburg_de
      args:
        street: Deine Straße (So wie sie auf der Website angezeigt wird)
```

**Comment by boehser-enkel** [comment]
> I'm not a Programmer. I just tinkerd around. To be honest i asked ChatGPT5 to help. After some try and error "we" came up with this code. It seems like it works fine. Here the Code:
> 
> ```
> from datetime import date, datetime
> import requests
> from bs4 import BeautifulSoup, Tag
> from waste_collection_schedule import Collection  # type: ignore[attr-defined]
> 
> TITLE = "Wolfsburger Abfallwirtschaft und Straßenreinigung"
> DESCRIPTION = "Source for waste collections for WAS-Wolfsburg, Germany."
> URL = "https://waswob.de"  # Neue URL
> TEST_CASES = {
>     "Dieselstr. Heßlingen": {"street": "Dieselstr. Heßlingen"},
>     "Heinrich-Nordhoff-Str.": {"street": "Heinrich-Nordhoff-Str."},
> }
> 
> ICON_MAP = {
>     "Gelber Sack": "mdi:recycle",
>     "Bioabfall": "mdi:leaf",
>     "Restabfall": "mdi:trash-can",
>     "Altpapier": "mdi:file-document-outline",
> }
> 
> 
> class Source:
>     def __init__(self, street: str | None):
>         self._street = street
>         if street is None:
>             raise ValueError("Street must be set")
> 
>     def fetch(self) -> list[Collection]:
>         """
>         Fetch waste collection data for the specified street.
>         """
>         if not self._street:
>             raise ValueError("Street must be provided to fetch data.")
> 
>         # URL der JSON-API
>         url = f"https://abfuhrtermine.waswob.de/php/abfuhrtermineeingabe.php?k={self._street.replace(' ', '%20')}"
> 
>         try:
>             # Daten abrufen
>             response = requests.get(url)
>             response.raise_for_status()  # Fehler prüfen
>             data = response.json()  # JSON-Inhalt parsen
>         except requests.RequestException as e:
>             raise RuntimeError(f"Error fetching data: {e}")
>         except ValueError:
>             raise RuntimeError("Invalid JSON response from the server.")
> 
>         # Ergebnisse verarbeiten
>         entries = []
>         for entry in data:
>             try:
>                 waste_type = entry.get("waste", "Unbekannt").title()  # Großbuchstaben anwenden
>                 date_str = entry.get("date", "01.01.1970")  # Fallback-Datum
>                 collection_date = datetime.strptime(date_str, "%d.%m.%Y").date()
> 
>                 # Icon zuordnen
>                 icon = ICON_MAP.get(waste_type, "mdi:trash-can")
> 
>                 # Sammlung hinzufügen
>                 entries.append(Collection(date=collection_date, t=waste_type, icon=icon))
>             except Exception as e:
>                 print(f"Error processing entry: {entry}, {e}")
> 
>         return entries
> ```
> 
> Afterwards I had to modify my configuration.yaml
> 
> ```
> waste_collection_schedule:
>   sources:
>     - name: was_wolfsburg_de
>       args:
>         street: your street (as shown on waswob.de)
> ```

Getting this error (wcs is configured via GUI):

```
Logger: homeassistant.config_entries
Quelle: config_entries.py:640
Erstmals aufgetreten: 06:58:35 (2 Vorkommnisse)
Zuletzt protokolliert: 06:59:47

Error setting up entry Wolfsburger Abfallwirtschaft und Straßenreinigung for waste_collection_schedule
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/waste_collection_schedule/init_ui.py", line 46, in async_setup_entry
    shell = await hass.async_add_executor_job(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 232, in create
    source: Fetchable = source_module.Source(**source_args)  # type: ignore
                        ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: Source.__init__() got an unexpected keyword argument 'city'
```

**Comment by standbrot** [comment]
Sieht so aus als würde der Code noch weitere Parameter bekommen. Als nur allein die "street"

**Comment by standbrot** [comment]
Wie ich eingangs ja schon erzählt habe, bin ich ja kein Programmierer und kenne mich demnach absolut gar nicht aus. Ich habe einfach nochmal meine Unterstützung ChatGPT gefragt

Dieser kam nochmal mit einer Änderrung des Codes, welcher weitere Parameter ignoriert sofern diese nicht "street" heißen.
Aber dadurch, dass man ggf sowieso die configuration.yaml anpassen muss (ob es über die GUI auch da gespeichert wird weiß ich nicht) könnte man auch einfach den Parameter "city" raus löschen...

**Ab hier wird es experimentell und ich übernehme keine Haftung für irgendwas. Ich habe diesen Code Teil selber NICHT überprüft/ausporbiert**

Man könnte den Source Teil folgendermaßen ändern, dann sollten alle zusätzlich übergebenen Parameter ignoriert werden

```
class Source:
    def __init__(self, street: str | None, **kwargs):
        self._street = street
        if street is None:
            raise ValueError("Street must be set")
```

**Comment by boehser-enkel** [comment]
> Wie ich eingangs ja schon erzählt habe, bin ich ja kein Programmierer und kenne mich demnach absolut gar nicht aus. Ich habe einfach nochmal meine Unterstützung ChatGPT gefragt
> 
> Dieser kam nochmal mit einer Änderrung des Codes, welcher weitere Parameter ignoriert sofern diese nicht "street" heißen. Aber dadurch, dass man ggf sowieso die configuration.yaml anpassen muss (ob es über die GUI auch da gespeichert wird weiß ich nicht) könnte man auch einfach den Parameter "city" raus löschen...
> 
> **Ab hier wird es experimentell und ich übernehme keine Haftung für irgendwas. Ich habe diesen Code Teil selber NICHT überprüft/ausporbiert**
> 
> Man könnte den Source Teil folgendermaßen ändern, dann sollten alle zusätzlich übergebenen Parameter ignoriert werden
> 
> ```
> class Source:
>     def __init__(self, street: str | None, **kwargs):
>         self._street = street
>         if street is None:
>             raise ValueError("Street must be set")
> ```

Funzt soweit. Über die GUI konnte ich die Angabe des Ortes nicht einfach entfernen

**Comment by Volker2828** [comment]
Also nachdem ich das folgende auskommentiert habe läuft es wieder. Allerdings habe ich keine Werte mehr in den Sensoren,
ich habe die Sensoren mal angehängt, mache ich da einen Fehler?

#waste_collection_schedule:
#  sources:
#    - name: was_wolfsburg_de
#      args:
#        street: strasse

  # ------- Garbage Collection -------
  # next collection
  - platform: waste_collection_schedule
    name: "Nächste Abholung"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
  # Nächste Restmüll-Abholung
  - platform: waste_collection_schedule
    name: "Restmüll"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    types:
      - Restabfall

**Comment by standbrot** [comment]
Die config für die Sensoren sehen bei mir genauso aus 


```
sensor:
    # ------- Garbage Collection ------- 
  # next collection
  - platform: waste_collection_schedule
    name: "Nächste Abholung"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
  # Nächste Restmüll-Abholung
  - platform: waste_collection_schedule
    name: "Restmüll"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    types:
      - Restabfall
  # Nächste Biomüll Abholung
  - platform: waste_collection_schedule
    name: "Biomüll"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    types:
      - Bioabfall
  # Nächste gelber-Sack Abholung
  - platform: waste_collection_schedule
    name: "Gelber Sack"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    types:
      - Gelber Sack
  # Nächste Papiermüll Abholung
  - platform: waste_collection_schedule
    name: "Papier"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    types:
      - Altpapier
```

**Comment by standbrot** [comment]
Die config für die Sensoren sehen bei mir genauso aus 


```
sensor:
    # ------- Garbage Collection ------- 
  # next collection
  - platform: waste_collection_schedule
    name: "Nächste Abholung"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
  # Nächste Restmüll-Abholung
  - platform: waste_collection_schedule
    name: "Restmüll"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    types:
      - Restabfall
  # Nächste Biomüll Abholung
  - platform: waste_collection_schedule
    name: "Biomüll"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    types:
      - Bioabfall
  # Nächste gelber-Sack Abholung
  - platform: waste_collection_schedule
    name: "Gelber Sack"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    types:
      - Gelber Sack
  # Nächste Papiermüll Abholung
  - platform: waste_collection_schedule
    name: "Papier"
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} tagen{% endif %}'
    types:
      - Altpapier
```
