### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by FloraFiat** [mampfes/hacs_waste_collection_schedule#3243]
### Municipality / Region

Cromer, Sydney

### Collection Calendar Webpage

https://www.northernbeaches.nsw.gov.au/services/rubbish-and-recycling/bin-collection-days

### Example Address

24 Howse Cr, Cromer 2099, Sydney, NSW, Australia

### Collection Data Format

As html on a webpage

**Comment by dt215git** [comment]
For that address you get this response from the website:
![image](https://github.com/user-attachments/assets/af776bac-a9d9-4f2f-83b4-25743a999f33)

It doesn't appear to list the different waste types collected on that date  (the pdf suggests it should be Vegetation & Container Recycling), so is just returning the date useful?

**Comment by markvp** [comment]
Thanks for the request — this is now supported! Northern Beaches Council was added in #5708.

To use it, configure the source as follows:

```yaml
waste_collection_schedule:
  sources:
    - name: northernbeaches_nsw_gov_au
      args:
        address: "24 Howse Cr CROMER"
```

The suburb should be uppercase and the postcode omitted (just like the autocomplete dropdown on the council website). Full details are in the [source documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/northernbeaches_nsw_gov_au.md).
