### ISSUE TITLE
[Source Request]: Deutschland

### ISSUE THREAD

**Issue by Florian17061995** [mampfes/hacs_waste_collection_schedule#3301]
### Municipality / Region

Bayern, Germany

### Example Address

gartenstraße 28, 84079 bruckberg

### Collection Data Format

As ICS/ICAL file

**Comment by bbr111** [comment]
please provide more info.

URL? App?

**Comment by markvp** [comment]
Thanks for the request! Bruckberg (Landkreis Landshut) is already supported via the existing **[Apps by Abfall+](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/app_abfallplus_de.md)** source.

Use `app_id: de.k4systems.landshutlk` in your configuration:

```yaml
waste_collection_schedule:
  sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.landshutlk
        city: Bruckberg
        strasse: Gartenstraße
        hnr: 28
```

You can look up the exact street/house-number names using the **Abfall App** (Kreis Landshut) — the same spelling must be used in the config. Closing as already supported.
