### ISSUE TITLE
Exception importing calendar

### ISSUE THREAD

**Issue by theanorak-keith** [mampfes/hacs_waste_collection_schedule#331]
I've cobbled together a new source for Richmondshire council and added it to my home assistant instance. The sensor entities I've configured show up more-or-less how I'd expect them to, but I get a notification that waste_collection_schedule could not be set up, and to check the logs. The logs say:

```
022-08-16 01:54:26.038 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.waste_collection_schedule.calendar
2022-08-16 01:54:26.105 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform waste_collection_schedule.calendar: Platform not found (Exception importing custom_components.waste_collection_schedule.calendar).
```

configuration.yaml relevant lines are:

```
# waste collection!
waste_collection_schedule:
  sources:
    - name: richmondshire_gov_uk
      args:
        uprn: [a number identifying my house]
      customize:
        - type: 140L GARDEN BIN
          alias: Green bin
        - type: 55L RECYCLING BOX
          alias: Recycling
        - type: 240L GREY RUBBISH BIN
          alias: Black bin
  day_switch_time: "18:00"


sensor:
  - platform: waste_collection_schedule
    name: Green bin
    count: 2
    types:
      - Green bin
  - platform: waste_collection_schedule
    name: Recycling
    count: 2
    types:
      - Recycling
  - platform: waste_collection_schedule
    name: Black bin
    count: 2
    types:
      - Black bin
  - platform: waste_collection_schedule
    name: All rubbish
    count: 6
```

Lastly, in case it's my cobbled-together-from-other-people's-code source that's at fault, here's richmondshire_gov_uk.py:

```
from datetime import datetime
import requests
from waste_collection_schedule import Collection  # type: ignore[attr-defined]
import json

TITLE = "Richmondshire (North Yorkshire)"
DESCRIPTION = "description goes here"
URL = "https://www.richmondshire.gov.uk/collectionCalendar"
TEST_CASES = {"test 1": {"uprn": 200001767082}, "test 2": {"uprn": 200001767078}, "test3": {"uprn": 200001767079 }}

ICONS = {
    "240L GREY RUBBISH BIN": "mdi:trash-can",
    "55L RECYCLING BOX": "mdi:recycle",
    "140L GARDEN BIN": "mdi:leaf",
}

class Source:
    def __init__(
        self, uprn
    ):  # argX correspond to the args dict in the source configuration
        self._uprn = uprn

    def fetch(self):
        r = requests.get(
            f"https://www.richmondshire.gov.uk/Umbraco/Api/MyAreaApi/GetBinRoundData?uprn={self._uprn}"
        )
#        print(r.text)
        ids = r.json()
#        print (len(ids))

        entries = []

        for id in ids:
            entries.append(
                Collection(
                    date=datetime.strptime(id["start"], "%Y-%m-%dT%H:%M:%S").date(),
                    t=id["title"],
                    icon=ICONS.get(id["title"]),
                )
            )
        return entries
```

**Comment by dt215git** [comment]
Seems to work okay for me.

```
- platform: waste_collection_schedule
  name: Green bin
  count: 2
  types:
    - Green bin
- platform: waste_collection_schedule
  name: Recycling
  count: 2
  types:
    - Recycling
- platform: waste_collection_schedule
  name: Black bin
  count: 2
  types:
    - Black bin
```

![image](https://user-images.githubusercontent.com/86194065/184918744-fd8604d7-88b6-4580-b112-71fcbf76b672.png)
