### ISSUE TITLE
[Bug]: Invalid Response - South Holland District Council (UK)

### ISSUE THREAD

**Issue by Lewis1352** [mampfes/hacs_waste_collection_schedule#3365]
### I Have A Problem With:

A specific source

### What's Your Problem

![image](https://github.com/user-attachments/assets/7c45fc8a-9054-4780-b133-e04694bb5196)

Invalid response when attempting to fetch the data from the South Holland website.

Also when attempting to use HACS instead sensors are populated with unknown, these worked until around the 29th of December (UK time):

![image](https://github.com/user-attachments/assets/d0381c92-dead-482f-966e-c3b518d392e6)
![image](https://github.com/user-attachments/assets/fc7e97d4-7f5a-4316-90dd-9a584a77dcee)

I haven't double checked but I suspect this has to do with the garden waste. Because it's the end of the year the garden waste collection takes a break so they don't put anything on the website (if they do it's very meaningless, see below image).

![image](https://github.com/user-attachments/assets/966dc1e4-87b9-4372-8638-f16d613b8521)

### Source (if relevant)

sholland_gov_uk

### Logs

```Shell
no relevant logs
```

### Relevant Configuration

```YAML
waste_collection_schedule:
    sources:
    - name: sholland_gov_uk
      args:
        uprn: -removed-
        postcode: -removed-
      customize:
        - type: Refuse
          alias: Refuse
        - type: Recycling
          alias: Recycling
        - type: Garden
          alias: Garden
    
sensor:
  - platform: waste_collection_schedule
    name: sensor for refuse collection
    types:
      - Refuse
    
  - platform: waste_collection_schedule
    name: sensor for recycling collection
    types:
      - Recycling
      
  - platform: waste_collection_schedule
    name: sensor for garden collection
    types:
      - Garden
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
