### ISSUE TITLE
[Bug]: Müllmax not working since 2025

### ISSUE THREAD

**Issue by makanimike** [mampfes/hacs_waste_collection_schedule#3367]
### I Have A Problem With:

A specific source

### What's Your Problem

Another source's data that stopped working with the new year is Müllmax.  
It actually showed "unknown" dates since a couple of weeks or so. But I thought perhaps something would happen automagically with the new year. The last valid data point returned from Müllmax was a few days ago for my home address. 

### Source (if relevant)

muellmax_de

### Relevant Configuration

```YAML
I confirmed that the example address from the documentation also does not work:

waste_collection_schedule:
  sources:
    - name: muellmax_de
      args:
        service: Fes
        mm_frm_str_sel: Achenbachstraße
        mm_frm_hnr_sel: 60596;Sachsenhausen;2;
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
