### ISSUE TITLE
Deprecated Source: Landkreis Gifhorn

### ISSUE THREAD

**Issue by ben-tsk** [mampfes/hacs_waste_collection_schedule#3376]
The source Landkreis Gifhorn - [abfallkalender_gifhorn_de.md](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfallkalender_gifhorn_de.md) is deprecated and no longer works.

They also use AWIDO. I tried the generic source [awido_de.md](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/awido_de.md) which works perfectly for me.

**Comment by dabepp** [comment]
Same for lra-regensburg

**Comment by cometchaser** [comment]
Works fine for me too. Thanks

**Comment by markvp** [comment]
Thanks for the report, and to @cometchaser for confirming! The `abfallkalender-gifhorn.de` website is no longer reachable, so this source is effectively dead.

The good news is that Landkreis Gifhorn is already supported via the generic **`awido_de`** source. A PR to remove the defunct source file is on the way, and the generated documentation will update automatically after merge.

In the meantime, configure it like this (see the [awido_de docs](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/awido_de.md) for the exact argument names):

```yaml
waste_collection_schedule:
  sources:
    - name: awido_de
      args:
        customer: gifhorn
        city: <your city>
        street: <your street>
```
