### ISSUE TITLE
[Bug] or [Source]: Poysdorf.at / Umweltverbände / Citiesapps

### ISSUE THREAD

**Issue by ArtheaRE** [mampfes/hacs_waste_collection_schedule#3377]
### I Have A Problem With:

A specific source

### What's Your Problem

Hallo es gab einen Wechsel der Müllabfuhr von Gemeide, welche Gaum bestellt hat und nun läuft es nicht mehr über die Gemeinde.
Die gemeinde stellt auf ihrer Website keine .icl Dateien oder Termine mehr zur Verfügung, welche ich sonst meistens so importiert hatte.
Das habe ich vor über einem Jahr dann auf die Unweltverbände geändert, da diese aber dann gerade in der Umstellungsphase waren hat dies recht bald auch nicht mehr funktioniert und ich habe alles auf die Citiesapp geändert.
Damals waren die Standorte Erdberg, Ketzelsdorf, Walterskirchen, Wetzelsdorf in einen Kalender zusammengelegt was mit den Filtern kein Problem dargestellt hat.
Auch bis vor kurzem in der Citiesapp waren die Katastral Standorte noch in einem Kalender zu finden.
Allerdings hat sich dies nun in der Citiesapp geändert und jeder Standort hat seinen eigenen Kalender. Das klingt alles nicht schlimm und lösbar, allerdings bekomme ich Ketzelsdorf oder Müllkalender-Ketzelsdorf oder wie auch immer der Kalender nun Korrekt heißt mit allen mitteln nicht eingebunden. Die Settings und sensoren funktionieren einwandfrei, allerdings kann der Fetchvorgang nicht sauber abgeschlossen werden. 

Fehler in HA: Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
Integration: Waste Collection Schedule ([Dokumentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
Erstmals aufgetreten: 1. Januar 2025 um 21:00:16 (4 Vorkommnisse)
Zuletzt protokolliert: 11:00:19

fetch failed for source App CITIES: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/citiesapps_com.py", line 73, in fetch garbage_plans = cities_apps.fetch_garbage_plans(self._city, self._calendar) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/CitiesAppsCom.py", line 1511, in fetch_garbage_plans specific_calendar = self.get_specific_calendar(city_id, calendar) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/CitiesAppsCom.py", line 1493, in get_specific_calendar raise SourceArgumentNotFoundWithSuggestions( ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ "calendar", [calendar["name"] for calendar in calendars] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ TypeError: SourceArgumentNotFoundWithSuggestions.__init__() missing 1 required positional argument: 'suggestions'

Meine Kalendereinstellung:

![hakalender](https://github.com/user-attachments/assets/a6ea897e-5193-43f2-8132-5ffb3044de76)

Leider bin ich in Python nicht bewandert sonst hätte ich versucht mittels der API ausfindig zu machen ob der Name des Kalenders überhaupt auftaucht oder richtig geschrieben wurde.

Die Invoke-Restmethod variante über PS ist mir leider ebenso nicht gelungen.

Die Authentifizierung mittels meiner E-Mail sowie Passwort habe ich überprüft und Funktioniert.

Die Integration habe ich neu installiert und aktuell, sowie meine HA Version

Anhand der Citiesapp Website habe ich versucht die Namen des Kalenders über die Debugging Console ausfindig zu machen. Leider ohne erfolg.

Probiert habe ich folgende Kalendernamen: 
- Erdberg, Ketzelsdorf, Walterskirchen, Wetzelsdorf (wie es früher war)
- Müllkalender - Ketzelsdorf wie es auf der Citiesapp Website steht
- Ketzelsdorf wie es in der Android App aufgelistet wird
![photo_2025-01-02_11-35-11](https://github.com/user-attachments/assets/42d0122b-e18f-4678-ad14-12a425d99f06)

Bitte um Info wie ich erfolgreich meinen Kalendernamen aus der CitiesApp beziehen kann oder bitte um Unterstützung ob ich bei der Einrichtung etwas übersehen hätte?

PS: Strauchschnitt und Wertstoffsammelzentrum wurde scheinbar auch entfernt, welches ich vermutlich der Umstellung und weniger der Integration anrechnen darf.

Die Python Files der Integration habe ich nicht verändert! 

Danke und liebe Grüße

German
-------------------------------------------------------------------
English

Hello, there has been a change in the waste collection service ordered by the municipality, which was previously managed by Gaum, and now it is no longer handled by the municipality. The municipality no longer provides .icl files or schedules on their website, which I used to import most of the time.

Over a year ago, I switched to the environmental associations, but since they were in the transition phase, it soon stopped working, and I switched everything to the Citiesapp. At that time, the locations Erdberg, Ketzelsdorf, Walterskirchen, and Wetzelsdorf were combined into one calendar, which was not a problem with the filters. Even until recently, the cadastral locations were still found in one calendar in the Citiesapp.

However, this has now changed in the Citiesapp, and each location has its own calendar. This doesn't sound bad and solvable, but I can't integrate Ketzelsdorf or Müllkalender-Ketzelsdorf or whatever the calendar is now correctly called by any means. The settings and sensors work perfectly, but the fetch process cannot be completed cleanly.

Error in HA: Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160 Integration: Waste Collection Schedule (Documentation) First occurred: January 1, 2025, at 21:00:16 (4 occurrences) Last logged: 11:00:19

fetch failed for source App CITIES: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/citiesapps_com.py", line 73, in fetch garbage_plans = cities_apps.fetch_garbage_plans(self._city, self._calendar) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/CitiesAppsCom.py", line 1511, in fetch_garbage_plans specific_calendar = self.get_specific_calendar(city_id, calendar) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/CitiesAppsCom.py", line 1493, in get_specific_calendar raise SourceArgumentNotFoundWithSuggestions( ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ "calendar", [calendar["name"] for calendar in calendars] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ TypeError: SourceArgumentNotFoundWithSuggestions.init() missing 1 required positional argument: 'suggestions'

My calendar settings:

Unfortunately, I am not proficient in Python; otherwise, I would have tried to find out via the API whether the name of the calendar appears at all or is spelled correctly.

The Invoke-Restmethod variant via PS also did not succeed.

I have checked the authentication using my email and password, and it works.

I have reinstalled and updated the integration, as well as my HA version.

Based on the Citiesapp website, I tried to find the names of the calendars via the debugging console. Unfortunately, without success.

I tried the following calendar names:

Erdberg, Ketzelsdorf, Walterskirchen, Wetzelsdorf (as it used to be)

Müllkalender - Ketzelsdorf as it is listed on the Citiesapp website

Ketzelsdorf as it is listed in the Android app

Please provide information on how I can successfully obtain my calendar name from the CitiesApp or support if I have overlooked something in the setup.

I have not changed the Python files of the integration!

Thank you and best regards

### Source (if relevant)

Citiesapps lately, also Umveltverbunde and ICL

### Logs

```Shell
Error in HA: Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160 Integration: Waste Collection Schedule (Documentation) First occurred: January 1, 2025, at 21:00:16 (4 occurrences) Last logged: 11:00:19

fetch failed for source App CITIES: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/citiesapps_com.py", line 73, in fetch garbage_plans = cities_apps.fetch_garbage_plans(self._city, self._calendar) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/CitiesAppsCom.py", line 1511, in fetch_garbage_plans specific_calendar = self.get_specific_calendar(city_id, calendar) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/CitiesAppsCom.py", line 1493, in get_specific_calendar raise SourceArgumentNotFoundWithSuggestions( ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^ "calendar", [calendar["name"] for calendar in calendars] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ TypeError: SourceArgumentNotFoundWithSuggestions.init() missing 1 required positional argument: 'suggestions'
```

### Relevant Configuration

```YAML
Kalendar:

 sources:
    - name: citiesapps_com
      args:
        city: Poysdorf
        calendar: Ketzelsdorf
        email: !secret CitiesAppBEN
        password: !secret CitiesAppPW
      calendar_title: Ketzelsdorf

          
  fetch_time: "04:00"
  day_switch_time: "18:00"



Sensors now with Citiesapp - Working a view Days ago:

# Abfall


- platform: waste_collection_schedule
  name: "Restmüll"

  details_format: "upcoming"
  value_template: "in {{ value.daysTo}} tagen"
  types:
    - "Restmüll"

- platform: waste_collection_schedule
  name: "Gelber Sack"

  details_format: "upcoming"
  value_template: "in {{ value.daysTo}} tagen"
  types:
    - "Gelber Sack"

- platform: waste_collection_schedule
  name: "Papier"

  details_format: "upcoming"
  value_template: "in {{ value.daysTo}} tagen"
  types:
    - "Papier"

- platform: waste_collection_schedule
  name: "Biomüll"

  details_format: "upcoming"
  value_template: "in {{ value.daysTo}} tagen"
  types:
    - "Biomüll"


- platform: waste_collection_schedule
  name: "Wertstoffsammelzentrum"

  details_format: "upcoming"
  value_template: "in {{ value.daysTo}} tagen"
  types:
    - "Wertstoffsammelzentrum"


- platform: waste_collection_schedule
  name: "Strauchschnittübernahme im WSZ"
  details_format: "upcoming"
  value_template: "in {{ value.daysTo}} tagen"
  types:
    - "Strauchschnittübernahme im WSZ"



sensorf previously on umweltverbände:

sources:
  - name: umweltverbaende_at
    calendar_title: Restmüll
    args:
      district: "mistelbach" #Mistelbach
      municipal: "Poysdorf"
      calendar: "Erdberg, Ketzelsdorf, Walterskirchen, Wetzelsdorf: Restmüll"
    customize:
      - type: "Restmüll"
        alias: "Restmüll"
        icon: mdi:trash-can

  - name: umweltverbaende_at
    calendar_title: GelberSack
    args:
      district: "mistelbach" #Mistelbach
      municipal: "Poysdorf"
      calendar: "Erdberg, Ketzelsdorf, Walterskirchen, Wetzelsdorf: Gelber Sack"
    customize:
      - type: "Gelber Sack"
        alias: "Gelber Sack"
        icon: mdi:sack

  - name: umweltverbaende_at
    calendar_title: Altpapier
    args:
      district: "mistelbach" #Mistelbach
      municipal: "Poysdorf"
      calendar: "Erdberg, Ketzelsdorf, Walterskirchen, Wetzelsdorf: Altpapier"
    customize:
      - type: "Altpapier"
        alias: "Altpapier"
        icon: mdi:trash-can

  - name: umweltverbaende_at
    calendar_title: Biotonne
    args:
      district: "mistelbach" #Mistelbach
      municipal: "Poysdorf"
      calendar: "Biotonne"
    customize:
      - type: "Biotonne"
        alias: "Biotonne"
        icon: mdi:apple

fetch_time: "04:00"
day_switch_time: "18:00"
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
