### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by SavanFlou** [mampfes/hacs_waste_collection_schedule#3378]
### Municipality / Region

Korneuburg area

### Collection Calendar Webpage

https://korneuburg.umweltverbaende.at

### Example Address

Korneuburger Strasse14-24, 2102 Bisamberg

### Collection Data Format

As html on a webpage, As PDF Download

### Additional Information

To be complete,
I used this app since long and it worked "perfectly" (I had a problem, but you helped me to fix it https://github.com/mampfes/hacs_waste_collection_schedule/discussions/1945)
Korneuburg is integrated in Waste Collection Schedule, through Cities app and I think it works great.
But lot of cities from the area depend on the same service but are not supported by CitiesApp. 
So I cannot find anymore my waste calendar, the easier would be to have a "Korneuburg area" or something like that, based on the website that was used before.

Thank you for your help and have a great year.

**Comment by markvp** [comment]
This municipality is already supported via the existing **citiesapps_com** source (App CITIES platform). See documentation: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/citiesapps_com.md

Configure with:
```yaml
waste_collection_schedule:
  sources:
    - name: citiesapps_com
      args:
        city: "Korneuburg"
        calendar: "<your calendar name>"
        email: "<email>"
        password: "<password>"
```

Closing as already supported — feel free to reopen if you hit a specific issue with this source.
