### ISSUE TITLE
[Bug]: Newcastle City Council fetching wrong dates

### ISSUE THREAD

**Issue by GTunney** [mampfes/hacs_waste_collection_schedule#3388]
### I Have A Problem With:

A specific source

### What's Your Problem

Bin days have changed due to the few public holidays we have had in the UK. My recycling was changed to today 03/01/2025 but the integration is still reporting what would have been my normal day 02/01/2025. 

Newcastle city council website is displaying correct for my URPN. 

### Source (if relevant)

Newcastle_gov_uk

### Relevant Configuration

```YAML
friendly_name: Newcastle City Council
message: Domestic
all_day: true
start_time: "2025-01-09 00:00:00"
end_time: "2025-01-10 00:00:00"
location: ""
description: ""

friendly_name: Bin Collections
types:
  - Domestic
  - Recycling
upcoming:
  - date: "2025-01-09"
    icon: mdi:trash-can
    picture: null
    type: Domestic
  - date: "2025-01-16"
    icon: mdi:recycle
    picture: null
    type: Recycling
last_update: "2025-01-03T10:53:24"
attribution: "Last update: 01/03/25 10:53:24"
icon: mdi:trash-can
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [X] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
