### ISSUE TITLE
[Bug]: day_switch_time not honored on HA restarts

### ISSUE THREAD

**Issue by jowi24** [mampfes/hacs_waste_collection_schedule#3395]
### I Have A Problem With:

The integration in general

### What's Your Problem

After restarting Home Assistant, the day_switch_time setting is not respected. The number of days until the next collection is calculated earlier in the day, as if the switch had already occurred based on the day_switch_time configuration.

For example, even though day_switch_time is set to 15:00, the sensors behave as if the switch occurred earlier in the day, which leads to incorrect daysTo values.

See screenshot below for an example. Green indicated are correct updates of the configured sensors. In red indicated the time of home assistant restart:

<img width="1439" alt="Bildschirmfoto 2025-01-04 um 10 18 42" src="https://github.com/user-attachments/assets/26bdcb9e-9254-45d6-801c-fb853adfac2f" />

### Source (if relevant)

not relevant

### Logs

```Shell
no relevant logs, see screenshot
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: 'www/waste.ics'
  fetch_time: "18:00"
  day_switch_time: "15:00"

sensor:
  - platform: waste_collection_schedule
    name: Grüne Tonne
    value_template: '{{value.daysTo}}'
    types:
      - Wertstoffbehaelter
      - Wertstoff (privat) 2-Rad 02-woechentl.
  - platform: waste_collection_schedule
    name: Biomüll
    value_template: '{{value.daysTo}}'
    types:
      - Biobehaelter
      - Bio(privat) 2-Rad 02-woechentl.
  - platform: waste_collection_schedule
    name: Restmüll
    value_template: '{{value.daysTo}}'
    types:
      - Restabfallbehaelter
      - Restabfall (privat) 2-Rad 02-woechentl.
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
