### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by X-Ray-122** [mampfes/hacs_waste_collection_schedule#3400]
### Municipality / Region

Herzberg(Elster), Germany

### Collection Calendar Webpage

https://www.schwarze-elster.de/abfallentsorgung/abfuhrtermine

### Example Address

Torgauer Straße 59
04916 Herzberg

### Collection Data Format

As ICS/ICAL file, As html on a webpage, Dedicated IOS/Android APP

**Comment by markvp** [comment]
Thanks for the request! Good news — Herzberg (Elster) is already supported.

The Abfallentsorgungsverband Schwarze Elster uses the **Abfall+** platform, which is covered by the existing [`app_abfallplus_de`](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/app_abfallplus_de.md) source.

Configure it like this in your `configuration.yaml`:

```yaml
waste_collection_schedule:
  sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.aevapp
        city: Herzberg
        strasse: Torgauer Straße
        hnr: "59"
```

Or via the Home Assistant UI, select **Apps by Abfall+** as the source, choose **AEV-App (Schwarze Elster)** from the provider list, then enter your street and house number.
