### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by H4wK15** [mampfes/hacs_waste_collection_schedule#3431]
### Municipality / Region

Passail, Austria

### Collection Calendar Webpage

https://www.passail.at/wp-content/uploads/sites/18/2024/12/Muelltermine-2025-Passail-Plenzengreith-teilw.Arzberg-1.ics

### Example Address

Passail 1, 8162 Passail

### Collection Data Format

As ICS/ICAL file

**Comment by bbr111** [comment]
https://www.passail.at/muellentsorgung/

extract ics links

**Comment by bbr111** [comment]
Thanks for the request! Passail has been added as an ICS-based source — see PR #6699.

To configure it in Home Assistant, visit https://www.passail.at/muellentsorgung/, right-click the ICS download link for your collection area, copy the link address, and use it as the `url` parameter with the generic `ics` source:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://www.passail.at/wp-content/uploads/..."
```

This will be available after the next release.
