### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by jannek09** [mampfes/hacs_waste_collection_schedule#3434]
### Municipality / Region

Brandenburg an der Havel Stadt - Brandenburg

### Collection Calendar Webpage

WasteBox

### Example Address

Riesaerweg Brandenburg 
https://brb.wastebox.gemos-management.de/Gemos/WasteBox/Frontend/TourSchedule/Raw/Name/2025/list/127708/1973,1974,1975,1976,1977,1978,1979,1980/1/Print/ics/Default/Abfuhrtermine.ics

### Collection Data Format

As ICS/ICAL file

### Additional Information

Quelle der DB -> https://www.stadt-brandenburg.de/leben/abfall-und-abwasser/entsorgungstermine

**Comment by bbr111** [comment]
Brandenburg an der Havel is already supported via the generic [ICS](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) source — see `doc/ics/yaml/brandenburg_an_der_havel.yaml` (added in #6109).

The city's collection calendar page (the same one linked in this issue, https://www.stadt-brandenburg.de/leben/abfall-und-abwasser/entsorgungstermine) now runs on a different backend than the WasteBox link originally posted here, but it works the same way:

- Go to <https://www.stadt-brandenburg.de/leben/abfall-und-abwasser/entsorgungstermine> and select your street
- Right-click on the `Kalenderimport` button and copy the URL
- Use that link as the `url` parameter of the generic `ics` source

Example configuration:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://brandenburg.abfall-app.net/download?system=ical&period=1&street=4&categories=&view=month
```

I just re-verified that URL is live and returning current 2026 collection dates, so closing this as already supported. Thanks for the report, and apologies for the long delay!
