### ISSUE TITLE
[Source Request]: Main-Kinzig-Kreis missing Gelnhausen

### ISSUE THREAD

**Issue by dream-MT** [mampfes/hacs_waste_collection_schedule#3435]
### Municipality / Region

Hessen, Main-Kinzig-Kreis, Gelnhausen

### Collection Calendar Webpage

https://gelnhausen.mein-abfallkalender.online/ical.ics?sid=699&cd=attachment&ft=6&fu=ical_download&fp=next_1000&wids=9,11,10,12,13,14&uid=4522&pwid=8c5e7e4a82&cid=2&fn=Mein-Abfallkalender_Stadt_Gelnhausen_Zukünftige_Termine.ics

### Example Address

Wingertstr.

### Collection Data Format

As ICS/ICAL file

**Comment by robingn79** [comment]
Would be great to have it added as part of mymuell.de
And closing the other request was the wrong way around, the initial request was for mein-abfallkalender.info (which is obsolete).

**Comment by markvp** [comment]
Thanks for the request! Gelnhausen is already supported via the `mein-abfallkalender.online` ICS provider — it is explicitly listed as a supported municipality. Visit `https://gelnhausen.mein-abfallkalender.online/`, register your email to generate a personal webcal URL, then follow the [mein_abfallkalender_online documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/ics/mein_abfallkalender_online.md) to configure it with the generic `ics` source. Closing as already supported.

**Comment by robingn79** [comment]
<img width="1320" height="969" alt="Image" src="https://github.com/user-attachments/assets/416f1bc9-61db-47e2-9ca1-740179ec6964" />

As it‘s difficult for you to understand, since Jan 2026 it‘s not part of it anymore

**Comment by markvp** [comment]
Apologies for the incorrect closure — you're right, Gelnhausen has left the mein-abfallkalender.online platform.

Good news: Gelnhausen is supported via the `jumomind_de` source using the **MyMuell** service. We've added it to the documented list and a PR is up. In the meantime you can configure it now:

```yaml
waste_collection_schedule:
  sources:
    - name: jumomind_de
      args:
        service_id: mymuell
        city: Gelnhausen
        street: Wingertstraße (Gelnhausen-Meerholz)  # adjust to your street
```
