### ISSUE TITLE
[Bug]: Montreal waste collection showing as unknown

### ISSUE THREAD

**Issue by adarrous** [mampfes/hacs_waste_collection_schedule#3525]
### I Have A Problem With:

A specific source

### What's Your Problem

Hello,

The Montréal area seems to be giving unknown status. For the example configuration it doesn't work as well.
waste_collection_schedule:
  sources:
    - name: montreal_ca
      args:
        sector: MHM_41-1

### Source (if relevant)

montreal_ca

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: montreal_ca
      args:
        sector: SO-5-R4
sensor:
  - platform: waste_collection_schedule
    name: sensor_waste_collection_schedule
    details_format: appointment_types
```

### Checklist Source Error

- [X] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [X] Checked that the website of your service provider is still working
- [X] Tested my attributes on the service provider website (if possible)
- [X] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [X] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [X] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
