### ISSUE TITLE
[Source Request]: Germany, Gemeinde Hille

### ISSUE THREAD

**Issue by bagsik** [mampfes/hacs_waste_collection_schedule#3526]
### Municipality / Region

Hille, Germany

### Collection Calendar Webpage

https://www.hille.de/Wirtschaft-Wohnen/Wohnen/Abfallkalender/

### Example Address

Am Rathaus 4, 32479 Hille

### Collection Data Format

As ICS/ICAL file

**Comment by bbr111** [comment]
Thanks for the request! Hille publishes static ICS calendar files per collection district directly on their website, so this can be covered by our generic ICS source rather than needing a dedicated integration.

I've opened a PR adding Hille to the ICS provider list: doc/ics/yaml/hille_de.yaml

Once merged, you'll be able to configure it like this:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://www.hille.de/media/custom/3015_1711_1.ICS   # Bezirk 1
        # or
        # url: https://www.hille.de/media/custom/3015_1712_1.ICS  # Bezirk 2
```

Check the [Abfallkalender page](https://www.hille.de/Wirtschaft-Wohnen/Wohnen/Abfallkalender/) to confirm which `Abfuhrbezirk` (collection district) your address belongs to, and use the matching link.
