### ISSUE TITLE
MEL

### ISSUE THREAD

**Issue by couzapointe** [mampfes/hacs_waste_collection_schedule#3540]
### Municipality / Region

Provin, France

### Collection Data Format

Something different (add to additional information)

**Comment by bbr111** [comment]
https://www.lillemetropole.fr/dechets
or
https://www.ville-provin.fr/page/les-dechets

**Comment by bbr111** [comment]
Thanks for the report!

MEL (Métropole Européenne de Lille), which covers Provin, is already supported here. Its waste-collection widget runs on the **Publidata** platform, and this repo's generic `publidata_fr` source already lists it (instance_id `876`).

You can configure it like this:

```yaml
waste_collection_schedule:
  sources:
    - name: publidata_fr
      args:
        address: "YOUR STREET ADDRESS"   # without city or postcode
        insee_code: "59477"              # Provin's INSEE code
        instance_id: 876
```

I verified this live against a Provin address and it returns collection dates. I also fixed this source's dead test case (it used a stale example address) so MEL stays covered by our automated tests: https://github.com/mampfes/hacs_waste_collection_schedule/pull/7529

Full docs: [`doc/source/publidata_fr.md`](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/publidata_fr.md)

Closing since MEL is already supported. Please reopen (or open a new issue) if you hit trouble with your specific address.
