### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by TomSchumi** [mampfes/hacs_waste_collection_schedule#3549]
### Municipality / Region

Böblingen

### Collection Calendar Webpage

ICS

### Example Address

Haupstraß2 38, 71034 Böblingen

### Collection Data Format

As ICS/ICAL file

### Additional Information

Dagersheim

**Comment by bbr111** [comment]
please provide more info.

app, url?

**Comment by bbr111** [comment]
Thanks for the report! Böblingen (Landkreis Böblingen, including Dagersheim) is served by Abfallwirtschaft Landkreis Böblingen (awb-bb.de), which uses the abfall.io v3 GraphQL widget. I've added it to the abfall_io_graphql source's provider list in a pull request, so once merged it will be selectable directly from the config wizard.

In the meantime, or if you'd like to set it up manually via YAML, use:

```yaml
waste_collection_schedule:
  sources:
    - name: abfall_io_graphql
      args:
        key: "76bdaac8568082d77e7a90cb41129f9b"
        idHouseNumber: 1057  # Dagersheim; use the config wizard to look up your own street/house number
```

I'll close this once the PR merges.
