### ISSUE TITLE
[Source Request]: 

### ISSUE THREAD

**Issue by Marc53639** [mampfes/hacs_waste_collection_schedule#3551]
### Municipality / Region

Königswinter, Germany

### Collection Calendar Webpage

https://www.rsag.de/abfallkalender/abfuhrtermine

### Example Address

Winzerstrasse 84, 53639 Königswinter

### Collection Data Format

As PDF Download

**Comment by markvp** [comment]
Thanks for the request! This is now implemented as a new source `rsag_de` — a PR has been opened.

Despite the PDF link on the page, the RSAG website has a public JSON/ICS API, so we were able to build a proper live-fetching source covering all 19 Rhein-Sieg-Kreis municipalities.

**Configuration:**
```yaml
waste_collection_schedule:
    sources:
    - name: rsag_de
      args:
        city: Königswinter
        street: Winzerstraße
```

Supported municipalities: Alfter, Bad Honnef, Bornheim, Eitorf, Hennef, Königswinter, Lohmar, Meckenheim, Much, Neunkirchen-Seelscheid, Niederkassel, Rheinbach, Ruppichteroth, Sankt Augustin, Siegburg, Swisttal, Troisdorf, Wachtberg, Windeck.
