### ISSUE TITLE
[Source Request]: Gronau Germany

### ISSUE THREAD

**Issue by marvinko88** [mampfes/hacs_waste_collection_schedule#3585]
### Municipality / Region

Gronau, Germany 

### Collection Calendar Webpage

https://abfallkalender.regioit.de/kalender-wml/index.jsp?format=pdf&zeit=&lang=de&jahr=2025&ort=Gronau&strasse=3997214&fraktion=0&fraktion=3&fraktion=4&fraktion=5&fraktion=11&md=1

### Example Address

Viktoriastraße 46, 48599 Gronau, Germany

### Collection Data Format

As ICS/ICAL file

**Comment by bbr111** [comment]
Thanks for the report! I've implemented a source for Gronau's Abfallkalender (regio iT, `kalender-wml`). It fetches your street's collection dates live (Restmüll, Bioabfall, Altpapier, Gelbe Tonne, Schadstoffmobil) via the calendar's ICS export.

A PR is up: https://github.com/mampfes/hacs_waste_collection_schedule/pull/7014

Once merged, you'll be able to configure it like this:

```yaml
waste_collection_schedule:
  sources:
    - name: gronau_de
      args:
        street: Viktoriastraße
```

Use the exact street spelling as shown on https://abfallkalender.regioit.de/kalender-wml/index.jsp?ort=Gronau
