### ISSUE TITLE
Request for provider - Baw Baw Shire, Australia

### ISSUE THREAD

**Issue by lifeandfate1** [mampfes/hacs_waste_collection_schedule#361]
Hi there, 

Would you please add the Baw Baw Shire as a provider.

Cheers
Callum

https://webmaps.bawbawshire.vic.gov.au/IntraMaps98/ApplicationEngine/frontend/mapbuilder/default.htm?configId=00000000-0000-0000-0000-000000000000&liteConfigId=9fbdca6d-93d7-4791-a60f-1b23baa36ef5&title=V2FzdGUgQ29sbGVjdGlvbiBEYXlz

**Comment by dt215git** [comment]
The updated url just times out for me, however, based on the pdf booklet  it looks like collection schedules are on a regular schedule:

- Garbage every week
- Recycling every two weeks
- Organics every two weeks

With the Recycling & Organics weeks alternating.

You can do that using the [static source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md#static-source) and the info in the booklet. Something like this, but you'll need to adjust the date to match you suburb.

```yaml
waste_collection_schedule:
  sources:
    - name: static
      calendar_title: Garbage
      args:
        type: Garbage
        frequency: WEEKLY
        interval: 1
        start: "2023-01-02" #change to earliest 2023 date for your suburb
        until: "2023-12-31" 
    - name: static
      calendar_title: Recycling
      args:
        type: Recycling
        frequency: WEEKLY
        interval: 2
        start: "2023-01-09" #change to earliest 2023 date for your suburb
        until: "2023-12-31" 
    - name: static
      calendar_title: Organics
      args:
        type: Organics
        frequency: WEEKLY
        interval: 2
        start: "2023-01-02" #change to earliest 2023 date for your suburb
        until: "2023-12-31"
```

```yaml
sensor:
  - platform: waste_collection_schedule
    name: BawBawShire_Test
    details_format: appointment_types
    add_days_to: true
```

![image](https://user-images.githubusercontent.com/86194065/232230334-1f185f3c-631c-43af-ada1-edf636b37c68.png)
