### ISSUE TITLE
[Source Request]: New Service Provider

### ISSUE THREAD

**Issue by MichaelSkergeth** [mampfes/hacs_waste_collection_schedule#3639]
### Municipality / Region

St. Georgen an der Stiefing, Austria

### Collection Calendar Webpage

https://citiesapps.com/cities/sankt-georgen-an-der-stiefing/waste-management/areas/67645730a35b8ef98f926157

### Example Address

Stiefing 5, 8413 St. Georgen an der Stiefing

### Collection Data Format

As html on a webpage

**Comment by lbloder** [comment]
Hi @MasterLink7,
This city should already be supported using `CitiesApps`.

However, there is currently a fix in the pipeline, which updates the `CitiesApps` integration, as they have changed the API on their side.

Also note, that for some reason in `CitiesApps` the city is: "Sankt Georgen an der Stiefing", but the calendar name is: "Sankt Georgen an der Stiefling".

The yaml config for this would be:

```
waste_collection_schedule:
    sources:
    - name: citiesapps_com
      args:
        city: Sankt Georgen an der Stiefing
        calendar: Sankt Georgen an der Stiefling
        password: 
        email: 
```

I do believe, that once version `2.7.0` is released your city should work as expected.

**Comment by markvp** [comment]
This municipality is already supported via the existing **citiesapps_com** source (App CITIES platform). See documentation: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/citiesapps_com.md

Configure with:
```yaml
waste_collection_schedule:
  sources:
    - name: citiesapps_com
      args:
        city: "Sankt Georgen an der Stiefing"
        calendar: "<your calendar name>"
        email: "<email>"
        password: "<password>"
```

Closing as already supported — feel free to reopen if you hit a specific issue with this source.
