### ISSUE TITLE
[Source Request]: missing data for Neuberg in Germany

### ISSUE THREAD

**Issue by spami007** [mampfes/hacs_waste_collection_schedule#3646]
### Municipality / Region

Neuberg

### Collection Calendar Webpage

https://neuberg.eu/leben-und-wohnen/abfallkalender

### Example Address

Bergstraße 9, 63543 Neuberg

### Collection Data Format

As ICS/ICAL file

**Comment by bbr111** [comment]
Thanks for the request! Neuberg's Abfallkalender is published as a single, publicly accessible static ICS file (no login, no per-address lookup needed), so I've added it to our generic ICS provider list:

https://github.com/mampfes/hacs_waste_collection_schedule/pull/6901

Once merged you'll be able to configure it using the generic `ics` source with:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://neuberg.eu/output/download.php?fid=3502.1370.1.ICS
```

This will include all waste types published for the whole municipality (Sondermüll, Restmüll, Bioabfälle, Altpapier, Gelber Sack). You can use the `types` / `exclude` filter options if you only want a subset.
