### ISSUE TITLE
[Source Request]: Aarberg, BE, Switzerland

### ISSUE THREAD

**Issue by brueni** [mampfes/hacs_waste_collection_schedule#3655]
### Municipality / Region

Aarberg, Switzerland

### Collection Calendar Webpage

https://www.aarberg.ch/de/abfallwirtschaft/abfallkalender/

### Example Address

Not stated by individual adress, but by a zone (part of the village).
Valid zones to filter are:
- Aarberg
- Grafenmoos
- Leimern
- Mülital
- Spins
- Zälgli

### Collection Data Format

As ICS/ICAL file

### Additional Information

Based on the view and structure of the page, it's likely that Aarberg uses the same Tool/CMS as "Rapperswil Bern, Switzerland" which was already integrated as a source, so please have a look at how it's implemented there:
https://github.com/mampfes/hacs_waste_collection_schedule/issues/2621

**Comment by bbr111** [comment]
Thanks for the request! Aarberg does indeed use the same Weblication CMS platform as Rapperswil BE (#2621), including a zone filter for the sub-areas you listed (Aarberg, Grafenmoos, Leimern, Mülital, Spins, Zälgli).

I've implemented a new source `aarberg_ch` that lets you select your zone directly:

```yaml
waste_collection_schedule:
  sources:
    - name: aarberg_ch
      args:
        zone: Aarberg   # or Grafenmoos, Leimern, Mülital, Spins, Zälgli
```

I've opened a PR with this implementation — it will show up here once merged. Closing this out once the PR lands.
