### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by rklueber** [mampfes/hacs_waste_collection_schedule#3660]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

Hello,

I wanted a calendar entity which only has a subset of the events/types. The config is below. I was able to create one calendar per wanted type (commented out section). Works.

However, when I create those 3 additional calendars the attribute `daysTo` of the sensors for each type disappears.

Attributes of one type with the additional calendars.

![Image](https://github.com/user-attachments/assets/3fa33b29-6e60-4cd5-a114-761bbe2a17ed)

Attributes of one type without the additional calendars.

![Image](https://github.com/user-attachments/assets/43a0849a-5694-4275-b774-7bb1c449585c)

### Logs

```Shell

```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: app_abfallplus_de
      args:
        app_id: de.k4systems.muellalarm
        city: "City"
        strasse: "Street"
        hnr: "HNR"
        bezirk: "Bezirk"
#       customize:
#         - type: Restabfall
#           alias: Schwarze Tonne
#           use_dedicated_calendar: true
#           dedicated_calendar_title: Müllkalender Schwarz
#         - type: Leichtverpackungen
#           alias: Gelbe Tonne
#           use_dedicated_calendar: true
#           dedicated_calendar_title: Müllkalender Gelb
#         - type: Bioabfall
#           alias: Braune Tonne
#           use_dedicated_calendar: true
#           dedicated_calendar_title: Müllkalender Braun

sensor:
  - platform: waste_collection_schedule
    name: Schwarze Tonne
    details_format: upcoming
    count: 1
    leadtime: 7
    value_template: "in {{value.daysTo}} Tagen"
    date_template: 'am {{value.date.strftime("%a")}}'
    add_days_to: true
    types:
      - Restabfall

  - platform: waste_collection_schedule
    name: Gelbe Tonne
    details_format: upcoming
    count: 1
    leadtime: 7
    value_template: "in {{value.daysTo}} Tagen"
    date_template: 'am {{value.date.strftime("%a")}}'
    add_days_to: true
    types:
      - Leichtverpackungen

  - platform: waste_collection_schedule
    name: Braune Tonne
    details_format: upcoming
    count: 1
    leadtime: 7
    value_template: "in {{value.daysTo}} Tagen"
    date_template: 'am {{value.date.strftime("%a")}}'
    add_days_to: true
    types:
      - Bioabfall
```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
