### ISSUE TITLE
[Source Request]:  Stadt Ratingen Müllabfuhr

### ISSUE THREAD

**Issue by gorzan14** [mampfes/hacs_waste_collection_schedule#3666]
### Municipality / Region

Stadt Ratingen

### Collection Calendar Webpage

https://www.stadt-ratingen.de/umweltschutz-und-abfall/abfallwirtschaft-und-stadtreinigung/abfuhrkalender-und-termine#c2174

### Example Address

Raifeisenstrasse

### Collection Data Format

As ICS/ICAL file

### Additional Information

.ics file for one Jear

**Comment by bbr111** [comment]
Hi @gorzan14, thanks for the request!

Ratingen is actually already supported today through the existing **Jumomind / MyMüll** source (`jumomind_de`, `service_id: mymuell`), which several municipalities in Kreis Mettmann use rather than the town's own `stadt-ratingen.de` ICS export. Since this integration already has a working, structured source for Ratingen, we'd rather point you to that instead of duplicating it with a second source for the same data.

You can configure it in `configuration.yaml` like this:

```yaml
waste_collection_schedule:
  sources:
    - name: jumomind_de
      args:
        service_id: mymuell
        city: Ratingen
        street: Raiffeisenstraße  # only needed if the city alone is ambiguous
```

Start with just `city: Ratingen` (no `street`); if the source complains that the city is ambiguous or asks for more detail, add your `street` as shown above.

Full docs: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/jumomind_de.md

I'll close this issue as already supported — please reopen or comment if `jumomind_de` doesn't return correct data for your address and we'll take another look.
