### ISSUE TITLE
[Source Request]: Gemeente Woensdrecht.  Saver

### ISSUE THREAD

**Issue by TurboVyv** [mampfes/hacs_waste_collection_schedule#3670]
### Municipality / Region

Gemeente Woensdrecht

### Collection Calendar Webpage

https://saver.nl/afvalkalender

### Example Address

Zes oktoberlaan 64,  4645GD, Putte

### Collection Data Format

As html on a webpage

### Additional Information

![Image](https://github.com/user-attachments/assets/986a97d7-9654-4ee7-9c58-8771c359a96f)

**Comment by bbr111** [comment]
Hi @TurboVyv, thanks for the request. Saver (saver.nl) is already supported by the `saver_nl` source, which covers Roosendaal, Halderberge, Bergen op Zoom, Rucphen, Zundert, Steenbergen and Woensdrecht. It was added after you opened this issue.

For your example address, the configuration would be:

```yaml
waste_collection_schedule:
  sources:
    - name: saver_nl
      args:
        postcode: "4645GD"
        huisnummer: 64
```

If the address has a house-number addition, add `toevoeging`. The docs are at https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/saver_nl.md. If it doesn't work for your address, please open a new bug report that names `saver_nl` and includes the logs. I'm closing this request as already supported.
