### ISSUE TITLE
[Source Request]: Austria, Frastanz, Citiesapp

### ISSUE THREAD

**Issue by sandro-byte32** [mampfes/hacs_waste_collection_schedule#3673]
### Municipality / Region

Frastanz

### Collection Calendar Webpage

frastanz.at

### Example Address

Alte Landstrasse 33

### Collection Data Format

Dedicated IOS/Android APP

### Additional Information

Its in the cities app but no supported now

**Comment by markvp** [comment]
This municipality is already supported via the existing **citiesapps_com** source (App CITIES platform). See documentation: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/citiesapps_com.md

Configure with:
```yaml
waste_collection_schedule:
  sources:
    - name: citiesapps_com
      args:
        city: "Frastanz"
        calendar: "<your calendar name>"
        email: "<email>"
        password: "<password>"
```

Closing as already supported — feel free to reopen if you hit a specific issue with this source.
