### ISSUE TITLE
[Source Request]:  Please add a new waste company

### ISSUE THREAD

**Issue by hennerich** [mampfes/hacs_waste_collection_schedule#3680]
### Municipality / Region

Saxony Anhalt South, Germany

### Collection Calendar Webpage

https://www.awsas.de/service/tourenplaene-2025.html

### Example Address

Elsteraue, District Langendorf

### Collection Data Format

As ICS/ICAL file

**Comment by bbr111** [comment]
Hi @hennerich, thank you for the request!

I've implemented a new source `awsas_de` for AW SAS (Abfallwirtschaft Sachsen-Anhalt Süd) covering the Burgenlandkreis. The source uses the provider's REST API to look up your municipality and district, then fetches the collection calendar as an ICS file.

**Configuration example (your address):**

```yaml
waste_collection_schedule:
  sources:
    - name: awsas_de
      args:
        municipality: Gemeinde Elsteraue
        district: Langendorf
```

Use the municipality and district names exactly as shown in the dropdowns on https://www.awsas.de/service/abfallkalender.html (including the prefix, e.g. `Gemeinde` or `Stadt`). A pull request has been opened.
