### ISSUE TITLE
[Bug]: integration doesnt load

### ISSUE THREAD

**Issue by sbeier23** [mampfes/hacs_waste_collection_schedule#3694]
### I Have A Problem With:

The integration in general

### What's Your Problem

The integration failes to load. Removing/reinstalling of integration and/or sensors doesnt help. When configuring via GUI everytime there ist "Unknown error occurred"

Even when trying to use a different source the error occurs.

### Source (if relevant)

Oberhavel AWU (ics)

### Logs

```Shell
First Error:

Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:226
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 13:55:14 (1 Vorkommnisse)
Zuletzt protokolliert: 13:55:14

error loading source ics: cannot import name 'use_pytz' from 'icalendar' (/usr/local/lib/python3.13/site-packages/icalendar/__init__.py) Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 217, in create source_module: SourceModule = importlib.import_module( ~~~~~~~~~~~~~~~~~~~~~~~^ f"waste_collection_schedule.source.{source_name}" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func return func(*args, **kwargs) File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module return _bootstrap._gcd_import(name[level:], package, level) ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "<frozen importlib._bootstrap>", line 1387, in _gcd_import File "<frozen importlib._bootstrap>", line 1360, in _find_and_load File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked File "<frozen importlib._bootstrap>", line 935, in _load_unlocked File "<frozen importlib._bootstrap_external>", line 1026, in exec_module File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 15, in <module> from waste_collection_schedule.service.ICS import ICS File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 7, in <module> from icalevents import icalevents File "/usr/local/lib/python3.13/site-packages/icalevents/icalevents.py", line 3, in <module> from .icalparser import parse_events, Event File "/usr/local/lib/python3.13/site-packages/icalevents/icalparser.py", line 18, in <module> from icalendar import use_pytz ImportError: cannot import name 'use_pytz' from 'icalendar' (/usr/local/lib/python3.13/site-packages/icalendar/__init__.py)

Second error:

Logger: homeassistant.components.sensor
Quelle: helpers/entity_platform.py:366
Integration: Sensor (Dokumentation, Probleme)
Erstmals aufgetreten: 13:55:14 (8 Vorkommnisse)
Zuletzt protokolliert: 13:55:14

Error while setting up waste_collection_schedule platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/waste_collection_schedule/sensor.py", line 147, in async_setup_platform
    raise ValueError(
        f"source_index {i} out of range (0-{len(api.shells) - 1}) please check your sensor configuration"
    )
ValueError: source_index 0 out of range (0--1) please check your sensor configuration
```

### Relevant Configuration

```YAML
old config not working as well, but here is my "old yaml config", which was working today morning:

configuration.yaml:

waste_collection_schedule:
  sources:
    - name: ics
      args:
        # file: "www/muell.ics"
        url: "https://www.awu-oberhavel.de/fuer-haushalte/zusatzinfos/tourenplan?no_cache=1&export=pap,hm,lvp,bio&city=Oranienburg&street=street"
      customize:
        - type: Hausmüll
          alias: Hausmüll
          icon: mdi:trash-can
        - type: Pappe/Papier
          alias: Pappe/Papier
          icon: mdi:tree
        - type: Leichtstoffverpackungen
          alias: Leichtstoffverpackungen
          icon: mdi:recycle
  fetch_time: "04:00"
  day_switch_time: "10:00"
  separator: ":"


sensors.yaml:

- platform: waste_collection_schedule
  name: Papierabfall_date
  value_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
    - Pappe/Papier

- platform: waste_collection_schedule
  name: Papierabfall_collection
  value_template: "{{value.daysTo}}"
  types:
    - Pappe/Papier

- platform: waste_collection_schedule
  name: Restmuelltonne_date
  value_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
    - Hausmüll

- platform: waste_collection_schedule
  name: Restmuelltonne_collection
  value_template: "{{value.daysTo}}"
  types:
    - Hausmüll

- platform: waste_collection_schedule
  name: Plastiktonne_date
  value_template: '{{value.date.strftime("%d.%m.%Y")}}'
  types:
    - Leichtstoffverpackungen

- platform: waste_collection_schedule
  name: Plastikmuelltonne_collection
  value_template: "{{value.daysTo}}"
  types:
    - Leichtstoffverpackungen

- platform: waste_collection_schedule
  name: next_waste_collection_daysto
  details_format: upcoming
  value_template: '{{value.types|join(", ")}} in {{value.daysTo}} Tagen'

- platform: waste_collection_schedule
  name: MyButtonCardSensor
  value_template: '{{value.types|join(", ")}}|{{value.daysTo}}|{{value.date.strftime("%d.%m.%Y")}}|{{value.date.strftime("%a")}}'
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
