### ISSUE TITLE
FES Frankfurt ICS not working

### ISSUE THREAD

**Issue by hearttheart** [mampfes/hacs_waste_collection_schedule#372]
Hi,

I'm struggling with implementing the ICS from FES Frankfurt. I suspect it's because of some strange characters in the ICS, but I can't get it to work.

ICS: https://www.fes-frankfurt.de/abfallkalender/Um9tYmVyZ3N0ci58OHw2NTkzMQ%3D%3D.ics

The sensors show up but don't have any state.

configuration.yaml:

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://www.fes-frankfurt.de/abfallkalender/Um9tYmVyZ3N0ci58OHw2NTkzMQ%3D%3D.ics
      customize:
        - type: Altpapier
          alias: altpapier
          icon: mdi:trash-can-outline
        - type: Restabfall
          alias: restmuell
          icon: mdi:trash-can
```

sensors.yaml:

```
  - platform: waste_collection_schedule
    name: AbfallRestmuell
    details_format: upcoming
    value_template: 'in {{value.daysTo}} days'
    types:
      - restmuell

  - platform: waste_collection_schedule
    name: AbfallAltpapier
    details_format: upcoming
    value_template: 'in {{value.daysTo}} days'
    types:
      - altpapier
```

**Comment by SimonBusse** [comment]
Hi @hearttheart,
I was struggling with this too. Managed to get it working by:

1. Downloading the ICS as a file and using it instead of the url
2. In the file CTRL+F "Search and Replace" these caracters (in VS Code or any other editor):
 - Replace "\" by ""
 - Replace " / Grüner Punkt " by ""

The unfortunate thing is that you would need to manually refresh this file every year and re-apply those modifications.

Hope this helps. Maybe @mampfes can consider adding support for \ in the ics files in future releases.

**Comment by dt215git** [comment]
Would regex help pull out the collections?

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://www.fes-frankfurt.de/abfallkalender/Um9tYmVyZ3N0ci58OHw2NTkzMQ%3D%3D.ics
        regex: "(^[a-zA-Z]*)\s"
        version: 2
```
Green shows what the regex should return, blue shows what it's matching. In this case it's trying to extract the first word that appears in the SUMMARY field.
![image](https://user-images.githubusercontent.com/86194065/205510502-0e3152fb-20b9-4df6-a512-8082881bbbef.png)

**Comment by humanBeer** [comment]
I cant get this to work.
I added to config.yaml:
```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://www.fes-frankfurt.de/abfallkalender/Sm9oYW5uYS1NZWxiZXItV2VnfDI4fDYwNTk5.ics
        split_at: " \/ "
        regex: "(.*)\\s+\\|"
      customize:
        - type: Altpapier
          alias: altpapier
          icon: mdi:trash-can-outline
        - type: Restabfall
          alias: restmuell
          icon: mdi:trash-can

```
Nothing is showing in the calendar:
![image](https://user-images.githubusercontent.com/47748428/209887473-7ccbaa84-799a-48fb-8242-0668ccf8a1dd.png)

Not sure what to do.
If anyone can point me in a direction
