### ISSUE TITLE
[Feature]: Alias for ICS, multiple ICS sources

### ISSUE THREAD

**Issue by florianru1984** [mampfes/hacs_waste_collection_schedule#3723]
### I propose a feature for:

Sources, The integration in general

### Describe your wanted feature

I added Abfall Kreis Kassel, in HomeAssistant it is labeled as "ICS", is it possible to give another Name? It doesnt work if i rename it.

And i wish to add the collection times from my Workplace, also Abfall Kreis Kassel but another municipality

**Comment by sonovice** [comment]
Use the attribute `calendar_title` as described here:
https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#attributes-for-sources

**Comment by markvp** [comment]
Thanks for raising this, @florianru1984 — both are already supported. Rename an ICS calendar with `calendar_title`, and add the same provider twice with different args/titles for two municipalities:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://...   # home
      calendar_title: "Kassel – Zuhause"
    - name: ics
      args:
        url: https://...   # work
      calendar_title: "Kassel – Arbeit"
```

See the installation docs and ICS source docs for details. Closing as already supported — reopen if you have trouble getting it working.
