### ISSUE TITLE
Waste collection schedule missing for AUSTRIA / NEULENGBACH

### ISSUE THREAD

**Issue by oesterrg** [mampfes/hacs_waste_collection_schedule#3725]
Hi 

missig the wast collection schedule for AUSTRIA / NEULENGBACH.

https://www.neulengbach.gv.at/Stadtgemeinde/Buergerservice/Abfallangelegenheiten/Muellabfuhrtermine

Thx
Ösi

**Comment by boecks** [comment]
Hi, is likely to be fixed with the next release, until then, a possible temporary solution is discussed in #3729

**Comment by markvp** [comment]
Thanks for the report! Neulengbach is already supported by the `umweltverbaende_at` source — it's part of the St. Pölten Land district. Municipalities aren't hard-coded, so you just pass the name:

```yaml
waste_collection_schedule:
  sources:
    - name: umweltverbaende_at
      args:
        district: stpoeltenland
        municipal: Neulengbach
```

Optional `street`/`hnr` args narrow it further. Closing as already supported — reopen if you hit problems.
