### ISSUE TITLE
[Bug]: Abfall.io not working

### ISSUE THREAD

**Issue by miggi92** [mampfes/hacs_waste_collection_schedule#3735]
### I Have A Problem With:

The integration in general

### What's Your Problem

I couldn't set up the Abfall.io integration.
Not via yaml nor config flow.

On the config flow I'm getting the info, that the source did not send any response.

![Image](https://github.com/user-attachments/assets/8b7612e5-a0bf-47e4-a79f-f9213e66025f)

### Source (if relevant)

https://www.aw-landkreis-heilbronn.de/abfall-entsorgen/abfuhrtermine/abfallkalender/

### Logs

```Shell
no relevant logs.
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: abfall_io
      args:
        key: !secret abfall_key
        f_id_kommune: !secret abfall_municipality
        f_id_strasse: !secret abfall_street
        f_abfallarten:
          - 28
```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
