### ISSUE TITLE
[Bug]: Umweltprofis AUSTRIA

### ISSUE THREAD

**Issue by XerxesFB** [mampfes/hacs_waste_collection_schedule#3747]
### I Have A Problem With:

A specific source

### What's Your Problem

Since the new year the old source /API does not work anymore - thus not data is available

It seems that the old API is not supported anymore

https://data.umweltprofis.at/opendata/AppointmentService/index.aspx

Sample Adress: Am Fundbach 24, 4501 Neuhofen

![Image](https://github.com/user-attachments/assets/a0605e9a-79ee-4fc2-bc03-31bd7d23d7bb)

Real Date can be found here https://www.umweltprofis.at/linz_land/module/wann_wird_mein_abfall_abgeholt.html

![Image](https://github.com/user-attachments/assets/84c305e3-3349-4d35-a062-5031a0bab67e)

But how can this data be inegrated in waste collection shedule?

### Source (if relevant)

https://data.umweltprofis.at/opendata/AppointmentService/index.aspx

### Logs

```Shell

```

### Relevant Configuration

```YAML

```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by hwtiziani** [comment]
Same Issue :/

**Comment by cobra1037** [comment]
Same here.

**Comment by tcrnr1** [comment]
The same issue for Schwertberg!

Umweltprofis has changed from webspaced calender to an app calender called "Abfall OÖ"!
Download the app, select your hometown and street and download the .ics-file. Integrate them in Home Assistant!

I hope we get a solution to get the data directly from the app without download the .ics-file.

**Comment by andyboeh** [comment]
You don't need to download the .ics file. You can just copy the URL and paste the into an ICS source.

**Comment by rama1981** [comment]
how do you get an ics file?
When I choose my adress, and I push the button "zum Kalender hinzufügen" the link is:
https://uwpio.gem2go.dev/ical/#####/######/394180,386999,386977

maybe you have an idea.
Thank you very much.

**Comment by andyboeh** [comment]
This link *is* an ICS file - it just doesn't have the ".ics" ending. My config looks like this:

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
         url: https://uwpio.gem2go.dev/ical/20xxx/46xxxx/38xxxx,38xxxx,41xxxx
      customize:
        - type: "Restabfall (2-wöchentlich)"
          alias: Restmüll
        - type: "Gelbe Tonne (zum angegebenem Datum)"
          alias: Gelbe Tonne
        - type: "Altpapier (zum angegebenem Datum)"
          alias: Papier
        - type: "Biotonne"
          alias: Biotonne
          show: false

sensor:
  - platform: waste_collection_schedule
    name: next_collection

  - platform: waste_collection_schedule
    name: next_restmuell_collection
    types:
      - Restmüll

  - platform: waste_collection_schedule
    name: next_papier_collection
    types:
      - Papier

  - platform: waste_collection_schedule
    name: next_gelbetonne_collection
    types:
      - Gelbe Tonne

```
