### ISSUE TITLE
[Source Request]:

### ISSUE THREAD

**Issue by Johnnyd2036** [mampfes/hacs_waste_collection_schedule#3780]
### Municipality / Region

San giovanni teatino(CH) 

### Collection Data Format

As ICS/ICAL file, Something different (add to additional information)

### Additional Information

I don't know how to extract  the data but it's available in junker app(both zone a and b)..

**Comment by bbr111** [comment]
https://differenziata.junker.app/san-giovanni-teatino
maybe this site?

**Comment by bbr111** [comment]
Good news — San Giovanni Teatino is already served by the Junker APP platform this project supports (see https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/junker_app.py). I confirmed it live: the town publishes collections via https://differenziata.junker.app/san-giovanni-teatino with two residential zones ("Zona A" and "Zona B") plus an industrial/commercial zone, exactly as you described.

You can configure it today with:

```yaml
waste_collection_schedule:
  sources:
    - name: junker_app
      args:
        municipality: San Giovanni Teatino
        area: Zona A   # or "Zona B", or "Zona industriale e commerciale"
```

I've opened a small PR (#7035) that adds San Giovanni Teatino to the documented provider list and to the automated test suite so it stays working going forward. Closing this issue once that merges — thanks for the report, and thanks @bbr111 for pointing at the right URL!
