### ISSUE TITLE
[Bug]: Recyclecoach.com (North Port, FL) fails, used to work

### ISSUE THREAD

**Issue by lk229** [mampfes/hacs_waste_collection_schedule#3784]
### I Have A Problem With:

A specific source

### What's Your Problem

I can no longer retrieve data from recyclecoach.com for North Port, FL. 

This has worked fine for the last year or so but I first noticed it failed on Feb. 8. I rolled back to a backup from the previous month, restarted HA and triggered the waste collection schedule fetch, but couldn't get it to retrieve data. 

I can manually go to the data source and retrieve data but I don't know if this is correct or complete.

[](https://[us-api-city.recyclecoach.com/collections?project_id=585&district_id=NPORT&zone_id=zone-z14464&lang_cd=en_US](https://us-api-city.recyclecoach.com/collections?project_id=585&district_id=NPORT&zone_id=zone-z14464&lang_cd=en_US)

### Source (if relevant)

recyclecoach.com

### Logs

```Shell
This error originated from a custom integration.

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
integration: Waste Collection Schedule (documentation)
First occurred: 12:58:18 PM (1 occurrences)
Last logged: 12:58:18 PM

fetch failed for source Recycle Coach: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/recyclecoach_com.py", line 364, in fetch for year in schedule_def["DATA"]: ~~~~~~~~~~~~^^^^^^^^ TypeError: string indices must be integers, not 'str'
```

### Relevant Configuration

```YAML
Configuration.yaml ---

waste_collection_schedule:
  sources:
    - name: recyclecoach_com
      calendar_title: Waste Collection Schedule
      args:
        project_id: 585
        district_id: NPORT
        zone_id: zone-z14464
        street: xxxx
        city: North Port
        state: Florida

Waste.yaml ---
value_template: '{{value.types|join(", ")}}|{{value.daysTo}}|{{value.date.strftime("%d.%m.%Y")}}|{{value.date.strftime("%a")}}'
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
