### ISSUE TITLE
[Source Request]: Knowsley Metropolitan Borough Council

### ISSUE THREAD

**Issue by Audigy01** [mampfes/hacs_waste_collection_schedule#3787]
### Municipality / Region

Knowsley Metropolitan Borough Council L35 2US

### Collection Calendar Webpage

https://knowsleytransaction.mendixcloud.com/index.html

### Collection Data Format

As html on a webpage

**Comment by bbr111** [comment]
Thanks for the request! This is already supported — Knowsley Council has been available since PR #3315 (merged shortly before this issue was opened) as the `knowsley_gov_uk` source, using this same Mendix portal.

You can configure it with your postcode and UPRN, e.g.:
```yaml
waste_collection_schedule:
  sources:
    - name: knowsley_gov_uk
      args:
        postcode: YOUR_POSTCODE
        uprn: YOUR_UPRN
```
You can find your UPRN by searching your address on https://www.findmyaddress.co.uk/search or on the council's bin collection lookup page.

See the docs here: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/knowsley_gov_uk.md

I just re-tested it live and it's still returning correct schedules, so closing this as already supported. Feel free to reopen if you run into any trouble configuring it.
