### ISSUE TITLE
[Source Request]: Trash City Karlsruhe

### ISSUE THREAD

**Issue by Julian272024** [mampfes/hacs_waste_collection_schedule#3794]
### Municipality / Region

Badenwürtemberg Karlsruhe

### Collection Calendar Webpage

https://tsk.karlsruhe.de/abfuhrkalender

### Example Address

Hey Guys,

if its possible to add this link?

Thanks Julian :)

### Collection Data Format

As ICS/ICAL file

**Comment by fft1010** [comment]
Isn't this very similar to
https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/karlsruhe_de.md

**Comment by markvp** [comment]
Thanks for the request, Julian! Good news — Karlsruhe is already covered by the `karlsruhe_de` source, which fetches from the same backend that powers the TSK collection calendar (and the Trash City app):

```yaml
waste_collection_schedule:
  sources:
    - name: karlsruhe_de
      args:
        street: YOUR_STREET
        hnr: YOUR_HOUSE_NUMBER
```

Docs: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/karlsruhe_de.md . Closing as already supported.
