### ISSUE TITLE
[Source Request]: New Providence, NJ

### ISSUE THREAD

**Issue by dannyrussell53** [mampfes/hacs_waste_collection_schedule#3808]
### Municipality / Region

New Providence, NJ

### Collection Calendar Webpage

https://www.newprov.us/common/modules/iCalendar/iCalendar.aspx?catID=26

### Example Address

EAST or WEST

### Collection Data Format

As ICS/ICAL file

**Comment by markvp** [comment]
Thanks for the request! Good news — this works today with the built-in ICS source, no custom module needed. The feed is at `https://www.newprov.us/common/modules/iCalendar/iCalendar.aspx?feed=calendar&catID=26` (the URL in your report returns empty — add `feed=calendar&` before `catID=26`):

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://www.newprov.us/common/modules/iCalendar/iCalendar.aspx?feed=calendar&catID=26"
```

It includes Curbside Recycling EAST/WEST, Recycling – DPW Yard, and Bulk Collection. To keep just your side, add a `filter` on the summary (see the ICS docs). Closing as supported via the generic ICS source.
