### ISSUE TITLE
source request: Zweibrücken 

### ISSUE THREAD

**Issue by deroos89** [mampfes/hacs_waste_collection_schedule#3823]
### Municipality / Region

Zweibrücken (Postleitzahl: 66482)

### Collection Data Format

As PDF Download

**Comment by bbr111** [comment]
https://www.ubzzw.com/servicebereiche/abfall/abfallkalender/

**Comment by bbr111** [comment]
Hi @deroos89, Zweibrücken is already supported by the `ubzzw_de` source (UBZ Umwelt- und Servicebetrieb Zweibrücken, https://www.ubzzw.com). It doesn't use the PDF calendar.

Example configuration:

```yaml
waste_collection_schedule:
  sources:
    - name: ubzzw_de
      args:
        street: Vogesenstraße
        house_number: "75"
```

See https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ubzzw_de.md for details. It can also be added through the Home Assistant UI. If it doesn't work for your address, please open a new bug report that names `ubzzw_de`. Closing as already supported.
