### ISSUE TITLE
[Bug]: Source Korneuburg City

### ISSUE THREAD

**Issue by cg001** [mampfes/hacs_waste_collection_schedule#3834]
### I Have A Problem With:

A specific source

### What's Your Problem

I am not able to fetch data for Korneuburg City. There are three possible sources:
- korneuburg_stadtservice_at
- umweltverbaende_at
- citiesapps_com

With umweltverbaende_at I was able to fetch district: Korneuburg; municipal: Bisamberg; town: Bisamberg so everything works in general. But nothing comes in with: district: Korneuburg; municipal: Korneuburg; town: Korneuburg
Also this delivers no data:
```yaml
    - name: korneuburg_stadtservice_at
      args:
        street_name: ********
        street_number: **
        teilgebiet: 2
```

I was able to run the citiesapp-py-script and get the data for the calendar:
```yaml
waste_collection_schedule:
    sources:
    - name: citiesapps_com
      args:
        city: Korneuburg
        calendar: Teilgebiet 1
        password: ***********
        email: *********@me.com
```

Calendar is created in HA but no data is coming in.

I was also able to setup the Korneuburg-connection via UI "add Integration" an citiesapp but there is also no data.

Any suggestions welcome!

### Source (if relevant)

- korneuburg_stadtservice_at - umweltverbaende_at - citiesapps_com

### Logs

```Shell
no log entries for this context
```

### Relevant Configuration

```YAML

```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
