### ISSUE TITLE
[Bug]: Muellmax is unable to fetch ics data, invalid server response

### ISSUE THREAD

**Issue by xF4m3** [mampfes/hacs_waste_collection_schedule#3839]
### I Have A Problem With:

A specific source

### What's Your Problem

I had a working configuration for over a year and have not changed anything and going by the error, atleast as far as i can understand something on the provider site has changed, it looks like its getting some kind of html file instead of an ics file? It was working until about ~14:00 yesterday.

### Source (if relevant)

muellmax_de

### Logs

```Shell
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 08:19:02 (1 Vorkommnisse)
Zuletzt protokolliert: 08:19:02

fetch failed for source Müllmax: Traceback (most recent call last): File "/usr/local/lib/python3.13/site-packages/icalendar/parser.py", line 326, in parts validate_token(name) ~~~~~~~~~~~~~~^^^^^^ File "/usr/local/lib/python3.13/site-packages/icalendar/parser.py", line 115, in validate_token raise ValueError(name) ValueError: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/muellmax_de.py", line 170, in fetch dates = self._ics.convert(r.text) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert events: List[Any] = icalevents.events( ~~~~~~~~~~~~~~~~~^ start=start_date, end=end_date, string_content=ics_data.encode() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.13/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ~~~~~~~~~~~~^ content, start=start, end=end, tzinfo=tzinfo, sort=sort, strict=strict ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.13/site-packages/icalevents/icalparser.py", line 303, in parse_events calendar = Calendar.from_ical(content) File "/usr/local/lib/python3.13/site-packages/icalendar/cal.py", line 410, in from_ical name, params, vals = line.parts() ~~~~~~~~~~^^ File "/usr/local/lib/python3.13/site-packages/icalendar/parser.py", line 340, in parts raise ValueError( f"Content line could not be parsed into parts: '{self}': {exc}") ValueError: Content line could not be parsed into parts: '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">': <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/muellmax_de.py", line 172, in fetch raise ValueError( "Got invalid response from the server, please recheck your arguments" ) from e ValueError: Got invalid response from the server, please recheck your arguments
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: muellmax_de
      args:
        service: Rsa
        mm_frm_ort_sel: Lohmar
        mm_frm_str_sel: redacted
      customize:
        - type: RSAG Weihnachtsbaumabfuhr
          show: yes
          alias: Weihnachtsbaumabfuhr
          icon: mdi:pine-tree
        - type: RSAG Biotonne Regelabfuhr
          show: yes
          alias: Biotonne
          icon: mdi:leaf
        - type: RSAG Papiertonne 4-wö.
          show: yes
          alias: Papiertonne
          icon: mdi:package-variant
        - type: RSAG Wertstofftonne oder -sack 4-wö.
          show: yes
          alias: Wertstofftonne
          icon: mdi:recycle
        - type: RSAG Restmülltonne 2-wö.
          show: yes
          alias: Restmülltonne
          icon: mdi:delete
      calendar_title: Garbage_Collection
  fetch_time: "05:00"
  day_switch_time: "14:00"
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by woorszt** [comment]
I can confirm this. Same issue but I didn't found a solution. Maybe someone can help here? 

Using v2.7.0 of the plugin

**Comment by bbr111** [comment]
please check with current release

**Comment by a-muecke** [comment]
I can confirm the issue with version 2.11.0 (same mm_frm_ort_sel :D )

**Comment by xF4m3** [comment]
I don't remember what fixed my issue, but i think i deleted the whole Integration and set it up from scratch to fix it. Has been working fine since but i am not sure if i did anything beside that.

**Comment by bbr111** [comment]
Thanks everyone for the reports, and sorry for the long wait.

Good news: this specific case (RSAG / Rhein-Sieg-Kreis, `service: Rsa`, e.g. Lohmar) now has a dedicated, more robust source called **`rsag_de`**, which talks to RSAG's own JSON/ICS API (`rsag.de/api`) instead of scraping the multi-step Müllmax HTML flow that this bug is about. It was added and the old `Rsa` entry was deprecated out of the Müllmax listings in #6553 / #6614.

Please switch your config to:
```yaml
waste_collection_schedule:
  sources:
    - name: rsag_de
      args:
        city: Lohmar
        street: <your street, e.g. Hauptstraße>
```
(Use the exact city/street names as shown on https://www.rsag.de/abfallkalender/abfuhrtermine.)

I re-tested the `rsag_de` source live just now and it returns a full year of correct collection dates for Rhein-Sieg-Kreis addresses. I also re-tested the original `muellmax_de` / `service: Rsa` flow from this issue directly against muellmax.de today, and — for what it's worth — it currently completes successfully too, so whatever HTML change briefly broke it on the provider's side seems to no longer be an issue. Either way, `rsag_de` is the supported path going forward for RSAG.

I'll close this out since a fix is available; please reopen (or file a new issue against `rsag_de`) if you hit any trouble migrating.
