### ISSUE TITLE
[Source Request]: Mornington Peninsula, Australia.

### ISSUE THREAD

**Issue by nBLnzbbBBvSGEd** [mampfes/hacs_waste_collection_schedule#3857]
### Municipality / Region

Mornington Peninsula, Victoria, Australia.

### Collection Calendar Webpage

https://www.mornpen.vic.gov.au/Your-Property/Rubbish-Recycling/Bins/Find-your-bin-day

### Example Address

112-114 Main Street, MORNINGTON ,VIC,3931

### Collection Data Format

As html on a webpage

### Additional Information

URL Encoded HTML response from https://www.mornpen.vic.gov.au/ocapi/Public/myarea/wasteservices?geolocationid=

**Comment by nBLnzbbBBvSGEd** [comment]
I've written the source python script. How do I go about actually adding it to HA to test it thoroughly? I'm running this through HACS, if that makes a difference.

**Comment by markvp** [comment]
Mornington Peninsula is already supported via the `mornpen_vic_gov_au` source. You can configure it via the GUI by selecting **Mornington Peninsula Shire** or via YAML:

```yaml
waste_collection_schedule:
  sources:
    - name: mornpen_vic_gov_au
      args:
        address: "112-114 Main Street, MORNINGTON ,VIC,3931"
```

Closing as already supported.
