### ISSUE TITLE
[Source Request]:

### ISSUE THREAD

**Issue by holger-deppe** [mampfes/hacs_waste_collection_schedule#3876]
### Municipality / Region

ex. Nordhorn, Germany

### Example Address

ex. melleschweg, 48531 nordhorn

### Collection Data Format

As ICS/ICAL file

**Comment by bbr111** [comment]
@holger-deppe 
please provide more Information.

**Comment by bbr111** [comment]
https://awb.grafschaft-bentheim.de/awb/muellabfuhr/abfuhrtermine.php

**Comment by bbr111** [comment]
Hi @holger-deppe,

Good news — Nordhorn (Landkreis Grafschaft Bentheim) is already supported. It runs on the Jumomind platform, which this integration already supports via the `jumomind_de` source.

Configuration for your address:

```yaml
waste_collection_schedule:
  sources:
    - name: jumomind_de
      args:
        service_id: ben
        city: Nordhorn
        street: Melleschweg
```

(`service_id: ben` is Landkreis Grafschaft Bentheim's Jumomind instance, at https://awb.grafschaft-bentheim.de/.) I verified this configuration returns collection dates for Melleschweg, Nordhorn.

No new source needs to be built — you should just be able to add this to your `configuration.yaml`, or configure it via the UI (Settings → Devices & Services → Add Integration → Waste Collection Schedule → jumomind_de → service_id `ben`).

Closing this as already supported. Feel free to reopen if you run into any issues with the configuration above.
