### ISSUE TITLE
Abfallkalender

### ISSUE THREAD

**Issue by sachsenmichel** [mampfes/hacs_waste_collection_schedule#3880]
### Municipality / Region

Leipzig, Deutschland 

### Collection Calendar Webpage

https://stadtreinigung-leipzig.de

### Collection Data Format

As html on a webpage

**Comment by bbr111** [comment]
Leipzig is already fully supported via the `stadtreinigung_leipzig_de` source, which has been in the repository since 2021. You can configure it directly with your street and house number:

```yaml
waste_collection_schedule:
  sources:
    - name: stadtreinigung_leipzig_de
      args:
        street: STREET
        house_number: HOUSE_NUMBER
```

See the docs here: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/stadtreinigung_leipzig_de.md

I just re-tested it live and it's returning current 2026 collection dates without issue, so I'll close this as already resolved. Feel free to reopen if you run into a specific problem configuring it.
