### ISSUE TITLE
[Source Request]:

### ISSUE THREAD

**Issue by BrianK-101** [mampfes/hacs_waste_collection_schedule#3892]
### Municipality / Region

Germantown, Wisconsin

### Collection Calendar Webpage

https://www.wm.com/us/en/mywm/my-services/view-pickup-eta

### Example Address

W168N10345 Wildrose LANE, Germantown, WI 53022

### Collection Data Format

As html on a webpage

### Additional Information

Seems to be pushed to a mobile app

**Comment by bbr111** [comment]
Thanks for the request! Good news — Waste Management (wm.com) is now supported as a generic source: [`wm_com`](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/wm_com.md). It uses the same public guest lookup as the MyWM "View Pickup ETA" page you linked (no account needed) and works for any US/Canada WM service address, so it should cover Germantown, WI.

To set it up, add a source with your street address, city, two-letter state code, and ZIP:

```yaml
waste_collection_schedule:
  sources:
    - name: wm_com
      args:
        street: "Your Street Address"
        city: "Germantown"
        state: "WI"
        zip_code: "Your ZIP"
```

Or via the Home Assistant UI: **Settings → Devices & Services → Add Integration → Waste Collection Schedule**, pick **United States**, then **Waste Management (WM)**.

Closing this as resolved by the existing `wm_com` source — please reopen (or file a new bug report) if it doesn't pick up your schedule correctly.
