### ISSUE TITLE
[Bug]: Portsmouth city council (UK) - maybe changed systems?

### ISSUE THREAD

**Issue by snigehere** [mampfes/hacs_waste_collection_schedule#3914]
### I Have A Problem With:

A specific source

### What's Your Problem

Portsmouth city council have started to move to a new system for rubbish and recycling and do not seem to be maintaining the data on the old system.  My recycling day has changed and that is reflected in the new system but not in the old.  This may be an oversight by the council or it maybe the transition to the new system is going ahead however the council web site is not updated so links on the page about rubbish and recycling still point to the old system. 

The new site is located at https://recyclingandrubbish.portsmouth.gov.uk/ however I am not able to find any details of a replacement API.  I have raised a query with the council and wait their feedback.  I will update the ticket with what I discover.

The new site has authentication that is required before being able to find any information - this may get reflected into any replacement API.

### Source (if relevant)

portsmouth_gov_uk

### Logs

```Shell
N/A as its a data issue rather than an issue with the code
```

### Relevant Configuration

```YAML
# waste collection schedule
waste_collection_schedule:
  sources:
    - name: portsmouth_gov_uk
      args:
        uprn: 1775062139
      customize:
        - type: recycling bin
          icon: mdi:recycle
        - type: refuse bin
          icon: mdi:trash-can
```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
