### ISSUE TITLE
Müllabholung

### ISSUE THREAD

**Issue by Lampe1984** [mampfes/hacs_waste_collection_schedule#3915]
### Municipality / Region

ex. Königsfeld Deutschland

### Example Address

ex. Burgstr. 33 78126 Königsfeld

![Image](https://github.com/user-attachments/assets/66fb546f-bf99-4357-a584-9882fffa25c9)

### Collection Data Format

As ICS/ICAL file

**Comment by bbr111** [comment]
https://www.lrasbk.de/Landratsamt-/%C3%84mter/Amt-f%C3%BCr-Abfallwirtschaft/Abfallkalender/

**Comment by bbr111** [comment]
This is served by the Schwarzwald-Baar-Kreis "Amt für Abfallwirtschaft" via the abfall.io platform, which this integration already supports through the `abfall_io_graphql` source. I've opened a PR adding this provider's key to the supported list, verified against a live query for Königsfeld: https://github.com/mampfes/hacs_waste_collection_schedule/pull/7031

Once merged, you can configure it with:

```yaml
waste_collection_schedule:
  sources:
    - name: abfall_io_graphql
      args:
        key: "30628292bdd8b43db86a48f7e0d85f85"
        idHouseNumber: 16437
```

This covers the municipality of Königsfeld as a whole (the provider doesn't split by individual street/house number for this town). Thanks for the report!
