### ISSUE TITLE
[Bug]: ICS source - Content line could not be parsed into parts: ' BEGIN:VCALENDAR': BEGIN

### ISSUE THREAD

**Issue by Korndaweizen** [mampfes/hacs_waste_collection_schedule#3917]
### I Have A Problem With:

A specific source

### What's Your Problem

Hi there, since today I am experiencing the following error for an ics source (Würzburg).
The config was working in the past and I did not make any changes in any config.

The only change I can think of is updating HA from 2025.3.2 to 2025.3.3.

### Source (if relevant)

https://www.wuerzburg.de/themen/umwelt-klima/abfall-und-stadtreinigung/abfallkalender/ics?ev[addr]=19944

### Logs

```Shell
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 12:41:26 (1 Vorkommnisse)
Zuletzt protokolliert: 12:41:26

fetch failed for source ICS: Traceback (most recent call last): File "/usr/local/lib/python3.13/site-packages/icalendar/parser.py", line 326, in parts validate_token(name) ~~~~~~~~~~~~~~^^^^^^ File "/usr/local/lib/python3.13/site-packages/icalendar/parser.py", line 115, in validate_token raise ValueError(name) ValueError: BEGIN During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 207, in fetch return self.fetch_url(self._url, self._params) ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 235, in fetch_url return self._convert(r.text) ~~~~~~~~~~~~~^^^^^^^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 250, in _convert dates = self._ics.convert(data) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert events: List[Any] = icalevents.events( ~~~~~~~~~~~~~~~~~^ start=start_date, end=end_date, string_content=ics_data.encode() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.13/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ~~~~~~~~~~~~^ content, start=start, end=end, tzinfo=tzinfo, sort=sort, strict=strict ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.13/site-packages/icalevents/icalparser.py", line 303, in parse_events calendar = Calendar.from_ical(content) File "/usr/local/lib/python3.13/site-packages/icalendar/cal.py", line 410, in from_ical name, params, vals = line.parts() ~~~~~~~~~~^^ File "/usr/local/lib/python3.13/site-packages/icalendar/parser.py", line 340, in parts raise ValueError( f"Content line could not be parsed into parts: '{self}': {exc}") ValueError: Content line could not be parsed into parts: ' BEGIN:VCALENDAR': BEGIN
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: ics
      calendar_title: Abfallkalender
      day_offset: 1
      args:
        url: https://www.wuerzburg.de/themen/umwelt-klima/abfall-und-stadtreinigung/abfallkalender/ics?ev[addr]=19944

sensor:
  - platform: waste_collection_schedule
    name: Abfall
    details_format: upcoming
    value_template: '{{value.types|join(", ")}}{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} in {{value.daysTo}} Tagen{% endif %}'
    add_days_to: true
```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
