### ISSUE TITLE
[Source Request]: Lonsee, Germany

### ISSUE THREAD

**Issue by Pageworker1957** [mampfes/hacs_waste_collection_schedule#3932]
### Municipality / Region

Lonsee, Germany

### Example Address

[Abfallkalender2025.pdf](https://github.com/user-attachments/files/19350116/Abfallkalender2025.pdf)

### Collection Data Format

As PDF Download

### Additional Information

[Abfallkalender2025.pdf](https://github.com/user-attachments/files/19350132/Abfallkalender2025.pdf)

**Comment by bbr111** [comment]
https://albdonaukreis.buergerportal.digital/calendar/

**Comment by bbr111** [comment]
Hi! Lonsee is in the Alb-Donau-Kreis, whose waste calendar runs on the Bürgerportal platform. It is already supported by the existing **Bürgerportal** source (`buergerportal_de`, operator `alb_donau`, listed as "Abfallwirtschaft Alb-Donau-Kreis"). Lonsee is available in that portal's location list.

To set it up, add the source with `operator: alb_donau`, then enter your district (`Lonsee`), your street and your house number as they appear on https://albdonaukreis.buergerportal.digital/calendar/. See the docs: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/buergerportal_de.md

Example:
```yaml
waste_collection_schedule:
  sources:
    - name: buergerportal_de
      args:
        operator: alb_donau
        district: Lonsee
        street: <your street>
        number: <your house number>
```
If you have trouble, please open a new issue with the details. Closing as already supported. Making individual towns discoverable is tracked in #7563. Thanks to @bbr111 for the pointer!
