### ISSUE TITLE
[Source Request]: Source Request for Waste Collection in Campo, Quesada, San Carlos, Alajuela, Costa Rica

### ISSUE THREAD

**Issue by danivar2** [mampfes/hacs_waste_collection_schedule#3934]
### Municipality / Region

Campo, Quesada, San Carlos, Alajuela, Costa Rica

### Collection Calendar Webpage

https://www.munisc.go.cr/Paginas/Visitantes/Noticias.aspx?idnoticia=38

### Example Address

8HRF+VR9, Provincia de Alajuela, Cd Quesada, Barrio El Campo

### Collection Data Format

As html on a webpage

### Additional Information

Recycling collection days:

Monday (weeks 1 and 3 of the month)

Regular trash collection:

Every Tuesday and Friday at 10 am.

**Comment by bbr111** [comment]
Thanks for the request!

Looking at the linked page, it turns out this isn't actually a live, queryable schedule API — it's a single static news article (a one-time 2014 announcement about the start of the recycling route) that maps neighborhoods to a fixed weekday. There's no per-address lookup, so a dedicated source module would just be hardcoding this same static mapping, which isn't something we can build a maintainable integration on top of (the announcement page itself could disappear or become outdated at any time).

The good news is that the schedule you described is a fixed, recurring pattern that this integration already supports out of the box via the built-in `static` source — no custom source code needed. Based on what you posted:

- Recycling: 1st and 3rd Monday of the month
- Regular trash: every Tuesday and Friday

You can configure both like this in `configuration.yaml`:

```yaml
waste_collection_schedule:
  sources:
    - name: static
      args:
        type: Recycling (reciclaje)
        frequency: MONTHLY
        start: "2024-01-01"
        weekdays: { MO: 1 }
    - name: static
      args:
        type: Recycling (reciclaje)
        frequency: MONTHLY
        start: "2024-01-01"
        weekdays: { MO: 3 }
    - name: static
      args:
        type: Regular trash (basura)
        frequency: WEEKLY
        weekdays: { TU: 1, FR: 1 }
```

Full documentation for all the options (excludes, until/count, other weekday patterns, etc.) is here: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md

Since this can already be configured today without a new source, I'll close this as resolved by an existing feature. Feel free to reopen or comment if your municipality later publishes a real address-lookup calendar tool (JSON/ICS/HTML with per-address search) — that would be a good candidate for a dedicated source.
