### ISSUE TITLE
[Source Request]: Waste calender of Sollenau / NÖ / Austria

### ISSUE THREAD

**Issue by bernd-de** [mampfes/hacs_waste_collection_schedule#3958]
### Municipality / Region

Sollenau

### Collection Calendar Webpage

https://sollenau.noe.gv.at/umwelt/muellkalender/

### Example Address

Hauptplatz 1, 2601 Sollenau

### Collection Data Format

As html on a webpage

**Comment by bbr111** [comment]
Thanks for the request! Sollenau's waste calendar is available as a public Google Calendar ICS feed — the same approach used by Markt Piesting Dreistetten in this repo. A PR has been opened (#6696).

Once merged, you can configure it like this:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://calendar.google.com/calendar/ical/muellsollenau%40gmail.com/public/basic.ics
```

The single feed contains all waste types for the whole municipality (Restmüll, Biomüll, Papier, Gelber Sack, Altkleidersammlung). No address lookup is needed.
