### ISSUE TITLE
[Source Request]:

### ISSUE THREAD

**Issue by ralfgroenendijk** [mampfes/hacs_waste_collection_schedule#3984]
### Municipality / Region

Maastricht, The Netherlands

### Collection Calendar Webpage

https://mijnafval.maastricht.nl/kalender

### Example Address

Minervahof 34, 6215VK, Maastricht

### Collection Data Format

As html on a webpage

**Comment by Avie238** [comment]
You can just use the rd4 source it's what the website uses in the background

**Comment by markvp** [comment]
Thanks for the request! Good news — Maastricht is already supported. The city is served by [Rd4](https://rd4.nl/), and there's an existing source for it: **`rd4_nl`**.

Configure it with your postal code and house number:

```yaml
waste_collection_schedule:
  sources:
    - name: rd4_nl
      args:
        postal_code: 6215 VK
        house_number: 34
```

Full documentation is at [doc/source/rd4_nl.md](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/rd4_nl.md).

Closing this as already supported.
