### ISSUE TITLE
[Source Request]: Novara Quartiere Sud-Est

### ISSUE THREAD

**Issue by AlbyDilu90** [mampfes/hacs_waste_collection_schedule#3987]
### Municipality / Region

Novara

### Collection Calendar Webpage

https://assanovara.trasparenzarifiuti.it/rt/calendario-raccolta-assa-novara/

### Example Address

Corso XXIII Marzo 200, Novara I-28100

### Collection Data Format

Dedicated IOS/Android APP

### Additional Information

Available on Junker app

**Comment by markvp** [comment]
Thanks for the report! Novara is served by the Junker app, which this project already integrates via the `junker_app` source — so you can configure it right now:

```yaml
waste_collection_schedule:
  sources:
    - name: junker_app
      args:
        municipality: Novara
        area: "Quartiere Sud Est - Bicocca, Olengo"
```

All 13 Novara quartieri are available as `area` values (Centro, Nord, Nord Est, Ovest, Pernate, Porta Mortara, Sacro Cuore, San Martino, Santa Rita, Sant'Agabio, Sud, Sud Est - Bicocca/Olengo, Lumellogno…). Novara isn't yet in the UI municipality picker — I'll add it there in a follow-up so it's discoverable from the setup flow. Leaving this open to track that.
