### ISSUE TITLE
[Bug]: AWIGO doesnt work sice update to HAOS15.1

### ISSUE THREAD

**Issue by mircebirke1399** [mampfes/hacs_waste_collection_schedule#3993]
### I Have A Problem With:

A specific source

### Problem
Suddenly stopped working since Update to 15.1

### LOG
```
fetch failed for source AWIGO Abfallwirtschaft Landkreis Osnabrück GmbH: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/awigo_de.py", line 63, in fetch r.raise_for_status() ~~~~~~~~~~~~~~~~~~^^ File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 404 Client Error: eID not registered for url: https://www.awigo.de/index.php?eID=awigoCalendar&calendar[method]=getCities&calendar[rest]=1&calendar[paper]=1&calendar[yellow]=1&calendar[brown]=1&calendar[mobile]=1
```

### Configuration
```
waste_collection_schedule:
  sources:
    - name: awigo_de
      args:
        ort: Quakenbrück
        strasse: XX.
        hnr: "XX"
  fetch_time: "04:00"
  day_switch_time: "10:00"
```
```
- platform: waste_collection_schedule
  name: "Gelber Sack"
  details_format: "upcoming"
  value_template: "{{ value.daysTo }}"
  add_days_to: True
  types:
    - Gelbe Tonne/Gelben Sack
# Nächste Abholung Restmül
- platform: waste_collection_schedule
  name: "Restmüll"
  details_format: "upcoming"
  value_template: "{{ value.daysTo }}"
  add_days_to: True
  types:
    - Restmülltonne
# Nächste Abholung Bio Tonne
- platform: waste_collection_schedule
  name: "Bio-Abfall"
  details_format: "upcoming"
  value_template: "{{ value.daysTo }}"
  add_days_to: True
  types:
    - Bio-Tonne
#Nächste Abholung Papiermüll
- platform: waste_collection_schedule
  name: "Papiermüll"
  details_format: "upcoming"
  value_template: "{{ value.daysTo }}"
  add_days_to: True
  types:
    - Papiermülltonne
#Nächstes Schadstoffmobil
- platform: waste_collection_schedule
  name: "Schadstoffmobil"
  details_format: "upcoming"
  value_template: "{{ value.daysTo }}"
  add_days_to: True
  types:
    - "Schadstoffmobil (Theisstraße Neuer Markt, 16:00-18:00 Uhr)"
```

### Logs

```Shell

```

### Relevant Configuration

```YAML

```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
