### ISSUE TITLE
[Bug]: AHA Region Hannover hat jetzt "*" in ihrem Kalender, nichts geht mehr

### ISSUE THREAD

**Issue by Flashx1979** [mampfes/hacs_waste_collection_schedule#3998]
### I Have A Problem With:

The integration in general

### What's Your Problem

Hallo zusammen,
in unserem Abfallkalender bei AHA Region Hannover, sind neuerdings "*" bei manchen Abholterminen angelegt. 
Diese werden einfach übersprungen.
Hat jemand eine Idee?

### Logs

```Shell

```

### Relevant Configuration

```YAML

```

### Checklist Source Error

- [ ] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by hseliger** [comment]
You closed the issue, so did you get it solved? I am having the same problem: aha seems to mark the next upcoming dates with the asterisk '*' and those dates are then ignored, which leads to HA always showing the second upcoming, not the next one. Useless this way.
I am on the newest release version 2.8.0.
How did you solve it?

**Comment by hseliger** [comment]
Just to document for others, in case you stumble over this: seems the code pulls the ical-calendar off the aha website. In that, aha seems to also have marked the next upcoming collection with an asterisk, such as "Papier *". So to fix this, configure the sensor to check for two different types, such as:
```
- platform: waste_collection_schedule
  name: "Restmüll"
  value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}In {{value.daysTo}} Tagen{% endif %}'
  types:
    - Restabfall
    - Restabfall *
```
