### ISSUE TITLE
[Bug]: Peterborough UK API change

### ISSUE THREAD

**Issue by skipishere** [mampfes/hacs_waste_collection_schedule#4020]
### I Have A Problem With:

A specific source

### What's Your Problem

In the last week I noticed the bin collection information was no longer populated. While investigating it appears the old end point `https://www.peterborough.gov.uk/api/jobs/{start}/{end}/{uprn}` is no longer available.

Apart from scrapping the result pages, it appears that the best way now to get the data is to hit a new(?) iCal endpoint which is `https://report.peterborough.gov.uk/waste/{postcode}:{uprn}/calendar.ics`.
The address look up still appears to work but this will mean that people that have configured to only use the UPRN alone would be broken as the postcode is now required (an additional reverse look up of UPRN to address would  be an alternative but given the extra work to do this for a minor configuration change and the need for an API key to access that data https://docs.os.uk/os-apis/accessing-os-apis/os-places-api/getting-started-with-example-queries-using-node.js I think a breaking change here would be acceptable)

From quick experimenting using the iCal works 
```yaml
waste_collection_schedule:
  sources:
#    - name: peterborough_gov_uk
#      args:
#        uprn: 10000000000
    - name: ics
      args:
        url: "https://report.peterborough.gov.uk/waste/PE9%201AA:10000000000/calendar.ics"
      customize:
        - type: Empty Bin 240L Black
          alias: rubbish
        - type: Empty Bin 240L Green
          alias: recycling
  fetch_time: "12:00"
  day_switch_time: "20:01"
```
Where `PE9%201AA` is the postcode with %20 instead of space (e.g. `PE9 1AA`) and `10000000000` is the UPRN

I'm happy to either programmatically fix the source and read in the iCal info or to update the docs to tell users to explicitly use iCal source for Peterborough.

### Source (if relevant)

peterborough_gov_uk

### Logs

```Shell

```

### Relevant Configuration

```YAML

```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [ ] Checked that the website of your service provider is still working
- [ ] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
