### ISSUE TITLE
Abfallkalender

### ISSUE THREAD

**Issue by larskoehler77** [mampfes/hacs_waste_collection_schedule#4043]
### Municipality / Region

Wuppertal

### Collection Calendar Webpage

https://awg-wuppertal.de/privatkunden/abfallkalender.html?tx_bwwastecalendar_pi1%5Baction%5D=month&tx_bwwastecalendar_pi1%5Bcontroller%5D=Calendar&tx_bwwastecalendar_pi1%5Bstreetname%5D=749&cHash=c7d4cd038cd936d368936a95ca43b591

### Collection Data Format

As ICS/ICAL file

**Comment by dt215git** [comment]
Have you tried the [iCal/ICS](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md#configuration-via-configurationyaml) source?

**Comment by markvp** [comment]
Hi @larskoehler77 — good news, AWG Wuppertal is already supported!

You can use the `awg_wuppertal_de` source. Configure it in your `configuration.yaml` with your street name:

```yaml
waste_collection_schedule:
  sources:
    - name: awg_wuppertal_de
      args:
        street: "Hauptstraße"  # replace with your street name
```

Full documentation including how to find your street name is here:
https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/awg_wuppertal_de.md

Closing this as already supported — let us know if you run into any trouble!
