### ISSUE TITLE
[Source Request]: Tasmania Australia North West Resource Recovery & Recycling

### ISSUE THREAD

**Issue by MankiniChykan** [mampfes/hacs_waste_collection_schedule#4053]
### Municipality / Region

Devonport Tasmania

### Collection Calendar Webpage

https://www.nwrrr.com.au/map

### Example Address

**Enter Address:**
18 Tucker Av, Devonport, Tasmania, 7310, AUS

or
**Select Location:**
Devonport City

### Collection Data Format

As html on a webpage, Something different (add to additional information)

### Additional Information

The website provides a map selector, utilising google location.

Unsure how it pulls the data.

Covers 8 Councils in the North West of Tasmania

![Image](https://github.com/user-attachments/assets/2e18dd94-2908-4c15-b5ef-8c186c4c029f)

**Comment by markvp** [comment]
Thanks for the request! I've implemented a new `nwrrr_com_au` source for the North West Resource Recovery & Recycling service covering all 8 councils in north-west Tasmania (Burnie, Central Coast, Circular Head, Devonport, Kentish, Latrobe, Waratah Wynyard, and West Coast).

A PR is on its way. Configuration will look like this:

```yaml
waste_collection_schedule:
    sources:
    - name: nwrrr_com_au
      args:
        municipality: Devonport
        region: "Devonport (Thursday)"
```

Visit https://www.nwrrr.com.au/map and use the 'Select Location' panel to find your municipality and region name.
