### ISSUE TITLE
[Source Request]:

### ISSUE THREAD

**Issue by 7xy** [mampfes/hacs_waste_collection_schedule#4071]
### Municipality / Region

Landkreis Neuburg-Schrobenhausen

### Collection Calendar Webpage

https://www.landkreisbetriebe.de/rund-um-die-tonne/abfuhrtermine.html

### Example Address

Kabisstraße 9, 86561 Aresing

### Collection Data Format

Dedicated IOS/Android APP

**Comment by markvp** [comment]
Hi @7xy — good news: Landkreis Neuburg-Schrobenhausen is already supported via the [AWIDO Online](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/awido_de.md) source (`awido_de`).

Use this configuration (adjust `city`, `street`, and `housenumber` to match your address — based on your example of Kabisstraße 9, Aresing):

**YAML configuration:**
```yaml
waste_collection_schedule:
  sources:
    - name: awido_de
      args:
        customer: landkreisbetriebe
        city: Aresing
        street: Kabisstraße
        housenumber: 9
```

**UI (Config Flow):**
Select "AWIDO Online" as the source, then enter `landkreisbetriebe` for customer, your city, street, and house number.

See the [full documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/awido_de.md) for more details. Closing this as already supported.
