### ISSUE TITLE
[Bug]: AHA Region Hannover - no data

### ISSUE THREAD

**Issue by Wigand0815** [mampfes/hacs_waste_collection_schedule#4082]
### I Have A Problem With:

A specific source

### What's Your Problem

Hi, unfortunately, the data retrieval no longer works (without external intervention), most likely in connection with one of the last system updates (message ‘unknown’). The configuration of the source also appears unchanged. The data in YAML is unchanged and correct.  HA Calendar ist empty. Thank you for your support.

### Source (if relevant)

aha_region_de

### Logs

```Shell

```

### Relevant Configuration

```YAML
# Waste_Collection_Schedule
waste_collection_schedule:
    sources:
      name: aha_region_de
      args:
        gemeinde: Hannover
        strasse: xxxxxxxxx. / Kirchrode
        hnr: "xx"
        zusatz: ""
```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
