### ISSUE TITLE
configuration.yaml can't be verified, no error shown

### ISSUE THREAD

**Issue by MaiKaY** [mampfes/hacs_waste_collection_schedule#409]
Hi there,

### Issue
I was trying to configure the `waste_collection_schedule` integration based on this [YouTube video](https://www.youtube.com/watch?v=aCKLKGYiA7w)
To verify the configurations I went to "Developer Tools -> Check Configuration", after clicking the button there is just an infinite loading animation, I waited a very long time without any provided errors. I also checked the network tab in my browser tools and the request keep staying in "pending".

**In concrete**: with the provided configuration from the video or from the README of this repository the `waste_collection_schedule` integration does not work on my system.

### System
```
Home Assistant 2022.10.5
Supervisor 2022.10.0
Operating System 9.2
Frontend 20221010.0 - latest
Waste Collection Schedule: 1.28.0
```

### Configuration
My `/config/configuration.yaml` looks as the following

```

# Loads default set of integrations. Do not remove.

frontend:
  themes: !include_dir_merge_named themes

default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

waste_collection_schedule:
  sources:
    - name: awsh_de
      args:
        city: "XXX"
        street: "XXX"
      customize:
        - type: "Restabfall 40L-80L(4-wöchentlich)"
          alias: rest
          icon: mdi:trash-can
        - type: "Papiertonne(monatlich)"
          alias: papier
          icon: mdi:trash-can
        - type: "Wertstoff/LVP(2-wöchentlich)"
          alias: wertstoff
          icon: mdi:trash-can
        - type: "Bioabfall(2-wöchentlich)"
          alias: bio
          icon: mdi:trash-can

sensor:
  # Abfall
  - platform: waste_collection_schedule
    name: abfallnaechster
    details_format: "upcoming"
    value_template: "{{ value.daysTo }}"
```

Do you have an idea why the configuration seems to be broken? Did I miss an important piece?
