### ISSUE TITLE
[Bug]: Unable to use Generic source for 1 weekday multiple times a week

### ISSUE THREAD

**Issue by stevenctran** [mampfes/hacs_waste_collection_schedule#4097]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

I am unable to create a schedule with multiple frequencies on the same day. I am trying to schedule it for every 2nd and 4th Thursday using a generic source, but when I submit the schedule, it creates a monthly frequency for today's date. Please see the attached images and let me know if you require any additional information.
Same weekday on the 2nd and 4th:
![Image](https://github.com/user-attachments/assets/12b2e058-f7e0-440d-9a7f-efb45bb69b2a)

![Image](https://github.com/user-attachments/assets/811d8f6f-2d12-4563-b0b1-9327cf155c81)

Different weekdays on the 2nd and 4th:

![Image](https://github.com/user-attachments/assets/29661b23-d954-4a62-9c3b-bae921cdc162)

![Image](https://github.com/user-attachments/assets/c4c9b34b-7ada-415f-9faf-fd2216b960bc)

### Logs

```Shell

```

### Relevant Configuration

```YAML

```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.

**Comment by dt215git** [comment]
I suspect the problem arises because `{ TH: 2, TH: 4 }`  is effectively a dictionary with two identical keys, so  one key is overwriting the other key, and that's messing up the underlying processing of days/dates. `{ TH: 2, FR: 4 }` are different keys, so the issue is avoided.

I'm not sure how you'd work around that without changing how the weekday patterns would have to be provided, and subsequently handled, to avoid generating duplicates during processing.

The simplest solution would be to add two static sources, one with `TH: 2` and the other with `TH: 4`. Alternatively, you could wrap them both in a [multiple source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/multiple.md) with a yaml config like this:

```yaml
waste_collection_schedule:  sources
    - name: multiple
      args:
        static:
          - type: "2nd TH"
            frequency: "MONTHLY"
            interval: 1
            weekdays: {TH: 2}
            start: "2025-05-08"
            until: "2025-12-31"
          - type: "4th TH"
            frequency: "MONTHLY"
            interval: 1
            weekdays: {TH: 4}
            start: "2025-05-08"
            until: "2025-12-31"
```

![Image](https://github.com/user-attachments/assets/2b8743c9-606c-4497-b2c6-2bfa25a14127)
