### ISSUE TITLE
AW Harburg throws

### ISSUE THREAD

**Issue by monoboy-hh** [mampfes/hacs_waste_collection_schedule#410]
With 1.28.0 fetching the calendar for aw_harburg_de stopped working.
Last working version probably was 1.26.x +- ... (skipped some updates)
config:```
```

waste_collection_schedule:
  sources:
    - name: aw_harburg_de
      args:
        level_1: "XXX"
        level_2: "YYY"
      customize:
        - type: Hausmüll 14-täglich
          alias: "waste"
          icon: mdi:trash-can
        - type: Gelber Sack
          alias: "recycle"
          icon: mdi:recycle
        - type: Altpapier
          alias: "paper"
          icon: mdi:trash-can-outline
  fetch_time: "04:00"
  day_switch_time: "10:00"
```
level_1 + 2 are set to real levels according to website and were not changed
Pls find log attached
```

Logger: waste_collection_schedule.scraper
Source: custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py:143
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 17:00:41 (1 occurrences)
Last logged: 17:00:41
fetch failed for source AW Harburg: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/scraper.py", line 141, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/aw_harburg_de.py", line 108, in fetch dates = self._ics.convert(r.text) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 38, in convert events: List[Any] = icalevents.events( File "/usr/local/lib/python3.10/site-packages/icalevents/icalevents.py", line 50, in events found_events += parse_events(content, start=start, end=end) File "/usr/local/lib/python3.10/site-packages/icalevents/icalparser.py", line 250, in parse_events raise ValueError('Content is invalid!') ValueError: Content is invalid!
```
