### ISSUE TITLE
[Bug]: Aha Region Hannover doesnt work

### ISSUE THREAD

**Issue by maryjam01** [mampfes/hacs_waste_collection_schedule#4115]
### I Have A Problem With:

The integration in general

### What's Your Problem

The Integration does`t load any data

<img width="570" alt="Image" src="https://github.com/user-attachments/assets/f00f0964-7ef8-4b54-b1ed-ef4624f94824" />

### Logs

```Shell
Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Quelle: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
Integration: Waste Collection Schedule (Dokumentation)
Erstmals aufgetreten: 11. Mai 2025 um 11:56:31 (2 Vorkommnisse)
Zuletzt protokolliert: 01:35:11

fetch failed for source Zweckverband Abfallwirtschaft Region Hannover: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/aha_region_de.py", line 94, in fetch raise SourceArgumentNotFoundWithSuggestions( "strasse", self._strasse, [select.text for select in selects] ) waste_collection_schedule.exceptions.SourceArgumentNotFoundWithSuggestions: We could not find values for the argument 'strasse' with the value 'Dürerweg / Wennigsen', you may want to use one of the following: ['Ahlerstr. / Wennigsen', 'Ahornstr. / Wennigsen', 'Akazienstr. / Wennigsen', 'Albert-Einstein-Str. / Wennigsen', 'Am Bache / Holtensen', 'Am Berge / Holtensen', 'Am Brink / Bredenbeck', 'Am Brunnen / Argestorf', 'Am Elfenhain / Wennigsen', 'Am Försterhof / Bredenbeck', 'Am Haselstrauch / Wennigsen', 'Am Häuserhof / Wennigsen', 'Am Hohen Holze / Bredenbeck', 'Am Kindergarten / Degersen', 'Am Kleinen Felde / Holtensen', 'Am Klostergarten / Wennigsen', 'Am Klosterkamp / Bredenbeck', 'Am Markt / Bredenbeck', 'Am Niederhof / Degersen', 'Am Rosenhag / Wennigser Mark', 'Am Rotdorn / Wennigser Mark', 'Am Rübekamp / Bredenbeck', 'Am Schleifbach / Wennigser Mark', 'Am Schönen Hoope / Bredenbeck', 'Am Sportplatz / Holtensen', 'Am Tongrund / Bredenbeck', 'Am Waldkater / Wennigsen', 'Am Waldwinkel / Wennigser Mark', 'Am Wehr / Wennigsen', 'Am Weingarten / Degersen', 'Am Westerholz / Wennigser Mark', 'Am Wiesengrunde / Bredenbeck', 'Am Wiesenhang / Wennigser Mark', 'Am Wolfshagen / Steinkrug', 'Am Ziegengarten / Holtensen', 'Amselweg / Wennigsen', 'An den Pappeln / Degersen', 'An den Rottekuhlen / Bredenbeck', 'An der B217 / Evestorf', 'An Der Beeke / Bredenbeck', 'An der Feuerwache / Wennigsen', 'An Der Kapelle / Sorsum', 'An der Kirche / Holtensen', 'An Der Wende / Bredenbeck', 'Angerweg / Bredenbeck', 'Annaturm / Wennigsen', 'Argestorfer Str. / Wennigsen', 'Asternstr. / Bredenbeck', 'Auf der Glashütte / Steinkrug', 'Auf der Weide / Bredenbeck', 'August-Warnecke-Weg / Bredenbeck']
```

### Relevant Configuration

```YAML
#Abfall
waste_collection_schedule:
    sources:
    - name: aha_region_de
      args:
        gemeinde: Wennigsen
        strasse: Ahlerstr. / Wennigsen
        hnr: "63
        zusatz: ""
      customize:
        - type: Restabfall
          alias: restabfall
          icon: mdi:trash-can
        - type: Leichtverpackungen
          alias: gelbersack
          icon: mdi:trash-circle
        - type: Papier
          alias: papier
          icon: mdi:trash-circle
        - type: Bioabfall
          alias: bioabfall
          icon: mdi:trash-circle
```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
