### ISSUE TITLE
[Source Request]: Ostprignitz-Ruppin

### ISSUE THREAD

**Issue by Rayden1981** [mampfes/hacs_waste_collection_schedule#4135]
### Municipality / Region

Breddin

### Collection Calendar Webpage

https://www.ostprignitz-ruppin.de/Informationen/index.php?ModID=48&object=tx%2C3039.2455.1&La=1&NavID=3033.2&kuo=2&locid=3033.77&pois=3033.77&poir=&poiname=Breddin+-+alle+Stra%DFen++%28Ostprignitz-Ruppin%29&typ=jahr&halbjahr=2&jahr=2025

### Collection Data Format

Dedicated IOS/Android APP

**Comment by markvp** [comment]
Thanks for the request! Good news — Ostprignitz-Ruppin is already supported by the `ostprignitz_ruppin_de` source.

For Breddin specifically, there is only one schedule entry (all streets are grouped together), so your configuration would be:

```yaml
waste_collection_schedule:
    sources:
    - name: ostprignitz_ruppin_de
      args:
        location: Breddin
        street: "Breddin - alle Straßen  (Ostprignitz-Ruppin)"
```

See the [source documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ostprignitz_ruppin_de.md) for full setup instructions.
