### ISSUE TITLE
[Source Request]: Please add city "Senden" ID 53710 (MyMuell)

### ISSUE THREAD

**Issue by hellgate42** [mampfes/hacs_waste_collection_schedule#4162]
### Municipality / Region

Senden, Germany

### Example Address

municipal: '53710'  # ID der Stadt Senden

### Collection Data Format

As documented API

**Comment by j0yze** [comment]
Since 2025, The City "Senden" in Bavaria is available in MyMuell App.

Example Adress
Birkenweg (Senden)

Is there anybody who can add this city to the sources?

**Comment by bbr111** [comment]
Thanks for the report, and thanks @j0yze for confirming availability via the MyMuell App!

Senden is already served by the MyMuell backend used by this integration's Jumomind/MyMuell source (`service_id: mymuell`) — it just wasn't listed yet. I've opened a PR to add it: https://github.com/mampfes/hacs_waste_collection_schedule/pull/7016

Once merged, you can configure it with:

```yaml
waste_collection_schedule:
  sources:
    - name: jumomind_de
      args:
        service_id: mymuell
        city: Senden
        street: Birkenweg (Senden)   # use your own street; include the "(Senden)" district suffix exactly as shown by the app
```

Note: the numeric ID `53710` mentioned in the original issue doesn't match what the live API returns for Senden (it's `57310`) — but that only matters for the deprecated `city_id`/`area_id` parameters; the `city`/`street` parameters above are the recommended way to configure it and don't need any ID.
