### ISSUE TITLE
[Source Request]: East Suffolk Council

### ISSUE THREAD

**Issue by CoderHarry98** [mampfes/hacs_waste_collection_schedule#4172]
### Municipality / Region

East Suffolk, UK

### Collection Calendar Webpage

https://my.eastsuffolk.gov.uk/service/Bin_collection_dates_finder

### Example Address

ip12 1db

### Collection Data Format

As html on a webpage

**Comment by bbr111** [comment]
Good news — East Suffolk Council is now supported! A source (`eastsuffolk_gov_uk`) was added in #6910 using the same "Bin collection dates finder" API linked in this issue.

To set it up, you'll need your UPRN (Unique Property Reference Number), which you can find at the [bin collection dates finder](https://my.eastsuffolk.gov.uk/service/Bin_collection_dates_finder) or at [findmyaddress.co.uk](https://www.findmyaddress.co.uk/). Then configure it like this:

```yaml
waste_collection_schedule:
  sources:
    - name: eastsuffolk_gov_uk
      args:
        uprn: "YOUR_UPRN_HERE"
```

Full documentation: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/eastsuffolk_gov_uk.md

Closing this as resolved — please reopen if you run into any issues with the new source. Thanks for the request!
