### ISSUE TITLE
[Bug]: Source IRIS Salten, Norway stopped working

### ISSUE THREAD

**Issue by p-t-e-r** [mampfes/hacs_waste_collection_schedule#4194]
### I Have A Problem With:

A specific source

### What's Your Problem

Thanks for a great integration, and for the help adding IRIS Salten about two years ago. It's been working flawless but they have changed their API now. Could you look into updating the source?

Thanks in advance :)

### Source (if relevant)

iris_salten_no

### Logs

```Shell

```

### Relevant Configuration

```YAML
Link to the search page: https://iris-salten.no/privat/tommeplan/
Example adress: Alsosgården 11 (Bodø kommune)

Waste types is the same as before: Matavfall uten hageavfall, Papir og papp, Restavfall, Plastemballasje, Glass- og metallemballasje
```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
