### ISSUE TITLE
[Bug]: Stadt Schweinfurt - showmobile not working

### ISSUE THREAD

**Issue by UeEiFetischist** [mampfes/hacs_waste_collection_schedule#4214]
### I Have A Problem With:

Sensor configuration

### What's Your Problem

Hello,

I am using the waste schedule for Stadt Schweinfurt, but unfortunately "Mobiler Wertstoffhof" is popping up in my calendar, even though I put showmobile on false. 

I also discovered other events in the calendar, which trigger my alarm, which I don't need. E.g. "Aktion Kompostverkauf" and "Wertstoffhof geschlossen"

In Schweinfurt, all types of waste are picked up on the same day ("Papier", "Restmüll" and "Gelber Sack")

Thank you!

### Logs

```Shell
no relevant logs.
```

### Relevant Configuration

```YAML
waste_collection_schedule:
  sources:
    - name: schweinfurt_de
      args:
        address: "Ahornstrasse"
        showmobile: "False"
      
#Link: https://www.schweinfurt.de/leben-freizeit/umwelt/abfallwirtschaft/4427.Aktuelle-Abfuhrtermine-und-Muellkalender.html

sensor:
  - platform: waste_collection_schedule
    name: Müllabfuhr
    value_template: 'in {{value.daysTo}} Tagen' #Gibt den Sensor die Tage bis zur nächsten Entleerung zurück
```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
