### ISSUE TITLE
[Bug]: gfa_lueneburg_de  - not working anymore

### ISSUE THREAD

**Issue by pmi1805** [mampfes/hacs_waste_collection_schedule#4231]
### I Have A Problem With:

A specific source

### What's Your Problem

Soure has been configured via configuration.yaml and sensors.yaml to define custom sensors based on "platform: waste_collection_schedule". Sensors show "unknown" since a week.
Configuration via GUI results in same error ("Content line could not be parsed into parts")

Source worked for months without any issues.

using CITY/STREET/HNR manually via source-website works well

### Source (if relevant)

gfa_lueneburg_de

### Logs

```Shell
Logger: custom_components.waste_collection_schedule.waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:160
integration: Waste Collection Schedule (documentation)
First occurred: 19:48:44 (1 occurrence)
Last logged: 19:48:44

fetch failed for source GFA Lüneburg: Traceback (most recent call last): File "/usr/local/lib/python3.13/site-packages/icalendar/parser.py", line 326, in parts validate_token(name) ~~~~~~~~~~~~~~^^^^^^ File "/usr/local/lib/python3.13/site-packages/icalendar/parser.py", line 115, in validate_token raise ValueError(name) ValueError: <!DOCTYPE HTML><HTML lang="de-DE"> During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 158, in fetch entries: Iterable[Collection] = self._source.fetch() ~~~~~~~~~~~~~~~~~~^^ File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/gfa_lueneburg_de.py", line 136, in fetch dates = self._ics.convert(r.text) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 48, in convert events: List[Any] = icalevents.events( ~~~~~~~~~~~~~~~~~^ start=start_date, end=end_date, string_content=ics_data.encode() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.13/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( ~~~~~~~~~~~~^ content, start=start, end=end, tzinfo=tzinfo, sort=sort, strict=strict ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/usr/local/lib/python3.13/site-packages/icalevents/icalparser.py", line 303, in parse_events calendar = Calendar.from_ical(content) File "/usr/local/lib/python3.13/site-packages/icalendar/cal.py", line 410, in from_ical name, params, vals = line.parts() ~~~~~~~~~~^^ File "/usr/local/lib/python3.13/site-packages/icalendar/parser.py", line 340, in parts raise ValueError( f"Content line could not be parsed into parts: '{self}': {exc}") ValueError: Content line could not be parsed into parts: '<!DOCTYPE HTML><HTML lang="de-DE"> ': <!DOCTYPE HTML><HTML lang="de-DE">
```

### Relevant Configuration

```YAML
##############
configuration.yaml
##############
waste_collection_schedule:
  sources:
    - name: gfa_lueneburg_de
      args:
        city: CITY
        street: STREET
        house_number: HNR
      customize:
        - type: Restmuell
          alias: Restmuell
          icon: mdi:trash-can
          picture: local/Images/schwarze-tonne.svg
        - type: Gelbe Tonne
          alias: Gelbe Tonne
          icon: mdi:recycle
          picture: local/Images/gelbe-tonne.svg
        - type: Papiertonne
          alias: Papiertonne
          icon: mdi:recycle
          picture: local/Images/blaue-tonne.svg
      calendar_title: Abfallkalender
  fetch_time: "04:00"
  day_switch_time: "10:00"
##############
sensors.yaml
##############
  # ------- Garbage Collection ------- 
  # Nächste Abholung Gelber Sack
  - platform: waste_collection_schedule
    name: "Gelbe Tonne"
    #value_template: '{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} {{value.daysTo}} Tage{% endif %}'
    value_template: '{{value.daysTo}}'
    add_days_to: True
    types:
      - Gelbe Tonne
  # Nächste Abholung Restmüll
  - platform: waste_collection_schedule
    name: "Restmuell"
    #value_template: '{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} {{value.daysTo}} Tage{% endif %}'
    value_template: '{{value.daysTo}}'
    add_days_to: True
    types:
      - Restmuell
  # Nächste Abholung Papier
  - platform: waste_collection_schedule
    name: "Papiertonne"
    #value_template: '{% if value.daysTo == 0 %} Heute{% elif value.daysTo == 1 %} Morgen{% else %} {{value.daysTo}} Tage{% endif %}'
    value_template: '{{value.daysTo}}'
    add_days_to: True
    types:
      - Papiertonne
  # Nächste Abholung - Berechnung im Template Helfer
  - platform: waste_collection_schedule
    name: "Naechster"
    details_format: "upcoming"
    value_template: '{{ value.daysTo }}'
    add_days_to: True
```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [ ] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
