### ISSUE TITLE
[Source Request]: Ecolan in Italy

### ISSUE THREAD

**Issue by sko22** [mampfes/hacs_waste_collection_schedule#4259]
### Municipality / Region

Lanciano, Italy

### Collection Calendar Webpage

https://www.ecolanspa.it/calendari/

### Example Address

My municipality is Lanciano, and the recycling calendar is available in PDF format:
https://www.ecolanspa.it/comuni/lanciano/lanciano.pdf

However, there are many other municipalities served by Ecolan, and their calendars can be found on this page in PDF format:
https://www.ecolanspa.it/calendari/

### Collection Data Format

As PDF Download

**Comment by sko22** [comment]
I found an old calendar that Ecolan still keeps updated. Please add it to the Waste Collection Schedule:

 https://www.google.com/calendar/ical/3vthrt88quqepasgt6hkn7dkc8%40group.calendar.google.com/public/basic.ics

**Comment by markvp** [comment]
Thanks for finding the ICS feed! We've added Ecolan Lanciano as a documented ICS source in PR #6019. Once merged, it will be discoverable in the integration's source list.

In the meantime, you can already use it with the existing ICS source:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://www.google.com/calendar/ical/3vthrt88quqepasgt6hkn7dkc8%40group.calendar.google.com/public/basic.ics"
```
