### ISSUE TITLE
[Source Request]: Veldhoven waste collection

### ISSUE THREAD

**Issue by BROSSIE-NL** [mampfes/hacs_waste_collection_schedule#4269]
### Municipality / Region

Veldhoven Netherlands

### Collection Calendar Webpage

https://www.veldhoven.nl/afvalkalender

### Example Address

Postal code
house number

### Collection Data Format

As ICS/ICAL file

**Comment by bbr111** [comment]
Hi @BROSSIE-NL, thanks for the request!

Veldhoven's waste calendar (https://www.veldhoven.nl/afvalkalender) already runs on the "Mijn Afvalwijzer" platform, which is generically supported by the existing `mijnafvalwijzer_nl` source in this integration — no per-municipality list is needed, it works for any Dutch address on mijnafvalwijzer.nl.

I verified this by looking up a Veldhoven address (postcode 5502JA) directly against mijnafvalwijzer.nl and it returned live 2026 collection dates for Restafval, PMD, GFT and Papier en karton.

You can configure it like this:

```yaml
waste_collection_schedule:
  sources:
    - name: mijnafvalwijzer_nl
      args:
        postcode: YOUR_POSTCODE
        number: YOUR_HOUSE_NUMBER
        add: YOUR_HOUSE_NUMBER_ADDITION  # optional, e.g. "A"
```

Docs: https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/mijnafvalwijzer_nl.md

You can also verify your address first at https://www.mijnafvalwijzer.nl to confirm it's recognized.

Closing as already supported — feel free to reopen if you hit any issues configuring it.
