### ISSUE TITLE
[Source Request]: Abfallkalender Stadt Vlotho

### ISSUE THREAD

**Issue by LE205** [mampfes/hacs_waste_collection_schedule#4282]
### Municipality / Region

Vlotho

### Collection Calendar Webpage

https://www.vlotho.de/Leben-in-Vlotho/Abfallkalender-online/index.php?set=fix&ort=393.8&strasse=3136.359.1&vtyp=1&abfart%5B%5D=3136.1&abfart%5B%5D=3136.2&abfart%5B%5D=3136.3&abfart%5B%5D=3136.4&abfart%5B%5D=3136.5&vJ=2025&call=suche&La=1&css=&bn=&Barriere=&sNavID=3136.147&mNavID=3136.12&ffmod=abf&ffsm=1&once=1

### Example Address

Topsundernweg

### Collection Data Format

As ICS/ICAL file

**Comment by markvp** [comment]
Thanks for the report! Vlotho uses the same `abfall_export.php?mode=vcal` pattern as a few other German municipalities already supported here. I've added it to the `abfall_export_vcal` provider — a PR is open at https://github.com/mampfes/hacs_waste_collection_schedule/pull/6657.

In the meantime you can configure it yourself using the generic ICS source:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://www.vlotho.de/output/abfall_export.php?csv_export=1&mode=vcal&ort=393.8&strasse=3136.359.1&abfart%5B0%5D=3136.1&abfart%5B1%5D=3136.2&abfart%5B2%5D=3136.3&abfart%5B3%5D=3136.4&abfart%5B4%5D=3136.5&vtyp=1&vMo=01&vJ=2026&bMo=12
        year_field: vJ
```

Adjust the `ort` and `strasse` parameters for your specific street — you can find these by navigating to the Vlotho waste calendar page and copying the export link for your address.
