### ISSUE TITLE
[Bug]: Icons in standard view disappeared

### ISSUE THREAD

**Issue by LorenJaffrey** [mampfes/hacs_waste_collection_schedule#4293]
### I Have A Problem With:

The integration in general

### What's Your Problem

The icons in the standard view disappeared a while ago. Today i had  a little time to look into it, Maybe some customization would do the trick, but even reconfiguring it wouldn't solve the problem.
The other display types (Chip card and Icon) are working correcly.

![Image](https://github.com/user-attachments/assets/5e382ab7-51da-4c27-a895-288b1cfd329a)

### Logs

```Shell

```

### Relevant Configuration

```YAML
event_grouping: true
drop_todayevents_from: "10:00:00"
next_days: 30
pattern:
  - icon: mdi:flower
    color: green
    type: organic
    pattern: Biotonne
    pattern_exact: false
    label: Biomüll
  - icon: mdi:newspaper
    color: blue
    type: paper
    pattern: Papiertonne
    label: Papiertonne
  - icon: mdi:recycle-variant
    color: amber
    type: recycle
    label: Gelber Sack
    pattern: Gelber Sack
  - icon: mdi:trash-can-outline
    color: black
    type: waste
    pattern: Restmüll
  - icon: mdi:dump-truck
    color: purple
    type: others
day_style: counter
alignment_style: left
items_per_row: 1
refresh_rate: 60
with_label: true
type: custom:trash-card
entities:
  - calendar.landkreis_neumarkt
hide_time_range: false
use_summary: false
full_size: false
filter_events: true
```

### Checklist Source Error

- [x] Use the example parameters for your source (often available in the documentation) (don't forget to restart Home Assistant after changing the configuration)
- [x] Checked that the website of your service provider is still working
- [x] Tested my attributes on the service provider website (if possible)
- [x] I have tested with the latest version of the integration (master) (for HACS in the 3 dot menu of the integration click on "Redownload" and choose master as version)

### Checklist Sensor Error

- [x] Checked in the Home Assistant Calendar tab if the event names match the types names (if types argument is used)

### Required

- [x] I have searched past (closed AND opened) issues to see if this bug has already been reported, and it hasn't been.
- [x] I understand that people give their precious time for free, and thus I've done my very best to make this problem as easy as possible to investigate.
