### ISSUE TITLE
[Source Request] Smictom Centre Ouest (63 communes)

### ISSUE THREAD

**Issue by herledant** [mampfes/hacs_waste_collection_schedule#4294]
### Municipality / Region

Montauban-De-Bretagne, Bretagne Centre, France

### Collection Calendar Webpage

https://www.smictom-centreouest35.fr/la-collecte/

### Example Address

6 rue des forges, 35360 Montauban-De-Bretagne

### Collection Data Format

As PDF Download

**Comment by bbr111** [comment]
Thanks for the request! Smictom Centre Ouest's street lookup on https://www.smictom-centreouest35.fr/la-collecte/ is powered by Montri (contract `SMICTOMCO`), which is already supported by the `montri_fr` source. You can add it with:

```yaml
waste_collection_schedule:
  sources:
    - name: montri_fr
      args:
        postal_code: "35750"
        city_name: "Iffendic"
        address: "30 La Ville Es Nouvelle"
```

Use your own postal code, commune name and street address as shown on https://montri.fr (see https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/montri_fr.md). Please reopen or comment here if your commune doesn't resolve. Closing as already supported.
