### ISSUE TITLE
Request for Wroclaw city PL support

### ISSUE THREAD

**Issue by barcik75** [mampfes/hacs_waste_collection_schedule#430]
Hi, 
On page [https://ekosystem.wroc.pl/gospodarowanie-odpadami/harmonogram-wywozu-odpadow/](https://ekosystem.wroc.pl/gospodarowanie-odpadami/harmonogram-wywozu-odpadow/) I can check when waste will be collect. But I have to specify street and number, after this calendar will be dipslay.
Example:
[https://ekosystem.wroc.pl/gospodarowanie-odpadami/harmonogram-wywozu-odpadow/?lokalizacja=379795&ulica=2104](https://ekosystem.wroc.pl/gospodarowanie-odpadami/harmonogram-wywozu-odpadow/?lokalizacja=379795&ulica=2104)

**Comment by 5ila5** [comment]
added by #833
[Documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ekosystem_wroc_pl.md)
```yaml
waste_collection_schedule:
  sources:
    - name: ekosystem_wroc_pl
      args:
        location_id: 379795
```
