### ISSUE TITLE
Request for OSTRÓW MAZOWIECKA city PL

### ISSUE THREAD

**Issue by giantoo** [mampfes/hacs_waste_collection_schedule#441]
Hi,
I have app with schedule from ecoharmonogram. It'll be great if Ostrów Mazowiecka were here.

Regards
Michal

**Comment by 5ila5** [comment]
The ZGK Info APP probably uses the Ecoharmonogram API.
Have you tried using the [Ecoharmonogram source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ecoharmonogram_pl.md)?

**Comment by markvp** [comment]
Hi @giantoo,

Good news — Ostrów Mazowiecka is already supported! As the previous comment suggested, you can use the [Ecoharmonogram source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ecoharmonogram_pl.md).

You will need to specify `app: "zgk-info"` in your configuration, since Ostrów Mazowiecka is served by the ZGK Info app. A minimal YAML example:

```yaml
waste_collection_schedule:
  sources:
    - name: ecoharmonogram_pl
      args:
        app: zgk-info
        town: Ostrów Mazowiecka
        street: YOUR_STREET
        house_number: YOUR_HOUSE_NUMBER
```

Refer to the [full documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ecoharmonogram_pl.md) for details on optional parameters such as `district`, `additional_sides_matcher`, and collection groups (`g1`–`g5`).

Closing this as already supported — feel free to reopen if you run into trouble.
