### ISSUE TITLE
make c_trace_de more flexible

### ISSUE THREAD

**Issue by ttnotet** [mampfes/hacs_waste_collection_schedule#446]
Please update c_trace  integration in that way that it support other regions then Bermen. 

I want to use it for **AugsburgLand**. 
Sample URL: https://web.c-trace.de/AugsburgLandkreis/(S(xxxxxxxx))/abfallkalender/cal?Ort=Königsbrunn&Strasse=Marktplatz&Hausnr=7&Abfall=1|2|3

For my setup  I have done some updates in my fork (see https://github.com/ttnotet/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/c_trace_de.py). 

This changes allow to configure it in this way: 
```
waste_collection_schedule:
  sources:
    - name: c_trace_de
      args:
        ort: Königsbrunn
        strasse: Marktplatz
        hausnummer: 7
        abfall: "1|2|3"
        service: AugsburgLandkreis
  fetch_time: "01:00"
  day_switch_time: "23:00"
```
