### ISSUE TITLE
Upcoming days wrong

### ISSUE THREAD

**Issue by boehser-enkel** [mampfes/hacs_waste_collection_schedule#452]
Hi there,

i am using was_wolfsburg_de
Today is gelber Sack and next wedneday is Bioabfall
Also upcoming days worked fine til now. 
Now it shows 12 days (this is the next gelber Sack) and not 7 (for Bioabfall)

greetings

**Comment by mampfes** [comment]
Do you still see this issue? With my test-data everything looks good.

**Comment by boehser-enkel** [comment]
Yes. My entities show Gelber Sack in 11 days but it’s Bioabfall next Wednesday.

**Comment by mampfes** [comment]
Could you share your configuration? I'm unable to reproduce the issue with my test address.

**Comment by boehser-enkel** [comment]
> Could you share your configuration? I'm unable to reproduce the issue with my test address.

Here you go:
```
waste_collection_schedule:
  sources:
    - name: was_wolfsburg_de
      args:
        city: Vorsfelde-Nord
        street: "Zum Alten Teich"
      calendar_title: Müll          
  day_switch_time: " 12:00"  
  
sensor:
  - platform: waste_collection_schedule
    name: Abfall
    details_format: upcoming
    count: 4
    leadtime: 4
    value_template: '{{value.types|join(", ")}}'
    add_days_to: true
#    types:
#      - altpapier

  - platform: waste_collection_schedule  
    name: Abfalltage
    details_format: upcoming
    value_template: '{{ value.daysTo }}'
    count: 4
    leadtime: 4
```
