### ISSUE TITLE
Different ics Url for next year

### ISSUE THREAD

**Issue by kgroshert** [mampfes/hacs_waste_collection_schedule#468]
My garbage-provider is using different URLs for the year 2022 and 2023. These are:

url: https://api.abfall.io/?kh=DaA02103019b46345f1998698563DaAd&t=ics&s=94f8ecf0190567fc16e43b59ec20e70a
url: https://api.abfall.io/?kh=DaA02103019b46345f1998698563DaAd&t=ics&s=94f8ecf0190567fc16e43b59ec20e70a&j=2023

I have configured both sources, but now I have to specify "source_index: 1" in my sensor configs for collections that happen in 2023
and "source_index: 0" for collections that happen in 2022.

I also tried the "awb_es_de" source instead of ics but that only show 2022.

Is there a way around reconfiguring the sensors around the end of the year?

**Comment by dt215git** [comment]
Do you get the current calendar if you use
`url: https://api.abfall.io/?kh=DaA02103019b46345f1998698563DaAd&t=ics&s=94f8ecf0190567fc16e43b59ec20e70a&j=2022`

**Comment by kgroshert** [comment]
Ah, yes, I can get the current calendar by leaving out the year number or by adding j=2022. That works.
What I meant was: now I have the year 2022 at index 0 and the year 2023 at index 1. Which means, some of my sensors use index 0
and the other ones already use index 1 (because the next garbage-date is already in 2023). Next week I have to reconfigure another
sensor to index 1 as it has no more garbage-date in 2022 and so on. On January 1st I will have to put "source_index: 0" on all
four sensors again and it will work for 12 months until it starts again 😄

Can I pull 2 ics-links for the same index? Basically something like:

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        - url: https://api.abfall.io/?kh=DaA02103019b46345f1998698563DaAd&t=ics&s=94f8ecf0190567fc16e43b59ec20e70a&j=2022
        - url: https://api.abfall.io/?kh=DaA02103019b46345f1998698563DaAd&t=ics&s=94f8ecf0190567fc16e43b59ec20e70a&j=2023

```

If no, I have at least something to do over the christmas holidays 😄

**Comment by dt215git** [comment]
Worth a try, but reading the [ICS docs](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) it's not clear whether the layout needs to be the way you have it, or something like this: 
```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        - url: https://api.abfall.io/?kh=DaA02103019b46345f1998698563DaAd&t=ics&s=94f8ecf0190567fc16e43b59ec20e70a&j=2022
    - name: ics
      args:
        - url: https://api.abfall.io/?kh=DaA02103019b46345f1998698563DaAd&t=ics&s=94f8ecf0190567fc16e43b59ec20e70a&j=2023
```

Part of the reason for asking whether the `j=2022` bit worked is that it may give you a way of automatically accounting for each new year. If you query the current date, you can extract the current year, and then doing a +1 gives you the next year. Kind of like this:
![image](https://user-images.githubusercontent.com/86194065/207545413-c5344b59-2760-427f-946f-d55b416e4d38.png)
![image](https://user-images.githubusercontent.com/86194065/207545609-8a2a5e12-8030-4d45-983d-95648d3bb29a.png)

Then maybe you could end up with something like this, that would automatically update itself each new year such that source_index 0 would always be referring to the current year and source_index 1 would be next year
```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        - url: >
          {% set this_year = int((states("sensor.date") | string)[0:4]) %}
          https://api.abfall.io/?kh=DaA02103019b46345f1998698563DaAd&t=ics&s=94f8ecf0190567fc16e43b59ec20e70a&j={{this_year}}
    - name: ics
      args:
        - url: >
          {% set next_year = int((states("sensor.date") | string)[0:4])+1 %}
          https://api.abfall.io/?kh=DaA02103019b46345f1998698563DaAd&t=ics&s=94f8ecf0190567fc16e43b59ec20e70a&j={{next_year}}
```
No idea if that'd work, but at least you've got a few more things to try over the holidays :smile:

**Comment by mampfes** [comment]
First of all: Did you already tried the [abfall_io](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfall_io.md) source instead of the `ics` source?

Regarding the year as argument: The `ics` source supports to replace a year field in the URL automatically. Please check the [documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md). See [Lübeck Entsorgungsbetriebe](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md#l%C3%BCbeck-entsorgungsbetriebe) for a similar example.

You can than remove the 2nd source for 2023.

**Comment by kgroshert** [comment]
@mampfes: I have not tried the "abfall_io" source as I found the "awb_es_de" and thought that was all.
It seems my provider is using a different lookup page - I tried to get the parameters as in the docs but the page is using some JS to get the data so I have not found any useful parameters in the developer tools:

[https://www.awb-es.de/abfuhr/abfuhrtermine/__Abfuhrtermine-suchen.html?direct=true&city=Wernau+%28Neckar%29&street=Lange+Stra%DFe#CONTENT](url)

Regarding the year_field parameter: thanks for that, I have put it in the config now (although it doesn't solve my original problem).

For reference, here's my config:



```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://api.abfall.io/?kh=DaA02103019b46345f1998698563DaAd&t=ics&s=94f8ecf0190567fc16e43b59ec20e70a&j=2023
        year_field: "j"
      customize:
        - type: Gelbe/r Sack/Tonne
          alias: Gelber Sack
        - type: Restmüll 2-wöchentlich
          alias: Restmüll
        - type: Restmüll 4-wöchentlich
          show: false
  day_switch_time: "16:00"

sensor:
  - platform: waste_collection_schedule
    name: AWB Biotonne
    types:
      - Biotonne
    value_template: "{{ value.daysTo }}"

  - platform: waste_collection_schedule
    name: AWB Gelber Sack
    types:
      - Gelber Sack
    value_template: "{{ value.daysTo }}"

  - platform: waste_collection_schedule
    name: AWB Papiertonne
    types:
      - Papiertonne
    value_template: "{{ value.daysTo }}"

  - platform: waste_collection_schedule
    name: AWB Restmüll
    types:
      - Restmüll
    value_template: "{{ value.daysTo }}"
```

And this gives me these 4 sensors:

![image](https://user-images.githubusercontent.com/60856997/207817872-3cfc3630-29ed-429d-8e81-cd0550bd20cf.png)

But the one sensor is unknown as the next date is in 2023 and the ics source doesn't provide that and the awb_es_de source doesn't as well.

@dt215git: Thanks for the idea, this would work to automatically get the URL for the coming year(s). But still I have
2 sources then and need to edit my four sensors in the last weeks of december.

What I could do is configuring 8 sensors, 4 for the current year and 4 for the next year and use templating to display the
one that is not "unavailable". Right now I show "TBA" for unavailable sensors: 😄

![image](https://user-images.githubusercontent.com/60856997/207821514-1fa3a48f-8d8d-4574-890e-e2634f0981c2.png)

**Comment by mampfes** [comment]
`year_field` only works together with `params`.

But in your case it would be sufficient to just replace the year using `{%Y}`:

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://api.abfall.io/?kh=DaA02103019b46345f1998698563DaAd&t=ics&s=94f8ecf0190567fc16e43b59ec20e70a&j={%Y}
```
