### ISSUE TITLE
Two (or more) static sources not work

### ISSUE THREAD

**Issue by GerdRuetten** [mampfes/hacs_waste_collection_schedule#482]
Please can you show an example, how two (or more) static sources must be configuration.

I test it with 

```
waste_collection_schedule:
   sources:
    - name: static
      args:
        - type: Bioabfall
          frequency: WEEKLY
          interval: 2
          start: '2023-01-17'
          until: '2023-04-30'
          excludes:
            - '2023-04-11'
          dates:
            - '2023-01-04'
            - '2023-04-12'
        - type: Leichtverpackungen
          frequency: WEEKLY
          interval: 2
          start: '2023-01-11'
          until: '2023-04-30'
          excludes:
            - '2023-02-22'
            - '2023-04-05'          
          dates:
            - '2022-12-27'
            - '2023-02-23'
            - '2023-04-04'
      customize:
        - type: Bioabfall
          alias: Bioabfall
          icon: mdi:flower-outline
        - type: Leichtverpackungen
          alias: Leichtverpackungen
          icon: mdi:recycle
  fetch_time: "03:00"
  day_switch_time: "12:00"

```
but i always get a configuration error.

TIA

Gerd

**Comment by GerdRuetten** [comment]
OK, i found the solution

```
waste_collection_schedule:
   sources:
    - name: static
      args:
        type: Bioabfall
        frequency: WEEKLY
        interval: 2
        start: '2023-01-17'
        until: '2023-04-30'
        excludes:
          - '2023-04-11'
        dates:
          - '2023-01-04'
          - '2023-04-12'
      customize:
        - type: Bioabfall
          alias: Bioabfall
          icon: mdi:flower-outline
    - name: static
      args:
        type: Leichtverpackungen
        frequency: WEEKLY
        interval: 2
        start: '2023-01-11'
        until: '2023-04-30'
        excludes:
          - '2023-02-22'
          - '2023-04-05'          
        dates:
          - '2022-12-27'
          - '2023-02-23'
          - '2023-04-04'
      customize:
        - type: Leichtverpackungen
          alias: Leichtverpackungen
          icon: mdi:recycle
    - name: static
      args:
        type: Restabfall
        frequency: WEEKLY
        interval: 2
        start: '2023-01-09'
        until: '2023-04-30'
        excludes:
          - '2023-02-20'
          - '2023-04-03'
        dates:
          - '2023-02-21'
          - '2023-04-01'
      customize:
        - type: Restabfall
          alias: Restabfall
          icon: mdi:trash-can
    - name: static
      args:
        type: Papier
        frequency: WEEKLY
        interval: 2
        start: '2023-01-20'
        until: '2023-04-30'
        excludes:
          - '2023-04-14'
        dates:
          - '2023-01-07'
          - '2023-04-15'
      customize:
        - type: Papier
          alias: Papier
          icon: mdi:trash-can-outline
  fetch_time: "03:00"
  day_switch_time: "12:00"
```

And the sensors must have the source_index - Attribut like

```
  - platform: waste_collection_schedule
    source_index: 3  
    name: AbfallPapier
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Heute{% elif value.daysTo == 1 %}Morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    types:
      - Papier

```
