### ISSUE TITLE
Adding 'Abfallwirtschaft Stuttgart' as service provider causes `check configuration` to load indefinitely

### ISSUE THREAD

**Issue by MarcelBochtler** [mampfes/hacs_waste_collection_schedule#488]
I tried to add the 'Abfallwirtschaft Stuttgart' service provider, by installing the integration through HACS on my HAOS on a Raspberry Pi 3b+ and restarted Home Assistant afterwards.
I generated the configuration by using the [stuttgart_de.py](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/wizard/stuttgart_de.py) wizard:
```yaml
waste_collection_schedule:
   sources:
     - name: stuttgart_de
       args:
         street: Mystr. # This is replaced by my real street.
         streetnr: 10
```

After saving the `configuration.yaml` I used Home Assistant's `check configuration` functionality. The check does not show an actual error, but the loading spinner never finishes completing the check.

I couldn't find any related entries in the logs in `/config/home-assistant.log`.
