### ISSUE TITLE
Sensor Unit / Friendly Name and Calendar Entity ID

### ISSUE THREAD

**Issue by perryflynn** [mampfes/hacs_waste_collection_schedule#538]
Hi,

I like your integration so far, thank you for your hard work.

A few ideas/comments:

- Allow to define a entity_id for the calendar  
  (it's called `calendar.ics` in my case right now, or is renaming in the UI the way here?)
- Add support for `unit_of_measurement` and `friendly_name` for the sensor

Thank you.

----

Provider: https://abfall.nerdbridge.de/
Data Source: https://abfall.nerdbridge.de/ical/abfall-nom-einbeck_bezirk_2-HM2W,PET,BIO,PAP,GL-notify_6.ics

Usage:

```yml
sensor:
  - &wastesensor
    platform: waste_collection_schedule
    name: abfall
    details_format: upcoming
    count: 4
    value_template: '{{value.types|join(" + ")}} in {{value.daysTo}} Tag(en)'
    date_template: '{{value.date.strftime("%d.%m.%Y")}}'

  - &singlewastesensor
    << : *wastesensor
    name: Biotonne
    value_template: '{{value.daysTo}}'
    types:
      - 'Biotonne'

  - << : *singlewastesensor
    name: Hausmüll
    types:
      - 'Hausmüll 2W'

  - << : *singlewastesensor
    name: Papiersammlung
    types:
      - 'Papiersammlung'

  - << : *singlewastesensor
    name: Glassammlung
    types:
      - 'Glassammlung'

  - << : *singlewastesensor
    name: Gelber Sack
    types:
      - 'Gelber Sack'

waste_collection_schedule:
  sources:
    - name: ics
      calendar_title: Abfallkalender
      args:
        url: 'https://abfall.nerdbridge.de/ical/abfall-nom-einbeck_bezirk_2-HM2W,PET,BIO,PAP,GL-notify_6.ics'
        method: GET
        version: 2
        verify_ssl: true
```
