### ISSUE TITLE
Setting up sensors for new West Devon source

### ISSUE THREAD

**Issue by mothy-tim** [mampfes/hacs_waste_collection_schedule#543]
Hi, I'm struggling to get sensors working on the new West Devon source! I can only get the Refuse to work, the Recycling and Garden waste says unavailable! Here is the code? Thanks Tim

```
sensor:
  - platform: waste_collection_schedule
    source_index: 0
    name: Refuse
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %} ({{value.date.strftime("%a, %d.%m.%Y")}})'
    date_template: '{{value.date.strftime("%a, %d.%m.%Y")}}'
    add_days_to: true
    types:
      - Refuse
  - platform: waste_collection_schedule
    source_index: 1
    name: Recycling
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %} ({{value.date.strftime("%a, %d.%m.%Y")}})'
    date_template: '{{value.date.strftime("%a, %d.%m.%Y")}}'
    add_days_to: true
    types:
      - Recycling
  - platform: waste_collection_schedule
    source_index: 2
    name: Garden Waste
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %} ({{value.date.strftime("%a, %d.%m.%Y")}})'
    date_template: '{{value.date.strftime("%a, %d.%m.%Y")}}'
    add_days_to: true
    types:
      - Garden

```
