### ISSUE TITLE
Fetch of ICS-File fails

### ISSUE THREAD

**Issue by Toche3007** [mampfes/hacs_waste_collection_schedule#575]
Hi all,
I replaced the old ics file with the new ics-File for 2023 and updated also Waste Collection.
I don't see any data in HA and found the following error in my logs.
```
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 10:41:06 (1 occurrences)
Last logged: 10:41:06

fetch failed for source ICS: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 184, in fetch return self.fetch_file(self._file) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 211, in fetch_file return self._convert(f.read()) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 214, in _convert dates = self._ics.convert(data) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/service/ICS.py", line 38, in convert events: List[Any] = icalevents.events( File "/usr/local/lib/python3.10/site-packages/icalevents/icalevents.py", line 57, in events found_events += parse_events( File "/usr/local/lib/python3.10/site-packages/icalevents/icalparser.py", line 370, in parse_events rule = parse_rrule(component) File "/usr/local/lib/python3.10/site-packages/icalevents/icalparser.py", line 528, in parse_rrule rule.exdate(exd.replace(tzinfo=None)) TypeError: 'tzinfo' is an invalid keyword argument for replace()
```

Hopefully someone can help me here. The only difference I saw in the file is, that the new file is much bigger than the old one (new 1569 KB and old 35 KB, seems new was exported with outlook and old was exported with google calender)
I also tried to import the ics into my google calender (worked fine) and than exported it manually from google. But same error in the logs.

As a workaround I tried to create the calenders manually with type static, but only the first static calender is taken by the plugin and shown at the dashboard.

```
- name: static
      calendar_title: Restmüll
      args:
        type: rest
        frequency: WEEKLY
        interval: 2
        start: "2023-01-02"
        until: "2023-12-31"
        excludes: # Add exception for the recurrence
          - "2023-04-10"
        dates: # Manually define dates that are not part of the recurrence
          - "2023-04-11"
    - name: static
      calendar_title: Papiermüll
      args:
        type: papier
        frequency: WEEKLY
        interval: 4
        start: "2023-01-03"
        until: "2023-12-31"
```
