### ISSUE TITLE
Bin collection in Sutherland Shire, NSW, Australia

### ISSUE THREAD

**Issue by EinSchwerd** [mampfes/hacs_waste_collection_schedule#588]
Could you please add support for the bin collection schedule in the Sutherland Shire, NSW, Australia?
The bin collection schedule can be obtained from the following source:
https://www.sutherlandshire.nsw.gov.au/living-here/waste-and-recycling/waste-information-booklet

**Comment by dt215git** [comment]
I'm not having much luck looking at that page - it never seems to load the section where you presumably enter address details.

![image](https://user-images.githubusercontent.com/86194065/211656124-a59220fe-3c55-460c-a7b2-09d3ba917bd0.png)

**Comment by bbr111** [comment]
the same on here.
maybe geo-blocking

**Comment by EinSchwerd** [comment]
This should load:
https://cms.ssc.nsw.gov.au/DXP/Forms/Waste-Information-Booklet-Form
Would the page source help to reverse engineer the API? Does accessing it through a VPN work?

**Comment by dt215git** [comment]
I'd tried linking direct previously, it doesn't make a difference and still times out.
A VPN might work around the issue - depends on whether any of the contributors use one with an AUS endpoint, or are based in AUS.
Page source could be useful depending on how the results are displayed, but it's really the requests/responses that get made as you interact with the page that are most useful. You can see these sorts of thing on the Network page of  the Web Developer tabs in most browsers, or other tools that intercept them.

As an example from a different page on their website:
![image](https://user-images.githubusercontent.com/86194065/215832470-5815bf98-896d-4bf4-a21b-d0b324a49a0e.png)

**Comment by EinSchwerd** [comment]
[cms.ssc.nsw.gov.au_Archive [23-02-04 07-37-25].zip](https://github.com/mampfes/hacs_waste_collection_schedule/files/10582613/cms.ssc.nsw.gov.au_Archive.23-02-04.07-37-25.zip)

Let me know if you need anything else.

**Comment by dt215git** [comment]
Looks like the address details are being posted using form fields called:
- ctl03$ddlSuburb
- ctl03$ddlStreet
- ctl03$ddlHouseNumber

However, they're being posted to `cms.ssc.nsw.gov.au/DXP/Forms/Waste-Information-Booklet-Form` which is the part of the page that times out. Trying to pull that page from within a script has the same issue:
```bash
TimeoutError: [Errno 110] Connection timed out
```

For the  address you used, this looks to be the final response:
```
Bin collection day for ***address removed*** is Monday, recycling and greenwaste is every second Monday.
For more information see the Waste Information Booklet (PDF)
```
There are no actual formatted dates in response, so if you see dates when using the  website they're probably being generated dynamically. If you don't see dates, then you'd be better off creating a [static](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md) schedule.

Not sure if anyone has any better ideas...?

**Comment by 5ila5** [comment]
I tried this using tor to get a Australian IP. The response is just:
Bin collection day for 5 Cleveland Place, BONNET BAY is Monday, recycling and greenwaste is every second Monday. For more information see the [Waste Information Booklet (PDF)](https://cms.ssc.nsw.gov.au/CustomControlsWeb/PropertyInformation/Zone%202.pdf)

PDFs are not realy parsable so creteing a [static](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md) source is the way to go.

For my example:
```yaml
waste_collection_schedule:
  sources:
    - name: static
      args:
        type: Garbage (red)
        frequency: WEEKLY
        weekdays: MO
    - name: static
      args:
        type: Recycling (yellow)
        frequency: WEEKLY
        interval: 2
        start: '2023-01-02' # Monday in correct week
    - name: static
      args:
        type: Garden (green)
        frequency: WEEKLY
        interval: 2
        start: '2023-01-09' # Monday in correct week
```
