### ISSUE TITLE
c_trace_de service + WZV: Restabfall/Weihnachtsbaum status "unknown"

### ISSUE THREAD

**Issue by Sphericals79** [mampfes/hacs_waste_collection_schedule#608]
Hi @mampfes, I'm not able to pull collection data for Restabfall and Weihnachtsbaum waste type from the Ctrace.de api for WZV (Segeberg).

Gelbe Säcke, Papier and Bio collection dates are coming in fine. The other two stay on entity status "unknown".

Using recent version of waste collection schedule via HACS on my test home assistant server.

Doing a manual pull with the "waste_collection_schedule: fetch_data" service in HA results in a error message:
`Fehler beim Aufrufen des Diensts waste_collection_schedule.fetch_data. Unknown error`

I can see you've made changes to the ID of Restabfall (in fix #585). Maybe there's still something wrong?

configuration.yaml (anonymized)
```
{...}
waste_collection_schedule:
  sources:
    - name: c_trace_de
      args:
        service: segebergwzv-abfallkalender
        ort: XYZ
        strasse: XYZ
        hausnummer: XYZ
      customize:
        - type: "Abfuhr: Restabfall"
          alias: Restabfall
          icon: mdi:trash-can
        - type: Gelber Sack
          alias: Gelber Sack
          icon: mdi:recycle
{...}
```

sensors.yaml
```
{...}
  - platform: waste_collection_schedule
    name: Restabfall
    details_format: "upcoming"
    value_template: '{% if value.daysTo == 0 %}heute{% elif value.daysTo == 1 %}morgen{% else %}in {{value.daysTo}} Tagen{% endif %}'
    date_template: '{{value.date.strftime("%d.%m.%Y")}}'
    add_days_to: True
    types:
      - Restabfall
{...}
```
