### ISSUE TITLE
ICS url fails to load

### ISSUE THREAD

**Issue by dkNeumann** [mampfes/hacs_waste_collection_schedule#628]
Hi,
For a while now I have experienced that the ICS URL-load fails with:

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 10.12.44 (1 occurrences)
Last logged: 10.12.44

fetch failed for source ICS: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 185, in fetch return self.fetch_url(self._url, self._params) File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 200, in fetch_url raise RuntimeError( RuntimeError: Error: unknown method to fetch URL, use GET or POST; got {self._method}

Configuration entries are:
waste_collection_schedule:
  sources:
    - name: ics
      calendar_title: "Nem Affaldsservice"
      args:
        url: "https://nemaffaldsservice.kk.dk/Calendar/GetICaldendar?customerId=d0c610ae-9ed5-dd11-ba8f-00137238f579&type=ics"
        method: get

This is on version 1.34.0 but seen on previous version from a least before Christmas 2022.

**Comment by dt215git** [comment]
try
```yaml
waste_collection_schedule:
  sources:
    - name: ics
      calendar_title: "Nem Affaldsservice"
      args:
        url: "https://nemaffaldsservice.kk.dk/Calendar/GetICaldendar?customerId=d0c610ae-9ed5-dd11-ba8f-00137238f579&type=ics"
        version: 1
```

![image](https://user-images.githubusercontent.com/86194065/213805415-fa2be3b3-9cd1-4d7d-be3c-01aa6467921b.png)

![image](https://user-images.githubusercontent.com/86194065/213805546-bd78e64c-727b-4ba6-add2-c4a2ba120f0a.png)
