### ISSUE TITLE
Problem with "Stadtreinigung Leipzig"

### ISSUE THREAD

**Issue by FoxXxHater** [mampfes/hacs_waste_collection_schedule#632]
Hello, 

i have problems wih the integration of my waste service and this error: 
![image](https://user-images.githubusercontent.com/54017453/213714829-21b8310a-f17b-4235-8537-2fbe582011c8.png)

The question is also, how i schould write the street? With "ß" or "ss" or "str."??

**Comment by FoxXxHater** [comment]
I also had the problem before the update

**Comment by dt215git** [comment]
Looking at the [source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/custom_components/waste_collection_schedule/waste_collection_schedule/source/stadtreinigung_leipzig_de.py) for that service provider, the street name and house number look like they need to match an entry in this list: https://stadtreinigung-leipzig.de/rest/Navision/Streets

Do you get anything back if you match the spelling there?

I don't think the "ß" character is the issue, if I change the test case to `Bahnhofstraße` it pulls back a shedule:

```bash
found 75 entries for Bahnhofstraße
    2023-01-24: Gelbe Tonne [None]
    2023-02-07: Gelbe Tonne [None]
    ...
    2023-01-23: Blaue Tonne [None]
    2023-02-06: Blaue Tonne [None]
    ...
    2023-12-13: Restabfalltonne [None]
    2023-12-28: Restabfalltonne [None]
```

**Comment by FoxXxHater** [comment]
My Street isnt in this list. But if i look on the main page the street exists.

**Comment by interpreterle** [comment]
Hello,
I sugesst the iCal implementation: https://stadtreinigung-leipzig.de/wir-kommen-zu-ihnen/abfallkalender (my street is also not implemented in the REST service but iCals works since 3 years with an iPhone calendar). Just type in your Street and Number and get the iCal Link. 
Because I'm new to HA I don't know how to make a nice card to Dashbord - this snippet works with the calendar: 
```

# Stadtreinigung
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://stadtreinigung-leipzig.de/wir-kommen-zu-ihnen/abfallkalender/ical.ics?position_nos=XXXXX&name=YYYYYYYYYYYYYYYYYYYYY"
```
