### ISSUE TITLE
Calender is Blank and Error when trying to call service

### ISSUE THREAD

**Issue by jb123567** [mampfes/hacs_waste_collection_schedule#649]
Hi trying to configure for Wiltshire Council in the UK. I am getting this error when I manually call the service and the calender is blank. Am I missing something?

`websocket_api script: Error executing script. Unexpected error for call_service at pos 1: async_setup.<locals>.fetch_data() takes 0 positional arguments but 1 was given`

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1798, in _execute_service
    await self._hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: async_setup.<locals>.fetch_data() takes 0 positional arguments but 1 was given`

**Comment by mampfes** [comment]
These are definitely 2 different problems.

1. How do you call `fetch_data`? It doesn't take an argument! But normally you don't have to call this service, esp. if you have problems with missing data.
2. Missing data: Please share your configuration. Did you set `postcode` and `uprn`?

**Comment by jb123567** [comment]
I get the area by simply selecting the fetch data service and calling it in developer tools? I only tried this as the calendar was blank.

My config is as below taken from the readme instructions. I removed my exact details but the post code didn't have spaces and UPRN is correct.

`waste_collection_schedule:
  sources:
    - name: wiltshire_gov_uk
      args:
        postcode: SP****
        uprn: 1009******* `

Thanks,

J

> These are definitely 2 different problems.
> 
> 
> 
> 1. How do you call `fetch_data`? It doesn't take an argument! But normally you don't have to call this service, esp. if you have problems with missing data.
> 
> 2. Missing data: Please share your configuration. Did you set `postcode` and `uprn`?

**Comment by dt215git** [comment]
Using a random SP2 postcode and corresponding uprn it seems to work for me.

```yaml
waste_collection_schedule:
  sources:
    - name: wiltshire_gov_uk
      args:
        postcode: "SP2 ..."
        uprn: "100121......"
      calendar_title: Wilts

sensor:
  - platform: waste_collection_schedule
    name: Wiltshire
    details_format: appointment_types
    date_template: '{{value.date.strftime("%A %d %B %Y")}}'
    add_days_to: true

```
![image](https://user-images.githubusercontent.com/86194065/215837373-d1e54ba8-217f-415b-bac5-a064ce9229fb.png)

![image](https://user-images.githubusercontent.com/86194065/215837786-498013e7-1e1b-483b-8898-ec62ae263137.png)

**Comment by andonevris** [comment]
I'm also getting no data for Wilts.  Using exactly the same config as the example you gave but with SN12 postcode

```
waste_collection_schedule:
  sources:
    - name: wiltshire_gov_uk
      args:
        postcode: "SN12 xxx"
        uprn: "1009xxxxxxx"
      calendar_title: Wilts
```

```
  - platform: waste_collection_schedule
    name: Wiltshire
    details_format: appointment_types
    date_template: '{{value.date.strftime("%A %d %B %Y")}}'
    add_days_to: true
```

![image](https://user-images.githubusercontent.com/1779529/215970976-71dba2a2-edc2-48ec-904c-a54494016a65.png)
