### ISSUE TITLE
Dedicated Calendar Issues

### ISSUE THREAD

**Issue by jprasm** [mampfes/hacs_waste_collection_schedule#653]
Hi guys,

I'm having two related issues: 

1) trouble creating a dedicated calendar for **_one type of waste_** (recycling) _**only**_. SO STRANGE. I've checked spelling repeatedly, and I can't figure it out. For some reason, it won't create a dedicated calendar for recycling - but it will for the other types of waste (GreenBin, Garbage, YardWaste are all ok).

2) when a dedicated calendar is included in the code, it disables the sensor for that waste type. Sensor shows 'unknown' after HA restart.

The reason I'm trying to get dedicated calendars is for automation triggering. I've had this working for a long time with dedicated calendars in the google calendar integration, but every year I've got to update the calendar myself when the city publishes it. 

If say, I have a dedicated recycling calendar that turns 'on', I can use calendar triggers with offsets to trigger automations within HA.

Here's the code:

```
waste_collection_schedule:
  sources:
    - name: toronto_ca
      args:
        street_address: **ADDRESS**
      customize:
        - type: Recycling
          alias: Recycling Bin
          show: True 
          icon: mdi:recycle
          use_dedicated_calendar: True
          dedicated_calendar_title: Waste Collection Schedule Recycling Bin
        - type: GreenBin
          alias: Green Bin
          show: True 
          icon: mdi:compost
          use_dedicated_calendar: True
          dedicated_calendar_title: Waste Collection Schedule Green Bin
        - type: Garbage
          alias: Garbage Bin
          show: True 
          icon: mdi:delete
          use_dedicated_calendar: True
          dedicated_calendar_title: Waste Collection Schedule Garbage Bin
        - type: YardWaste
          alias: Yard Waste
          show: True 
          icon: mdi:leaf
          use_dedicated_calendar: True
          dedicated_calendar_title: Waste Collection Schedule Yard Waste
      calendar_title: City of Toronto Waste Collection Schedule


sensor:
  - platform: waste_collection_schedule
    name: next_green_bin_collection
    types:
      - GreenBin
    value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'

  - platform: waste_collection_schedule
    name: next_recycling_bin_collection
    types:
      - Recycling
    value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'


  - platform: waste_collection_schedule
    name: next_garbage_bin_collection
    types:
      - Garbage
    value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'


  - platform: waste_collection_schedule
    name: next_yard_waste_collection
    types:
      - YardWaste
    value_template: '{% if value.daysTo == 0 %}Today{% elif value.daysTo == 1 %}Tomorrow{% else %}in {{value.daysTo}} days{% endif %}'
```
