### ISSUE TITLE
[Request] Add WAS Vorsfelde

### ISSUE THREAD

**Issue by boehser-enkel** [mampfes/hacs_waste_collection_schedule#66]
Hey,
could you add WAS Vorsflede?

Both "Rest, Bio, Papier" via Street name: https://was-wolfsburg.de/was/biorestpapierics2021.php
And Gelber Sack via street name where you just get the dates: https://was-wolfsburg.de/was/gelber_sack.php

greetz

**Comment by mampfes** [comment]
The ICS file download for "Restmüll, Bio, Papier" works with the following config:

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://was-wolfsburg.de/subabfuhrtermine/ics_abfuhrtermine3.php"
        method: POST
        params:
          ortabf: Denkmalplatz
```

"Gelber Sack" requires to implement an own source.
