### ISSUE TITLE
Online ICS Source / add Abfallkalender Detmold as source

### ISSUE THREAD

**Issue by bluenazgul** [mampfes/hacs_waste_collection_schedule#67]
I use an local ICS Source at the moment. 

Just would like to ask of it is possible to use this URL as Source for the ICS file

https://abfuhrkalender.detmold.de/icsmaker.php?strid=***&year=2021

The "strid" is the ID of the Street

If it is possible to use the URL as Source, is there a way to Set the year as variable given from HA?

**Comment by mampfes** [comment]
The following config should do the trick, including automatic replacement of the year argument:
```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://abfuhrkalender.detmold.de/icsmaker.php"
        params:
          strid: 338
        year_field: year 
```
