### ISSUE TITLE
Anable Landkreis Karlsruhe

### ISSUE THREAD

**Issue by amiga4everyone** [mampfes/hacs_waste_collection_schedule#684]
Like most here a request to integrate another provider named Landkreis Karlsruhe. The district of Karlsruhe allows a street-level generation of an ical link

**Comment by 5ila5** [comment]
They seem to offer a Ical Subscription URL, which seems not to change over time. Have you tried using it with the [ICS source](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md)?

**Comment by amiga4everyone** [comment]
Thanks for the answer. Yes, I tried but it didn't work. There were no appointments in the calendar. But I can't rule out the possibility that it was due to my implementation. I'll try again tomorrow
.

On the road


18.02.2023 19:39:05 5ila5 ***@***.***>:

**Comment by mampfes** [comment]
I tried the `ical-Kalenderabo` with the following config and it return valid results:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://waste.awb-landkreis-karlsruhe.de/WasteManagementKarlsruheHaushalteBlank/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=703821001&AboID=56758&Fra=RC2;RC1;BT2;BC;RT;Schad;WC;WT;BT1"

sensor:
  - platform: waste_collection_schedule
    name: all_waste_types
```

![image](https://user-images.githubusercontent.com/375950/219967071-0cd3d95f-3a12-43e3-b36b-d9cac05b16c7.png)
