### ISSUE TITLE
Add additional source for AWIDO: AWV Isar-Inn

### ISSUE THREAD

**Issue by mampfes** [mampfes/hacs_waste_collection_schedule#691]
### Discussed in https://github.com/mampfes/hacs_waste_collection_schedule/discussions/687

<div type='discussions-op-text'>

<sup>Originally posted by **m4c3** February 19, 2023</sup>
Hi,
the awido integration also works great with the data for [Abfallwirtschaftsverband Isar-Inn](https://www.awv-isar-inn.de/) 

```
waste_collection_schedule:
  sources:
    - name: awido_de
      args:
        customer: awv-isar-inn
        city: Simbach a. Inn
        street: Bayernwerkstr.
```
can somebody add this? Thanks! </div>
