### ISSUE TITLE
Request: Entsorgungs- und Wirtschaftsbetrieb Landau (in der Pfalz)

### ISSUE THREAD

**Issue by Kurisutian** [mampfes/hacs_waste_collection_schedule#697]
After looking to integrate the waste schedule for this provider a friend and I kinda started using the ICS integration since the website creates a unique link to what to download. However, part of that link seems to be a random session id which we are not sure of if this remains or changes over time so at one point the download no longer works. 
Not being a programmer I wanted to ask if someone more skilled can take a look at it. 
The website can be found here: https://www.ew-landau.de/Kurzmen%C3%BC/Entsorgungskalender/

When choosing a street and building number a link like this will be created: https://apps.c-trace.de/web.landau/(S(db5sn4tg0wstgioyfdcvhg0v))/abfallkalender/downloadcal?Strasse=Am%20Kindergarten&Hausnr=1

So it contains the street name but also that session id part (S(<SessionID>)) which we are not sure of whether it can be random so we can stick to the ICS download path of if it would be worth having a distinct integration for the provider.

If somebody can advise me if we should stick to the ICS download way or could alternatively look into coding a integration for this that would be awesome. Thanks in advance!

**Comment by 5ila5** [comment]
there is already an existing integration for these c-trace.de urls:
[c-trace](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/c_trace_de.md)

but it seems like it only works for web.c-trace.de urls at the moment I made a pull request so that this might be possible:
```yaml
waste_collection_schedule:
  sources:
  - name: c_trace_de
    args:
      strasse: Am Kindergarten
      hausnummer: 1
      service: web.landau
      subdomain: apps
      ical_url_file: downloadcal
```

but I'm not the biggest fan of the ical_url_file so maybe there will be some changes
