### ISSUE TITLE
fetch failed for source C-Trace (v1.34.0 and 1.35.0)

### ISSUE THREAD

**Issue by Sphericals79** [mampfes/hacs_waste_collection_schedule#698]
Since a few days the Waste Collection Schedule with CTRace is not working anymore. 

I updated to 1.35.0 to see if this fixes the problem. Switched back to 1.34.0 after noticing, it didn´t help.

```
Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule ([documentation](https://github.com/mampfes/hacs_waste_collection_schedule#readme))
First occurred: 00:06:50 (2 occurrences)
Last logged: 01:40:20

fetch failed for source C-Trace: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/c_trace_de.py", line 66, in fetch session_id = r.headers["location"].split("/")[ File "/usr/local/lib/python3.10/site-packages/requests/structures.py", line 52, in __getitem__ return self._store[key.lower()][1] KeyError: 'location'
```
Untouched config (worked peferctly fine so far)

```
#WZV Abfallkalender
waste_collection_schedule:
  sources:
    - name: c_trace_de
      args:
        service: segebergwzv-abfallkalender
        ort: [...]
        strasse: [...]
        hausnummer: [...]
      customize:
        - type: Bio
          alias: Bioabfall
          icon: mdi:flower-outline
        - type: Gelber Sack
          alias: Gelber Sack
          icon: mdi:recycle
        - type: "Abfuhr: Restabfall"
          alias: Restabfall
          icon: mdi:trash-can
        - type: Papier
          alias: Papierabfall
          icon: mdi:trash-can-outline
      calendar_title: Abfallkalender
```
