### ISSUE TITLE
possible recurring ics events issue

### ISSUE THREAD

**Issue by a-nicholls** [mampfes/hacs_waste_collection_schedule#7]
I have had to publish my own calendar entries as my provider doesn't publish ICS events themselves, now our collection days are shifted whenever there is a public holiday so I created recurring events and moved the exceptions in Outlook and it has shared the ICS file

Found some info on ics formats and recurring events that may help
https://icalevents.com/4437-correct-handling-of-uid-recurrence-id-sequence/

[calendar.ics.txt](https://github.com/mampfes/hacs_waste_collection_schedule/files/4671956/calendar.ics.txt)

**Comment by mampfes** [comment]
@a-nicholls Sorry, but I didn't understand your actual problem. Recurring events are supported since some days using a library from pypi and I fixed an issue 16 days ago. Could you describe your problem?

**Comment by a-nicholls** [comment]
Sure created recurring events, and edited recurring exception (like this week)
![image](https://user-images.githubusercontent.com/51675087/82790145-7fb8f480-9e63-11ea-8881-239db96868db.png)

this produces the following ICS file if I download manually
[calendar.ics (2).txt](https://github.com/mampfes/hacs_waste_collection_schedule/files/4675869/calendar.ics.2.txt)

with the following config

configuration.yaml;
```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: !secret waste_collection_schedule_url
        offset: 0
```
sensor config

```yaml
- platform: waste_collection_schedule
  name: Bin days
  details_format: upcoming
  value_template: '{{value.types|join(" + ")}} in {{value.daysTo}} days'
  date_template: '{{value.types|join(" + ")}} in {{value.daysTo}} days'
```

this shows up in home assistant glance card;

![image](https://user-images.githubusercontent.com/51675087/82790991-e559b080-9e64-11ea-9444-470c51897f1c.png)

Doesn't show any blue bin collections, and shows black bin next collection after this week is in 102 days...
