### ISSUE TITLE
Fehler beim Abrufen von ZAW Darmstadt-Dieburg

### ISSUE THREAD

**Issue by Whilk-and-Misky** [mampfes/hacs_waste_collection_schedule#711]
Beim Abrufen der Daten von ZAW Darmstadt-Dieburg füllt sich das Log mit folgenden Zeilen:

```
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 210, in _fetch
    shell.fetch()
AttributeError: 'NoneType' object has no attribute 'fetch'
```

Es wird auch keine Entität angelegt.

_Systemdaten:_
> Home Assistant 2023.2.5
> Supervisor 2023.01.1
> Operating System 9.5
> Frontend 20230202.0 - latest

**Comment by 5ila5** [comment]
Wie sieht deine Konfiguration aus? Ich kann den Fehler aktuell nicht reproduzieren.
Die Konfiguration sollte beispielsweise so aussehen:

für Alsbach-Hähnlein Akatienweg:
```yaml
waste_collection_schedule:
  sources:
    - name: zaw_online_de
      args:
        city: MQ
        street: Nzc0MQ
```
[weitere Infos ](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/zaw_online_de.md)

Mit den Codes ist nicht das eleganteste Vielleicht gehe ich die Tage da nochmal dran und mache es auch möglich den Ort und die Straße normal anzugeben

**Comment by Whilk-and-Misky** [comment]
Meine Config sieht folgendermaßen aus:

```
waste_collection_schedule:
  sources:
    - name: zaw_online_de
      args:
        city: Mw
        street: ODAzMw
```

Ich habe mal testweise deine oben stehende genommen, der Fehler bleibt der gleiche. Die Version von Waste Collection Schedule ist 1.35.0
