### ISSUE TITLE
Request: Mein-Abfallkalender.de

### ISSUE THREAD

**Issue by TheBassfly** [mampfes/hacs_waste_collection_schedule#727]
I would love to see an integration for the "mein-abfallmalender.de"

I couldn't make the ICS Import to work correct.

Thank you:

https://eppstein.mein-abfallkalender.de

**Comment by mampfes** [comment]
What was the problem with ics?

I did a short test with mein-abfallkalender.de and the ics source and it worked:
Select your adress in the web page, then go to "Termine iCal / WebCal". Set "Erinnerung" to "keine Erinnerung" and set "Verwendung" to "Termine via WebCal Protokoll abonnieren (Allgemein)". You then get a webcal and a http link. Use the http link with the ics source.

Example:
http://eppstein.mein-abfallkalender.de/ical.ics?sid=19799&cd=inline&ft=noalarm&fu=webcal_other&fp=next_30&wids=494,495,496,498,497,499,502,500,513,501&uid=263834&pwid=d9caede3b1&cid=80

**Comment by TheBassfly** [comment]
Maybe I need some advanced help.

The Integration got an error in the log:

2023-03-06 18:51:23.153 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration waste_collection_schedule which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-06 18:51:23.157 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration govee which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-06 18:51:23.159 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-06 18:51:23.161 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration eufy_security which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-06 18:51:23.163 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration ics_calendar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-06 18:51:23.165 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-06 18:51:23.168 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration webrtc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-06 18:51:34.807 ERROR (MainThread) [homeassistant.setup] Error during setup of component waste_collection_schedule
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 109, in async_setup
    api.add_source_shell(
  File "/config/custom_components/waste_collection_schedule/__init__.py", line 202, in add_source_shell
    SourceShell.create(
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 196, in create
    source = source_module.Source(**source_args)  # type: ignore
  File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/ics.py", line 146, in __init__
    raise RuntimeError("Specify either url or file")

Here is my config:

waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "My Calender URL"
        file: url
        version: 2

**Comment by mampfes** [comment]
Try:

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "http://eppstein.mein-abfallkalender.de/ical.ics?sid=19799&cd=inline&ft=noalarm&fu=webcal_other&fp=next_30&wids=494,495,496,498,497,499,502,500,513,501&uid=263834&pwid=d9caede3b1&cid=80"
```

Replace the URL with the one that you get from the webpage for your location.

**Comment by TheBassfly** [comment]
Thank you

So the Calendar looks Imported, but the Sensor thing is still not working.

**Comment by 5ila5** [comment]
looks like it should work. this gives me the two sensors with the time till pickup

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "http://eppstein.mein-abfallkalender.de/ical.ics?sid=19799&cd=inline&ft=noalarm&fu=webcal_other&fp=next_30&wids=494,495,496,498,497,499,502,500,513,501&uid=263834&pwid=d9caede3b1&cid=80"
      customize:
        - type: Papier
          alias: papier
          icon: mdi:file-outline
        - type: Gelber Sack
          alias: gelber
          icon: mdi:recycle

sensor:
  - platform: waste_collection_schedule
    name: Abfall Papier
    details_format: "upcoming"
    types:
      - papier
  
  - platform: waste_collection_schedule
    name: Abfall Gelber Sack
    details_format: "upcoming"
    types:
      - gelber
```
![grafik](https://user-images.githubusercontent.com/38183212/230876771-536300b1-6b66-44d7-a4ff-85d66a04bc89.png)
