### ISSUE TITLE
Help wanted: Entity showing next recollection day for each type

### ISSUE THREAD

**Issue by thor9898** [mampfes/hacs_waste_collection_schedule#740]
In my city there are only 2 types of recollection, rubbish and recycling:

![06 03 1](https://user-images.githubusercontent.com/58491644/223111756-1f92e33a-1b95-4feb-b019-392219003c74.jpg)

So I wanted to have 2 entities, one for each, reporting when's the next day for that type of recollection, so I can have this kind of card:

![card](https://user-images.githubusercontent.com/58491644/223112626-f1c1d863-9a2d-44ac-8376-28dd7bd88247.png)

But I'm getting unknown for both entities:

![06 03 2](https://user-images.githubusercontent.com/58491644/223113341-fdc567c2-0c46-4166-8d6d-906e796ecc21.png)

This is my code: 
```
sensor:
  - platform: waste_collection_schedule
    name: Rubbish
    count: 1
    value_template: 'in {{value.daysTo}} days'
    add_days_to: true 
    types:
    - Rubbish
  - platform: waste_collection_schedule
    name: Recycling
    count: 1
    value_template: 'in {{value.daysTo}} days'
    add_days_to: true 
    types:
    - Recycling

waste_collection_schedule:
    sources:
    - name: midsussex_gov_uk
      args:
        house_number: !Secret
        street: Snow Hill
        postcode: RH10 3EF
      customize:
        - type: Rubbish
          alias: Rubbish
        - type: Recycling
          alias: Recycling

```

Although the calendar is fine, but I'm more interested in the card:

![image](https://user-images.githubusercontent.com/58491644/223115229-39f40d2e-d3c4-4d67-ab82-1bd527d9c9d8.png)

**Comment by thor9898** [comment]
I was able to make 2 different calendars:


![image](https://user-images.githubusercontent.com/58491644/223175082-9a9ecf21-5775-4aef-8722-668cc4ce55c9.png)


By changing the code to:
```
sensor:
  - platform: waste_collection_schedule
    name: Rubbish bin collection
    count: 2
    value_template: 'in {{value.daysTo}} days'
    add_days_to: true 
    types:
    - Rubbish bin collection
  - platform: waste_collection_schedule
    name: Recycling bin collection
    count: 2
    value_template: 'in {{value.daysTo}} days'
    add_days_to: true 
    types:
    - Recycling bin collection

waste_collection_schedule:
    sources:
    - name: midsussex_gov_uk
      args:
        house_number: Everest House
        street: Snow Hill
        postcode: RH10 3EF
      customize:
        - type: Rubbish bin collection
          alias: Rubbish
          use_dedicated_calendar: true
          dedicated_calendar_title: rubbish
        - type: Recycling bin collection
          alias: Recycling
          use_dedicated_calendar: true
          dedicated_calendar_title: recycling

```


But I still cant get the sensors neither the calendar to tall me when's the next recollection:


![image](https://user-images.githubusercontent.com/58491644/223176611-14707a90-faf2-4fa8-80de-79db3231f6cb.png)

**Comment by thor9898** [comment]
I was able to make 2 different calendars:


![image](https://user-images.githubusercontent.com/58491644/223175082-9a9ecf21-5775-4aef-8722-668cc4ce55c9.png)


By changing the code to:
```
sensor:
  - platform: waste_collection_schedule
    name: Rubbish bin collection
    count: 2
    value_template: 'in {{value.daysTo}} days'
    add_days_to: true 
    types:
    - Rubbish bin collection
  - platform: waste_collection_schedule
    name: Recycling bin collection
    count: 2
    value_template: 'in {{value.daysTo}} days'
    add_days_to: true 
    types:
    - Recycling bin collection

waste_collection_schedule:
    sources:
    - name: midsussex_gov_uk
      args:
        house_number: !Secret
        street: Snow Hill
        postcode: RH10 3EF
      customize:
        - type: Rubbish bin collection
          alias: Rubbish
          use_dedicated_calendar: true
          dedicated_calendar_title: rubbish
        - type: Recycling bin collection
          alias: Recycling
          use_dedicated_calendar: true
          dedicated_calendar_title: recycling

```


But I still cant get the sensors neither the calendar to tall me when's the next recollection:


![image](https://user-images.githubusercontent.com/58491644/223176611-14707a90-faf2-4fa8-80de-79db3231f6cb.png)

**Comment by mampfes** [comment]
You mixed up the aliases. If you set an alias, you have to use the alias name in the types field of the sensor config from now on. So, if you want to see it as "Rubbish", use the following config:

```
waste_collection_schedule:
  sources:
    - name: midsussex_gov_uk
      args:
        house_number: !Secret
        street: Snow Hill
        postcode: RH10 3EF
      customize:
        - type: Rubbish bin collection
          alias: Rubbish

sensor:
  - platform: waste_collection_schedule
    name: Rubbish (use whatever you want here)
    count: 2
    value_template: 'in {{value.daysTo}} days'
    add_days_to: true 
    types:
      - Rubbish
```
