### ISSUE TITLE
add Zweckverband Abfallwirtschaft Oberes Elbtal?

### ISSUE THREAD

**Issue by mampfes** [mampfes/hacs_waste_collection_schedule#779]
### Discussed in https://github.com/mampfes/hacs_waste_collection_schedule/discussions/778

<div type='discussions-op-text'>

<sup>Originally posted by **Schmarni** March 19, 2023</sup>
Hello,
can you please add source for Zweckverband Abfallwirtschaft Oberes Elbtal in Germany?
https://www.zaoe.de/abfallkalender/entsorgungstermine/
Thank you very much :-)</div>

**Comment by mampfes** [comment]
@schmarni: zaoe.de provides a iCal abo which should work with the [ICS](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md) source:

![image](https://user-images.githubusercontent.com/375950/226200769-7efe3fba-c192-4f79-a0d8-1a077b76fc03.png)

Have you tried this already?

**Comment by Schmarni** [comment]
or did I do something wrong somewhere?
![Uploading 46961265-B70C-479F-B59C-5F5CF1F763C0.jpeg…]()

**Comment by Schmarni** [comment]
![339B4051-9A3E-43C6-8B9C-B8D9B1BAC7F3](https://user-images.githubusercontent.com/74195536/226404955-a5510f07-2bde-4449-9d0d-dcf446a89dd5.png)
![04654F45-6912-45C7-8F69-483956E8729F](https://user-images.githubusercontent.com/74195536/226404983-8b85bca9-f4dd-4b29-9829-69e5271305bb.png)

**Comment by Schmarni** [comment]
![Uploading F6BBE88D-C99B-4A87-A182-FACD7F9230D0.jpeg…]()

**Comment by mampfes** [comment]
This config works on my machine:

```yaml
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: "https://www.zaoe.de/kalender/ical/7473/_1-2-3-4-5-6-7/24/"

sensor:
  - platform: waste_collection_schedule
    name: all_waste_types


```
