### ISSUE TITLE
Milton Keynes Council, UK please

### ISSUE THREAD

**Issue by aatur-ravani** [mampfes/hacs_waste_collection_schedule#780]
Hi,

Can we add the source for Milton Keynes council please. 

https://www.milton-keynes.gov.uk/waste-and-recycling/collection-days

Thanks!

**Comment by 5ila5** [comment]
The collection days seem to be static at a given Weekday you might have a look at the [Static/User Specified](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/static.md) source
you could try the following which generates a weekly event at at the weekday of the given start date (Monday in this case):

```yaml
waste_collection_schedule:
  sources:
    - name: static
      calendar_title: Rubbish #feel free to edit
      args:
        type: Rubbish #feel free to edit
        frequency: WEEKLY
        interval: 1
        start: '2023-03-20'
        until: '2024-12-31'
```

or do I understand the page wrong?
