### ISSUE TITLE
Cannot fetch from West Berkshire Council

### ISSUE THREAD

**Issue by Quark999** [mampfes/hacs_waste_collection_schedule#789]
I have never been able to fetch using the West Berkshire Council integration and see the following in the logs:
fetch failed for source West Berkshire Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/westberks_gov_uk.py", line 81, in fetch if not rubbish_data['result']['nextRubbishDateSubText']: KeyError: 'nextRubbishDateSubText'

**Comment by Quark999** [comment]
Running test_source.py manually showed an error "No module named 'requests", so I manually ran pip install requests and things seem to be working now. Is this a prerequisite that I missed somehow, and should that have been in my Home Assistant installation all along?

**Comment by mampfes** [comment]
Please share your configuration. The defined test cases in the source file are working, therefore it probably has something to do with your location.

```
./test_sources.py -s westberks_gov_uk -l
Testing source westberks_gov_uk ...
  found 2 entries for known_uprn
    2023-03-31 : Rubbish
    2023-03-24 : Recycling
  found 2 entries for unknown_uprn_by_name
    2023-03-31 : Rubbish
    2023-03-24 : Recycling
  found 2 entries for unknown_uprn_by_number
    2023-04-05 : Rubbish
    2023-03-29 : Recycling
  found 2 entries for unknown_uprn_business
    2023-04-05 : Rubbish
    2023-03-29 : Recycling
```

**Comment by Quark999** [comment]
I'm using
`waste_collection_schedule:
  sources:
    - name: westberks_gov_uk
      args:
        uprn: 100081026602`

Manually editing the uprn into westberks_gov_uk as a test case still works in test_sources.py, but it doesn't work when trying to use it properly through configuration.yaml . I'm not sure how I can debug it more, there most be something going wrong in my environment...

**Comment by dt215git** [comment]
Seemed to work okay for me

```yaml
waste_collection_schedule:
  sources:
    - name: westberks_gov_uk
      args:
        uprn: "100081026602"

sensor:
  - platform: waste_collection_schedule
    name: WestBerks_Waste
    details_format: appointment_types
    add_days_to: true
```

![image](https://user-images.githubusercontent.com/86194065/227596715-0fc532ee-9dc4-473a-862b-99391fb64bf6.png)
