### ISSUE TITLE
Desperately trying to add Solingen

### ISSUE THREAD

**Issue by Chakkaaa** [mampfes/hacs_waste_collection_schedule#795]
Hi Steffen,

I am new to HA and all its features and I am trying to get the Waste schedule configured for Solingen, but it isn't working at all.
Tried the yaml code for reading the downloaded ics file and that works ok, but I would like to get the data directly from abfallnavi instead.

Any hint?

This is what I put together:

waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service_id: solingen
        ort: solingen
        strasse: 
        hausnummer: 

Thanks for any input

**Comment by 5ila5** [comment]
like described in the documentation for [abfallnavi](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfallnavi_de.md#how-to-get-the-source-arguments) you can run the wizard and select your city, street and house number and it returns a valid yaml configuration if you do not want/can run this script your yaml should look like this: (indentation is important)
```yaml
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: solingen
        ort: Solingen
        strasse: Agnesstraße
        hausnummer: 15
```
