### ISSUE TITLE
Today event is missing in Generic ICS

### ISSUE THREAD

**Issue by derwolff** [mampfes/hacs_waste_collection_schedule#8]
Hi,
I'm using the Generic ICS File implementation. Everything works fine but the event for today is not shown in the list. I have played with 'day_switch_time' without success.

**Comment by mampfes** [comment]
Hi, there was an issue in the documentation of the source configuration. Could you please check if the updated documentation fixes your issue:

https://github.com/mampfes/hacs_waste_collection_schedule/tree/fix_docu

Abbreviation: Move ```day_switch_time``` 4 spaces to the left.

**Comment by derwolff** [comment]
It doesn't solve the issue. Only the next event from 27.05.2020 is shown.
Here is my configuration:
--------------------------------------------------
waste_collection_schedule:
  sources:
    - name: ics
      day_switch_time: "18:00"     #only for testing
      args:
        file: "/config/custom_components/waste_collection_schedule/cal.ics"
---------------------------------------------------

cal.ics
--------------------------------------------------
BEGIN:VEVENT
UID:5ec7844f68f00
DTSTART;VALUE=DATE:20200525
SEQUENCE:0
TRANSP:OPAQUE
LOCATION:nnn
SUMMARY:Graue Tonne
CLASS:PUBLIC
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
DTSTAMP:20200522T095039Z
END:VEVENT
BEGIN:VEVENT
UID:5ec7844f69139
DTSTART;VALUE=DATE:20200527
SEQUENCE:0
TRANSP:OPAQUE
LOCATION:nnn
SUMMARY:Papiertonne
CLASS:PUBLIC
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
DTSTAMP:20200522T095039Z
END:VEVENT
--------------------------------------------------

**Comment by mampfes** [comment]
Hi, I found multiple issues:

1. 51ead5c should fix your initial problem.
2. Your configuration is still wrong:
```
waste_collection_schedule:
  day_switch_time: "18:00"     #only for testing
  sources:
    - name: ics
      args:
        file: "/config/custom_components/waste_collection_schedule/cal.ics"
```
3. In your cal.ics the BEGIN:VCALENDAR / END:CALENDAR tags are missing

**Comment by derwolff** [comment]
It's working after fix checkout and correction of my configuration.

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
          file: "/config/custom_components/cal.ics"
  day_switch_time: "09:00" 
```

The example of my ICS File was was only an extract of the entire file.
Thanks.
