### ISSUE TITLE
AbfallNavi missing Fraktion

### ISSUE THREAD

**Issue by flotomation** [mampfes/hacs_waste_collection_schedule#829]
I noticed something odd:

With AbfallnaviDE there is an issue with my waste type "Papier", the integration isn't fetching it not correctly.
I use service_id: oberhausen 
The calendar is filled with all the types/fraktions except Papier. 
When I use the API manually or with the site WBO Wirtschaftsbetriebe Oberhausen, I get the correct dates, even with the Papier Type. 

WBO:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/129587589/229286124-129d0b32-0c80-4030-b6eb-e62636ba4e38.png">

HA Calendar:
<img width="926" alt="image" src="https://user-images.githubusercontent.com/129587589/229286206-0d72c7f1-c471-4acd-98a8-8453761331cb.png">

Could you please look into it?

**Comment by 5ila5** [comment]
there seems to be an error with the `hausnummer` parameter i get a lot more entries if `hausnummer` is an Integer, seems like providing hausnummer as Iteger e.g:
```yaml
waste_collection_schedule:
  sources:
    - name: abfallnavi_de
      args:
        service: oberhausen
        ort: Oberhausen
        strasse: Blumenthalstraße
        hausnummer: 22 #instead of "22"
```
seems to be a work around. can you try if it helps?
but I will check why this happens
