### ISSUE TITLE
set light colour based on calendar event

### ISSUE THREAD

**Issue by jgeorge1983** [mampfes/hacs_waste_collection_schedule#843]
I am attempting to set my lights to the colour of the bins 6 hours before the start date, so in my head thats 18:00 the day before.
i have individual sensors per bin type and scenes for light colours.  my yaml is as below:

```
alias: Lights - Bin Day Green test
description: ""
trigger:
  - platform: calendar
    event: start
    offset: "-6:0:0"
    entity_id: calendar.liverpool_city_council
condition:
  - condition: template
    value_template: "{{ 'Green' in trigger.calendar_event.summary }}"
action:
  - service: scene.turn_on
    target:
      entity_id: scene.green_bim
    metadata: {}
mode: single
```
this did not work, but when i manually run the automation it worked.  
any thoughts? couLd be a good one for the FAQ...
