### ISSUE TITLE
Request for hygea_be

### ISSUE THREAD

**Issue by danielp58** [mampfes/hacs_waste_collection_schedule#845]
Hello,
If my configuration is right, I don’t receive any result from hygea_be.
From the source, I try unsuccessfully to reach the two web pages https://www.hygea.be/displaycal.html and https://www.hygea.be/displaycalws.html
 I think that hygea moved to something else

In config file:
```yaml
waste_collection_schedule:
  sources:
    - name: hygea_be
      args:
        cp: 6560

    - name: static
      args:
        type: rubbish
        frequency: WEEKLY
        interval: 1
        start: "2023-04-04"
        until: "2025-01-14"
      #    fetch_time: "12:00"
      #    day_switch_time: "08:00"

      customize:
        - type: om
          icon: mdi:bin
        - type: pmc
          icon: mdi:recycle
```
In sensor file
```yaml
- platform: waste_collection_schedule
  name: all_waste_types

- platform: waste_collection_schedule
  name: pmc
  types:
    - pmc

- platform: waste_collection_schedule
  name: om
  types:
    - om
```
Is there someone who can help?
Many thanks
Phil

**Comment by danielp58** [comment]
Thanks a lot, 
This works perfectly now. The agenda is now properly updated with PMD - ordures ménagères  - paper-carboards dates.
Names are not linked to my config . I shall check this.

Config file:
waste_collection_schedule:
  sources:
    - name: recycleapp_be
      args:
        postcode: xxxx
        street: rue xxxxxxxxxxxx
        house_number: 10

    - name: static
      args:
        type: ordures ménagères
        frequency: WEEKLY
        interval: 1
        start: "2023-04-04"
        until: "2030-01-14"
      
      customize:
        - type: ordures ménagères
          icon: mdi:bin
        - type: pmc
          icon: mdi:recycle

Sensor file:
- platform: waste_collection_schedule
  name: papiers-cartons

- platform: waste_collection_schedule
  name: pmc
  types:
    - pmc

- platform: waste_collection_schedule
  name: ordures ménagères
  types:
    - ordures ménagères

**Comment by Drac0fly** [comment]
Hey, please can you help me with HYGEA...  I try many time but i'm newby on HA and i have some difficulties ... i don't understant how can i make work waste one the calendar :(

**Comment by danielp58** [comment]
Hello Drac0fly,
On my side, i configured two files for hygea: configuration.yaml and sensors.yaml

In the first one(configuration.yaml):
waste_collection_schedule:
  sources:
    - name: recycleapp_be
      args:
        postcode: xxx
        street: rue xxxxx
        house_number: x
       customize:
        - type: Déchets organiques
          alias: déchets organiques
          icon: mdi:trash-can
        - type: PMD
          alias: pmc
          icon: mdi:recycle
          picture: local/pmc.png
        - type: Paper-cardboard
          alias: papiers-cartons
          icon: mdi:trash-can
        - type: dėchets résiduels
          alias: déchets résiduels
          icon: mdi:trash-can
  fetch_time: "04:00"
  day_switch_time: "18:00"

In the 2nd file (sensor.yaml):
platform: waste_collection_schedule
  name: Paper-cardboard
  details_format: upcoming
  value_template: 'on {{value.date.strftime("%a")}}, {{value.date.strftime("%d %b %Y")}}'
  types:
    - papiers-cartons

- platform: waste_collection_schedule
  name: PMD
  details_format: upcoming
  value_template: 'on {{value.date.strftime("%a")}}, {{value.date.strftime("%d %b %Y")}}'
  types:
    - pmc

- platform: waste_collection_schedule
  name: déchets organiques
  details_format: upcoming
  value_template: 'on {{value.date.strftime("%a")}}, {{value.date.strftime("%d %b %Y")}}'
  types:
    - déchets organiques

- platform: waste_collection_schedule
  name: Déchets résiduels
  details_format: upcoming
  value_template: 'on {{value.date.strftime("%a")}}, {{value.date.strftime("%d %b %Y")}}'
  types:
    - Déchets résiduels

There is actually a fault on the x-secret whch should be modified in the file homeassistant/custom_components/waste_collection_schedule/waste_collection_schedule/source/recycleapp_be.py. the ”x-secret” should be             "x-secret": "Op2tDi2pBmh1wzeC5TaN2U3knZan7ATcfOQgxh4vqC0mDKmnPP2qzoQusmInpglfIkxx8SZrasBqi5zgMSvyHggK9j6xCQNQ8xwPFY2o03GCcQfcXVOyKsvGWLze7iwcfcgk2Ujpl0dmrt3hSJMCDqzAlvTrsvAEiaSzC9hKRwhijQAFHuFIhJssnHtDSB76vnFQeTCCvwVB27DjSVpDmq8fWQKEmjEncdLqIsRnfxLcOjGIVwX5V0LBntVbeiBvcjyKF2nQ08rIxqHHGXNJ6SbnAmTgsPTg7k6Ejqa7dVfTmGtEPdftezDbuEc8DdK66KDecqnxwOOPSJIN0zaJ6k2Ye2tgMSxxf16gxAmaOUqHS0i7dtG5PgPSINti3qlDdw6DTKEPni7X0rxM",
            
When done, you should wait a few hours for a first update

Home this helps
Phil

**Comment by Drac0fly** [comment]
Hey, 

thanks for your help. As i told, i'm pretty new so, it's just possible to tell me why i can't find the "sensors.yaml" file? ^^'
I find only sensor.py on the waste-collection folders

Thank you ;p

**Comment by danielp58** [comment]
Drac0fly,

I use a separated sensors.yaml file located in the same folder as the configuration.yaml file.
sensor: !include sensor.yaml
Phil

**Comment by 5ila5** [comment]
@Drac0fly you do not put any configuration in the custom-components folder, where all the .py files are. These are just to provide the ability for Home-Assistant to find and use that custom integration. You do not have (unless specifically created and imported) a separate waste-collection folder for configuration purposes. You just put all of your configuration in the HA configuration.yaml file (should be located in the HA root directory). If you want to separate the sensor configuration in a different file you can add `sensor: !include sensor.yaml` in the configuration if you then create a sensor.yaml file you can put your sensor configuration in this file instead.

Example:

configuration.yaml:

```yaml
waste_collection_schedule:
  sources:
    - name: republicservices_com
      args:
        street_address: 101 E Main St, Georgetown, KY 40324
      customize:
        - type: Recycle
          alias: Recycling
          icon: mdi:recycle
          use_dedicated_calendar: true
          dedicated_calendar_title: Republic Services Recycling
sensor:
  - platform: waste_collection_schedule
    name: recycling_days
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    types:
      - Recycling
```

OR

configuration.yaml:

```yaml
sensor: !include sensor.yaml


waste_collection_schedule:
  sources:
    - name: republicservices_com
      args:
        street_address: 101 E Main St, Georgetown, KY 40324
      customize:
        - type: Recycle
          alias: Recycling
          icon: mdi:recycle
          use_dedicated_calendar: true
          dedicated_calendar_title: Republic Services Recycling
```
sensor.yaml

```yaml
sensor:
  - platform: waste_collection_schedule
    name: recycling_days
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    types:
      - Recycling
```
