### ISSUE TITLE
Tewkesbury borough council: No data, no errors, nothing?

### ISSUE THREAD

**Issue by tribey2** [mampfes/hacs_waste_collection_schedule#897]
I've just attempted to set up a very basic config hacs_waste_collection_schedule but can't seem to get any data into my calendar - it's completely empty, and the sensor says 'unknown'. I also can't see anything relevant in the logs (no results if I search the logs for 'waste').

Configuration.yaml:

```yaml
waste_collection_schedule:
  sources:
    - name: tewkesbury_gov_uk
      args:
        postcode: "GL3 1NH"
      calendar_title: "TBC waste collections"
  day_switch_time: "10:00"

sensor:
  - platform: waste_collection_schedule
    name: "TBC waste collections"
    details_format: appointment_types
    add_days_to: true
```
<img width="1437" alt="Screenshot 2023-04-19 at 20 08 56" src="https://user-images.githubusercontent.com/10151091/233175956-62b8e236-338a-44d8-9202-34e5111cf8c7.png">

Any ideas why this might be the case? As far as I can see and from checking other issues/configs, I'm not missing anything - but I'm surprised there's nothing in the logs.

Thanks!
