### ISSUE TITLE
How can I split waste entries with "," for the same date?

### ISSUE THREAD

**Issue by NilsMinor** [mampfes/hacs_waste_collection_schedule#908]
I got the ics in my calendar running. now I got the following output for my sensor that is configured like this :

```
  - platform: waste_collection_schedule
    name: "abfallkalender"
```

The output for sensor. abfallkalender looks like:

```
attribution: 'Last update: 04/20/23 21:34:26'
icon: mdi:trash-can
friendly_name: abfallkalender
'2023-05-04': Altpapiertonne, Gelbe Tonne, Biotonne, Restmülltonne
'2023-05-06': Tonnentausch
'2023-05-10': Biotonne
'2023-05-17': Restmülltonne, Biotonne, Gelbe Tonne
'2023-05-24': Biotonne
'2023-06-01': Altpapiertonne, Biotonne, Gelbe Tonne, Restmülltonne
'2023-06-03': Tonnentausch
'2023-06-07': Biotonne
'2023-06-14': Restmülltonne, Gelbe Tonne, Biotonne
'2023-06-21': Biotonne
'2023-06-28': Biotonne, Altpapiertonne, Gelbe Tonne, Restmülltonne
'2023-06-30': Tonnentausch
...
```

When trying to split the sensors by type, I don't get it working. It only works for "Biotonne" as this has single entries. The sensor config looks like:

```
  - platform: waste_collection_schedule
    name: "abfallkalender"
    types:
      - Biotonne
```

The question is, how can I split the entires `Altpapiertonne, Gelbe Tonne, Biotonne, Restmülltonne` by "," so I get the entries as sensors?

Thanks,
Nils

**Comment by mampfes** [comment]
Which source are you using? ics?
The ics source can split waste types using the `split_at` attribute.

**Comment by NilsMinor** [comment]
@mampfes tankt for your quick feedback :)

Yes I use ICS. I configured it like :

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        url: https://www.eaw-rheingau-taunus.de/abfallsammlung/abfuhrtermine/ics/gutenbergstrasse-749/feed.ics
        split_at: ", "
```

Is the split_at correctly used? 🤔
