### ISSUE TITLE
Add better examples for api.abfall.io

### ISSUE THREAD

**Issue by c64emulator** [mampfes/hacs_waste_collection_schedule#913]
This is a great component.
The most examples on the inet are for integration with ics (calendar file). I did not find any example for usage of the api.abfall.io.
In your example there is no explanation for "f_abfallarten" and no example for the sensors entry. 
For my city I get
```
        "f_id_kommune": "1072",
	"f_id_bezirk": "1335",
	"f_id_strasse": "2669",
	"f_id_abfalltyp_0": "52",
	"f_id_abfalltyp_1": "17",
	"f_id_abfalltyp_2": "53",
	"f_id_abfalltyp_3": "60",
	"f_id_abfalltyp_4": "54",
	"f_abfallarten_index_max": "5",
	"f_abfallarten": "52,17,53,60,54",
	"f_zeitraum": "20230101-20231231",
```
How to I use this for sensors? What cards to I use?
Thank your for your effort.

**Comment by 5ila5** [comment]
[Abfall.IO / AbfallPlus.de Documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/abfall_io.md):
```yaml
waste_collection_schedule:
  sources:
    - name: abfall_io
      args:
        key: KEY
        f_id_kommune: 1072
        f_id_bezirk: 1335
        f_id_strasse: 2669
        f_abfallarten:
          - 52
          - 17
          - 53
          - 60
          - 54
```
You also need the key parameter described in documentation.

[Sensor documentation](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#configuring-sensors)
