### ISSUE TITLE
North Lincs Error

### ISSUE THREAD

**Issue by V3L** [mampfes/hacs_waste_collection_schedule#919]
I am getting the following error in Home Assistant for the North Lincs source:
```
This error originated from a custom integration.

Logger: waste_collection_schedule.source_shell
Source: custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py:136
Integration: waste_collection_schedule (documentation)
First occurred: 12:32:01 (1 occurrences)
Last logged: 12:32:01

fetch failed for source North Lincolnshire Council: Traceback (most recent call last): File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source_shell.py", line 134, in fetch entries = self._source.fetch() File "/config/custom_components/waste_collection_schedule/waste_collection_schedule/source/northlincs_gov_uk.py", line 40, in fetch waste_type = collection["BinCodeDescription"] KeyError: 'BinCodeDescription'
```

The information I have in my configuration.yaml is:
```
waste_collection_schedule:
  sources:
    - name: northlincs_gov_uk
      args:
        uprn: "100050196285"
      customize:
        - type: Brown garden waste wheeled bin
          alias: Brown Bin
          icon: mdi:mdiTrashCanOutline
        - type: Plastic and cardboard wheeled bin
          alias: Red Bin
          icon: mdi:mdiTrashCanOutline
        - type: Blue kerbside box - paper
          alias: Blue Box
          icon: mdi:mdiTrashCanOutline
        - type: Green kerbside box - cans, glass and aluminium foil
          alias: Green Box
          icon: mdi:mdiTrashCanOutline
        - type: General waste wheeled bin
          alias: Green Bin
          icon: mdi:mdiTrashCanOutline
        - type: Textiles Bag
          show: False
```
Additional Logic for a Sensor:
```
  - platform: waste_collection_schedule
    name: Bin Schedule
    details_format: upcoming
    leadtime: 14
    date_template: '{{value.date.strftime("%d/%m/%Y (%a)")}}'
```
Running the current version of Home Assistant and the Plugin.

Please note I've replaced my UPRN in the config above.

If you need anymore information just let me know.

Thanks,
Vel
