### ISSUE TITLE
Issue: zaw-online.de is not working

### ISSUE THREAD

**Issue by STmsDbg** [mampfes/hacs_waste_collection_schedule#932]
Hi,

the source German "zaw-online.de" is not working any more.
I think they changed the website/api.

I hope you can fix it.

**Comment by coreuter** [comment]
It looks like they have switched to a service called "mymuell.de".

In the meantime, the calendar can be made functional again by using an .ics file. Navigate to https://www.zaw-online.de/abfallkalender/,  generate an .ics file via the city and street name and include it in your configuration (see https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/ics.md).

```
waste_collection_schedule:
  sources:
    - name: ics
      args:
        file: custom_data/calendar/2023_abfallkalender.ics
```
*Note*: Replace `custom_data/calendar/` with the path where you placed the .ics file.
