### ISSUE TITLE
Request for Buckinghamshire Country Council Source

### ISSUE THREAD

**Issue by stuax** [mampfes/hacs_waste_collection_schedule#962]
https://account.aylesburyvaledc.gov.uk/resident2/s/guest-flow-form?service_ref=DSHLC_AVDC_Find_Bin_Days

There is one for South Bucks (Chilterns) already but the Councils have merged into one now and they use a different API to Chilterns.

It can return 

General Waste,
Recyling,
Garden Waste,
Food Waste

Thanks :)

**Comment by MrSeanRoss** [comment]
Additional Information

Name of Council
Aylesbury Vale

Example Postcode
LU7 9EQ

https://www.buckinghamshire.gov.uk/waste-and-recycling/find-out-when-its-your-bin-collection/

https://account.aylesburyvaledc.gov.uk/resident2/s/guest-flow-form?service_ref=DSHLC_AVDC_Find_Bin_Days

This council site is a child of the Buckinghamshire Council site and seems to work the same as the Chilterns site https://github.com/robbrad/UKBinCollectionData/issues/154#issue-1523059303

**Comment by sambarre** [comment]
I had been watching this issue for a while as I wanted this, but realised today it has already been implemented in #1153 

I've managed to get it working with the following setup in my configuration.yaml file 
```
waste_collection_schedule:
  sources:
    - name: aylesburyvaledc_gov_uk
      args:
        uprn: (not sure if you can reverse search these so I redacted it)
```

It gives me the following in my calendar
![image](https://github.com/mampfes/hacs_waste_collection_schedule/assets/29493203/93979bf8-ef1b-41ca-958d-36cdfc12cd18)

The one thing I would really like to know is if there is something I am missing in the configuration and if it is possible to split them up into 4 different calendars for the different types of bin. ie: 
- General Waste,
- Recyling,
- Garden Waste,
- Food Waste

**Comment by markvp** [comment]
This source is already supported via **[iapp_itouchvision_com](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/source/iapp_itouchvision_com.md)** with `municipality: "AYLESBURY VALE"`.

Use the following configuration:

```yaml
waste_collection_schedule:
  sources:
    - name: iapp_itouchvision_com
      args:
        uprn: "YOUR_UPRN"
        municipality: "AYLESBURY VALE"
```

You can find your UPRN at https://www.findmyaddress.co.uk/.

To split collections into separate sensors by waste type, use the `customize` option — see the [README](https://github.com/mampfes/hacs_waste_collection_schedule#customize-waste-type) for details.

Closing as already supported.
