### ISSUE TITLE
[Question] cmcitymedia_de not working

### ISSUE THREAD

**Issue by Serph91P** [mampfes/hacs_waste_collection_schedule#985]
Want to ask if my configuration is not working or the source is broken.
Tried to GET the URL like stated on the page(https://sslslim.cmcitymedia.de/v1/): http://slim.cmcitymedia.de/v1/107/waste/173/types/
which returns noting?
Or is it my configuration:

```yaml
waste_collection_schedule:
  sources:
    - name: cmcitymedia_de
      args:
        hpid: 107
        district: 173
      calendar_title: garbage
  random_fetch_time_offset: "10"
  day_switch_time: "08:00"
```

```yaml
  - platform: waste_collection_schedule
    name: waste
    details_format: appointment_types
    count: 1
    value_template: 'in {{value.daysTo}} Tagen'
    add_days_to: true
    types:
      - Bio- und Restmüllabfuhr
      - Gelbe Säcke
      - Papiertonne
```
