### ISSUE TITLE
Can't load multiple Static sensors

### ISSUE THREAD

**Issue by bschatzow** [mampfes/hacs_waste_collection_schedule#987]
I have tried multiple times loading the following:
```
sensor:
# next garbage collection
  - platform: waste_collection_schedule
    name: garbage1
    source_index: 0
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    types:
      - Garbage
# next yard waste collection
  - platform: waste_collection_schedule
    name: yard_waste1
    source_index: 
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    types:
      - Yard
# next recycle_collection
  - platform: waste_collection_schedule
    name: recycle1
    source_index: 2
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    types:
      - Recycle
# next branches collection
  - platform: waste_collection_schedule
    name: branches1
    source_index: 3
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    types:
      - Branches
     ```
And any of the sensors work find by themselves.  Loading multiple ones either one or two work (usually one) and the other ones show as unknown.

**Comment by 5ila5** [comment]
I don't know your complete config but `source_index` is only needed if you have multiple sources if you only have one Source your `Recycle` and `Branches` sensor would not work because they are looking for the third and fouth source but you only have one.

[Configuration guide:
](https://github.com/mampfes/hacs_waste_collection_schedule/blob/master/doc/installation.md#configuring-sensors)
| Parameter | Type | Requirement | Description |
|--|--|--|--|
|...|...|...|...|
| source_index | int | optional | Used to assign a sensor to a specific source. Only needed if multiple sources are defined. The first source defined is source_index 0, the second source_index 1, etc. If no value is supplied, the default of 0 is used.<br><br>If you want to have a sensor which combines the data from multiple sources, just add a list of sources here. [Example](#combine-data-from-multiple-sources) |
|...|...|...|...|

**Comment by bschatzow** [comment]
@5ila5 
My sensors yaml file.
```
sensor:
# next garbage collection
  - platform: waste_collection_schedule
    name: garbage1
    source_index: 0
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    types:
      - Garbage
# next yard waste collection
  - platform: waste_collection_schedule
    name: yard_waste1
    source_index: 
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    types:
      - Yard
# next recycle_collection
  - platform: waste_collection_schedule
    name: recycle1
    source_index: 2
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    types:
      - Recycle
# next branches collection
  - platform: waste_collection_schedule
    name: branches1
    source_index: 3
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    types:
      - Branches
     ```

**Comment by 5ila5** [comment]
No If you have multiple Static source this should work as you've done it. Is the calendar populated? if not its not the fault of the Sensor but the source configuration.

Tested, works with: (your sensor config just added `source_index: 1` to Yard)
```yaml
waste_collection_schedule:
  sources:
    - name: static
      calendar_title: Garbage-Title
      args:
        type: Garbage
        frequency: MONTHLY
        #weekdays: {FR: -1, MO: 2, TU: Every}
        weekdays: {FR: -1, MO: 2, TU: 3}
        start: '2023-01-14'
        until: '2023-12-31'
        excludes: # Add exception for the recurrence
          - '2023-07-29'
          - '2023-09-23'
        dates: # Manually define dates that are not part of the recurrence
          - '2023-07-28'
          - '2023-09-22'
    - name: static
      calendar_title: Yard-Title
      args:
        type: Yard
        frequency: MONTHLY
        weekdays: SA
        start: '2023-01-14'
        until: '2023-12-31'
    - name: static
      calendar_title: Recycle-Title
      args:
        type: Recycle
        frequency: WEEKLY
        weekdays: TH
        start: '2023-01-14'
        until: '2023-12-31'
    - name: static
      calendar_title: Branches-Tytle
      args:
        type: Branches
        frequency: MONTHLY
        weekdays: {WE: 1}
        start: '2023-01-14'
        until: '2023-12-31'

sensor:
# next garbage collection
  - platform: waste_collection_schedule
    name: garbage1
    source_index: 0
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    types:
      - Garbage
# next yard waste collection
  - platform: waste_collection_schedule
    name: yard_waste1
    source_index: 1
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    types:
      - Yard
# next recycle_collection
  - platform: waste_collection_schedule
    name: recycle1
    source_index: 2
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    types:
      - Recycle
# next branches collection
  - platform: waste_collection_schedule
    name: branches1
    source_index: 3
    details_format: appointment_types
    value_template: "{{ value.daysTo }}"
    types:
      - Branches

```

**Comment by bschatzow** [comment]
@5ila5, The calendar is populated.  The sensors just say unknown.

```
waste_collection_schedule:
  sources:
    - name: static
      args:
        type: Garbage
        frequency: WEEKLY
        weekdays: {MO, TH}
    - name: static
      args:
        type: Recycle
        frequency: WEEKLY
        weekdays: WE
    - name: static
      args:
        type: Yard Waste
        frequency: WEEKLY
        weekdays: MO
    - name: static
      args:
        type: Branches
        frequency: WEEKLY
        weekdays: TU
```
Is the rest of my yaml
