### ISSUE TITLE
Cannot set up South Norfolk/Broadland

### ISSUE THREAD

**Issue by marsdeat** [mampfes/hacs_waste_collection_schedule#996]
I'm not sure if I'm just being particularly dense, but I keep getting an invalid config error when trying to set up south_norfolk_and_broadland_gov_uk

Error message: "Invalid config for [waste_collection_schedule]: required key not provided @ data['waste_collection_schedule']['sources'][0]['args']. Got None. (See /config/configuration.yaml, line 26). Please check the docs at https://github.com/mampfes/hacs_waste_collection_schedule#readme"

I'm currently testing with one of the test addresses given in the docs and code:
```yaml
waste_collection_schedule:
  sources:
    - name: south_norfolk_and_broadland_gov_uk
    - args:
      address_payload: {
        "Uprn": "100091575309",
        "Address": "Tesco Stores Ltd, Blue Boar Lane, Sprowston, Norwich, Norfolk, NR7 8AB",
        "X": "625657.00000",
        "Y": "312146.00000",
        "Ward": "Sprowston East",
        "Parish": "Sprowston",
        "Village": "Sprowston",
        "Street": "Blue Boar Lane",
        "Authority": "2610"
        }
```

I've tried with `name` as `south_norfolk_and_broadland_gov_uk` AND `south_norfolk_gov_uk`, and various levels of indent and combinations of leaving out or adding in the`args` line or a `-` before the `address_payload`. What am I missing? I'm not very well-versed in YAML yet, so it could be something really obvious.

(As a side note: the final example on the documentation page for this council is different in structure from the earlier example, which does not help with setting up the module.)

**Comment by 5ila5** [comment]
your `- args`: is probably your problem. Try using: 

```yaml
waste_collection_schedule:
  sources:
    - name: south_norfolk_and_broadland_gov_uk
      args:
        address_payload: {
          "Uprn": "100091575309",
          "Address": "Tesco Stores Ltd, Blue Boar Lane, Sprowston, Norwich, Norfolk, NR7 8AB",
          "X": "625657.00000",
          "Y": "312146.00000",
          "Ward": "Sprowston East",
          "Parish": "Sprowston",
          "Village": "Sprowston",
          "Street": "Blue Boar Lane",
          "Authority": "2610"
          }
```
same as
```yaml
waste_collection_schedule:
  sources:
    - name: south_norfolk_and_broadland_gov_uk
      args:
        address_payload:
          "Uprn": "100091575309"
          "Address": "Tesco Stores Ltd, Blue Boar Lane, Sprowston, Norwich, Norfolk, NR7 8AB"
          "X": "625657.00000"
          "Y": "312146.00000"
          "Ward": "Sprowston East"
          "Parish": "Sprowston"
          "Village": "Sprowston"
          "Street": "Blue Boar Lane"
          "Authority": "2610"
```

This works for me but only returns 2 garden events
 

I agree we should change the documentation. It also isn't helpful, that this source accepts a dict instead of single attributes
